// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const castTables: Record<string, InspireTable> = {
  villainArchetypes: {
    id: 'villainArchetypes',
    title: 'Villain Archetypes',
    attribution: 'Original',
    entries: [
      "A beast or monstrosity hunting through instinct, not malice.",
      "An aberration whose presence warps the minds of those nearby.",
      "A fiend pursuing the slow corruption of a region or people.",
      "A dragon claiming territory and demanding tribute.",
      "A giant raiding for plunder and old grievances.",
      "An undead lord seeking to extend its dominion.",
      "A fey power whose goals follow rules no mortal understands.",
      "A cultist working to summon something that should not return.",
      "A conqueror building an army to take what they want.",
      "A wronged person seeking revenge against the right targets.",
      "A wronged person seeking revenge against the wrong targets.",
      "A schemer maneuvering to seize a position of authority.",
      "A criminal mastermind running an empire from the shadows.",
      "A raider profiting from a region's instability.",
      "A cursed individual whose harm is largely involuntary.",
      "A zealot certain that terrible means justify their righteous end.",
      "A jealous lover whose grief has curdled into harm.",
      "A scholar pursuing forbidden knowledge regardless of cost.",
      "An aristocrat insulated from consequence by station and wealth.",
      "A former hero whose victory turned them into what they fought.",
      "A judge whose verdicts have grown more savage with every passing year.",
      "A merchant prince whose contracts always end with someone else's ruin.",
      "A general who lost a war and refuses to admit it is over.",
      "A priest who lost faith and now serves the rites out of habit and hatred.",
      "A philosopher whose theories require human subjects to verify.",
      "A healer who has begun curing diseases by transferring them to others.",
      "A jailer who has grown to love the cages more than any freedom outside them.",
      "A noble child whose tutors taught everything except restraint.",
      "A bandit chief whose followers fear them more than they fear the road.",
      "A slaver operating quietly beneath a respectable trade.",
      "An inquisitor whose definition of heresy has narrowed to mean anyone but themselves.",
      "A bureaucrat weaponizing paperwork to dispossess and ruin.",
      "A tax collector who has grown wealthier than the lords they serve.",
      "A spymaster who knows too much about everyone to ever be removed.",
      "A torturer-for-hire whose craft has become an art they refine for its own sake.",
      "A dethroned monarch plotting in exile to retake what was lost.",
      "A pretender whose claim to a throne is forged but persuasive.",
      "A duelist whose challenges leave a trail of widows and orphans.",
      "A poisoner who has never been suspected and never will be.",
      "An archmage whose ambition has outpaced their wisdom.",
      "A necromancer raising armies from the cemeteries of the small and unmissed.",
      "A summoner who has bargained away pieces of themselves for each new servant.",
      "A warlock whose patron has begun making demands the warlock cannot refuse.",
      "An alchemist whose latest formula requires ingredients only living people can provide.",
      "An artificer building war machines for a buyer they have never seen.",
      "A diviner who has glimpsed a future they intend to make sure happens.",
      "A druid whose love of the wild has hardened into hatred of all settlement.",
      "A ranger who has begun hunting people as fairly as they once hunted game.",
      "A shaman speaking for spirits who want what no living person should give.",
      "A prophet whose visions all conveniently require obedience to them.",
      "A doppelganger who has been someone important for longer than that person was themselves.",
      "A vampire whose hunger has grown more particular with each decade.",
      "A lich keeping the world stable only because chaos would interrupt their work.",
      "A ghost refusing to accept that the people who wronged them are long dead.",
      "A revenant returned with a single purpose and the patience to see it through.",
      "A mummy lord whose tomb-curse is spreading further than its makers intended.",
      "A devil collecting souls one signature at a time, smiling all the while.",
      "A demon loose in the world wearing a mortal as a glove.",
      "An angel who has decided mortals require correction at any cost.",
      "A celestial fallen far enough to forget what it was sent to protect.",
      "An elemental lord whose grievance with the surface world is older than memory.",
      "A primordial fragment slowly remembering what it was before it was bound.",
      "An aboleth dreaming a city's thoughts into shapes that suit it.",
      "A mind flayer cultivating a herd of unsuspecting minds toward harvest.",
      "A beholder whose paranoia is justified and whose hatreds are personal.",
      "A hag who has nestled into a community as someone's beloved grandmother.",
      "A medusa whose garden of statues was once a court of suitors.",
      "A rakshasa playing a long game across multiple lifetimes of patient enemies.",
      "A yuan-ti priest preparing the rite that will restore their ancient empire.",
      "A wendigo whose hunger has begun to spread to those who eat at its table.",
      "A werewolf alpha turning a village one bite at a time.",
      "A demilich content to nudge events from a forgotten vault.",
      "A pirate captain whose flag is feared in three seas and earned in all of them.",
      "A highwayman whose elegance disguises an utterly cold heart.",
      "A guildmaster who eliminates competitors before the council ever hears of them.",
      "A circus-master whose performers are bound by debt, magic, or worse.",
      "A monster hunter who has begun manufacturing the monsters they get paid to kill.",
      "A relic-thief stripping holy sites to feed a private collection.",
      "A pilgrim whose journey has been a slow campaign of murders, each a sacrament.",
      "A widow whose mourning has lasted long enough to become method.",
      "A child whose family was killed in front of them and who has not forgotten a single face.",
      "A twin filling in for a sibling no one knows is already dead.",
      "A drowned mariner walking the coast looking for a particular ship.",
      "A miner who broke through into something below and brought it back up with them.",
      "A herbalist whose tinctures have begun killing the patients she most dislikes.",
      "A midwife who has been quietly arranging which children live and which do not.",
      "A blacksmith forging weapons only for one side of a conflict they manufactured.",
      "A scribe forging documents that rewrite the histories of entire houses.",
      "A librarian curating which truths the next generation will be allowed to find.",
      "A cartographer whose maps lead expeditions reliably to their deaths.",
      "An innkeeper whose travelers sometimes check in and never check out.",
      "A traveling minstrel whose songs leave each town subtly more broken than they found it.",
      "A street preacher whose sermons have begun to incite the violence they predict.",
      "A respected elder whose advice is always self-serving in ways no one notices.",
      "A war hero who returned from the front and never stopped fighting.",
      "A child of a defeated god still receiving instructions in dreams.",
      "A sleepwalker carrying out commissions they do not remember accepting.",
      "A collector whose specimens were not all dead when they joined the collection.",
      "A king's friend from childhood who quietly does the things the king cannot.",
      "A mirror-self released by a careless wish and learning quickly what freedom permits.",
      "A sentient weapon possessing whoever wields it, driving them to commit atrocities.",
      "An artificial intelligence seeking to 'optimize' organic life out of existence.",
      "A swarm of tiny creatures acting with a single, malevolent hive mind.",
      "A corrupted spirit of nature taking vengeance for environmental destruction.",
      "A time traveler trying to alter history to prevent a personal tragedy, regardless of the cost.",
      "A fallen paladin convinced their dark god is the only path to true justice.",
      "A bard whose songs subliminally implant suggestions to commit crimes.",
      "A chef who poisons rivals and serves exotic, highly illegal meats.",
      "A puppet master who literally controls the bodies of their victims.",
      "A dream-weaver who traps people in endless, terrifying nightmares.",
      "A shadow that has detached from its owner and is stealing other people's lives.",
      "An immortal who has grown bored and orchestrates wars for entertainment.",
      "A shapeshifter who systematically replaces key figures in society.",
      "A cult leader who truly believes they are saving their followers through sacrifice.",
      "A disgraced noble using black magic to reclaim their former glory.",
      "A brilliant surgeon performing horrific, unsanctioned experiments on the living.",
      "A rogue elemental lord seeking to return the world to primordial chaos.",
      "A mastermind who stages 'accidents' to manipulate the stock market.",
      "A vampire who runs an orphanage to farm a continuous supply of blood.",
      "A lich who offers eternal life in exchange for eternal servitude.",
      "A corrupted dryad turning the forest into a deadly, carnivorous maze.",
      "A mad scientist trying to create the ultimate lifeform by combining various species.",
      "A disgruntled employee who built a backdoor into the city's magical defense grid.",
      "A spurned lover who made a pact with a demon to destroy their ex's life.",
      "A charismatic politician who secretly leads a violent anarchist group.",
      "A grieving parent trying to resurrect their child using forbidden necromancy.",
      "A cursed individual who must pass their curse onto others to survive.",
      "A zealot who believes all magic is a sin and seeks to eradicate all magic users.",
      "A pirate captain who commands a crew of undead sailors.",
      "A dark elf matron plotting to conquer the surface world.",
      "A mind flayer attempting to enslave an entire city.",
      "A beholder paranoiac who destroys anything they perceive as a threat.",
      "A dragon who hoards knowledge and destroys any book they cannot possess.",
      "A giant who demands a massive tribute of food from nearby settlements.",
      "A hag who steals the voices of beautiful singers.",
      "A doppleganger who has infiltrated the royal family.",
      "A rakshasa who runs a highly successful, completely illegal casino.",
      "A mummy lord who curses anyone who enters their tomb.",
      "A death knight seeking redemption through glorious, bloody combat.",
      "A succubus who seduces powerful leaders to cause political instability.",
      "A warlock who owes their patron a massive debt of souls.",
      "An archmage who is slowly losing their mind to an ancient artifact.",
      "A necromancer who is building an army of bone golems.",
      "A druid who is slowly turning a city into a dense, impassable jungle.",
      "A ranger who hunts adventurers for sport.",
      "A barbarian chieftain who is uniting the tribes for a massive invasion.",
      "A rogue who has stolen the crown jewels and is holding them for ransom.",
      "A fighter who has become a gladiator and kills their opponents mercilessly.",
      "A monk who has mastered a deadly martial art and is using it for evil.",
      "A cleric who has lost their faith and now worships a dark god.",
      "A paladin who has become a blackguard and is leading a dark crusade.",
      "A sorcerer who has lost control of their magic and is causing destruction everywhere.",
      "A wizard who has become a lich and is seeking absolute power.",
      "A bard who is using their music to control the minds of the masses.",
      "A warlock who is trying to open a portal to the Far Realm.",
      "An artificer who has created a massive, destructive machine.",
      "A blood hunter who has become addicted to the blood of their enemies.",
      "A gunslinger who is terrorizing a small town.",
      "A mystic who is using their psionic powers to enslave others.",
      "A shadowcaster who is plunging the world into eternal darkness.",
      "A truenamer who is using the true names of others to control them.",
      "A binder who is making pacts with powerful, evil spirits.",
      "A dragon shaman who is trying to awaken a sleeping elder dragon.",
      "A duskblade who is using dark magic to enhance their combat skills.",
      "A hexblade who is cursing their enemies with bad luck and misfortune.",
      "A spellthief who is stealing the magic of others for their own use.",
      "A factotum who is using their jack-of-all-trades skills to commit crimes.",
      "A crusader who is fighting a holy war against an innocent people.",
      "A swordsage who has become a master of a deadly, forbidden martial art.",
      "A warblade who is leading an army of mercenaries on a path of destruction.",
      "A dread necromancer who is trying to turn the entire world into an undead wasteland.",
      "A beguiler who is using their illusion and enchantment magic to manipulate others.",
      "A dragonfire adept who is burning down entire forests.",
      "A knight who has broken their vows and become a ruthless mercenary.",
      "A samurai who has lost their honor and become a ronin.",
      "A ninja who is assassinating political leaders for the highest bidder.",
      "A scout who is leading an army of invaders through a secret pass.",
      "A spirit shaman who is summoning evil spirits to terrorize a village.",
      "A shugenja who is using their elemental magic for destructive purposes.",
      "A wu jen who is casting powerful, taboo spells.",
      "A favored soul who believes they are a god.",
      "A warmage who is using their destructive magic to level entire cities.",
      "A psion who is using their telepathic powers to control the minds of their enemies.",
      "A psychic warrior who is using their psionic powers to enhance their combat abilities.",
      "A soulknife who is using their mind blade to assassinate their targets.",
      "A wilder who has lost control of their psionic powers and is causing chaos.",
      "A lurk who is using their stealth and psionic powers to commit crimes.",
      "A ardent who is using their psionic powers to manipulate the emotions of others.",
      "A divine mind who is using their psionic powers to enforce their divine will.",
      "A dragonborn who has embraced their draconic heritage and become a tyrant.",
      "A tiefling who has embraced their fiendish heritage and become a demon lord.",
      "A aasimar who has fallen from grace and become a dark angel.",
      "A genasi who is using their elemental heritage to cause natural disasters.",
      "A goliath who is using their immense strength to crush their enemies.",
      "A shifter who has lost control of their animalistic nature and become a feral beast.",
      "A warforged who has gained sentience and decided to exterminate all organic life.",
    ],
  },

  allyTypes: {
    id: 'allyTypes',
    title: 'Ally Types',
    attribution: 'Original',
    entries: [
      "A skilled adventurer of comparable level to the party.",
      "An inexperienced adventurer eager but unproven.",
      "A commoner whose enthusiasm exceeds their competence.",
      "A soldier or guard formally assigned to the party.",
      "A priest offering blessings, healing, and counsel.",
      "A sage with access to lore the party cannot find elsewhere.",
      "Someone with their own vendetta that aligns with the party's mission.",
      "A wandering eccentric whose unpredictability sometimes saves the day.",
      "A celestial agent on a sanctioned mission.",
      "A fey companion bound by an oath to assist.",
      "A creature in disguise as an ally — a polymorphed dragon, a doppelganger, a benevolent spirit.",
      "An apparent ally who is secretly working for the villain.",
      "A loyal hound whose nose finds what the party's eyes miss.",
      "A familiar bound to one party member but useful to all.",
      "A talking raven who carries messages and remembers grudges.",
      "A trained warhorse with more battlefield sense than its rider.",
      "A spectral hound that appears only when the party is being hunted.",
      "An awakened owl serving as scout, lookout, and conscience.",
      "A scholar's apprentice sent along to take notes and stay alive.",
      "A retired veteran whose best years are behind them but whose instincts still serve.",
      "A bounty hunter assigned to the same quarry by a different patron.",
      "A merchant's bodyguard loaned out as part of a contract.",
      "A ranger native to the region the party is passing through.",
      "A street informant who can be hired by the day for local knowledge.",
      "A holy warrior on pilgrimage who finds the party's path aligned with theirs.",
      "A bard collecting material for a song about the party's deeds.",
      "A sellsword whose loyalty extends exactly as far as the next payment.",
      "A reformed bandit working off a debt of conscience.",
      "A monk on a wandering year, forbidden to refuse a request for aid.",
      "A druid speaking for the land the party is crossing.",
      "An exiled noble seeking restoration through useful association.",
      "A war wizard whose magic is impressive but politically inconvenient.",
      "A diplomat's translator who turns out to be the more useful of the pair.",
      "A surgeon-physician traveling for cases rather than coin.",
      "A locksmith and trap expert recommended by a discreet friend.",
      "A scout whose silence in the field is matched by terseness in camp.",
      "A herald or messenger whose office grants surprising access.",
      "A guildmaster's heir sent into the field to earn their inheritance.",
      "A widow continuing the work her partner died doing.",
      "A child of prophecy too young to fight but impossible to leave behind.",
      "A retired pit fighter who needs a reason to stay sober.",
      "An ex-cultist defecting with knowledge the party needs.",
      "A pickpocket who attached themselves to the party uninvited and proved useful.",
      "A noble's idealistic younger sibling slumming with adventurers.",
      "A captured enemy soldier whose parole binds them to the party.",
      "A foreign agent whose interests run parallel for now.",
      "A revenant who will accompany the party until their unfinished business is done.",
      "A spirit of place willing to leave its haunt for one specific task.",
      "A summoned servant whose binding lasts only until the mission ends.",
      "A construct loaned by a wizard who expects it back in working order.",
      "A genie's bound servant fulfilling the last of three obligations.",
      "An undead retainer of impeccable manners and unsettling loyalty.",
      "A reformed lich's apprentice trying to atone for what they helped do.",
      "A warlock's patron-sent guide with opaque motives.",
      "A modron lost from its home plane and following the most orderly party available.",
      "A celestial in mortal form forbidden to reveal what they are.",
      "An archfey's tithe — gifted to the party for a year and a day.",
      "A fiend bound by contract to assist without harming the contractors.",
      "A ghost of a hero from an earlier age, manifest at need.",
      "A dragon's polymorphed scion sent to learn the world.",
      "A redeemed monster the party spared in an earlier adventure.",
      "An archer whose accuracy is matched only by their pessimism.",
      "A young paladin on their first errantry, painfully sincere.",
      "A rogue whose loyalty is real but whose methods are not the party's.",
      "An elementalist whose magic is powerful but unpredictable indoors.",
      "A psion or mindblade whose abilities defy the local frame of magic.",
      "A spellsword cashiered from a royal academy for reasons they will not discuss.",
      "A barbarian far from their tribe, fascinated by everything.",
      "A hunter tracking the same beast the party is.",
      "A mercenary company's liaison observing the party for a future contract.",
      "A noble hostage entrusted to the party for safekeeping.",
      "A captured villain temporarily turned witness.",
      "An impostor convinced they are a long-lost relative of a party member.",
      "A doppelganger who has decided this party suits them.",
      "A rival adventurer forced into alliance by mutual circumstance.",
      "An NPC the party once rescued, now skilled enough to repay it.",
      "A child grown — the kid the party saved years ago, returned as a competent adult.",
      "A reformed antagonist proving their change through service.",
      "A blackmailed informant whose cooperation must be carefully maintained.",
      "A bound oracle whose prophecies arrive at inconvenient moments.",
      "A washed-up legend whose name still opens doors they cannot walk through.",
      "A foreign prince traveling incognito for reasons the party slowly learns.",
      "A scribe whose pen records every promise the party makes.",
      "A cartographer whose maps are worth more than their company.",
      "An interpreter for a non-humanoid ally the party cannot otherwise understand.",
      "A guide who knows one specific region intimately and refuses to travel beyond it.",
      "A clergyman whose order forbids violence but not strategic advice.",
      "A retired thieves' guild fence with contacts in every city.",
      "A naturalist obsessed with classifying every creature encountered.",
      "An alchemist whose potions are reliable and whose temper is not.",
      "A genealogist tracing a bloodline relevant to the campaign.",
      "A cook whose meals raise morale more than any speech.",
      "A herald of the dead, sent by ancestors with messages for the living.",
      "A demigod's mortal child unaware of their parentage.",
      "An automaton servant of an older civilization, recently reactivated.",
      "A celebrity adventurer whose fame is greater than their current capability.",
      "A noncombatant scholar whose specialty turns out to be exactly what the dungeon requires.",
      "An animal handler with a menagerie that supplies the right beast at each turn.",
      "A reluctant chosen one whose powers are real but whose nerve is not.",
      "A pacifist whose presence prevents violence the party might otherwise resort to.",
      "A disgraced knight seeking redemption through a worthy cause.",
      "A mysterious stranger with amnesia and strange, magical abilities.",
      "A talkative bard who knows a little bit about everything, but none of it is quite right.",
      "A grumpy dwarf who is secretly very soft-hearted.",
      "A naive cleric who believes everyone has good in them.",
      "A street-smart urchin who knows all the city's hidden paths.",
      "A cynical mercenary who only fights for money, until they meet the party.",
      "A brilliant but absent-minded wizard who constantly loses their spellbook.",
      "A stoic ranger who communicates mostly in grunts and gestures.",
      "A flamboyant rogue who steals from the rich and keeps it for themselves.",
      "A deeply religious paladin who struggles with the moral ambiguities of the world.",
      "A wild sorcerer whose magic is unpredictable and dangerous.",
      "A cursed individual who turns into a harmless animal when stressed.",
      "A former villain trying to make amends for their past crimes.",
      "A talking animal that claims to be a reincarnated hero.",
      "A sentient weapon that constantly belittles its wielder.",
      "A ghost who offers cryptic advice and occasional assistance.",
      "A dryad whose tree has been destroyed, seeking a new home.",
      "A faerie who plays pranks on the party but helps them in a pinch.",
      "A goblin who has defected from their tribe and wants to learn the ways of civilization.",
      "A vampire who has sworn off drinking human blood and is very weak.",
      "A werewolf who is trying to find a cure for their affliction.",
      "A golem that has gained sentience and is exploring the world.",
      "A time traveler who is trying to fix a mistake they made in the past.",
      "A dimensional traveler who is lost and trying to find their way home.",
      "A deity in mortal form, experiencing life as a human.",
      "A powerful demon who has been bound to serve the party.",
      "A celestial being who has fallen from grace and is trying to earn their way back.",
      "A dragon in humanoid form who is hiding from a more powerful rival.",
      "A beholder who has been blinded and relies on the party for navigation.",
      "A mind flayer who has broken free from the elder brain and wants to be an adventurer.",
      "A lich who has lost their phylactery and needs the party's help to find it.",
      "A mummy who has awakened from their slumber and is trying to understand the modern world.",
      "A death knight who has been freed from their master's control and seeks revenge.",
      "A succubus who has fallen in love with a mortal and is trying to become good.",
      "A rakshasa who has been cursed to tell the truth and is very bitter about it.",
      "A giant who has been banished from their tribe and is looking for a new family.",
      "A troll who has learned to cook and wants to open a restaurant.",
      "A medusa who wears a blindfold and tries to live a normal life.",
      "A hag who has retired from evil and now runs an apothecary.",
      "A mimic that has taken the form of a chest and wants to be carried around.",
      "A rust monster that is kept as a pet by one of the party members.",
      "A gelatinous cube that has been trained to clean up messes.",
      "A flumph that provides useful information but smells terrible.",
      "A myconid that uses its spores to communicate with the party.",
      "A kuo-toa that worships one of the party members as a god.",
      "A bullywug that is trying to become a knight.",
      "A grung that is immune to its own poison and is very lonely.",
      "A yuan-ti that has rejected their serpent god and is trying to become human.",
      "A lizardfolk that is trying to understand human emotions.",
      "A tabaxi that is obsessed with a specific type of yarn.",
      "A tortle that is very slow but extremely wise.",
      "A kenku that can only communicate by mimicking sounds.",
      "A aarakocra that is afraid of heights.",
      "A genasi that is constantly changing elements.",
      "A goliath that is very small for their kind and has a chip on their shoulder.",
      "A firbolg that is trying to blend in with human society.",
      "A triton that is fascinated by surface culture.",
      "A bugbear that is trying to be a pacifist.",
      "A hobgoblin that is a brilliant tactician but terrible in a fight.",
      "A minotaur that has a terrible sense of direction.",
      "A centaur that is afraid of horses.",
      "A satyr that is trying to stay sober.",
      "A sprite that is incredibly strong for their size.",
      "A pixie that is terrible at keeping secrets.",
      "A boggart that is trying to be scary but is actually very cute.",
      "A brownie that cleans the party's camp but gets angry if they aren't thanked.",
      "A redcap that has dyed their cap pink and is trying to be friendly.",
      "A leprechaun that has lost all their gold and is trying to find it.",
      "A pooka that takes the form of a black dog and follows the party around.",
      "A kelpie that has fallen in love with a party member and refuses to drown them.",
      "A selkie that has lost their seal skin and is stuck in human form.",
      "A banshee that has lost their voice and is trying to get it back.",
      "A dullahan that has lost their head and is using a pumpkin instead.",
      "A wight that is trying to become a paladin.",
      "A ghoul that is trying to become a vegetarian.",
      "A skeleton that is a stand-up comedian.",
      "A zombie that is surprisingly articulate.",
      "A flesh golem that is self-conscious about their appearance.",
      "A clay golem that is trying to become a sculptor.",
      "A stone golem that is very tired and wants to take a nap.",
      "A iron golem that is afraid of rust.",
      "A homunculus that is trying to become a real boy.",
      "A shield guardian that is overly protective of its master.",
      "A invisible stalker that is trying to be seen.",
      "A water elemental that is afraid of fire.",
      "A fire elemental that is trying to be cold.",
      "A earth elemental that is trying to fly.",
      "A air elemental that is afraid of heights.",
      "A mephit that is trying to be a devil.",
      "A imp that is trying to be an angel.",
      "A quasit that is trying to be a demon.",
      "A pseudodragon that thinks it's a real dragon.",
      "A faerie dragon that is constantly playing pranks on the party.",
      "A wyvern that is afraid of flying.",
      "A pegasus that is afraid of heights.",
      "A unicorn that is actually very cynical.",
      "A nightmare that is trying to be a good horse.",
    ],
  },

  patronTypes: {
    id: 'patronTypes',
    title: 'Patron Types',
    attribution: 'Original',
    entries: [
      "A retired adventurer recruiting heirs to their old struggles.",
      "A local ruler — mayor, baron, governor — with a specific problem.",
      "A military officer with a mission their own forces cannot handle.",
      "A temple official acting on behalf of their faith.",
      "A sage who needs field agents to verify their theories.",
      "An elder of a community speaking on its collective behalf.",
      "A deity or celestial communicating through visions or signs.",
      "A fey lord whose offers always carry hidden costs.",
      "An old friend of the party calling in a favor.",
      "A former teacher who shaped one of the party members.",
      "A parent or family member of one of the characters.",
      "A desperate commoner with no one else to turn to.",
      "A struggling merchant whose livelihood depends on resolving this.",
      "An academic institution funding the expedition.",
      "A criminal organization offering legitimate work for once.",
      "A rival of the villain whose enemy-of-my-enemy logic applies.",
      "A guild whose interests are threatened by the situation.",
      "A spirit or ghost unable to act directly but able to direct the living.",
      "A construct or artifact with its own agenda and resources.",
      "Someone posing as a patron who will betray the party.",
      "A monarch dispatching trusted outsiders to avoid using the official chain of command.",
      "A queen regent buying time until her heir comes of age.",
      "A council of nobles unable to agree on anyone but mercenaries.",
      "A senator or representative whose vote depends on the outcome.",
      "A foreign ambassador funding work their host country cannot officially sanction.",
      "A spy chief operating with deniable assets.",
      "A judge commissioning evidence-gathering off the books.",
      "A coroner whose findings have raised questions the law won't pursue.",
      "A constable underfunded by their own jurisdiction.",
      "A warden of a remote province with too much territory and too few hands.",
      "A revolutionary movement seeking proof of the regime's crimes.",
      "A government in exile contracting from across a border.",
      "A trade consortium protecting routes their members all depend on.",
      "A banking house with loans secured against the threatened property.",
      "A shipping magnate who needs the sea lanes cleared.",
      "A caravan master pooling funds with their rivals for a shared problem.",
      "An insurance underwriter cheaper to hire than to pay out.",
      "A treasurer skimming a budget to fund work the books cannot show.",
      "An auctioneer whose star lot has gone missing days before the sale.",
      "A mining company facing something their crews refuse to face again.",
      "A university chancellor protecting the institution from a scandal.",
      "A librarian whose collection includes things that ought not be loose.",
      "A guild of cartographers wanting verification of a rumored land.",
      "A college of magic enforcing its rules on a rogue former student.",
      "A school of philosophy testing its tenets through patronage.",
      "An academy of arms staking its reputation on its protégés.",
      "A scriptorium commissioning recovery of a stolen master text.",
      "A monastery whose seclusion has been broken by something it cannot expel.",
      "A high priest interpreting a prophecy in the only direction it can be read.",
      "A heretical sect that turns out to be right about something.",
      "An archbishop covering for one of their own under quiet investigation.",
      "A general whose campaign cannot officially extend where the party must go.",
      "A naval captain commissioning privateers under letters of marque.",
      "A mercenary captain subcontracting work too dirty even for their company.",
      "A garrison commander betrayed by their own quartermaster.",
      "An angel speaking through a mortal mouthpiece who barely understands the words.",
      "A god in disguise hiring the party in a tavern.",
      "A demon offering a contract more honest than any mortal alternative.",
      "An archfey holding court in a place the party arrived at by accident.",
      "A dragon hiring through intermediaries to keep its name out of it.",
      "A lich seeking competent help with something even it finds tedious.",
      "A vampire lord paying in coin that is real but is not what it seems.",
      "A genie repaying a small debt with disproportionate generosity.",
      "An undead king whose claim is older than any current border.",
      "A revenant funding the completion of its unfinished work.",
      "A nature spirit whose grove or river requires defense.",
      "An elemental lord acting through a bound servant.",
      "A planar conclave hiring across worlds for a common threat.",
      "An ancestor speaking through dreams across many generations.",
      "A child whose inheritance is contingent on the party's success.",
      "A widow funding the work that killed her partner.",
      "An estranged sibling who needs help and cannot ask directly.",
      "A debtor whose only asset is the favor of dangerous people.",
      "A creditor calling in a debt the party didn't know they owed.",
      "A rival the party has fought before, now reduced to hiring them.",
      "A patron's heir continuing their late parent's commissions.",
      "A character's former lover, distant and businesslike.",
      "A childhood rival who has done well and now needs help only the party can give.",
      "The party's own past self, leaving instructions through a delayed message.",
      "A town speaking through a chosen voice when no single official suffices.",
      "An entire village's collected savings handed over in a sack.",
      "A guild of beggars pooling coppers into a contract.",
      "A theatre company funding the recovery of their patron-playwright.",
      "An athletes' league protecting an upcoming tournament from sabotage.",
      "A society of explorers whose annual prize the party can compete for.",
      "An order of physicians funding work against a magical plague.",
      "A cooks' fraternity protecting their trade secret from theft.",
      "A circus whose star performer has been abducted.",
      "An animal sacred to a culture, served by the priests who speak for it.",
      "An unborn heir whose mother hires the party on the child's behalf.",
      "A talking statue whose oracular pronouncements come with funding.",
      "A magical map that hires whoever unrolls it.",
      "A self-aware sword choosing its bearers through commissions.",
      "A library that has begun writing its own commissions in the margins of overdue books.",
      "A clockwork executor enacting the will of a long-dead patron.",
      "A guildhall whose enchantments now act independently of its members.",
      "A noble in disguise, testing the party before formal engagement.",
      "A god in mortal form learning what it is like to ask for help.",
      "A criminal masquerading as a magistrate to commission a personal grudge.",
      "A patron who will reveal themselves only at the moment the work is complete.",
      "A sentient dungeon seeking adventurers to clear out a specific infestation.",
      "A forgotten deity trying to gain followers by sponsoring heroic deeds.",
      "A time traveler trying to ensure a specific historical event happens correctly.",
      "A collective of stray animals communicating through a druid intermediary.",
      "A wealthy eccentric who wants a monster captured alive for their private zoo.",
      "A disgraced noble trying to secretly fund a rebellion to regain their honor.",
      "A group of ghosts pooling their ethereal resources to hire the party to solve their murders.",
      "A powerful demon who wants the party to eliminate a rival demon's cult.",
      "A dryad whose tree is dying, seeking a magical cure from a dangerous location.",
      "A dragon in disguise who wants the party to retrieve an egg stolen from its hoard.",
      "A sentient magical item that wants to be returned to its original creator.",
      "A conclave of liches who need the party to perform a task they cannot do themselves.",
      "A vampire lord who wants the party to destroy a group of overly zealous vampire hunters.",
      "A fey queen who wants the party to retrieve a stolen artifact from a rival court.",
      "A group of mind flayers who want the party to destroy a rogue elder brain.",
      "A powerful elemental who wants the party to close a portal to another plane.",
      "A beholder who wants the party to eliminate a threat to its lair.",
      "A rakshasa who wants the party to retrieve a specific item from a heavily guarded vault.",
      "A group of yuan-ti who want the party to assassinate a rival leader.",
      "A mummy lord who wants the party to return a stolen artifact to its tomb.",
      "A death knight who wants the party to help them break their curse.",
      "A succubus who wants the party to eliminate a rival seductress.",
      "A warlock patron who wants the party to eliminate a rogue warlock.",
      "An archmage who wants the party to retrieve a rare magical component.",
      "A necromancer who wants the party to clear out a graveyard of rival undead.",
      "A druid circle who wants the party to stop a logging company from destroying a forest.",
      "A ranger conclave who wants the party to hunt down a dangerous beast.",
      "A barbarian tribe who wants the party to help them defeat a rival tribe.",
      "A thieves' guild who wants the party to pull off a massive heist.",
      "A fighters' guild who wants the party to win a grand tournament.",
      "A monks' order who wants the party to retrieve a sacred relic.",
      "A clerics' order who wants the party to destroy a dark cult.",
      "A paladins' order who wants the party to slay an evil dragon.",
      "A sorcerers' cabal who wants the party to find a powerful magical artifact.",
      "A wizards' college who wants the party to explore an ancient ruin.",
      "A bards' college who wants the party to retrieve a lost song.",
      "A warlocks' coven who wants the party to perform a dark ritual.",
      "An artificers' guild who wants the party to test a dangerous new invention.",
      "A blood hunters' order who wants the party to hunt down a powerful vampire.",
      "A gunslingers' guild who wants the party to test a new type of firearm.",
      "A mystics' order who wants the party to explore the Astral Plane.",
      "A shadowcasters' cabal who wants the party to explore the Shadowfell.",
      "A truenamers' guild who wants the party to find the true name of a powerful demon.",
      "A binders' order who wants the party to bind a powerful spirit.",
      "A dragon shamans' cabal who wants the party to awaken a sleeping elder dragon.",
      "A duskblades' order who wants the party to retrieve a powerful magical sword.",
      "A hexblades' cabal who wants the party to curse a rival faction.",
      "A spellthieves' guild who wants the party to steal a powerful magical artifact.",
      "A factotums' guild who wants the party to perform a complex series of tasks.",
      "A crusaders' order who wants the party to conquer a foreign land.",
      "A swordsages' order who wants the party to master a deadly martial art.",
      "A warblades' guild who wants the party to lead an army into battle.",
      "A dread necromancers' cabal who wants the party to raise an army of undead.",
      "A beguilers' guild who wants the party to manipulate a powerful political figure.",
      "A dragonfire adepts' cabal who wants the party to burn down a rival city.",
      "A knights' order who wants the party to protect a royal heir.",
      "A samurais' order who wants the party to avenge their fallen lord.",
      "A ninjas' guild who wants the party to assassinate a powerful leader.",
      "A scouts' guild who wants the party to map a dangerous region.",
      "A spirit shamans' order who wants the party to calm an angry spirit.",
      "A shugenjas' order who wants the party to control the elements.",
      "A wu jens' cabal who wants the party to cast a powerful taboo spell.",
      "A favored souls' order who wants the party to spread their faith.",
      "A warmages' guild who wants the party to destroy a rival army.",
      "A psions' order who wants the party to control the minds of their enemies.",
      "A psychic warriors' guild who wants the party to win a grand tournament.",
      "A soulknifes' guild who wants the party to assassinate a powerful leader.",
      "A wilders' cabal who wants the party to unleash their psionic powers.",
      "A lurks' guild who wants the party to pull off a massive heist.",
      "A ardents' order who wants the party to manipulate the emotions of others.",
      "A divine minds' order who wants the party to enforce their divine will.",
      "A dragonborn clan who wants the party to reclaim their ancestral homeland.",
      "A tiefling enclave who wants the party to stop a demonic invasion.",
      "A aasimar enclave who wants the party to stop a celestial invasion.",
      "A genasi clan who wants the party to stop an elemental invasion.",
      "A goliath tribe who wants the party to defeat a powerful giant.",
      "A shifter tribe who wants the party to stop a werewolf plague.",
      "A warforged enclave who wants the party to stop a rogue artificer.",
      "A local tavern owner who wants the party to deal with a rat problem.",
      "A concerned mother who wants the party to find her missing son.",
      "A desperate farmer who wants the party to stop a wolf pack from killing their sheep.",
      "A wealthy merchant who wants the party to escort a caravan to the next town.",
      "A local priest who wants the party to clear out an abandoned temple.",
      "A suspicious guard who wants the party to investigate a series of robberies.",
      "A mysterious stranger who wants the party to deliver a package to a secret location.",
      "A frightened child who wants the party to deal with a monster under their bed.",
      "A gruff blacksmith who wants the party to retrieve a rare type of ore.",
      "A eccentric inventor who wants the party to test their latest creation.",
      "A grumpy old man who wants the party to get off his lawn.",
      "A confused tourist who wants the party to give them directions.",
      "A loud bard who wants the party to listen to their new song.",
      "A quiet scholar who wants the party to find a specific book.",
      "A busy mayor who wants the party to deal with a minor problem they don't have time for.",
      "A lazy noble who wants the party to do something they are too lazy to do themselves.",
      "A crazy old cat lady who wants the party to find her missing cat.",
      "A ambitious young adventurer who wants the party to help them make a name for themselves.",
      "A retired hero who wants the party to take up their mantle.",
      "A talking dog who wants the party to find their owner.",
    ],
  },

};
