// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const complicationTables: Record<string, InspireTable> = {
  moralQuandaries: {
    id: 'moralQuandaries',
    title: 'Moral Quandaries',
    attribution: 'Original',
    entries: [
      "Two allies the party desperately needs hate each other and refuse to work together.",
      "Someone the party loves demands they abandon a quest that affects many lives.",
      "A close friend pleads with the party to spare the villain to prove their own better nature.",
      "An NPC the party trusts asks for a chance to redeem themselves through a dangerous mission.",
      "A character's oath or code is incompatible with the most effective path forward.",
      "A loyal companion's faith demands an action the rest of the party finds repugnant.",
      "The party must choose between catching the villain and saving innocents the villain is harming.",
      "Two important advisors give directly opposing strategic advice — choosing one loses the other.",
      "A prisoner who deserves death has information the party cannot get any other way.",
      "An innocent will be punished for a crime the party committed.",
      "A child idolizes someone who genuinely doesn't deserve it — speaking up would shatter them.",
      "The party must decide whether to violate a sacred place to save lives.",
      "A villain offers to surrender peacefully if the party will simply let them keep what they took.",
      "Someone the party freed in an earlier adventure has gone on to commit terrible acts.",
      "The cure for one disaster requires materials taken from the victims of another.",
      "A young person begs to join the adventure that will likely kill them.",
      "The party can save a dying friend by accepting a deal that will haunt them.",
      "Two communities depend on a single scarce resource the party controls access to.",
      "A truth the party uncovered will destroy a peace that everyone is currently grateful for.",
      "Someone the party promised to protect asks them to break that promise to do what is right.",
      "The party must decide whether to expose a beloved leader's old crime or let the lie continue.",
      "A captured enemy will be executed under local law that the party finds unjust.",
      "A grieving parent asks the party to lie about how their child died.",
      "A confession freely given was obtained in a way that should not have been used.",
      "The only one who can identify a killer is too young to be believed in court.",
      "A dying oath-breaker asks for the rites their oath denied them.",
      "An animal the party loves is suffering, and the only available end is at their hands.",
      "A spy the party has come to like must be turned in for the party's own safety.",
      "Two villages each present convincing evidence that the same stretch of land is theirs.",
      "A treasure recovered from the dungeon was stolen, originally, from people still alive.",
      "A wounded enemy combatant could be treated, or left, and the party has limited supplies.",
      "The party can ransom a captive for funds they desperately need or release them freely.",
      "A noble offers the party shelter on the condition that they betray a poorer ally.",
      "A village will host the party if they will publicly endorse a local feud the party knows is wrong.",
      "An ailing patron will pay double for results delivered before they die — at the cost of doing them right.",
      "A magical item could save a hundred strangers or one specific friend, but not both.",
      "An apology owed by one party member would heal a community but humiliate the speaker.",
      "A child wants to know what happened to a parent the party knows died badly.",
      "A trusted mentor asks the party to lie to a court that has been good to them.",
      "Stopping the villain requires letting an opportunist seize the position the villain held.",
      "A friend's last request is to be killed quickly, and the party has not consented to be the one to do it.",
      "A villager confesses to a crime the party knows another villager actually committed.",
      "A guilty party offers full restitution to their victims if the party will let them escape justice.",
      "A villain offers to spare a city in exchange for being allowed to take another.",
      "The party is asked to vouch for the character of someone whose character is questionable.",
      "A spell could read a sleeping ally's thoughts and resolve the question — without consent.",
      "A poison only the villain knows the cure for is already in someone the party loves.",
      "An old enemy offers genuine help and there is no obvious catch.",
      "A trusted ally has clearly broken the law to protect the party from worse harm.",
      "The party can finish the adventure quickly through means a paladin in the group will not survive doing.",
      "A faction the party despises is the right ally for the next battle.",
      "A faction the party respects is asking them to do something only the despised faction would do.",
      "A child is the heir to a dynasty no one alive thinks should continue.",
      "A grieving widow asks the party to kill the lover she has chosen not to leave.",
      "A long-suffering servant of the villain has earned the right to be heard — and to be spared.",
      "The truth would shatter the patron, and lying would let them die in peace.",
      "A confessor of one faith has been entrusted with secrets that would save lives in another's hands.",
      "A judge offers leniency in exchange for testimony the party isn't sure is honest.",
      "An infant cursed at birth will grow into a monster — or, perhaps, will not.",
      "A village wants the party to drive out a creature that has done nothing yet but might.",
      "A dying enemy asks for water, and the water is needed for someone else.",
      "A patron promised one reward and is now offering twice as much to take a different action.",
      "A loyal hireling has been stealing — small things, badly hidden, plainly out of need.",
      "An oath of secrecy binds one party member to information the rest of the party needs.",
      "A community offers gratitude in a form one of the party's gods specifically forbids.",
      "A stranger demands the return of an heirloom the party legitimately purchased from a thief.",
      "An ally's beloved is the villain — and the ally insists they have changed.",
      "The party can save one captive easily or three captives at significantly greater risk.",
      "An infiltrated cult member begs the party to let them keep their family by lying for them.",
      "A merchant the party owes their lives to is selling something the party knows is unsafe.",
      "An enemy who once spared a party member now asks that same mercy in return.",
      "A magical truth-compulsion would resolve a dispute, but compelling truth is forbidden by local law.",
      "A bandit camp the party plans to clear includes people who were taken there as captives.",
      "An innocent has been framed in a way that protects someone the party would also rather see protected.",
      "A friend who served the villain wants to come back, with no penance the party finds adequate.",
      "A starving family has stolen from the temple the party is sworn to protect.",
      "A magical sleep has been laid on a town, and waking the town will also wake what it contained.",
      "A prophecy names a specific child for a specific terrible death the party can prevent.",
      "A war hero deeply respected by the party is the same person who burned a now-abandoned village.",
      "A piece of evidence vital to the party was stolen by a thief now in serious danger.",
      "A monstrous creature the party hunts turns out to have young that will not survive without it.",
      "The only escape route runs through a sanctuary that has refused all weapons within its walls.",
      "A confession given under threat is admissible in this jurisdiction, and the party would be believed.",
      "A ritual that will save a region requires the willing self-sacrifice of someone the party would have to ask.",
      "A useful lie protects a fragile peace, and the party are the only ones in a position to maintain it.",
      "A judge with full authority asks the party to render the verdict in their place.",
      "An apparition asks the party to settle an injustice that occurred long before they were born.",
      "A patron pays for an outcome and demands the party not seek any explanation for why.",
      "A magical creature offers a wish at the cost of a memory the granter, not the receiver, chooses.",
      "A child wants justice for a parent in a way that requires the child to remain a witness.",
      "An act of vandalism on a sacred symbol would, this once, save the lives of those it represents.",
      "A monstrous villain has done one verifiable kindness, recently, and asks credit for it.",
      "A reward offered for a fugitive is generous enough to settle every debt the party has.",
      "A wounded animal the party is responsible for harming is begging — clearly — for help.",
      "The party are asked to certify, in writing, an outcome they witnessed but cannot fully explain.",
      "A faithful follower of the villain repents on the steps of the temple and asks for sanctuary.",
      "An enemy combatant has surrendered, and the surrender will be ignored by the local soldiers if the party leaves.",
      "An old companion has slipped into addiction or madness and demands not to be helped.",
      "A long-standing ally publicly disowns the party to keep them safe from political consequences.",
      "The right thing to do will be remembered as the wrong thing for the rest of the party's lives.",
      "The party must choose whether to kill a child who is destined to become a terrible tyrant.",
      "A magical artifact can save the life of a party member, but it requires the sacrifice of a stranger.",
      "The party must decide whether to overthrow a harsh but effective ruler in favor of a kind but incompetent one.",
      "A group of refugees begs the party for protection, but helping them will bring the wrath of a powerful army.",
      "The party discovers that a revered local hero is actually a fraud, and exposing them will crush the town's spirit.",
      "A captured enemy soldier offers crucial intelligence in exchange for their freedom, but the party knows they will likely kill again.",
      "The party must decide whether to use a powerful dark magic spell to defeat a greater evil, risking corruption.",
      "A wealthy merchant offers the party a massive bribe to look the other way while they commit a crime.",
      "The party must choose whether to save a burning orphanage or a burning library full of ancient knowledge.",
      "A sentient machine begs the party not to deactivate it, arguing it has a right to live.",
      "The party must decide whether to intervene in a cultural practice they find barbaric, but the locals consider sacred.",
      "A beloved party member is infected with a highly contagious, incurable disease, and the party must decide their fate.",
      "The party discovers that their employer's wealth comes from slave labor, but the money is needed to save a kingdom.",
      "A powerful demon offers to fulfill the party's greatest desires, but the price is their souls.",
      "The party must choose whether to break a promise to a dying friend in order to save lives.",
      "A group of rebels uses terrorist tactics to fight an oppressive regime, and the party must decide whose side they are on.",
      "The party must decide whether to execute a prisoner who committed terrible crimes but has since reformed and done good.",
      "A magical artifact grants the party incredible power, but it slowly drains the life of the surrounding environment.",
      "The party must choose whether to sacrifice a small village to save a large city.",
      "A powerful wizard offers to erase a painful memory from a party member's mind, but it might change who they are.",
      "The party discovers that a local religious order is hoarding food while people starve, claiming it's for a coming apocalypse.",
      "A group of vigilantes is hunting down criminals, but their methods are brutal and they often kill innocents.",
      "The party must decide whether to betray an ally to gain an advantage in a crucial battle.",
      "A magical creature asks the party to kill it, as its existence causes suffering to others.",
      "The party must choose whether to save a brilliant scientist who is also a terrible person, or let them die.",
      "A local lord demands the party turn over a fugitive they believe is innocent, threatening the town if they refuse.",
      "The party discovers a way to time travel and change a past tragedy, but it might create a paradox or worse future.",
      "A powerful artifact can revive the dead, but it requires the sacrifice of a living soul.",
      "The party must decide whether to tell a lie that will bring peace, or the truth that will cause war.",
      "A group of desperate people steals food to survive, and the party is hired to stop them.",
      "The party must choose whether to support a corrupt government that maintains order, or a rebel group that brings chaos.",
      "A magical creature offers the party immense wealth, but the gold turns to dust when given to the needy.",
      "The party must decide whether to save a member of their own group or a group of innocent strangers.",
      "A powerful demon offers to stop a war, but demands the soul of an innocent child as payment.",
      "The party must choose whether to destroy a beautiful piece of art that is cursed to bring misfortune to anyone who sees it.",
      "A group of monks has sworn a vow of silence, and the party needs them to speak to prevent a disaster.",
      "The party must decide whether to use a powerful weapon that will win the war, but cause massive collateral damage.",
      "A local ruler is executing people for minor crimes, and the party must decide whether to intervene.",
      "The party must choose whether to save a traitor who has valuable information, or let them face justice.",
      "A magical artifact can heal any wound, but it causes terrible pain to the user.",
      "The party must decide whether to help a group of exiles return to their homeland, even though it will cause conflict.",
      "A powerful wizard is performing dangerous experiments that could benefit society, but risk catastrophic failure.",
      "The party must choose whether to respect the wishes of a dying person, even if it goes against the party's goals.",
      "A group of mercenaries is hired to protect a town, but they are extorting the townsfolk.",
      "The party must decide whether to steal an artifact that belongs to an evil cult, even though stealing is wrong.",
      "A magical creature is being hunted for its valuable parts, and the party must decide whether to protect it or profit.",
      "The party must choose whether to support a leader who is effective but cruel, or one who is kind but ineffective.",
      "A powerful demon is sealed away, but the seal is weakening, and the party must decide whether to reinforce it or let it break.",
      "The party must decide whether to sacrifice their own happiness to ensure the happiness of others.",
      "A local religion demands a sacrifice to appease their god, and the party must decide whether to intervene.",
      "The party must choose whether to tell a painful truth or a comforting lie to someone they care about.",
      "A group of people is trapped in a burning building, and the party can only save a few of them.",
      "The party must decide whether to use a forbidden spell to save a life, knowing the consequences.",
      "A powerful artifact can grant any wish, but the wish always comes with a terrible twist.",
      "The party must choose whether to avenge a fallen friend, knowing it will start a cycle of violence.",
      "A magical creature offers the party a choice: immense power or the ability to save a loved one.",
      "The party must decide whether to let a criminal go free to gain their help, or bring them to justice.",
      "A group of refugees is seeking asylum, but the town they are trying to enter is already struggling with resources.",
      "The party must choose whether to destroy a dangerous artifact or study it to understand its power.",
      "A powerful demon offers the party a chance to undo their biggest mistake, but at a terrible cost.",
      "The party must decide whether to break the law to do what is right, or uphold the law even when it is unjust.",
      "A local leader is using fear to control their people, and the party must decide whether to expose them.",
      "The party must choose whether to support a rebellion that is likely to fail, or stay out of it.",
      "A magical creature asks the party to help it die, as it has lived too long and is tired.",
      "The party must decide whether to accept the help of an evil creature to defeat a greater evil.",
      "A group of people is suffering from a curse, and the party must decide whether to lift it, knowing it will pass to them.",
      "The party must choose whether to save a person who has wronged them in the past.",
      "A powerful wizard is trying to achieve immortality, but the process requires the sacrifice of innocents.",
      "The party must decide whether to use violence to solve a problem when peaceful methods have failed.",
      "A local religion is spreading a message of hate, and the party must decide whether to silence them.",
      "The party must choose whether to trust someone who has betrayed them before.",
      "A magical creature is being held captive for its magical properties, and the party must decide whether to free it.",
      "The party must decide whether to sacrifice a small part of their soul for a necessary power.",
      "A group of people is trying to rebuild their lives after a disaster, but the party needs their resources to complete a quest.",
      "The party must choose whether to expose a secret that will cause chaos but is the right thing to do.",
      "A powerful demon offers the party the power to defeat their enemies, but it will corrupt them.",
      "The party must decide whether to forgive someone who has committed a terrible crime.",
      "A local leader is making decisions that benefit the few at the expense of the many, and the party must intervene.",
      "The party must choose whether to risk everything to save one person, or sacrifice that person to save many.",
      "A magical creature offers the party a glimpse into the future, but it might drive them mad.",
      "The party must decide whether to follow orders that they believe are morally wrong.",
      "A group of people is being persecuted for their beliefs, and the party must decide whether to protect them.",
      "The party must choose whether to use deception to achieve a noble goal.",
      "A powerful wizard is offering to teach the party a spell that can solve all their problems, but it has a dark cost.",
      "The party must decide whether to hold someone accountable for an accident.",
      "A local religion is demanding that the party perform a ritual that goes against their beliefs.",
      "The party must choose whether to sacrifice their own lives to save the world.",
      "A magical creature offers the party a choice between saving their family or saving their friends.",
      "The party must decide whether to accept a reward for doing the right thing, or refuse it out of principle.",
      "A group of people is trying to start a new life, but their past mistakes are catching up to them, and the party must help.",
      "The party must choose whether to let go of their past trauma or hold onto it for strength.",
      "A powerful demon offers the party a chance to change their past, but it will erase their current relationships.",
      "The party must decide whether to trust their instincts or follow logic when making a difficult decision.",
      "A local leader is offering the party a position of power, but it requires them to compromise their values.",
      "The party must choose whether to fight a battle they know they will lose, or surrender.",
      "A magical creature offers the party a wish, but the party must agree on what to wish for.",
      "The party must decide whether to sacrifice their own freedom to save others.",
    ],
  },

  sideQuests: {
    id: 'sideQuests',
    title: 'Side Quests',
    attribution: 'Original',
    entries: [
      "Recover a specific item rumored to be somewhere in this area.",
      "Take from the villain something the villain doesn't yet know is missing.",
      "Locate and persuade a single NPC who has information no one else does.",
      "Free a captive held somewhere along the path the party is already taking.",
      "Find what happened to an NPC who went this way and never came back.",
      "Slay a specific creature whose death would simplify the main quest.",
      "Learn the truth of a strange phenomenon affecting the area.",
      "Recruit someone whose specific skill the party will need later.",
      "Deliver a letter to a recipient who has been hard to reach.",
      "Carry medicine to a household that cannot send anyone for it themselves.",
      "Return a lost dog, hawk, or other animal to its anxious owner.",
      "Settle a small debt on behalf of someone who can't show their face in town.",
      "Find a lost wedding ring before the wedding tomorrow.",
      "Buy a particular cask of wine the buyer doesn't want traced to them.",
      "Walk an elderly pilgrim to a shrine the next village over.",
      "Find a child's lost toy that the child has been inconsolable about.",
      "Bring a working chicken back to a coop emptied by a thief.",
      "Carry a love letter and wait for the reply.",
      "Witness a small payment and sign as a third party.",
      "Pick up a package from a tailor and deliver it without opening it.",
      "Deliver tools to a smith who lost his to a flood last week.",
      "Help an old soldier locate the grave of a comrade buried near here.",
      "Walk a frightened bride to her wedding through a forest.",
      "Find the right grave in a cemetery so a mourner can pay respects.",
      "Deliver a message of apology from one neighbor to another.",
      "Carry a child to safety while their parents finish closing up shop.",
      "Track down a debtor and politely encourage payment.",
      "Buy seed grain at a market and bring it back before the planting hour.",
      "Carry a wax-sealed jar to a herbalist without breaking the seal.",
      "Find an apprentice who has run away from a craft they hate.",
      "Identify which of two coins is the counterfeit.",
      "Walk a flock of geese from one pasture to another along a road they fear.",
      "Read a letter aloud to someone who can't read it for themselves.",
      "Witness a will being signed by a dying person.",
      "Find a recipe a cook misplaced before tonight's meal.",
      "Buy a single specific book from a stall before another buyer claims it.",
      "Carry a song from one bard to another exactly as it was sung.",
      "Find the owner of a purse left behind at an inn.",
      "Deliver a complaint to a neighbor over an ongoing nuisance.",
      "Settle a wager by witnessing the outcome of a small contest.",
      "Carry a candle lit at one shrine to another without letting it go out.",
      "Walk a goat through town on market day for someone too embarrassed to do it.",
      "Identify the bird whose call is keeping a household awake.",
      "Buy bread from a baker who has stopped speaking to your patron.",
      "Find a quiet spot in the wood where a couple can meet undisturbed.",
      "Carry an apology gift to a slighted relation and read the note aloud.",
      "Look in on a sick aunt and report honestly on her condition.",
      "Walk a deaf elder to a hearing before a magistrate.",
      "Find a man who owes alimony and is hiding behind his work.",
      "Coax a cat down from a high shelf without breaking anything around it.",
      "Drop a coin into the offering bowl of three specific shrines in order.",
      "Carry a thank-you basket from one farm to another after a barn raising.",
      "Find which stall at the market sells a particular spice today.",
      "Identify a stranger whose face a friend keeps seeing in dreams.",
      "Walk a horse home that wandered in from somewhere unknown.",
      "Pay a respectful visit to the family of someone who died abroad.",
      "Recover a hat blown off a balcony into a courtyard nobody enters.",
      "Sit with a dying neighbor through one long evening.",
      "Find the rumor source that has a respectable family upset.",
      "Walk a guilty man to confession and stay until he goes through with it.",
      "Carry a single intact egg across town for a baker's specific recipe.",
      "Lay flowers at a grave each day for a week on behalf of someone abroad.",
      "Buy a piglet at fair price and walk it to a farm that needs one.",
      "Confirm a rumor by speaking with one named witness and returning.",
      "Find an apprentice's lost tool kit before the master notices it missing.",
      "Carry an iron pot from a tinker's shop to a kitchen still hot enough to use.",
      "Walk a frightened child past a house they have learned to fear.",
      "Locate the original of a portrait everyone in town has heard about.",
      "Find which of two visiting traders has been honest about their goods.",
      "Carry a gift between feuding cousins and try not to be drawn into it.",
      "Buy back a pawned heirloom before the pawnbroker sells it on.",
      "Settle a small accounting question between two neighbors over a fence line.",
      "Find a single specific flower in bloom this week and bring it home.",
      "Recover a stolen sign and rehang it without the thief noticing.",
      "Read a notice aloud in the square at noon for someone too proud to do it.",
      "Carry a small bag of coin to a soldier's widow without explanation.",
      "Verify that a courier reached his destination and ask for proof.",
      "Walk a beekeeper's complaint to a neighbor whose smoke is killing the hive.",
      "Find a missing bell from a shrine before the holy day arrives.",
      "Carry a vial of clean water from a particular spring to a sick child.",
      "Witness a baptism, naming, or coming-of-age on behalf of an absent relation.",
      "Buy a small loaf and leave it at a doorstep without being seen.",
      "Walk a stray pig home before someone less honest claims it.",
      "Identify which of three strangers in town matches a description in a letter.",
      "Pick up laundry from a washer who refuses to deliver to one particular house.",
      "Carry a sealed envelope to a magistrate's chambers without speaking on its contents.",
      "Find which fisher caught the unusual fish a curious patron wants to buy.",
      "Walk a blind musician to a hall where they are expected to play tonight.",
      "Settle a small bet on which of two trees was struck by last week's lightning.",
      "Buy a single nail from a smith and leave it on a specific doorstep.",
      "Find a runaway who has not gone far and will come back if asked gently.",
      "Carry a child's drawing across town to a grandparent who has been ill.",
      "Identify which dog in a kennel matches the description of a lost pet.",
      "Find a misplaced ledger before the bookkeeper has to admit he lost it.",
      "Walk a young scholar to their first examination so they don't lose nerve.",
      "Buy two yards of cloth in a specific shade for an embarrassed customer.",
      "Carry a small piece of wedding cake to a friend who couldn't attend.",
      "Find the rumor's first speaker and learn what they actually said.",
      "Confirm that a particular shop is open this morning without going in.",
      "Carry a borrowed book back to its owner before the loan is noticed late.",
      "Deliver a love letter to someone who is heavily guarded.",
      "Find a lost pet that happens to be a dangerous magical creature.",
      "Settle a bet between two rival wizards about the properties of a local plant.",
      "Escort an elderly scholar to a specific hilltop to observe a rare astrological event.",
      "Retrieve a family heirloom from a pawn shop run by a notoriously tricky merchant.",
      "Investigate a series of strange noises coming from the town well.",
      "Help a young apprentice bake a complex, magical cake for their master's birthday.",
      "Distract a guard so a group of kids can sneak into a restricted area.",
      "Translate an ancient text that was found inscribed on a local farmer's plow.",
      "Convince a stubborn ghost to move its haunting to a different room.",
      "Find a specific rare flower to use as a cure for a minor, but annoying, ailment.",
      "Settle a dispute between two neighbors over the property line.",
      "Deliver a highly volatile alchemical potion across town without spilling a drop.",
      "Help a bard write the perfect song to win a local competition.",
      "Find out who has been leaving anonymous gifts on the mayor's doorstep.",
      "Escort a group of orphans on a field trip to a 'safe' nearby ruin.",
      "Retrieve a lost item from the bottom of a murky lake.",
      "Investigate a sudden influx of very aggressive squirrels in the local park.",
      "Help a merchant negotiate a trade deal with a difficult client.",
      "Distract a crowd while a street performer sets up their act.",
      "Translate a cryptic message left by a traveling fortune teller.",
      "Convince a local tavern owner to change their menu.",
      "Find a specific type of wood for a local carpenter.",
      "Settle a dispute between two rival gangs of street urchins.",
      "Deliver a package to a hermit living in a remote cave.",
      "Help a local farmer deal with a minor pest problem.",
      "Find out who has been defacing the local statues.",
      "Escort a group of tourists on a tour of the city.",
      "Retrieve a lost piece of jewelry from a crowded marketplace.",
      "Investigate a strange glowing light in the local graveyard.",
      "Help a local inventor test their new, slightly dangerous, invention.",
      "Distract a busy official so someone can slip them an important document.",
      "Translate a strange language spoken by a newly arrived merchant.",
      "Convince a local noble to fund a public works project.",
      "Find a specific type of fabric for a local tailor.",
      "Settle a dispute between two rival merchants.",
      "Deliver a message to a spy hidden in the city.",
      "Help a local doctor deal with a sudden outbreak of a strange, but harmless, disease.",
      "Find out who has been starting rumors about the local mayor.",
      "Escort a group of prisoners to a new facility.",
      "Retrieve a lost document from a highly secure building.",
      "Investigate a strange smell coming from the local sewer.",
      "Help a local chef find a rare ingredient for a special dish.",
      "Distract a guard so someone can escape from jail.",
      "Translate a strange symbol found on a local building.",
      "Convince a local leader to step down.",
      "Find a specific type of metal for a local blacksmith.",
      "Settle a dispute between two rival families.",
      "Deliver a secret message to a rebel leader.",
      "Help a local historian find a lost artifact.",
      "Find out who has been sabotaging the local water supply.",
      "Escort a group of diplomats to a peace conference.",
      "Retrieve a lost item from a dangerous dungeon.",
      "Investigate a strange noise coming from the local forest.",
      "Help a local wizard find a lost spellbook.",
      "Distract a powerful enemy so someone can escape.",
      "Translate a strange language spoken by a dangerous monster.",
      "Convince a powerful enemy to surrender.",
      "Find a specific type of magical component for a powerful spell.",
      "Settle a dispute between two powerful nations.",
      "Deliver a dangerous artifact to a secure location.",
      "Help a local hero defeat a powerful villain.",
      "Find out who has been summoning demons in the local town.",
      "Escort a powerful artifact to a secure location.",
      "Retrieve a lost item from a powerful dragon's hoard.",
      "Investigate a strange glowing light in the sky.",
      "Help a local god answer a prayer.",
      "Distract a powerful god so someone can escape.",
      "Translate a strange language spoken by a powerful alien.",
      "Convince a powerful god to spare the world.",
      "Find a specific type of magical component for a powerful spell that will save the world.",
      "Settle a dispute between two powerful gods.",
      "Deliver a dangerous artifact to a secure location to prevent the end of the world.",
      "Help a local hero defeat a powerful villain who is trying to destroy the world.",
      "Find out who has been trying to destroy the world.",
      "Escort a powerful artifact to a secure location to prevent the end of the world.",
      "Retrieve a lost item from a powerful dragon's hoard to save the world.",
      "Investigate a strange glowing light in the sky that might destroy the world.",
      "Help a local god answer a prayer that will save the world.",
      "Distract a powerful god so someone can escape and save the world.",
      "Translate a strange language spoken by a powerful alien who is trying to destroy the world.",
      "Convince a powerful god to spare the world from destruction.",
      "Find a specific type of magical component for a powerful spell that will save the universe.",
      "Settle a dispute between two powerful gods who are trying to destroy the universe.",
      "Deliver a dangerous artifact to a secure location to prevent the end of the universe.",
      "Help a local hero defeat a powerful villain who is trying to destroy the universe.",
      "Find out who has been trying to destroy the universe.",
      "Escort a powerful artifact to a secure location to prevent the end of the universe.",
      "Retrieve a lost item from a powerful dragon's hoard to save the universe.",
      "Investigate a strange glowing light in the sky that might destroy the universe.",
      "Help a local god answer a prayer that will save the universe.",
      "Distract a powerful god so someone can escape and save the universe.",
      "Translate a strange language spoken by a powerful alien who is trying to destroy the universe.",
      "Convince a powerful god to spare the universe from destruction.",
      "Find a specific type of magical component for a powerful spell that will save reality.",
      "Settle a dispute between two powerful gods who are trying to destroy reality.",
    ],
  },

  sideComplications: {
    id: 'sideComplications',
    title: 'Side Complications',
    attribution: 'Original',
    entries: [
      "A piece of equipment crucial to the next stage breaks at the worst time.",
      "The party's funds are stolen, frozen, or denied to them.",
      "A misunderstanding makes the party temporary targets of local law.",
      "Weather, terrain, or season makes the obvious route impossible.",
      "An NPC the party trusted has been replaced — recently and convincingly.",
      "A messenger arrives with urgent news that complicates current plans.",
      "Someone the party harmed earlier returns and remembers everything.",
      "A creature has been following the party for some time, and now reveals itself.",
      "The party arrives at a location to find others have been there first.",
      "A magical effect — wild magic, divine sign, planar bleed — alters the situation.",
      "A mount, familiar, or pack animal goes lame at the wrong moment.",
      "Rations spoil overnight, leaving the party hungry going in.",
      "A spellcaster wakes to find a prepared spell stubbornly refusing to settle.",
      "Local guides quote prices far higher than expected — or refuse outright.",
      "A border is closed by decree, and the obvious crossing is no longer an option.",
      "Papers, permits, or letters of passage are demanded by suspicious officials.",
      "A festival or procession has filled the streets the party needs to move through.",
      "A bridge, gate, or causeway has been damaged since the party last passed.",
      "The inn the party planned to use is fully booked or closed for cleaning.",
      "Another adventuring band beats the party to a tavern hire and takes the work.",
      "A child latches onto one of the party and will not be shaken loose.",
      "A drunken stranger insists they know one of the party from somewhere.",
      "A street performer recognizes a disguise and starts loudly admiring it.",
      "A pickpocket lifts something small but critical from a party member.",
      "A merchant short-changes the party deliberately, daring them to make a scene.",
      "A rumor spreads through town placing the party at the scene of a crime they didn't commit.",
      "A bounty notice goes up overnight bearing a face that resembles one of the party.",
      "A local zealot publicly denounces something one of the party did or wore.",
      "A clerk insists a critical document has been mis-filed and cannot be found today.",
      "An ally cancels at the last minute, citing an emergency the party can't verify.",
      "A second party arrives chasing the same lead from a different patron.",
      "A guide turns out to know less about the route than they claimed.",
      "A hired sword takes a better offer mid-job and walks away clean.",
      "A patron changes the terms of the job after work has already started.",
      "A patron goes silent — no reply, no payment, no answer at the door.",
      "A creditor catches up with one of the party at exactly the wrong moment.",
      "An old contact insists on a long conversation before they'll hand over what's needed.",
      "A useful contact has died, moved, or been arrested since the party last needed them.",
      "Translation breaks down at a critical exchange — the interpreter is hiding something.",
      "A vital map proves to be from a different era and no longer matches the terrain.",
      "The party realizes the directions they were given are a regional dialect they misread.",
      "A door, lock, or seal that should be straightforward refuses to yield.",
      "Spell components needed for the next step are unavailable at any local supplier.",
      "A holy day forbids the kind of work the party intended to do today.",
      "A passing patrol takes interest in a weapon openly carried.",
      "The dog wakes the neighborhood at exactly the wrong moment.",
      "A river is flooded, a pass is snowed in, or a road is washed out.",
      "Fog rolls in heavy enough to make tracking — or being tracked — much harder.",
      "An unseasonable heat or cold drains the party faster than expected.",
      "A swarm of insects, vermin, or scavengers descends on the camp.",
      "Wildlife in the area is behaving strangely — restless, silent, or migrating away.",
      "A local guide insists on a long ritual before they'll lead the party further.",
      "A guard at a checkpoint has personal cause to dislike one of the party.",
      "A rival demands a duel, contest, or public apology in front of witnesses.",
      "A noble's procession blocks a road and will not be hurried for anyone.",
      "A funeral procession requires hours of waiting — and visible respect.",
      "A drunk swings at one of the party in a tavern over old, unrelated business.",
      "The party's lodging is searched while they're out — nothing taken, much disturbed.",
      "A landlord raises the rent, evicts them, or demands they leave by morning.",
      "Stolen goods turn up in the party's room with no clear culprit.",
      "A piece of jewelry, sigil, or token has gone missing from a party member's belongings.",
      "An NPC the party promised to help shows up demanding that help right now.",
      "Letters from home arrive carrying news that distracts one party member.",
"A relative the party didn't know they had appears asking for shelter.",
      "A character's old superior, master, or commander is in town and wants to speak.",
      "An old debt — favor, money, or honor — is called in at this exact moment.",
      "A character recognizes a face in the crowd they were not supposed to ever see again.",
      "A childhood friend of one party member is now working for the opposition.",
      "A former lover turns up entangled with the current job in unexpected ways.",
      "An ex-companion the party parted with on bad terms is also pursuing this lead.",
      "A character's hometown sends a delegation asking them to come back for something serious.",
      "A holy order requests one of the party come account for an old transgression.",
      "A street prophet specifically points at one of the party and shouts a warning.",
      "A curse the party thought lifted shows a small but unmistakable new symptom.",
      "A magical item begins behaving unpredictably for no obvious reason.",
      "A familiar or animal companion goes missing during the night.",
      "A spellbook page is found torn out or scorched in the morning.",
      "A potion in the party's stores has clouded and no one wants to be the one to test it.",
      "A consecrated location nearby is interfering with one party member's abilities.",
      "Local groundwater tastes wrong — and so does anything made with it.",
      "The night sky over this region shows a star that wasn't there last week.",
      "A pet, mount, or companion takes an instant dislike to a key local figure.",
      "An item the party sold turns up in the possession of an enemy.",
      "A merchant the party shopped from yesterday has been arrested today.",
      "A guide says the route is haunted this week — not always, just this week.",
      "Children whisper warnings about the party that they couldn't have invented themselves.",
      "A bard composes an unflattering song about the party that's catching on.",
      "Someone is offering a small bounty for information about the party's movements.",
      "A trade caravan refuses to share the road with the party, citing bad luck.",
      "A small shrine on the path demands an offering the party didn't bring.",
      "A toll bridge has changed its terms — and the new keeper does not bargain.",
      "A nighttime watch is disrupted by something that leaves no tracks at all.",
      "An ally's family has decided this is the trip on which they finally meet the party.",
      "A formal invitation arrives that cannot be politely refused.",
      "A pet of one of the party falls suddenly, alarmingly ill.",
      "The party is invited to judge a local dispute, and refusing will insult someone important.",
      "A traveling priest insists on blessing the party at length before they depart.",
      "A talkative companion attaches themselves to the party and shares everything they overhear.",
      "Two NPCs the party needs separately turn out to be feuding and will not be in a room together.",
      "A loud, conspicuous celebration in town makes any quiet work impossible tonight.",
    ],
  },

};
