// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const goalTables: Record<string, InspireTable> = {
  dungeonGoals: {
    id: 'dungeonGoals',
    title: 'Dungeon Goals',
    attribution: 'Original',
    entries: [
      "Stop the inhabitants from raiding nearby settlements.",
      "Foil a specific scheme being orchestrated from within.",
      "Destroy a magical wellspring corrupting the surrounding area.",
      "Acquire a hoard of treasure rumored to lie deep within.",
      "Find a single specific item needed to complete a ritual.",
      "Retrieve property stolen from a patron or community.",
      "Discover information needed to solve a mystery aboveground.",
      "Rescue a prisoner held by the dungeon's master.",
      "Discover the fate of a previous expedition that never returned.",
      "Find an NPC who was last seen entering the area.",
      "Slay a legendary creature making its lair here.",
      "Investigate strange phenomena originating from this place.",
      "Pursue enemies who fled into the dungeon for refuge.",
      "Escape from the dungeon after being imprisoned within it.",
      "Clear the ruin so it can be claimed and rebuilt.",
      "Discover why a third party is also exploring this dungeon.",
      "Survive a set period within the dungeon as a test or wager.",
      "Negotiate with the dungeon's master rather than kill them.",
      "Hide in the dungeon from a threat outside.",
      "Seal the dungeon permanently so nothing else escapes.",
      "Disarm an ancient defense system before it activates on the surface.",
      "Recover the remains of a fallen hero for proper burial.",
      "Map the layout in full for a patron who intends to return later.",
      "Sabotage a supply line that runs through these depths.",
      "Plant evidence that will incriminate the dungeon's master to outside powers.",
      "Retrieve a captive's journal that contains coded military intelligence.",
      "Bring a relic out so it can be presented at a coronation.",
      "Bring a relic in so it can be returned to where it belongs.",
      "Witness firsthand what happens at a recurring midnight ritual.",
      "Interrupt a marriage being conducted between unwilling parties below.",
      "Recover a child taken weeks ago and presumed lost.",
      "Confirm or refute a rumor that a dead enemy is alive down here.",
      "Lead a captured ally back out before their captors notice them gone.",
      "Convince a faction inside to switch sides before the next assault.",
      "Steal the master's personal correspondence without alerting them.",
      "Identify the inside agent feeding information to the dungeon from above.",
      "Lift a curse anchored to an object kept somewhere in these chambers.",
      "Cleanse a desecrated shrine and restore its proper rites.",
      "Locate the source of a poison spreading into the water table.",
      "Find the missing piece of a broken artifact stored deeper within.",
      "Verify whether a sealed chamber has been opened recently.",
      "Cut off the dungeon's reinforcements by collapsing a known tunnel.",
      "Burn out a breeding chamber before its occupants reach maturity.",
      "Rescue a creature being tortured for the secrets it knows.",
      "Settle a question of inheritance by retrieving a sealed will.",
      "Recover a holy banner lost in an old defeat.",
      "Trace a slave route to the place where the captives are kept.",
      "Free the spirits bound to serve here so the place falls quiet.",
      "Deliver a message to a prisoner without their guards knowing.",
      "Test a theory about the dungeon's original builders by examining its walls.",
      "Recover bodies of the dead so their families can stop searching.",
      "Find proof that the master and a public figure are the same person.",
      "Plant a magical beacon for a strike force that will arrive later.",
      "Identify which entrance the next attack on the surface will come from.",
      "Determine whether the dungeon is older than the kingdom above it.",
      "Recover a weapon laid to rest with the founder of a now-fallen order.",
      "Pour a sanctifying fluid into a basin in the lowest chamber.",
      "Find the door that none of the inhabitants are permitted to approach.",
      "Sever a chain that binds something the inhabitants are afraid of.",
      "Retrieve a key from a vault where the master keeps personal treasures.",
      "Place a ward at a junction to prevent an entity from passing through.",
      "Carry a captive priest somewhere they can perform last rites.",
      "Disrupt the burial of someone who must not be allowed to rise.",
      "Catch the moment when a portal inside the dungeon opens.",
      "Replace a stolen idol with a convincing forgery.",
      "Locate the underground river that everyone insists does not exist.",
      "Find the prisoner who has been here the longest and learn what they know.",
      "Discover where the inhabitants take their dead.",
      "Recover a tax ledger that proves the kingdom has been robbed.",
      "Free a beast bound here that wants to leave more than anyone.",
      "Establish whether the master is human, ever was, or never was.",
      "Plant a forged order that will turn the inhabitants against each other.",
      "Retrieve a torn page from a book whose remainder is held elsewhere.",
      "Find out why the inhabitants pay tribute to something deeper still.",
      "Salt a cache of supplies before the inhabitants can move them.",
      "Find the architect's hidden notes for a passage no one has used in centuries.",
      "Carry water from a particular spring back to the surface intact.",
      "Witness a meeting between the master and a visitor from outside.",
      "Steal back a corpse before it can be raised as a servant.",
      "Find an apprentice willing to testify against their master.",
      "Recover a stolen heirloom that proves a claim of lineage.",
      "Disable the trap that has been killing trespassers for generations.",
      "Find the chamber where the inhabitants keep what they cannot eat.",
      "Verify that an object stored here is the genuine article and not a copy.",
      "Take a rubbing from an inscription that only this place still bears.",
      "Recover the lost portion of a treaty that ended a forgotten war.",
      "Locate the prisoner who arrived last week and find out who sent them.",
      "Set a fire that will be seen from the surface at a precise hour.",
      "Find out what is being smelted in the forges that never go cold.",
      "Carry a sealed coffer to an altar without opening it.",
      "Capture a single inhabitant alive for questioning above.",
      "Find the room where decisions are made and who is in it.",
      "Determine whether the prisoners outnumber the guards yet.",
      "Repair a broken seal before what it kept in finishes pushing through.",
      "Retrieve a contract written in blood that binds two parties still living.",
      "Cut down a tree growing in defiance of nature in the dungeon's heart.",
      "Find proof that the previous expedition was betrayed by one of its own.",
      "Drag a wounded comrade out before the inhabitants find them.",
      "Recover the body of a saint before a cult can use it.",
      "Discover what the inhabitants are mining for and why it matters.",
      "Activate a dormant teleportation circle deep within the complex.",
      "Retrieve a rare alchemical ingredient found only in the lowest levels.",
      "Assassinate a specific monster without alerting the rest of the dungeon.",
      "Map out the fluctuating layout of a magically shifting maze.",
      "Steal a specific page from a grimoire held by a powerful lich.",
      "Plant a magical sensor in the dungeon's central chamber.",
      "Extract a petrified ally and carry them to safety.",
      "Divert an underground river that is flooding a nearby town.",
      "Seal a portal to the Abyss that has recently opened.",
      "Discover the true name of the demon bound to the dungeon.",
      "Recover a family heirloom stolen by a band of goblins.",
      "Determine the fate of a legendary hero who vanished here.",
      "Sabotage a massive war machine being built by the inhabitants.",
      "Rescue a group of miners trapped by a cave-in.",
      "Find the source of a mysterious magical hum.",
      "Neutralize a magical trap that threatens to destroy the entire dungeon.",
      "Retrieve a specific gem that powers the dungeon's defenses.",
      "Befriend a misunderstood monster living in the dungeon.",
      "Steal a magical artifact that controls the weather.",
      "Destroy a cursed altar that is corrupting the surrounding land.",
      "Find a hidden cache of weapons to arm a rebellion.",
      "Escort a scholar studying the dungeon's ancient architecture.",
      "Determine if the dungeon's inhabitants are planning an attack.",
      "Recover a lost spellbook belonging to a famous wizard.",
      "Find a cure for a magical disease contracted in the dungeon.",
      "Retrieve a specific piece of armor forged by a legendary smith.",
      "Discover the secret of the dungeon's seemingly endless supply of monsters.",
      "Plant evidence to incriminate a rival faction operating in the dungeon.",
      "Steal a magical key that opens any door in the world.",
      "Destroy a magical crystal that is causing earthquakes.",
      "Find a hidden passage that leads directly to the treasure room.",
      "Escort a noble to a secret meeting within the dungeon.",
      "Determine the weakness of a powerful monster that lives here.",
      "Recover a specific magical ring stolen by a thief.",
      "Find a way to communicate with the dungeon's ghostly inhabitants.",
      "Retrieve a specific magical staff that controls minds.",
      "Discover the history of the dungeon's ancient creators.",
      "Plant a magical bomb to destroy the dungeon's master.",
      "Steal a specific magical amulet that grants immortality.",
      "Destroy a magical mirror that shows a dark future.",
      "Find a hidden cache of gold to pay off a debt.",
      "Escort a priest to perform a cleansing ritual.",
      "Determine the true purpose of a mysterious magical device.",
      "Recover a specific magical cloak that grants invisibility.",
      "Find a way to break a curse that haunts the dungeon.",
      "Retrieve a specific magical sword that slays dragons.",
      "Discover the secret of the dungeon's magical traps.",
      "Plant a magical beacon to guide an army.",
      "Steal a specific magical shield that deflects spells.",
      "Destroy a magical fountain that grants dark powers.",
      "Find a hidden passage that leads to the surface.",
      "Escort a merchant to a secret black market.",
      "Determine the identity of the dungeon's mysterious master.",
      "Recover a specific magical bow that never misses.",
      "Find a way to appease the dungeon's angry spirits.",
      "Retrieve a specific magical horn that summons beasts.",
      "Discover the secret of the dungeon's magical illusions.",
      "Plant a magical seed that will grow into a powerful tree.",
      "Steal a specific magical flute that charms animals.",
      "Destroy a magical statue that comes to life.",
      "Find a hidden cache of gems to fund a quest.",
      "Escort a spy to a secret rendezvous.",
      "Determine the nature of a mysterious magical illness.",
      "Recover a specific magical harp that cures diseases.",
      "Find a way to seal a magical portal to another dimension.",
      "Retrieve a specific magical drum that causes earthquakes.",
      "Discover the secret of the dungeon's magical puzzles.",
      "Plant a magical ward to protect the dungeon from intruders.",
      "Steal a specific magical lute that causes sleep.",
      "Destroy a magical tapestry that tells a dark prophecy.",
      "Find a hidden passage that leads to a secret room.",
      "Escort a diplomat to a secret negotiation.",
      "Determine the origin of a mysterious magical beast.",
      "Recover a specific magical lyre that controls the weather.",
      "Find a way to disarm a massive magical trap.",
      "Retrieve a specific magical bell that summons the dead.",
      "Discover the secret of the dungeon's magical history.",
      "Plant a magical tracker on a specific monster.",
      "Steal a specific magical chime that opens portals.",
      "Destroy a magical orb that controls minds.",
      "Find a hidden cache of magical scrolls.",
      "Escort a prisoner to a secret execution.",
      "Determine the truth behind a mysterious magical rumor.",
      "Recover a specific magical map that reveals hidden treasure.",
      "Find a way to reverse a magical transformation.",
      "Retrieve a specific magical compass that points to true love.",
      "Discover the secret of the dungeon's magical architecture.",
      "Plant a magical spyglass to observe the dungeon's master.",
      "Steal a specific magical spyglass that reveals secrets.",
      "Destroy a magical crown that grants immense power.",
      "Find a hidden passage that leads to a magical spring.",
      "Escort a pilgrim to a secret shrine.",
      "Determine the cause of a mysterious magical explosion.",
      "Recover a specific magical chalice that grants eternal youth.",
      "Find a way to restore a damaged magical artifact.",
      "Retrieve a specific magical book that contains all knowledge.",
    ],
  },

  wildernessGoals: {
    id: 'wildernessGoals',
    title: 'Wilderness Goals',
    attribution: 'Original',
    entries: [
      "Locate a hidden site whose entrance is concealed in the wilds.",
      "Assess the scope of a natural or magical disaster.",
      "Escort an NPC safely to a remote destination.",
      "Reach a destination without being detected by hostile forces.",
      "Stop monsters from raiding caravans, roads, or settlements.",
      "Establish a trade route between two distant communities.",
      "Protect a caravan against the wilderness's many dangers.",
      "Map an uncharted region for a patron or expedition.",
      "Identify a location suitable for founding a settlement.",
      "Locate a specific natural resource — a vein, grove, or spring.",
      "Hunt a named beast plaguing a region.",
      "Travel home from a place where the party is stranded.",
      "Obtain information from a reclusive hermit or oracle.",
      "Recover an object lost or hidden somewhere in the wilds.",
      "Determine what happened to a missing group of travelers.",
      "Pursue and capture fugitives fleeing through the wilderness.",
      "Reconnoiter an approaching army or invasion force.",
      "Escape across a wilderness from a regime that hunts the party.",
      "Defend a wilderness location from approaching attackers.",
      "Cleanse a place of corruption tied to the land itself.",
      "Find and seal a breach where something from elsewhere keeps crossing in.",
      "Drive a herd of livestock across rough country to market.",
      "Plant a series of boundary markers that will be respected by all sides.",
      "Reach a high vantage to verify whether smoke on the horizon is friend or foe.",
      "Lead refugees across hostile country to a place that will accept them.",
      "Cross a frozen pass before the season seals it for the year.",
      "Find a route through terrain previous expeditions have called impassable.",
      "Locate the headwaters of a river running unnaturally low this year.",
      "Track a wounded creature for days until it stops moving.",
      "Find what is killing the trees along a particular ridge.",
      "Recover a downed flier and whatever they were carrying.",
      "Make contact with a tribe that has refused all envoys so far.",
      "Retrieve seeds from a grove that flowers only once in a generation.",
      "Plant a sapling at a site chosen by an oracle.",
      "Find the migration route an entire species has abandoned.",
      "Bury a body at the place where the person was born.",
      "Confirm whether a legendary creature still lives in its old range.",
      "Walk a pilgrimage path that has not been completed in living memory.",
      "Find a child raised by something not human, and decide what to do.",
      "Cross a desert before a sandstorm season makes it lethal.",
      "Recover survivors from a shipwreck on a hostile coast.",
      "Reach an isolated lighthouse and learn why its keeper has gone silent.",
      "Find the source of a song that travelers keep hearing at dusk.",
      "Catch a creature alive and deliver it to a menagerie or sanctuary.",
      "Release a creature back into a range it was taken from long ago.",
      "Locate the cairn where a fallen leader was buried in retreat.",
      "Carry a relic to the spot where it was forged and lay it down.",
      "Find clean water in country where wells have all turned bitter.",
      "Find shelter for a wounded ally before they bleed out.",
      "Cross a battlefield while burial parties from both sides are still working.",
      "Steal a horse herd from a band that took them in the first place.",
      "Burn out a swarm before it reaches farmland downwind.",
      "Save crops from a blight by reaching the seed bank in time.",
      "Locate the moving grove that no two travelers ever find in the same place.",
      "Reach a glacier and recover what was frozen into it last winter.",
      "Settle a boundary dispute by reaching a landmark and witnessing it firsthand.",
      "Bring a healer to a remote camp before the sickness spreads further.",
      "Lead an escapee to the border before pursuit catches up.",
      "Recover a banner left on a battlefield no one has dared revisit.",
      "Track a thief whose only mistake was going overland.",
      "Find a place quiet enough for a ritual to be performed undisturbed.",
      "Confirm whether a rumored road actually exists between two valleys.",
      "Locate a stash that an outlaw left behind before being captured.",
      "Find what made the path everyone uses suddenly impassable.",
      "Bring a captive back across the wild without their faction noticing.",
      "Survey damage from a flood and report it to the people downstream.",
      "Find the campsite where a vanished party last lit a fire.",
      "Negotiate passage through territory whose owners speak no shared language.",
      "Cross a haunted moor on the only night the dead are said to move.",
      "Hunt a beast that has learned to imitate the calls of its hunters.",
      "Recover supplies from a cache before scavengers reach it.",
      "Test whether a rumored shortcut is real or a trap set for the credulous.",
      "Find a beast wounded by a previous expedition before it dies in cover.",
      "Reach a peak in time to observe a celestial event from the proper place.",
      "Drive off squatters from land claimed by the people who hired you.",
      "Find a fugitive willing to come in if escorted past the people hunting them.",
      "Make a clearing where airborne allies can land safely.",
      "Confirm whether a buried temple has surfaced where landslide reports suggest.",
      "Bring a captured beast safely past the village that wants it dead on sight.",
      "Find where a river has changed course and what it has uncovered.",
      "Lay markers along a safe route so a larger force can follow later.",
      "Reach a sacred tree before someone arrives to cut it down.",
      "Confirm that a remote watchtower has been overrun and at what cost.",
      "Locate the camp of a deserter band and decide whether to bring them in.",
      "Find the wagon that was sent ahead and never reached its destination.",
      "Trace smoke to its source without being seen.",
      "Find a place along the coast where a small vessel can put in unseen.",
      "Recover a balloon, glider, or wreck that came down in country no one travels.",
      "Find someone who saw what happened the night the comet passed.",
      "Bury a creature whose corpse is dangerous to leave above ground.",
      "Find the path the migrating dead take and reach a spot ahead of them.",
      "Carry warning to a village before the column of riders gets there.",
      "Search a forest for a quiet spot where pursuers will not look.",
      "Find out why the game has vanished from a region that used to feed villages.",
      "Locate a buried road from an older age beneath layers of soil.",
      "Track a smuggler's route by following what they discard along it.",
      "Recover banners lost in a rout so the survivors can be reformed.",
      "Find where the wolves are taking the children and what they want with them.",
      "Cross a swamp before the only guide who knows it stops being willing.",
      "Reach a sacred site at the proper hour to perform a duty no one else will.",
      "Discover the location of a legendary oasis in the deep desert.",
      "Track down a poacher who is hunting endangered magical creatures.",
      "Find a rare herb that only blooms during a lunar eclipse.",
      "Escort a caravan carrying a dangerous magical artifact through the wilderness.",
      "Map the changing boundaries of a creeping magical forest.",
      "Investigate a series of unnatural localized storms.",
      "Recover a lost caravan that seemingly vanished into thin air.",
      "Find the source of a strange illness afflicting the local wildlife.",
      "Negotiate peace between two warring tribes of forest dwellers.",
      "Escort a cartographer charting a dangerous, uncharted region.",
      "Find a legendary spring whose waters can cure any poison.",
      "Track a notorious bandit leader to their hidden wilderness camp.",
      "Investigate rumors of a waking earth elemental causing earthquakes.",
      "Recover a stolen magical beast before it causes havoc.",
      "Find the ancient ruins of a civilization that worshipped the sun.",
      "Negotiate with a powerful druid to stop an encroaching forest.",
      "Escort a group of refugees through a dangerous mountain pass.",
      "Find a rare, glowing mushroom that only grows in deep caves.",
      "Track a pack of dire wolves that have been attacking travelers.",
      "Investigate a strange, glowing crater left by a falling star.",
      "Recover a lost family heirloom from the bottom of a deep lake.",
      "Find the source of a mysterious, haunting melody heard in the woods.",
      "Negotiate a treaty with a clan of reclusive mountain dwarves.",
      "Escort a wealthy merchant on a hunting expedition for a rare beast.",
      "Find a legendary tree whose fruit grants eternal youth.",
      "Track a rogue wizard who has fled into the wilderness.",
      "Investigate rumors of a massive, subterranean monster.",
      "Recover a stolen magical artifact from a group of cultists.",
      "Find the ancient ruins of a civilization that worshipped the moon.",
      "Negotiate with a powerful spirit of the forest.",
      "Escort a group of pilgrims to a sacred shrine deep in the woods.",
      "Find a rare, magical flower that only blooms once a century.",
      "Track a legendary beast that has been terrorizing the countryside.",
      "Investigate a strange, localized area of anti-magic.",
      "Recover a lost spellbook from the lair of a dragon.",
      "Find the source of a mysterious, magical fog.",
      "Negotiate a peace treaty with a clan of hostile centaurs.",
      "Escort a group of scholars studying a rare magical phenomenon.",
      "Find a legendary cave that is said to contain immense wealth.",
      "Track a notorious assassin who has fled into the wilderness.",
      "Investigate rumors of a massive, ancient machine.",
      "Recover a stolen magical weapon from a group of bandits.",
      "Find the ancient ruins of a civilization that worshipped the stars.",
      "Negotiate with a powerful water spirit.",
      "Escort a group of diplomats to a secret meeting.",
      "Find a rare, magical crystal that only grows in volcanic craters.",
      "Track a legendary hero who has gone into hiding.",
      "Investigate a strange, localized area of intense heat.",
      "Recover a lost artifact from a sunken city.",
      "Find the source of a mysterious, magical light.",
      "Negotiate a trade agreement with a clan of desert nomads.",
      "Escort a group of entertainers to a remote village.",
      "Find a legendary island that is said to be a paradise.",
      "Track a notorious thief who has fled into the wilderness.",
      "Investigate rumors of a massive, ancient portal.",
      "Recover a stolen magical shield from a group of goblins.",
      "Find the ancient ruins of a civilization that worshipped the earth.",
      "Negotiate with a powerful fire spirit.",
      "Escort a group of exiles to a new home.",
      "Find a rare, magical feather that only falls from a mythical bird.",
      "Track a legendary monster that is said to be immortal.",
      "Investigate a strange, localized area of intense cold.",
      "Recover a lost artifact from a floating island.",
      "Find the source of a mysterious, magical darkness.",
      "Negotiate a peace treaty with a clan of ice giants.",
      "Escort a group of prisoners to a remote penal colony.",
      "Find a legendary mountain that is said to touch the heavens.",
      "Track a notorious pirate who has hidden their treasure in the wilderness.",
      "Investigate rumors of a massive, ancient weapon.",
      "Recover a stolen magical ring from a group of orcs.",
      "Find the ancient ruins of a civilization that worshipped the sea.",
      "Negotiate with a powerful air spirit.",
      "Escort a group of merchants through a dangerous swamp.",
      "Find a rare, magical scale that only falls from a dragon.",
      "Track a legendary sage who has isolated themselves in the wilderness.",
      "Investigate a strange, localized area of intense gravity.",
      "Recover a lost artifact from a deep chasm.",
      "Find the source of a mysterious, magical sound.",
      "Negotiate a trade agreement with a clan of merfolk.",
      "Escort a group of refugees across a dangerous desert.",
      "Find a legendary valley that is said to be hidden from the world.",
      "Track a notorious cult leader who has fled into the wilderness.",
      "Investigate rumors of a massive, ancient city.",
      "Recover a stolen magical amulet from a group of trolls.",
      "Find the ancient ruins of a civilization that worshipped the wind.",
      "Negotiate with a powerful earth spirit.",
      "Escort a group of explorers charting a new continent.",
      "Find a rare, magical tooth that only falls from a sea monster.",
      "Track a legendary warrior who has gone rogue.",
      "Investigate a strange, localized area of intense magical energy.",
      "Recover a lost artifact from a haunted forest.",
      "Find the source of a mysterious, magical smell.",
      "Negotiate a peace treaty with a clan of subterranean dwellers.",
      "Escort a group of nobles on a safari.",
      "Find a legendary river that is said to flow with gold.",
      "Track a notorious warlord who is hiding in the wilderness.",
    ],
  },

  urbanGoals: {
    id: 'urbanGoals',
    title: 'Urban & Other Goals',
    attribution: 'Original',
    entries: [
      "Seize control of a fortified place — a tower, ship, or compound.",
      "Defend a place against attackers who will arrive soon.",
      "Steal a specific object from inside a guarded building.",
      "Steal a specific object from a moving caravan or convoy.",
      "Recover salvage from a wrecked vessel or destroyed caravan.",
      "Break a specific prisoner out of confinement.",
      "Escape captivity after being imprisoned.",
      "Win standing or recognition by completing a public trial.",
      "Infiltrate a closed organization or stronghold.",
      "Investigate strange happenings in a single haunted location.",
      "Disrupt the operations of a specific business or guild.",
      "Rescue someone from an unfolding disaster as it happens.",
      "Win a contest, tournament, or duel against named rivals.",
      "Expose a corrupt official by gathering admissible evidence.",
      "Smuggle a person or object past a watchful authority.",
      "Mediate a dispute that threatens to erupt into violence.",
      "Solve a murder before the wrong person is condemned.",
      "Discredit a public figure who deserves to fall.",
      "Survive a single night under conditions designed to kill you.",
      "Recover stolen identity, status, or rightful position.",
      "Cross an ocean aboard a vessel whose captain doesn't want passengers.",
      "Travel to another plane to retrieve something only available there.",
      "Pose as members of a noble household long enough to attend one event.",
      "Deliver a sealed letter into the hand of someone heavily guarded.",
      "Read a document kept in an archive that does not allow visitors.",
      "Plant a forged document where the right person will find it.",
      "Switch two identical objects without either party noticing the swap.",
      "Bribe an official without the bribe being traceable back to anyone.",
      "Identify the silent partner backing an enterprise that should not exist.",
      "Spend a season as guests at a court where the wrong word is fatal.",
      "Win a hand at cards against an opponent who never loses on purpose.",
      "Negotiate a hostage exchange between parties who hate each other.",
      "Convince a witness to testify when doing so will cost them everything.",
      "Escort a defector across hostile territory and into protection.",
      "Buy something at auction without being identified as the buyer.",
      "Convince a council to vote against the way they intended to vote.",
      "Survive a sea voyage on a ship that something is following.",
      "Cross the sea on a ship whose crew is planning a mutiny.",
      "Reach a sky-island, floating city, or aerial vessel by your own means.",
      "Travel to the realm of the dead and return able to speak of it.",
      "Spend a night in a fey court without giving offense or accepting a gift.",
      "Deliver a message to a sleeping god without waking it.",
      "Escort a soul to its proper destination after death.",
      "Recover a person who has been drawn into a dream and cannot return.",
      "Find a way into a sealed quarter of the city no one is supposed to enter.",
      "Talk a hostage-taker into releasing the people they're holding.",
      "Carry out a robbery in a way that frames a specific party for it.",
      "Read the will of the deceased before the heirs can have it altered.",
      "Recover a body before it can be buried by people who shouldn't bury it.",
      "Stand as champion in a judicial combat on behalf of someone wronged.",
      "Win a public debate against an opponent the crowd already favors.",
      "Spend a market day passing as locals to learn what's being said.",
      "Find the safehouse where a wanted person is hiding without alerting them.",
      "Identify which servant in a household is reporting to someone outside.",
      "Plant a listening device — magical or mundane — in a private chamber.",
      "Steal a moment alone with a prisoner long enough to learn one fact.",
      "Replace a guard's drink without anyone seeing the substitution.",
      "Forge an introduction into a salon where outsiders are not welcome.",
      "Convince a duelist to withdraw without dishonor before the appointed hour.",
      "Find a craftsman willing to copy a piece of regalia exactly.",
      "Deliver testimony before a panel that has already decided the verdict.",
      "Reach a particular grave and read what is carved on its stone.",
      "Sit through a ceremony in disguise without being recognized.",
      "Recover an item pawned to a broker who will not admit it exists.",
      "Find which of seven suspects actually committed a particular act.",
      "Survive a banquet at which one of the dishes is poisoned.",
      "Identify the poisoner before the next course is served.",
      "Convince a creditor to extend terms they have already refused once.",
      "Win freedom for someone sold into debt-bondage by paying the right person.",
      "Recover an inheritance held in trust by a guardian unwilling to release it.",
      "Cross a border without papers, in the company of someone famous.",
      "Court a stranger long enough to learn their secret, then withdraw cleanly.",
      "Reach a coronation in time to dispute the claim before it is sealed.",
      "Stop a marriage that should not happen, without revealing who you are.",
      "Find which book in a public library has been read most recently.",
      "Sit in on a guild meeting closed to outsiders.",
      "Convince a captain to take a route they have sworn never to take again.",
      "Steal a ship and reach a port where she can be made over before pursuit arrives.",
      "Spend a night in a haunted mansion and remember everything you saw.",
      "Find which of the inns in town a particular traveler has stayed at recently.",
      "Outbid a rival at auction without your funds being checked.",
      "Carry a sick noble across a continent in time to reach the only healer who can help.",
      "Convince a court astrologer to revise a reading already given.",
      "Win passage on a ship that does not normally carry your kind.",
      "Reach a temple's inner sanctum and witness what is done there.",
      "Trail a target through three quarters of the city without losing them.",
      "Place evidence into a sealed room without leaving sign of entry.",
      "Identify the artist of an unsigned work and what it actually depicts.",
      "Spend a season as a tutor in a household to learn what happens behind its doors.",
      "Convince a foreign ambassador to break protocol on a matter of substance.",
      "Carry sensitive news to a ruler before their rivals do.",
      "Settle a question of paternity that has held up an inheritance for years.",
      "Cross between cities aboard an airship whose crew has reason to delay you.",
      "Stop the publication of a pamphlet that will cause riots if it goes out.",
      "Recover a child sold across a border, without alerting either nation.",
      "Travel into a planar pocket to retrieve someone the universe has forgotten.",
      "Reach an audience with a sovereign whose courtiers have all denied you access.",
      "Cross a city under quarantine in time to deliver something the sick need.",
      "Find the room in the palace where a particular conversation took place.",
      "Stand vigil through a night on which something is owed.",
      "Infiltrate an exclusive noble gala to swap a forged painting for the original.",
      "Evict a stubborn ghost from a highly contested piece of prime real estate.",
      "Rig a local election without leaving a paper trail.",
      "Break up a powerful syndicate monopoly over the city's docks.",
      "Track down a rogue golem rampaging through the sewer system.",
      "Solve a series of high-profile kidnappings targeting the city's elite.",
      "Smuggle a forbidden magical tome out of the Grand Library.",
      "Expose a cult that has infiltrated the city guard.",
      "Protect a controversial figurehead during a massive city-wide parade.",
      "Determine who is poisoning the city's main aqueduct.",
      "Organize a jailbreak for a wrongly accused political dissident.",
      "Sabotage a rival merchant's warehouse without causing physical harm.",
      "Negotiate a tense standoff between two rival thieves' guilds.",
      "Uncover a conspiracy involving the mayor and a foreign power.",
      "Find the hidden entrance to a legendary underground black market.",
      "Steal the blueprints for a revolutionary new weapon from an inventor's lab.",
      "Escort a defecting spy to a safe house across town.",
      "Determine the true identity of a masked vigilante.",
      "Recover a stolen shipment of rare, magical components.",
      "Prevent an assassination attempt at the city's grand opera house.",
      "Investigate a series of seemingly unrelated arson attacks.",
      "Find the missing heir to a powerful noble family.",
      "Expose a corrupt judge who has been taking bribes.",
      "Smuggle a group of refugees out of the city.",
      "Protect a witness who is set to testify against a powerful crime lord.",
      "Determine the source of a mysterious magical illness spreading through the slums.",
      "Organize a heist on the city's heavily fortified mint.",
      "Sabotage a massive, magical clock that controls the city's defenses.",
      "Negotiate peace between the city guard and a group of striking workers.",
      "Uncover a plot to overthrow the city council.",
      "Find a legendary artifact hidden somewhere in the city's catacombs.",
      "Steal a specific magical artifact from a wealthy collector's private museum.",
      "Escort a renowned scholar safely to a university.",
      "Determine who is blackmailing the city's most powerful merchant.",
      "Recover a lost masterpiece of art before it is destroyed.",
      "Prevent a magical disaster from occurring in the city center.",
      "Investigate a strange cult operating out of an abandoned warehouse.",
      "Find the missing leader of the local thieves' guild.",
      "Expose a charlatan who has been swindling the city's elite.",
      "Smuggle a dangerous magical creature out of the city.",
      "Protect a prominent politician during a heated debate.",
      "Determine the cause of a series of strange disappearances in the city.",
      "Organize a rebellion against a tyrannical ruler.",
      "Sabotage a massive, magical gate that leads to another dimension.",
      "Negotiate a treaty between the city and a neighboring tribe.",
      "Uncover a secret society operating within the city's walls.",
      "Find the hidden vault of a legendary thief.",
      "Steal a powerful magical weapon from the city's armory.",
      "Escort a captured spy to a remote prison.",
      "Determine the identity of a serial killer stalking the city streets.",
      "Recover a stolen magical book that contains forbidden spells.",
      "Prevent a massive riot from breaking out in the city.",
      "Investigate a strange, glowing light emanating from a graveyard.",
      "Find the missing daughter of a prominent noble.",
      "Expose a corrupt merchant who is selling shoddy goods.",
      "Smuggle a valuable artifact out of the city.",
      "Protect a famous bard from an obsessive fan.",
      "Determine the origin of a mysterious magical artifact found in the city.",
      "Organize a jailbreak for a group of political prisoners.",
      "Sabotage a massive, magical ship that is threatening the city.",
      "Negotiate a trade agreement between the city and a foreign power.",
      "Uncover a plot to assassinate the king.",
      "Find a legendary sword hidden somewhere in the city.",
      "Steal a specific magical ring from a powerful mage.",
      "Escort a group of pilgrims safely to a holy site.",
      "Determine who is behind a series of bombings in the city.",
      "Recover a lost magical amulet before it falls into the wrong hands.",
      "Prevent a magical plague from spreading through the city.",
      "Investigate a strange cult operating out of a local tavern.",
      "Find the missing son of a powerful merchant.",
      "Expose a corrupt city guard who has been taking bribes.",
      "Smuggle a group of slaves out of the city.",
      "Protect a wealthy merchant during a dangerous journey.",
      "Determine the cause of a series of strange magical anomalies in the city.",
      "Organize a heist on a wealthy noble's mansion.",
      "Sabotage a massive, magical device that is causing earthquakes.",
      "Negotiate a peace treaty between two warring factions in the city.",
      "Uncover a secret plot to destroy the city.",
      "Find a legendary shield hidden somewhere in the city.",
      "Steal a specific magical staff from a powerful wizard.",
      "Escort a renowned artist safely to a new patron.",
      "Determine who is behind a series of kidnappings in the city.",
      "Recover a lost magical crown before it is used for evil.",
      "Prevent a magical invasion from occurring in the city.",
      "Investigate a strange cult operating out of an abandoned temple.",
      "Find the missing leader of a local guild.",
      "Expose a corrupt politician who has been stealing from the city's coffers.",
      "Smuggle a dangerous criminal out of the city.",
      "Protect a famous athlete during a high-stakes competition.",
      "Determine the origin of a mysterious magical creature found in the city.",
      "Organize a rebellion against a corrupt city council.",
      "Sabotage a massive, magical portal that leads to the Abyss.",
      "Negotiate a treaty between the city and a group of rebels.",
      "Uncover a secret society dedicated to dark magic.",
      "Find the hidden treasure of a legendary pirate.",
      "Steal a powerful magical orb from a dangerous cult.",
      "Escort a captured criminal to a secure facility.",
      "Determine the identity of a master thief operating in the city.",
    ],
  },

};
