// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const npcTraitTables: Record<string, InspireTable> = {
  npcMannerisms: {
    id: 'npcMannerisms',
    title: 'NPC Mannerisms',
    attribution: 'Original',
    entries: [
      "Hums quietly during silences in conversation.",
      "Speaks in short, complete sentences with no filler.",
      "Has a notably high, low, or rasping voice.",
      "Lisps, slurs, or stutters on specific sounds.",
      "Enunciates each word as if for a slow listener.",
      "Speaks louder than necessary in indoor settings.",
      "Whispers regardless of how private the setting actually is.",
      "Uses long words where short ones would do.",
      "Frequently misuses words but never accepts correction.",
      "Has a personal oath they swear instead of common ones.",
      "Makes jokes — usually bad — at inopportune moments.",
      "Predicts disaster regardless of evidence.",
      "Cannot sit still — taps, fidgets, paces.",
      "Squints at everything, near and far.",
      "Stares slightly past the person they're addressing.",
      "Always seems to be chewing on something — a toothpick, a stem, nothing.",
      "Drums fingers on any nearby surface.",
      "Bites their fingernails when thinking.",
      "Twirls hair, beard, or jewelry while speaking.",
      "Laughs at things that aren't funny, never at things that are.",
      "Trails off mid-sentence and rarely circles back.",
      "Repeats the last few words of whoever just spoke.",
      "Ends every statement with a small interrogative lift.",
      "Sniffs sharply before delivering any opinion.",
      "Clears their throat between every two sentences.",
      "Pauses uncomfortably long before answering simple questions.",
      "Finishes other people's sentences, usually incorrectly.",
      "Refers to themselves in the third person without irony.",
      "Salts every story with an obscure proverb.",
      "Quotes a single favorite text in any conversation longer than a minute.",
      "Inserts the names of saints, ancestors, or local figures into ordinary remarks.",
      "Inhales through their teeth before delivering bad news.",
      "Chuckles at their own statements before anyone else can react.",
      "Sighs heavily at the start of every sentence.",
      "Mutters under their breath after agreeing to anything.",
      "Translates idioms literally between languages they speak.",
      "Speaks with their hands flat on the table in front of them.",
      "Gestures broadly with whatever they happen to be holding.",
      "Points at unrelated objects while making unrelated arguments.",
      "Adjusts their clothing or hair after every important statement.",
      "Tucks an imaginary strand of hair behind one ear, repeatedly.",
      "Cracks their knuckles one at a time when thinking.",
      "Rolls a coin, ring, or pebble between their fingers constantly.",
      "Polishes a small object on their sleeve while talking.",
      "Rests their chin on one fist whenever forced to listen.",
      "Mimics the posture of whoever they're talking to within seconds.",
      "Stands closer to others than is conventionally comfortable.",
      "Stands farther from others than is conventionally comfortable.",
      "Refuses to face anyone directly, addressing them at an angle.",
      "Looks at the floor when delivering compliments.",
      "Locks eyes for slightly too long without blinking.",
      "Blinks rapidly in bursts when listening intently.",
      "Tilts their head sideways whenever puzzled.",
      "Nods slowly throughout the entire conversation, agreement unclear.",
      "Frowns reflexively at every greeting before recovering.",
      "Smiles broadly while saying something grim.",
      "Bares their teeth when they intend to smile.",
      "Smells everything before touching it — coins, papers, food.",
      "Tastes their food carefully, as if checking it.",
      "Rearranges objects on the table while in conversation.",
      "Lines up coins, cutlery, or trinkets in tidy rows.",
      "Counts the doors and exits of any room within moments of entering.",
      "Refuses to sit with their back to a door.",
      "Insists on standing through entire meetings, however long.",
      "Sits very still, then moves all at once, then stills again.",
      "Walks with an audibly heavy tread for someone their size.",
      "Walks so quietly that others jump when noticing them.",
      "Limps mildly on one side, depending on the weather.",
      "Lists slightly to one side when standing, as if listening downhill.",
      "Carries themselves like they expect to be struck at any moment.",
      "Carries themselves like the room has been arranged for them.",
      "Pulls at the cuffs of their sleeves whenever uncertain.",
      "Touches a particular ring, pendant, or scar when thinking.",
      "Rubs the bridge of their nose as if a headache always threatens.",
      "Wipes their hands on a kerchief at regular intervals.",
      "Brushes invisible dust off their shoulders during conversation.",
      "Picks at the same spot on their thumbnail without realizing.",
      "Sharpens a pencil, knife, or stylus during important discussions.",
      "Carries a small notebook and writes briefly after notable remarks.",
      "Wears spectacles they don't need and removes them for emphasis.",
      "Cleans their spectacles repeatedly on a sleeve already dirty.",
      "Squints over the top of their lenses rather than through them.",
      "Refers to a pocket watch, sundial, or hourglass throughout.",
      "Begins anecdotes with a date and refuses to be hurried past it.",
      "Speaks of long-dead relatives as if they were in the next room.",
      "Addresses strangers by relational terms — cousin, uncle, dear one.",
      "Calls everyone by a title they have not earned.",
      "Refuses to use anyone's first name, however well acquainted.",
      "Pronounces foreign names with deliberate, audible care.",
      "Apologizes preemptively for opinions they have not yet stated.",
      "Thanks people for things they did not in fact do.",
      "Says goodbye three or four times before actually leaving.",
      "Lingers in doorways for one last remark each time.",
      "Whistles tunelessly when alone or when bored in company.",
      "Sings under their breath in a language no one nearby speaks.",
      "Snaps their fingers at the end of any decision they've made.",
      "Slaps the table once, lightly, to mark agreement.",
      "Steeples their fingers and stares over them at the speaker.",
      "Folds their arms whenever they intend to refuse something.",
      "Crosses themselves, or gestures equivalently, after speaking of the dead.",
      "Bites their lip when they are nervous or unsure.",
      "Runs a hand through their hair constantly when stressed.",
      "Taps their foot impatiently when they want the conversation to end.",
      "Paces back and forth while explaining something complex.",
      "Adjusts their glasses frequently, even when they aren't slipping.",
      "Rubs the back of their neck when they are embarrassed.",
      "Plays with a piece of jewelry when they are deep in thought.",
      "Crosses their legs and swings one foot slightly when relaxed.",
      "Leans forward intently when they are interested in the topic.",
      "Leans back and crosses their arms when they are skeptical.",
      "Sighs heavily before answering a difficult question.",
      "Chuckles nervously when they are uncomfortable.",
      "Averts their gaze when lying or hiding something.",
      "Stares unblinkingly when trying to intimidate someone.",
      "Smiles faintly when they know something the other person doesn't.",
      "Frowns deeply when they are confused or displeased.",
      "Raises one eyebrow to express doubt or surprise.",
      "Nods enthusiastically to show agreement or encouragement.",
      "Shakes their head slowly when they are disappointed.",
      "Rolls their eyes when they are annoyed or exasperated.",
      "Winks slyly when making a joke or a secret deal.",
      "Points a finger when they are making a strong accusation.",
      "Waves a hand dismissively when they don't care about a topic.",
      "Clenches their fists when they are angry or frustrated.",
      "Open their hands palms up when they are being honest or vulnerable.",
      "Rubs their hands together when they are excited or anticipating something.",
      "Places a hand on their chest when they are expressing deep emotion.",
      "Touches someone's arm lightly to show empathy or connection.",
      "Pats someone on the back to offer comfort or congratulations.",
      "Shrugs their shoulders when they don't know the answer.",
      "Clears their throat loudly to get someone's attention.",
      "Coughs politely to interrupt a conversation.",
      "Yawns widely without covering their mouth when they are bored.",
      "Stretches their arms over their head when they are tired.",
      "Cracks their neck by tilting their head from side to side.",
      "Pops their knuckles loudly before starting a physical task.",
      "Bites their fingernails down to the quick.",
      "Picks at their cuticles until they bleed.",
      "Chews on the inside of their cheek.",
      "Grinds their teeth audibly.",
      "Licks their lips frequently.",
      "Smacks their lips when they are hungry or thirsty.",
      "Whistles a tuneless melody under their breath.",
      "Hums a familiar song when they are happy or distracted.",
      "Mutters to themselves when they are trying to solve a problem.",
      "Speaks very quickly when they are excited or nervous.",
      "Speaks very slowly and deliberately to ensure they are understood.",
      "Uses a lot of slang or colloquialisms.",
      "Uses very formal or archaic language.",
      "Swears frequently and casually.",
      "Never swears, using creative alternatives instead.",
      "Apologizes constantly, even when it isn't their fault.",
      "Never apologizes, even when they are clearly in the wrong.",
      "Compliments people excessively.",
      "Insults people casually as a form of affection.",
      "Interrupts people frequently.",
      "Never interrupts, always waiting for the other person to finish.",
      "Talks loudly over everyone else.",
      "Speaks so softly that people have to lean in to hear them.",
      "Uses dramatic pauses for effect.",
      "Speaks in a monotone voice.",
      "Changes their tone and pitch frequently.",
      "Uses a lot of hand gestures while speaking.",
      "Keeps their hands completely still while speaking.",
      "Maintains intense eye contact.",
      "Avoids eye contact altogether.",
      "Looks around the room constantly while speaking.",
      "Focuses on a specific object while speaking.",
      "Blinks rapidly when they are lying.",
      "Stares blankly when they are confused.",
      "Smiles inappropriately during serious conversations.",
      "Frowns inappropriately during happy conversations.",
      "Laughs at their own jokes.",
      "Never laughs at anything.",
      "Cries easily.",
      "Never shows any emotion.",
      "Gets angry very quickly.",
      "Never gets angry, even when they should.",
      "Is always calm and collected.",
      "Is always anxious and nervous.",
      "Is always happy and optimistic.",
      "Is always sad and pessimistic.",
      "Is always suspicious and paranoid.",
      "Is always trusting and naive.",
      "Is always confident and arrogant.",
      "Is always humble and self-deprecating.",
      "Is always generous and giving.",
      "Is always selfish and greedy.",
      "Is always kind and compassionate.",
      "Is always cruel and heartless.",
      "Is always honest and truthful.",
      "Is always deceitful and manipulative.",
      "Is always loyal and dependable.",
      "Is always treacherous and unreliable.",
      "Is always brave and courageous.",
      "Is always cowardly and fearful.",
    ],
  },

  npcTalents: {
    id: 'npcTalents',
    title: 'NPC Talents',
    attribution: 'Original',
    entries: [
      "Plays a musical instrument well.",
      "Speaks several languages, including unusual ones.",
      "Has improbable luck — coins land their way, dice favor them.",
      "Has a flawless memory for faces or for words spoken aloud.",
      "Calms agitated animals without trying.",
      "Charms children without effort or condescension.",
      "Solves puzzles, riddles, and lateral problems quickly.",
      "Is unbeatable at one specific game — chess, cards, dice.",
      "Mimics voices and accents convincingly.",
      "Draws or sketches well from memory.",
      "Paints — formally or in charcoal — with real skill.",
      "Sings beautifully but rarely does so without prompting.",
      "Has impossibly high alcohol tolerance.",
      "Carpenters or builds skillfully as a hobby.",
      "Cooks well enough that others go out of their way to be fed.",
      "Throws, juggles, or skips objects with uncanny accuracy.",
      "Performs sleight of hand as casual entertainment.",
      "Acts well enough to disguise themselves convincingly.",
      "Dances better than their station would suggest.",
      "Knows a secret language — thieves' cant, druidic gesture, military signs.",
      "Composes verse extemporaneously on whatever subject is offered.",
      "Reads lips across a noisy room without difficulty.",
      "Catches falling objects without seeming to look.",
      "Picks any lock given time and a piece of wire.",
      "Estimates distances, weights, and crowds with disturbing accuracy.",
      "Tells the time within a minute without consulting any device.",
      "Navigates by stars alone, even under partial cloud.",
      "Reads weather days in advance from sky and wind.",
      "Identifies wild plants — edible, medicinal, fatal — at a glance.",
      "Tracks game or people across terrain others assume hides nothing.",
      "Identifies regional accents to a precise town or valley.",
      "Recognizes the maker of a forged signature, coin, or seal.",
      "Spots counterfeit coins by weight and ring alone.",
      "Bakes bread better than most people have ever tasted.",
      "Brews ale, wine, or spirits of remarkable quality.",
      "Distills perfumes that subtly suit whoever wears them.",
      "Mends torn clothing so cleanly the repair vanishes.",
      "Knots ropes for any purpose — climbing, binding, snaring.",
      "Whittles small figurines and gives them away unsigned.",
      "Sews wounds neatly enough to leave only thin scars.",
      "Sets broken bones with calm and confident hands.",
      "Recognizes most common diseases by symptom and onset.",
      "Soothes the dying without needing to find the right words.",
      "Names every star in the visible sky and the stories attached.",
      "Recites genealogies of local families three generations back.",
      "Recalls the verses of long ballads without hesitation.",
      "Writes in a beautiful, almost calligraphic hand.",
      "Forges handwriting after a single sample.",
      "Carves stone passably for someone with no formal training.",
      "Shoes horses and other beasts with patient competence.",
      "Rides any mount within an hour of meeting it.",
      "Trains dogs to specific tasks in remarkably little time.",
      "Falconries with quiet authority and a soft glove.",
      "Swims long distances in cold water without apparent strain.",
      "Holds their breath far longer than seems reasonable.",
      "Climbs walls and trees with the ease of long practice.",
      "Walks tightropes, beams, and narrow ledges with no concern.",
      "Tumbles, rolls, and falls without ever quite hurting themselves.",
      "Lifts surprisingly heavy loads despite an ordinary frame.",
      "Outwalks much younger companions without complaint.",
      "Sleeps anywhere, in any conditions, on command.",
      "Wakes at any chosen hour without aid.",
      "Drives a hard bargain even in markets where they're a stranger.",
      "Reads a crowd's mood within seconds of stepping into it.",
      "Senses when they are being followed before any sign shows.",
      "Knows the going price of nearly any common good.",
      "Recites the inventory of any room after a single glance.",
      "Identifies metals, gemstones, and ores by feel and color.",
      "Names woods by smell when freshly cut.",
      "Cuts hair well enough to charge for it.",
      "Mends boots and saddles invisibly with cobbler's tools.",
      "Tans hide and leather without the usual stink.",
      "Builds a fire in conditions where others give up trying.",
      "Cleans and cooks game from field to table on their own.",
      "Fishes successfully in any water within an hour.",
      "Reads sea charts and river maps fluently, even old ones.",
      "Sails small craft alone in weather others wouldn't risk.",
      "Whistles for animals in their own languages, more or less.",
      "Speaks softly to bees without being stung.",
      "Settles bar disputes without throwing or taking a punch.",
      "Sees others' lies almost as quickly as they are told.",
      "Conceals their own thoughts behind a perfect ordinary face.",
      "Holds a poker face through any provocation.",
      "Plays parlor tricks that delight the easily impressed.",
      "Knows enough astrology to flatter without committing to nonsense.",
      "Tells fortunes that, against odds, are sometimes right.",
      "Remembers every name they have ever been told once.",
      "Repeats long speeches verbatim after hearing them once.",
      "Plays the part of a peasant or noble equally convincingly.",
      "Bears cold or heat with no visible discomfort.",
      "Goes long stretches without food, by habit rather than need.",
      "Walks barefoot across rough ground as easily as in boots.",
      "Sleeps standing up if circumstances require.",
      "Stands perfectly still longer than seems possible.",
      "Throws their voice across a room when amusement requires.",
      "Whistles between their fingers loud enough to silence a tavern.",
      "Knows the prayers of half a dozen faiths well enough to pass.",
      "Reads ancient scripts haltingly but enough to gist the meaning.",
      "Restores damaged books, scrolls, and bindings with care.",
      "Carries an absurd amount of useful small gear in their pockets.",
      "Can perfectly mimic the call of almost any local bird.",
      "Instantly accurately gauges the weight of any object they lift.",
      "Can fall asleep anywhere, in any position, within seconds.",
      "Has an uncanny knack for finding lost items, even without trying.",
      "Can read lips from a surprisingly long distance.",
      "Mixes drinks that perfectly match the mood of the drinker.",
      "Remembers the exact details of every face they've ever seen.",
      "Can tie and untie incredibly complex knots with one hand.",
      "Sings in a beautiful, clear voice, but only when working.",
      "Can tell the exact time of day simply by looking at the sun or stars.",
      "Is naturally double-jointed and can slip out of ordinary bindings.",
      "Can identify the origin of any accent after hearing a few sentences.",
      "Has a calming presence that soothes nervous animals instantly.",
      "Can juggle up to six objects of varying sizes and weights.",
      "Is an incredibly fast and accurate reader.",
      "Can perfectly replicate any signature after seeing it once.",
      "Has a 'green thumb'—even dying plants seem to recover under their care.",
      "Can whistle loudly enough to be heard over a roaring crowd or storm.",
      "Is a master of making a very little amount of food stretch to feed many.",
      "Can always find north, even deep underground or in a magical darkness.",
      "Can hold their breath for an uncomfortably long time.",
      "Is surprisingly skilled at basic first aid and bandaging.",
      "Can instantly memorize short sequences of numbers or symbols.",
      "Has an excellent sense of smell, able to identify specific spices or poisons.",
      "Can perfectly imitate the sound of a crying baby or a barking dog.",
      "Is incredibly good at stacking things so they won't fall over.",
      "Can throw small objects with pin-point accuracy.",
      "Has a talent for making very comfortable beds out of rough materials.",
      "Can always tell when someone is lying, but never reveals how.",
      "Is surprisingly graceful, moving silently despite their size or footwear.",
      "Can quickly repair minor tears or damage to clothing.",
      "Has an instinct for knowing which way the weather will turn.",
      "Can start a fire in almost any condition with minimal supplies.",
      "Is remarkably good at estimating distances and measurements by eye.",
      "Can quickly sketch a very accurate portrait or map from memory.",
      "Has a knack for finding the best deals in any market.",
      "Can always open a stuck jar or unstick a rusty lock.",
      "Is incredibly good at skipping stones.",
      "Can perfectly mimic the handwriting of anyone they've seen write.",
      "Has an encyclopedic knowledge of local folklore and superstitions.",
      "Can quickly decipher simple codes and ciphers.",
      "Is surprisingly good at braiding hair or weaving small baskets.",
      "Can always tell if a coin is counterfeit just by the feel of it.",
      "Has a talent for making people feel comfortable and welcome.",
      "Can quickly build a sturdy temporary shelter.",
      "Is incredibly good at catching things that are thrown or dropped.",
      "Can play a simple tune on almost any musical instrument.",
      "Has a knack for remembering people's names and faces.",
      "Can always find a good hiding spot in any environment.",
      "Is surprisingly good at calming down angry or upset people.",
      "Can quickly gut and clean a fish or small animal.",
      "Has an excellent sense of direction and never gets lost.",
      "Can perfectly imitate the posture and walk of others.",
      "Is incredibly good at balancing objects on their head or nose.",
      "Can always tell when food is starting to spoil before anyone else.",
      "Has a talent for telling captivating stories to children.",
      "Can quickly mend a broken strap or buckle.",
      "Is surprisingly good at identifying different types of wood or stone.",
      "Can always find the softest patch of ground to sleep on.",
      "Has a knack for winning simple bar bets or games of chance.",
      "Can perfectly whistle the tune of a song they've only heard once.",
      "Is incredibly good at packing bags and making everything fit.",
      "Can quickly untangle even the most knotted rope or string.",
      "Has an instinct for knowing when someone is sneaking up on them.",
      "Can always tell if someone is wearing a disguise.",
      "Is surprisingly good at mimicking animal sounds.",
      "Can quickly fashion a simple tool out of available materials.",
      "Has a talent for making terrible situations seem funny.",
      "Can always find the best route through a crowded street.",
      "Is incredibly good at predicting the outcome of sporting events.",
      "Can perfectly remember the layout of any building they've been in.",
      "Has a knack for finding valuable objects in trash or debris.",
      "Can always tell when someone is pregnant before they show.",
      "Is surprisingly good at giving massages and relieving tension.",
      "Can quickly identify the best cuts of meat.",
      "Has an instinct for knowing when to stay quiet and when to speak.",
      "Can always find a silver lining in a bad situation.",
      "Is incredibly good at staying awake for long periods of time.",
      "Can perfectly replicate a recipe after tasting a dish once.",
      "Has a talent for making children stop crying.",
      "Can always tell when a storm is coming by the smell of the air.",
      "Is surprisingly good at keeping a secret.",
      "Can quickly fashion a comfortable pair of shoes from scraps.",
      "Has a knack for finding the best place to fish in any body of water.",
      "Can always tell when someone is hiding something in their pockets.",
      "Is incredibly good at untying knots with their teeth.",
      "Can perfectly remember a long list of instructions.",
      "Has a talent for making people feel guilty.",
      "Can always find a hidden compartment in a desk or chest.",
      "Is surprisingly good at predicting the weather.",
      "Can quickly build a fire using only friction.",
      "Has a knack for finding the best ingredients for a spell or potion.",
      "Can always tell when a magical item is nearby.",
      "Is incredibly good at resisting interrogation.",
      "Can perfectly mimic the voice of someone they just met.",
      "Has a talent for making people trust them.",
      "Can always find a way to escape a tight situation.",
      "Is surprisingly good at surviving in the wilderness.",
    ],
  },

  npcInteractionTraits: {
    id: 'npcInteractionTraits',
    title: 'NPC Interaction Traits',
    attribution: 'Original',
    entries: [
      "Argumentative — disagrees first, considers later.",
      "Arrogant — assumes their own superiority.",
      "Blustering — talks loudly to project confidence they don't have.",
      "Rude — abrupt, dismissive, easily annoyed.",
      "Curious — asks more questions than they answer.",
      "Friendly — open, warm, easily trusting.",
      "Honest — gives true answers even when it costs them.",
      "Hot-tempered — escalates quickly under pressure.",
      "Irritable — patience is a finite resource that's already low.",
      "Ponderous — slow to speak, slower to commit.",
      "Quiet — speaks only when they have something specific to say.",
      "Suspicious — assumes ulterior motives until proven otherwise.",
      "Gracious — receives every word as if it were a gift.",
      "Pedantic — corrects small errors as a matter of duty.",
      "Conspiratorial — leans close and shares as if every fact were secret.",
      "Maudlin — drifts into reminiscence at the smallest prompt.",
      "Brusque — words clipped short, time always running out.",
      "Effusive — overflows with greetings, compliments, and emphasis.",
      "Coy — answers obliquely and seems pleased to.",
      "Sardonic — comments dryly on whatever is unfolding around them.",
      "Disarming — puts everyone at ease before they realize it.",
      "Calculating — every reply is weighed before it leaves their lips.",
      "Hesitant — words come reluctantly, qualified and qualified again.",
      "Imperious — speaks as if obedience were the only sensible response.",
      "Garrulous — talks freely and at length about nothing in particular.",
      "Laconic — uses three words where five would have been polite.",
      "Cheerful — bright in tone regardless of subject matter.",
      "Gloomy — sees the cloud where others mention the silver.",
      "Earnest — means everything they say, in the plainest sense.",
      "Wry — finds quiet amusement in serious matters.",
      "Pompous — pads simple statements with unnecessary grandeur.",
      "Anxious — checks reactions constantly while speaking.",
      "Aloof — addresses people as if from a distance they prefer.",
      "Doting — treats everyone like a slightly slow younger relative.",
      "Stoic — gives little away, even when pressed.",
      "Flighty — leaps from topic to topic without warning.",
      "Pious — works mention of the divine into ordinary exchanges.",
      "Cynical — assumes the worst motive and is rarely surprised.",
      "Naive — assumes the best motive and is occasionally rewarded.",
      "Smug — visibly enjoys knowing something others don't.",
      "Theatrical — performs every conversation as if to a small audience.",
      "Solicitous — fusses over the comfort of everyone present.",
      "Dismissive — waves away inconvenient remarks as not worth answering.",
      "Vague — answers loosely and changes the shape of the question.",
      "Pedagogical — explains things at length whether asked or not.",
      "Officious — insists on procedure where none is required.",
      "Lecherous — comments slip toward the inappropriate at every turn.",
      "Reverent — speaks of certain subjects only in hushed tones.",
      "Boisterous — fills the room before anyone else has a chance.",
      "Sullen — radiates dissatisfaction without saying why.",
      "Charming — leaves people wondering why they agreed so easily.",
      "Withdrawn — answers reluctantly and watches the door.",
      "Eccentric — follows their own conversational rules entirely.",
      "Gruff — hides warmth under a layer of plain speech.",
      "Mocking — turns the other speaker's words against them lightly.",
      "Wistful — speaks of things as if they had already been lost.",
      "Snide — slips small insults inside otherwise ordinary remarks.",
      "Avuncular — offers advice no one asked for and means it kindly.",
      "Forthright — states their position before they're asked to.",
      "Mischievous — looks for the small joke at every opportunity.",
      "Reserved — withholds opinion until certain it will be welcome.",
      "Patient — waits out every interruption without losing the thread.",
      "Impatient — visibly counts the seconds until they can speak again.",
      "Apologetic — softens every assertion with a preemptive sorry.",
      "Boastful — works personal achievements into unrelated answers.",
      "Self-deprecating — heads off compliments with a small joke at themselves.",
      "Long-winded — every answer carries three more than it needed.",
      "Tactful — finds the gentlest version of the necessary truth.",
      "Blunt — finds the shortest version of the necessary truth.",
      "Tender — speaks to others as if they might break.",
      "Cold — replies precisely, without warmth or hostility.",
      "Inquisitive — turns conversations into interviews without noticing.",
      "Skeptical — meets enthusiasm with an arched eyebrow.",
      "Restless — fidgets while others speak, eager to move on.",
      "Composed — answers steadily under provocations others wouldn't bear.",
      "Wary — leaves themselves an exit in every sentence.",
      "Open-handed — offers help, advice, or coin almost before being asked.",
      "Possessive — refers to people and things as theirs more than is true.",
      "Worldly — drops references to far places casually into talk.",
      "Provincial — measures everything against home, and home wins.",
      "Sentimental — moved easily by stories of love, loss, or homecoming.",
      "Practical — steers every conversation toward what to do next.",
      "Romantic — frames mundane events as moments of larger meaning.",
      "Pedant-mocking — punctures pomposity wherever they find it.",
      "Gentle — phrases even refusals as if to spare feelings.",
      "Severe — frowns at humor and reaches quickly for principle.",
      "Genial — meets strangers as if resuming an old friendship.",
      "Distant — answers across a gap they make no effort to close.",
      "Indignant — finds something to be offended by within minutes.",
      "Forgiving — drops grudges so quickly others wonder if they registered.",
      "Tenacious — keeps to a point past anyone else's willingness to argue.",
      "Manic — energy spills past whatever the situation actually requires.",
      "Listless — speaks as if from under a great weight of tiredness.",
      "Penitent — slips small confessions into otherwise ordinary chat.",
      "Defensive — treats neutral remarks as attacks and answers in kind.",
      "Watchful — speaks little while taking the measure of everyone present.",
      "Mannered — adheres to old courtesies even where they've fallen out of use.",
      "Familiar — closes the social distance faster than is conventional.",
      "Crafty — phrases questions so the answer reveals more than intended.",
      "Affable — pleasant by default, even when pleasant isn't deserved.",
      "Overbearing — dominates conversations and insists on their own way.",
      "Obsequious — overly eager to please, fawning and submissive.",
      "Vindictive — holds grudges and seeks revenge for minor slights.",
      "Magnanimous — generous and forgiving, especially toward rivals.",
      "Abrasive — harsh and rough in manner, often causing offense.",
      "Diplomatic — skilled in handling sensitive situations without causing offense.",
      "Erratic — unpredictable and inconsistent in behavior and mood.",
      "Methodical — does things in a very ordered, careful way.",
      "Frivolous — doesn't take anything seriously, focusing on silly things.",
      "Somber — grave and serious, rarely showing amusement.",
      "Capricious — given to sudden and unaccountable changes of mood or behavior.",
      "Steadfast — resolutely or dutifully firm and unwavering.",
      "Glib — fluent and voluble but insincere and shallow.",
      "Profound — having or showing great knowledge or insight.",
      "Petulant — childishly sulky or bad-tempered.",
      "Equable — not easily disturbed or angered; calm and even-tempered.",
      "Fawning — displaying exaggerated flattery or affection.",
      "Imperious — assuming power or authority without justification.",
      "Ingratiating — intended to gain approval or favor.",
      "Recalcitrant — having an obstinately uncooperative attitude.",
      "Amiable — having or displaying a friendly and pleasant manner.",
      "Cantankerous — bad-tempered, argumentative, and uncooperative.",
      "Cordial — warm and friendly.",
      "Churlish — rude in a mean-spirited and surly way.",
      "Deferential — showing deference; respectful.",
      "Insolent — showing a rude and arrogant lack of respect.",
      "Earnest — resulting from or showing sincere and intense conviction.",
      "Flippant — not showing a serious or respectful attitude.",
      "Gregarious — fond of company; sociable.",
      "Reclusive — avoiding the company of other people.",
      "Haughty — arrogantly superior and disdainful.",
      "Humble — having or showing a modest or low estimate of one's own importance.",
      "Intense — having or showing strong feelings or opinions.",
      "Nonchalant — feeling or appearing casually calm and relaxed.",
      "Jovial — cheerful and friendly.",
      "Morose — sullen and ill-tempered.",
      "Kindred — having similar qualities or character.",
      "Alienated — feeling isolated or estranged.",
      "Lucid — expressed clearly; easy to understand.",
      "Obscure — not discovered or known about; uncertain.",
      "Malleable — easily influenced; pliable.",
      "Rigid — unable to bend or be forced out of shape; not flexible.",
      "Naive — showing a lack of experience, wisdom, or judgment.",
      "Cynical — believing that people are motivated by self-interest.",
      "Optimistic — hopeful and confident about the future.",
      "Pessimistic — tending to see the worst aspect of things.",
      "Pragmatic — dealing with things sensibly and realistically.",
      "Idealistic — characterized by idealism; unrealistically aiming for perfection.",
      "Quixotic — exceedingly idealistic; unrealistic and impractical.",
      "Realistic — having or showing a sensible and practical idea of what can be achieved.",
      "Resolute — admirably purposeful, determined, and unwavering.",
      "Irresolute — showing or feeling hesitancy; uncertain.",
      "Sagacious — having or showing keen mental discernment and good judgment.",
      "Foolish — lacking good sense or judgment.",
      "Taciturn — reserved or uncommunicative in speech.",
      "Voluble — speaking or spoken incessantly and fluently.",
      "Urbane — suave, courteous, and refined in manner.",
      "Boorish — rough and bad-mannered; coarse.",
      "Vigilant — keeping careful watch for possible danger or difficulties.",
      "Careless — not giving sufficient attention or thought to avoiding harm.",
      "Wary — feeling or showing caution about possible dangers.",
      "Trusting — showing or tending to have a belief in a person's honesty.",
      "Zealous — showing great energy or enthusiasm.",
      "Apathetic — showing or feeling no interest, enthusiasm, or concern.",
      "Adaptable — able to adjust to new conditions.",
      "Inflexible — unwilling to change or compromise.",
      "Benevolent — well meaning and kindly.",
      "Malevolent — having or showing a wish to do evil to others.",
      "Candid — truthful and straightforward; frank.",
      "Deceitful — guilty of or involving deceit; deceiving or misleading others.",
      "Diligent — having or showing care and conscientiousness in one's work.",
      "Lazy — unwilling to work or use energy.",
      "Empathetic — showing an ability to understand and share the feelings of another.",
      "Callous — showing or having an insensitive and cruel disregard for others.",
      "Frugal — sparing or economical with regard to money or food.",
      "Extravagant — lacking restraint in spending money or using resources.",
      "Gallant — brave or heroic.",
      "Craven — contemptibly lacking in courage; cowardly.",
      "Hospitable — friendly and welcoming to strangers or guests.",
      "Inhospitable — harsh and difficult to live in.",
      "Impartial — treating all rivals or disputants equally; fair and just.",
      "Biased — unfairly prejudiced for or against someone or something.",
      "Judicious — having, showing, or done with good judgment or sense.",
      "Rash — displaying or proceeding from a lack of careful consideration.",
      "Loyal — giving or showing firm and constant support or allegiance.",
      "Treacherous — guilty of or involving betrayal or deception.",
      "Meticulous — showing great attention to detail; very careful and precise.",
      "Sloppy — careless and unsystematic; excessively casual.",
      "Nostalgic — characterized by or exhibiting feelings of nostalgia.",
      "Forward-looking — favoring innovation and development; progressive.",
      "Observant — quick to notice things.",
      "Oblivious — not aware of or not concerned about what is happening around one.",
      "Placid — not easily upset or excited.",
      "Volatile — liable to change rapidly and unpredictably, especially for the worse.",
      "Resourceful — having the ability to find quick and clever ways to overcome difficulties.",
      "Helpless — unable to defend oneself or to act without help.",
      "Scrupulous — diligent, thorough, and extremely attentive to details.",
      "Unscrupulous — having or showing no moral principles; not honest or fair.",
    ],
  },

};
