// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const npcDepthTables: Record<string, InspireTable> = {
  npcIdeals: {
    id: 'npcIdeals',
    title: 'NPC Ideals',
    attribution: 'Original',
    entries: [
      "Beauty — there should be more of it in the world. (Good)",
      "Charity — those with more should give to those with less. (Good)",
      "Greater good — individuals must sometimes sacrifice for the many. (Good)",
      "Life — every living being deserves their full span of years. (Good)",
      "Respect — every person deserves their dignity acknowledged. (Good)",
      "Self-sacrifice — to give is more important than to take. (Good)",
      "Domination — strength gives the right to rule weakness. (Evil)",
      "Greed — wealth and possessions measure a life's worth. (Evil)",
      "Might — only force matters in the end. (Evil)",
      "Cruelty — the suffering of others is its own justification. (Evil)",
      "Vengeance — wrongs must be repaid, never forgiven. (Evil)",
      "Slaughter — destruction is the purest form of action. (Evil)",
      "Community — bonds between people are sacred. (Lawful)",
      "Fairness — rules apply equally to everyone. (Lawful)",
      "Honor — promises and oaths must be kept. (Lawful)",
      "Logic — reason guides every decision worth making. (Lawful)",
      "Responsibility — duties to others come before personal want. (Lawful)",
      "Tradition — the wisdom of those before us deserves respect. (Lawful)",
      "Change — what stops growing dies. (Chaotic)",
      "Creativity — the new is always worth the risk of the unknown. (Chaotic)",
      "Freedom — no one should bind another's will. (Chaotic)",
      "Independence — each person decides for themselves. (Chaotic)",
      "No limits — rules exist to be tested and broken. (Chaotic)",
      "Whimsy — the moment matters more than the long arc. (Chaotic)",
      "Balance — extremes of any kind invite disaster. (Neutral)",
      "Knowledge — understanding is its own reward. (Neutral)",
      "Live and let live — others' choices are not your business. (Neutral)",
      "Moderation — too much of anything spoils it. (Neutral)",
      "Aspiration — to become more than you currently are. (Other)",
      "Discovery — what's around the next bend is the only thing that matters. (Other)",
      "Glory — to be remembered is to live forever. (Other)",
      "Nation — loyalty to a people or a place above all else. (Other)",
      "Redemption — past wrongs can and must be made right. (Other)",
      "Self-knowledge — the only real journey is inward. (Other)",
      "Mercy — even enemies deserve the chance to lay down their arms. (Good)",
      "Hope — despair is a luxury the suffering cannot afford. (Good)",
      "Healing — broken things and broken people can both be mended. (Good)",
      "Compassion — to feel another's pain is to share the burden of it. (Good)",
      "Shelter — no one in need should be turned away from a warm door. (Good)",
      "Generosity — what you hold lightly returns to you tenfold. (Good)",
      "Protection — the strong exist to stand between harm and the weak. (Good)",
      "Truthfulness — kindness without honesty is a slower cruelty. (Good)",
      "Forgiveness — to release a grudge is to free oneself first. (Good)",
      "Stewardship — the world is borrowed, not owned. (Good)",
      "Kindness — small mercies cost nothing and outlast empires. (Good)",
      "Tyranny — order is best imposed from above with a heavy hand. (Evil)",
      "Selfishness — what is mine matters more than what is anyone's. (Evil)",
      "Hatred — to despise is to know who you are not. (Evil)",
      "Treachery — trust is a weapon best used against the trusting. (Evil)",
      "Predation — the world divides into the eater and the eaten. (Evil)",
      "Spite — better to ruin a thing than let another have it. (Evil)",
      "Conquest — peace is only the breath drawn before the next blow. (Evil)",
      "Despair — to crush hope in others is the only honest act. (Evil)",
      "Corruption — every soul has its price, and finding it is sport. (Evil)",
      "Annihilation — what cannot be ruled deserves to be unmade. (Evil)",
      "Duty — what is required of you is more important than what you want. (Lawful)",
      "Order — without rules, all that remains is appetite. (Lawful)",
      "Hierarchy — each rank has its place, and knowing yours is wisdom. (Lawful)",
      "Loyalty — to stand by your own through every storm. (Lawful)",
      "Discipline — the trained will outlasts the wild one. (Lawful)",
      "Justice — the scales must be made level, even at cost. (Lawful)",
      "Custom — the old ways were paid for in blood and should not be wasted. (Lawful)",
      "Obedience — those who command have earned the right to be heeded. (Lawful)",
      "Precision — a thing half-done is a thing not done. (Lawful)",
      "Contract — a word given is a chain forged. (Lawful)",
      "Defiance — every wall asks to be climbed over. (Chaotic)",
      "Spontaneity — the planned act is half-dead before it begins. (Chaotic)",
      "Wildness — the tame heart has already surrendered. (Chaotic)",
      "Mischief — a world too solemn deserves to be tipped over. (Chaotic)",
      "Impulse — the gut speaks faster than the head, and often truer. (Chaotic)",
      "Revolution — what cannot be reformed must be torn down. (Chaotic)",
      "Wandering — a road followed too long becomes a cage. (Chaotic)",
      "Expression — what is felt must be shown, however it lands. (Chaotic)",
      "Disruption — comfortable certainties deserve a hard knock. (Chaotic)",
      "Caprice — to do a thing simply because no one expects it. (Chaotic)",
      "Practicality — what works matters more than what's elegant. (Neutral)",
      "Nature — the wild was here first and will be here last. (Neutral)",
      "Self-reliance — depend on yourself and you cannot be disappointed. (Neutral)",
      "Acceptance — the world is as it is, not as we wish. (Neutral)",
      "Survival — staying alive is a sufficient project for any day. (Neutral)",
      "Detachment — the wise observer keeps their hands clean of all sides. (Neutral)",
      "Stability — what endures is worth more than what shines briefly. (Neutral)",
      "Sufficiency — to want less is to need less. (Neutral)",
      "Family — blood and chosen kin are the only true country. (Other)",
      "Curiosity — the unexamined corner of the map is an itch that must be scratched. (Other)",
      "Faith — there is more than what the eye can measure. (Other)",
      "Legacy — to plant trees whose shade you will never sit under. (Other)",
      "Mastery — to do one thing better than anyone living has done it. (Other)",
      "Service — a life spent for others is a life well spent. (Other)",
      "Wonder — the world is stranger than reports suggest, and worth meeting. (Other)",
      "Craft — the work of one's hands is the truest signature. (Other)",
      "Story — a life unremembered is a life half-lived. (Other)",
      "Sacrifice — the price of meaning is paid in what you give up. (Other)",
      "Reckoning — every account opened must one day be closed. (Other)",
      "Pilgrimage — the journey is the prayer. (Other)",
      "Witness — to see clearly and report honestly is the first duty. (Other)",
      "Belonging — to be known by your people is the deepest comfort. (Other)",
      "Patience — most wounds the world deals will mend, given time and care. (Neutral)",
      "Adventure — a life lived inside walls is no life at all. (Chaotic)",
      "Reform — a law that fails the people must be remade by them. (Lawful)",
      "Knowledge — ignorance is the root of all suffering. (Neutral)",
      "Power — only the strong can protect the weak, or themselves. (Evil)",
      "Compassion — we must help each other, for no one else will. (Good)",
      "Order — chaos is the enemy of prosperity. (Lawful)",
      "Freedom — no one has the right to chain another. (Chaotic)",
      "Tradition — the old ways are the best ways. (Lawful)",
      "Progress — we must build a better future, whatever the cost. (Neutral)",
      "Loyalty — my word is my bond, and my friends are my family. (Lawful)",
      "Independence — I rely on no one but myself. (Chaotic)",
      "Harmony — we must live in balance with nature and each other. (Good)",
      "Greed — the one with the most gold when they die wins. (Evil)",
      "Justice — every wrong must be righted, no matter how small. (Lawful)",
      "Mercy — forgiveness is harder than vengeance, but more important. (Good)",
      "Ambition — I will be remembered, no matter what it takes. (Any)",
      "Curiosity — I must see what is over the next hill. (Chaotic)",
      "Duty — I will do what is required of me, even if it kills me. (Lawful)",
      "Hedonism — life is short, so enjoy every pleasure it offers. (Chaotic)",
      "Survival — the only rule that matters is staying alive. (Neutral)",
      "Vengeance — those who wrong me will pay in blood. (Evil)",
      "Truth — a painful truth is better than a comforting lie. (Lawful)",
      "Deception — the world is a game, and the best liar wins. (Chaotic)",
      "Honor — my reputation is the only thing I truly own. (Lawful)",
      "Pragmatism — the ends always justify the means. (Neutral)",
      "Faith — the gods have a plan, and I am its instrument. (Lawful)",
      "Skepticism — trust nothing you cannot see with your own eyes. (Neutral)",
      "Generosity — what I have is meant to be shared. (Good)",
      "Selfishness — I look out for number one. (Evil)",
      "Bravery — fear is an illusion meant to be shattered. (Good)",
      "Caution — the bold die young. (Neutral)",
      "Creativity — I must bring new beauty into the world. (Good)",
      "Destruction — tearing down the old makes way for the new. (Chaotic)",
      "Equality — no one is inherently better than anyone else. (Good)",
      "Hierarchy — everyone has their place, and society functions best when they stay in it. (Lawful)",
      "Family — blood is thicker than water. (Neutral)",
      "Community — we are stronger together than we are apart. (Good)",
      "Individuality — I will not be shaped by the expectations of others. (Chaotic)",
      "Respect — everyone deserves to be treated with dignity. (Good)",
      "Cruelty — the weak exist to be exploited by the strong. (Evil)",
      "Humility — I am but a small part of a vast universe. (Good)",
      "Pride — I am exceptional, and others should recognize it. (Any)",
      "Simplicity — a complex life is a stressful life. (Neutral)",
      "Complexity — the world is a puzzle to be solved. (Neutral)",
      "Romance — true love is the only thing worth fighting for. (Good)",
      "Cynicism — love is a fairy tale for fools. (Neutral)",
      "Optimism — tomorrow will always be better than today. (Good)",
      "Pessimism — expect the worst, and you'll never be disappointed. (Neutral)",
      "Stoicism — endure hardship without complaint. (Lawful)",
      "Passion — feel everything deeply, or don't feel at all. (Chaotic)",
      "Responsibility — we must clean up our own messes. (Lawful)",
      "Rebellion — rules are meant to be broken. (Chaotic)",
    ],
  },

  npcBonds: {
    id: 'npcBonds',
    title: 'NPC Bonds',
    attribution: 'Original',
    entries: [
      "Devoted to a personal goal they have not yet achieved.",
      "Fiercely protective of close family members.",
      "Loyal to colleagues, comrades, or guild-fellows.",
      "Owes a deep debt to a benefactor, patron, or employer.",
      "Carries an unfulfilled love or romantic obligation.",
      "Drawn to a specific place that has special meaning.",
      "Treasures a small keepsake of immense personal value.",
      "Tied to a valuable object — heirloom, prize, or instrument.",
      "Driven by a need for revenge against a specific party.",
      "Holds an oath to a deceased person they still consider binding.",
      "Sworn to protect a younger sibling from a danger only they see clearly.",
      "Searching for a parent who disappeared before they were old enough to remember.",
      "Bound by gratitude to the stranger who once saved their life.",
      "Carries letters from someone they intend to deliver in person.",
      "Owes their education to a mentor whose later choices they cannot defend.",
      "Promised a dying friend they would finish a specific task.",
      "Pledged to return a borrowed object before the lender's patience runs out.",
      "Honors the memory of a fallen company by wearing some part of their uniform.",
      "Keeps a child safe whose true parentage would make them a target.",
      "Carries the ashes of a loved one toward a place they once meant to visit together.",
      "Returns each year to a grave that no one else remembers.",
      "Bound to a temple that took them in when no one else would.",
      "Indebted to a criminal whose price has not yet been named.",
      "Tied to a ship and its crew more than to any city ashore.",
      "Pledged to a cause whose other members have all been killed or scattered.",
      "Carries a coin from every place they have left a friend behind.",
      "Owes everything to a rescuer they have not seen in years.",
      "Sworn to find and free a comrade still held captive somewhere.",
      "Marked by a debt of honor to someone whose name they will not speak.",
      "Bound to a master whose orders they no longer respect but still obey.",
      "Travels in search of the artist whose work changed their life.",
      "Carries a song that was taught to them on the condition they teach it to one other.",
      "Promised to tell a specific story to a specific person before they die.",
      "Sworn to a religious vow whose terms are too private to share.",
      "Tied to a piece of land their family has worked for generations.",
      "Bound by a marriage made in haste and not yet undone.",
      "Holds a key whose lock they have never found.",
      "Carries a sealed message they swore not to open.",
      "Devoted to a teacher whose teachings they have begun to doubt.",
      "Looks after an aging relative who has nowhere else to go.",
      "Adopted by a community that asked nothing in return and may someday need everything.",
      "Sworn to never set foot in a particular city again until a condition is met.",
      "Maintains a friendship with someone their faction officially considers an enemy.",
      "Carries an unspoken love for a friend who has never noticed.",
      "Bound by a childhood promise made in earnest and never released.",
      "Owes their freedom to a smuggler who may one day call in the favor.",
      "Returns a favor each year to the family that hid them when they were hunted.",
      "Sworn to find the person who stole something irreplaceable from their household.",
      "Holds a place at a table that has been empty for years, waiting for one return.",
      "Tied to an animal companion whose loss would unmake them.",
      "Carries the unfinished work of a parent or master who died midway.",
      "Pledged to ensure a particular book never falls into a particular hand.",
      "Bound to a co-conspirator by a secret only the two of them know.",
      "Sworn to repay every kindness ever shown to them, ledger in mind.",
      "Returns regularly to a tree planted on the day a loved one was born.",
      "Carries a debt to a healer whose payment was a future favor unspecified.",
      "Bound to a deity through a personal vow rather than ordained service.",
      "Maintains a grudge they know is too old to be useful and still cannot release.",
      "Honors a treaty their people no longer formally recognize.",
      "Sworn to a code their order has officially abandoned.",
      "Pledged to see a particular ship returned to its rightful port.",
      "Cares for a stranger's child entrusted to them in an emergency.",
      "Holds a piece of jewelry meant to be returned to a family they cannot find.",
      "Bound to a place by the burial of someone they cannot leave alone.",
      "Sworn to find the truth about a death officially ruled an accident.",
      "Pursues the completion of an ancestor's broken quest.",
      "Tied to a guild apprentice whose progress they consider their personal responsibility.",
      "Carries the colors of a banner that has not flown in a generation.",
      "Pledged to bring a wandering family member home before a season ends.",
      "Bound to repay a magical favor whose terms grow stranger with time.",
      "Honors a sworn-sibling bond made on a battlefield neither has spoken of since.",
      "Sworn to keep a particular grave undisturbed no matter what is buried with it.",
      "Carries a list of names they have promised to find or to mourn.",
      "Promised to finish the apprenticeship of someone who could not.",
      "Devoted to a craft passed down through their family for many generations.",
      "Bound by hospitality to anyone who once shared bread with them.",
      "Owes their life to an enemy who chose mercy on an unrecorded day.",
      "Sworn to protect a stretch of road from the bandits who once ambushed them there.",
      "Tied to a small village whose troubles will always pull them back.",
      "Carries the seal of a guild that no longer exists, hoping to revive it.",
      "Bound to a partner in a venture neither of them has yet completed.",
      "Promised to deliver an inheritance to an heir who may not want it.",
      "Holds vigil each year on the anniversary of a battle they survived alone.",
      "Sworn to defend a sacred grove or spring against any who would defile it.",
      "Sworn to teach what they were taught, to at least one student before the end.",
      "Pledged to walk the route of an old pilgrimage their grandmother could not finish.",
      "Tied by gratitude to a road-warden who looked the other way at the right moment.",
      "Carries a ring that must be returned to a hand they have never seen.",
      "Owes a confession to one person and dreads the day they find them.",
      "Bound to fulfill the last request of a stranger who died in their arms.",
      "Holds a token from a fey patron who has not yet asked for anything in return.",
      "Promised to never refuse aid to anyone wearing a specific symbol.",
    ],
  },

  npcFlawsSecrets: {
    id: 'npcFlawsSecrets',
    title: 'NPC Flaws & Secrets',
    attribution: 'Original',
    entries: [
      "Carries a forbidden or socially unacceptable love.",
      "Indulges secret habits incompatible with their public role.",
      "Profound arrogance disguised as competence.",
      "Envies another person's life and would take it if they could.",
      "Greed deep enough to compromise their other values.",
      "Loses self-control under stress, sometimes destructively.",
      "Has a powerful enemy who doesn't know where they are yet.",
      "Carries a specific phobia they have arranged their life to avoid.",
      "Has a shameful incident in their past nobody else knows about.",
      "Committed a serious crime that remains unprosecuted.",
      "Possesses forbidden knowledge they would lose much by revealing.",
      "Is reckless to a degree that endangers their companions.",
      "Drinks more than they admit and remembers less than they pretend.",
      "Owes money to people who are running out of patience.",
      "Is not the person their family thinks died years ago.",
      "Cannot bring themselves to spend a single coin of an inheritance they didn't earn.",
      "Lies about a small fact so often it has become impossible to retract.",
      "Has a child somewhere whose other parent has not been told.",
      "Once abandoned a comrade and lets the survivors believe a different story.",
      "Took credit for a deed they did not perform and cannot now disclaim.",
      "Holds a position they obtained by sabotaging the previous occupant.",
      "Stole from a friend long ago and watches them search to this day.",
      "Cannot resist a wager, and has lost important things this way.",
      "Believes themselves cursed and orders their life around small superstitions.",
      "Cannot say no to a sob story, and has been used for this more than once.",
      "Despises a specific group quietly and overcompensates in their company.",
      "Is in love with their best friend's spouse and has never said a word.",
      "Reads every letter they're entrusted with before passing it along.",
      "Is a deserter from a war their nation officially won.",
      "Was the only survivor of a disaster and does not know why.",
      "Has memorized confidential information they were not meant to retain.",
      "Sleeps poorly and is not quite themselves before noon.",
      "Has secretly converted to a faith their community would not tolerate.",
      "Practices a magical art they swore to give up.",
      "Is functionally illiterate and has hidden it through clever workarounds.",
      "Holds an heirloom that does not, in fact, belong to their family.",
      "Was once paid to kill someone and learned afterward they had been deceived.",
      "Suffers a chronic illness they cannot afford to let employers learn of.",
      "Is being blackmailed quietly for something they did long ago.",
      "Has a twin no one currently in their life knows about.",
      "Cannot resist correcting others, even when it costs them allies.",
      "Holds a grudge older than most of the people now around them.",
      "Has a violent temper they have learned to mask but not to cure.",
      "Cheated once on something that mattered and still flinches at the word.",
      "Eats compulsively when anxious and is ashamed of it.",
      "Is terrified of one specific person and would do anything to avoid them.",
      "Carries a weapon they were sworn never to draw again.",
      "Once let an innocent person take the blame for what they did.",
      "Suffers nightmares so vivid they have begun to confuse them with memory.",
      "Has a price on their head in a city they have not visited in years.",
      "Forged credentials they have used so long they almost feel genuine.",
      "Cannot stand to be touched, and conceals this with careful staging.",
      "Has an addiction to a substance they obtain through inconvenient channels.",
      "Believes in a prophecy about themselves that no one else takes seriously.",
      "Is the unacknowledged child of someone well known.",
      "Sold a secret once and has spent years hoping no one traces it back.",
      "Practices a small ritual each morning that would mark them as a heretic.",
      "Has stolen identity papers in a hidden compartment, ready for an emergency.",
      "Knows the location of a body whose disappearance was never explained.",
      "Was once a member of an organization they now publicly oppose.",
      "Speaks a language they pretend not to understand, and listens carefully.",
      "Has betrayed a friend in a small way that grew into a large one.",
      "Cannot bear silence and will fill it with admissions they later regret.",
      "Keeps a journal that, if found, would ruin several other lives besides theirs.",
      "Is impotent in a culture that measures worth by progeny.",
      "Was healed by a being whose price has not yet been collected.",
      "Has a familiar or bound servant they keep entirely hidden.",
      "Once received a warning they ignored, and the consequences are still unfolding.",
      "Cannot turn down a dare and has lost teeth, friends, and fingers this way.",
      "Carries proof of a noble's parentage they have never used.",
      "Has a hidden room at home containing things they should not own.",
      "Avoids mirrors for a reason they have never explained.",
      "Is allergic to a common substance and has built their life around hiding it.",
      "Believes themselves slowly dying of an undiagnosed condition.",
      "Knows the true author of a famous work credited to someone else.",
      "Took a child from a battlefield long ago and raised them as their own.",
      "Has been sober for years and would rather not say from what.",
      "Carries old scars that match an account in another town's official records.",
      "Once read a forbidden book and remembers more of it than they should.",
      "Suspects one of their parents was not who their other parent thought.",
      "Has murdered, exactly once, and lives in fear of doing it again.",
      "Sells small confidences for small sums to a contact they meet at night.",
      "Is in possession of stolen art they cannot sell and will not surrender.",
      "Hides a magical mark from a pact they no longer remember making clearly.",
      "Has betrayed every romantic partner they have ever had and does not know why.",
      "Once swore to a deity they have since privately abandoned.",
      "Cannot read a face accurately and has been deceived because of it more than once.",
      "Bears a tattoo from a group they fled, hidden where no one looks.",
      "Stole their current name from a gravestone in a distant town.",
      "Hoards small useless objects and panics when any of them are moved.",
      "Cannot keep a confidence and tells themselves each disclosure is the last.",
      "Witnessed a murder long ago and chose not to report it.",
      "Is intensely superstitious and has hidden routines no observer would guess.",
      "Believes one of their closest companions is plotting against them, without evidence.",
      "Has falsified records in their workplace that have not yet been discovered.",
      "Hears voices on certain nights and is not sure whether to trust them.",
      "Suffers from a recurring memory lapse and has begun to lose hours at a time.",
      "Once impersonated a dead relative to collect what was owed them.",
      "Owns a map they took from a corpse and have never dared to follow.",
      "Has trained their voice and accent to disguise their true origin.",
      "Is secretly addicted to a rare and expensive magical substance.",
      "Once abandoned their post during a battle, leading to the deaths of their comrades.",
      "Has a crippling phobia of the dark that they hide behind bravado.",
      "Stole the credit for a major discovery or invention from a deceased colleague.",
      "Is the illegitimate child of a notorious criminal, and fears being found out.",
      "Accidentally caused the fire that destroyed their family home, blaming it on a dragon.",
      "Is deeply in debt to a dangerous local crime boss.",
      "Secretly sympathizes with the enemy faction in the current war.",
      "Has a spouse or child in another town that they abandoned years ago.",
      "Stole a sacred artifact from their own temple and sold it to pay off debts.",
      "Is slowly turning into a monster due to a cursed bite, and is hiding the symptoms.",
      "Falsified their credentials to get their current, highly respected position.",
      "Is blackmailed by someone who knows they committed a petty theft in their youth.",
      "Harbors a deep-seated prejudice against a specific, harmless race or group.",
      "Secretly hoards wealth while pretending to live in poverty.",
      "Is desperately envious of their sibling's success and actively sabotages them.",
      "Accidentally poisoned a prominent figure and framed someone else for the crime.",
      "Maintains a hidden shrine to a forbidden or evil deity in their basement.",
      "Is a coward who always finds an excuse to avoid real danger.",
      "Has a habit of 'borrowing' things and forgetting to return them.",
      "Secretly reads other people's mail or diaries whenever they get the chance.",
      "Is a compulsive liar who makes up stories to make themselves seem more interesting.",
      "Has a terrible temper that they struggle to keep in check, often lashing out at subordinates.",
      "Is secretly illiterate and has gone to great lengths to hide it from their peers.",
      "Takes credit for the charitable acts of others.",
      "Is terrified of animals, even small, harmless ones.",
      "Secretly believes they are a reincarnated hero from a past age, and demands to be treated as such.",
      "Has a tendency to betray confidences when they think it will benefit them.",
      "Is deeply vain and spends an exorbitant amount of time and money on their appearance.",
      "Secretly hates the town they live in and everyone in it, but pretends to be a proud citizen.",
      "Is a glutton who frequently eats more than their share of communal rations.",
      "Has a tendency to blame their own mistakes on bad luck or the interference of others.",
      "Is secretly a member of a revolutionary group that wants to overthrow the current government.",
      "Maintains a secret, highly embarrassing hobby that they would die rather than reveal.",
      "Is terrified of water and refuses to travel by boat or cross deep rivers.",
      "Secretly resents their own children and wishes they had never become a parent.",
      "Is a kleptomaniac who steals small, worthless items for the thrill of it.",
      "Has a tendency to hold grudges over minor slights for years.",
      "Is secretly tone-deaf but insists on singing loudly at every opportunity.",
      "Maintains a facade of piety while secretly indulging in numerous vices.",
      "Is terrified of aging and will try any dangerous, untested remedy to stay young.",
      "Secretly believes that they are superior to everyone else because of a minor, obscure talent.",
      "Has a tendency to eavesdrop on conversations and use the information for their own gain.",
      "Is secretly afraid of magic and refuses to trust anyone who uses it.",
      "Takes pleasure in the misfortune of others, even those they call friends.",
      "Is a hypochondriac who constantly believes they are dying of some exotic disease.",
      "Secretly wishes they had chosen a different path in life and bitterly regrets their choices.",
      "Has a tendency to interrupt others and rarely listens to what anyone else is saying.",
      "Is terrified of being alone and will cling to anyone who pays them attention.",
      "Secretly despises the work they do but feels trapped by the need for money.",
      "Is a sore loser who will cheat or throw tantrums if they don't win at games.",
      "Has a tendency to make promises they have no intention of keeping.",
      "Is secretly afraid of the dark and sleeps with a lantern burning bright.",
      "Takes credit for the ideas of their subordinates without acknowledging them.",
      "Is terrified of failure and will avoid taking any risks, no matter the potential reward.",
      "Secretly believes that the world is out to get them and that everyone is plotting their downfall.",
      "Has a tendency to borrow money and never pay it back.",
      "Is secretly a hopeless romantic who falls in love with anyone who is kind to them.",
      "Maintains a secret collection of morbid curiosities.",
      "Is terrified of commitment and will sabotage any relationship that gets too serious.",
      "Secretly enjoys causing drama and stirring up conflict between others.",
      "Has a tendency to exaggerate their own accomplishments to ridiculous proportions.",
      "Is secretly afraid of physical pain and will capitulate immediately if threatened.",
      "Takes pleasure in belittling others to make themselves feel more important.",
      "Is terrified of being forgotten and will do anything for attention, even if it's negative.",
      "Secretly believes that they are destined for greatness and that everyone else is just an extra in their story.",
      "Has a tendency to jump to conclusions without gathering all the facts.",
      "Is secretly a coward who will push others into danger to save themselves.",
      "Maintains a secret diary filled with hateful thoughts about everyone they know.",
      "Is terrified of germs and goes to extreme lengths to avoid contact with dirty things.",
      "Secretly wishes they were someone else and constantly tries to imitate their idol.",
      "Has a tendency to gossip and spread rumors, even if they know they are false.",
      "Is secretly afraid of success and will sabotage themselves just when things are going well.",
      "Takes credit for the hard work of others while doing as little as possible themselves.",
      "Is terrified of authority figures and will agree with anything they say, even if it's wrong.",
      "Secretly believes that they are always right and will argue endlessly to prove it.",
      "Has a tendency to judge others harshly based on superficial characteristics.",
      "Is secretly a very lonely person who pushes people away out of fear of rejection.",
      "Maintains a secret stash of illicit substances that they use to cope with stress.",
      "Is terrified of change and will fight tooth and nail to keep things exactly as they are.",
      "Secretly wishes ill upon those who have wronged them, even for minor offenses.",
      "Has a tendency to focus on the negative aspects of every situation.",
      "Is secretly afraid of the future and constantly worries about what might happen.",
      "Takes pleasure in proving others wrong, even in trivial matters.",
      "Is terrified of making the wrong decision and will agonize over even simple choices.",
      "Secretly believes that they are unlovable and unworthy of happiness.",
      "Has a tendency to manipulate others to get what they want without them realizing it.",
      "Is secretly a very selfish person who only cares about their own needs and desires.",
    ],
  },

  npcBackgroundConcepts: {
    id: 'npcBackgroundConcepts',
    title: 'NPC Background Concepts',
    attribution: 'Original',
    entries: [
      "An acolyte who serves their temple loyally but doubts privately.",
      "A charlatan whose latest scheme has caught up with them in this town.",
      "A criminal trying to leave the life but unable to refuse one last job.",
      "An entertainer who performs in public to gather information for someone.",
      "A folk hero unable to live up to the story local people tell about them.",
      "A guild artisan whose mastery is recognized, whose loyalty is not.",
      "A hermit who knew something important and has come down from the hills to share it.",
      "A noble whose title is intact and whose fortune is not.",
      "An outlander whose people are no longer where they used to be.",
      "A sage whose theories are correct but professionally dismissed.",
      "A sailor whose ship will not have them back.",
      "A soldier whose war ended but whose habits did not.",
      "An urchin who knows the underside of the city better than anyone living.",
      "A midwife who has delivered half the town and knows which families to fear.",
      "A scribe who has copied documents they were ordered to forget.",
      "A merchant whose ledger balances only because of one transaction they cannot discuss.",
      "A blacksmith who once forged a weapon they wish had been lost.",
      "A tax collector whose route passes through villages that hate them on principle.",
      "A jailer who began to suspect they had been keeping innocent people.",
      "A judge who handed down a sentence they have privately doubted ever since.",
      "A bounty hunter who has begun to like the kind of people they're paid to bring in.",
      "A mercenary who took a contract for the losing side and lived through it.",
      "A coachman who has driven nearly every road in the region and remembers what they saw.",
      "An innkeeper who hears more than they let on and writes none of it down.",
      "A cook for a great household who knows exactly how that household is run.",
      "A musician who plays at funerals and at weddings, depending on the season.",
      "A puppeteer whose plays have a habit of mirroring local scandals too closely.",
      "An apothecary whose remedies sometimes work and whose patients always pay.",
      "A surgeon trained in a war they will not name.",
      "A diviner whose visions are accurate but whose interpretations are not.",
      "A retired adventurer who quit one quest short of the one that mattered.",
      "A bodyguard whose last charge died in their arms.",
      "A bookbinder who has read every volume they have ever stitched.",
      "An archivist whose archive was burned and who is rebuilding it from memory.",
      "A cartographer whose maps are accurate to the village level and unauthorized.",
      "A surveyor whose findings would dispossess important people if published.",
      "A hunter who tracks for the lord by day and for the peasantry by night.",
      "A poacher whose family has hunted these woods longer than the lord has owned them.",
      "A trapper who came in from the deep woods because something else moved in.",
      "A gardener at a great house who is the only one who notices everything.",
      "A stablehand who has overheard the most important conversations of the past decade.",
      "A nurse who raised a child who became someone famous and infamous in equal measure.",
      "A tutor whose former pupils have grown into the powers of the region.",
      "A bell-ringer who marks every birth and every death of the parish.",
      "A grave-digger who knows which coffins were lighter than they should have been.",
      "A coroner who has signed off on more accidents than statistics would predict.",
      "A barber whose customers tell them more than their confessors hear.",
      "A laundress who has seen every household's linens, in every condition.",
      "A pawnbroker who holds objects whose stories the owners cannot afford to tell.",
      "A moneylender whose ledger is the most accurate record of the town's failures.",
      "A clerk in a magistrate's office who has noticed a pattern no one else has.",
      "A herald who has carried messages whose contents would shame their senders.",
      "A diplomat-in-disgrace whose minor mistake had major consequences.",
      "A spy whose handler has gone silent and may be dead.",
      "A defector from a foreign court who is still being looked for.",
      "A deserter who has rebuilt a quiet life and watches the road.",
      "A veteran of a lost cause that no one is allowed to mention.",
      "A revolutionary whose comrades all died and who alone walked away.",
      "A reformer whose own reforms made them enemies on every side.",
      "A retired thief who teaches their grandchildren a more honest trade.",
      "A retired assassin who has been polite to neighbors for twenty years.",
      "A confidence artist who has stopped running and is wondering if they should start again.",
      "A smuggler who has learned every coastline and every excuse.",
      "A pirate granted a pardon they don't quite trust.",
      "A privateer whose letters of marque are no longer recognized.",
      "A guide who has led parties into places they themselves no longer enter.",
      "A pilgrim who reached their destination and discovered no answer waiting.",
      "A penitent doing a long, quiet penance no one else knows about.",
      "A defrocked priest who still keeps the small offices privately.",
      "A heretic whose only crime was reading the wrong text aloud.",
      "An exorcist who has begun to suspect their last subject was not possessed.",
      "A monk who left their order over a disagreement they will not detail.",
      "A nun who left to nurse a relative and never went back.",
      "A scholar whose patron died midway through a manuscript and left it in their hands.",
      "A linguist who can read a script that scholars insist no one ever wrote.",
      "A historian whose research embarrasses the families currently in power.",
      "A genealogist who has discovered a bloodline that complicates a current succession.",
      "An astronomer who has noticed something in the sky that shouldn't be there.",
      "An alchemist whose finest preparation was destroyed before they could record the formula.",
      "An inventor whose best machine was confiscated and never returned.",
      "A clockmaker whose finest piece runs in the home of a tyrant.",
      "A jeweler who has set stones whose origins they preferred not to know.",
      "A tailor who measures the powerful and remembers every fitting.",
      "A perfumer whose scents are worn by half the court without their knowledge.",
      "A vintner whose vintage is sought, whose lands are quietly contested.",
      "A miller whose mill stands on land claimed by three different parties.",
      "A shepherd who has wandered farther than most maps depict.",
      "A drover who knows where every herd has been driven for thirty years.",
      "A river-pilot whose stretch of water is full of inconvenient bodies.",
      "A ferryman who decided, at a certain hour, to start ferrying for free.",
      "A lighthouse keeper who has watched ships go down and reported only some of them.",
      "A fisher who pulled something from the sea that they have not told anyone about.",
      "A whaler who has come home to find their trade is being banned.",
      "A widow who runs the family business better than her husband ever did.",
      "A widower who has not yet told the children that the savings are gone.",
      "An orphan grown old without ever quite settling into a kind of life.",
      "A bastard child quietly acknowledged by a parent who cannot acknowledge them publicly.",
      "An heir whose inheritance is real but whose siblings are determined.",
      "A foundling who has begun to suspect the family that raised them was not their first.",
      "A messenger who carries letters across borders that change without warning.",
      "An apothecary whose cures work but whose methods are deeply suspect.",
      "A blacksmith who secretly forges weapons for a rebellion they don't fully support.",
      "A baker who uses magic to make their pastries incredibly addictive.",
      "A retired soldier who now runs an orphanage and struggles to keep it funded.",
      "A corrupt official who genuinely believes they are doing what's best for the town.",
      "A struggling artist who has recently found a very dark, very demanding patron.",
      "A wealthy merchant who is secretly funding an expedition to find a mythical city.",
      "A jaded guard who has seen too much and now only cares about their pension.",
      "A young noble who has fled an arranged marriage and is hiding in the slums.",
      "A grizzled veteran who refuses to talk about the war they barely survived.",
      "A seemingly crazy hermit who actually knows the truth about a local legend.",
      "A charming rogue who always has a scheme but never quite pulls it off.",
      "A stern librarian who strictly enforces the rules but secretly reads romance novels.",
      "A traveling performer who uses their shows as a cover for espionage.",
      "A bitter former champion who now trains others but resents their youth.",
      "A naive idealist who is in for a rude awakening when they face the real world.",
      "A pragmatic smuggler who will move anything for a price, no questions asked.",
      "A devout cleric who is beginning to question the teachings of their church.",
      "A mysterious stranger who arrived in town with no memory of their past.",
      "A cowardly thief who relies on luck and fast talking rather than skill.",
      "A brilliant scholar who is arrogant and dismissive of anyone they consider inferior.",
      "A reformed criminal who is trying desperately to make amends for their past.",
      "A stoic bounty hunter who never fails to bring in their target.",
      "A passionate revolutionary who is willing to burn the city down to save it.",
      "A cynical mercenary who only cares about the next paycheck.",
      "A kindly old grandparent who is secretly a retired master assassin.",
      "A disgraced noble who is trying to claw their way back to power.",
      "A dedicated healer who is willing to risk everything to save a life.",
      "A restless explorer who can never stay in one place for long.",
      "A shrewd politician who is always three steps ahead of their opponents.",
      "A haunted survivor who is plagued by nightmares of a terrible event.",
      "A desperate parent who will do anything to protect their child.",
      "A loyal retainer who will follow their master to the bitter end.",
      "A conflicted spy who has fallen in love with their target.",
      "A weary traveler who is just looking for a place to rest.",
      "A fiercely independent ranger who prefers the company of animals to people.",
      "A disgraced knight who is trying to regain their honor.",
      "A master thief who is planning one last, impossible heist.",
      "A cynical gravedigger who has heard all the local gossip.",
      "A dedicated historian who is obsessed with uncovering a lost truth.",
      "A troubled youth who is drawn to dark magic.",
      "A wise elder who provides cryptic advice to those who seek it.",
      "A charming swindler who sells fake magical remedies.",
      "A stern magistrate who is unyielding in their application of the law.",
      "A mysterious fortune teller whose predictions are always accurate but unhelpful.",
      "A dedicated craftsman who is obsessed with creating a masterpiece.",
      "A loyal dog who is surprisingly intelligent and fiercely protective.",
      "A seemingly ordinary farmer who is actually a powerful retired adventurer.",
      "A bitter rival who is always trying to one-up the heroes.",
      "A tragic figure who is doomed to repeat the mistakes of their past.",
      "A cheerful innkeeper who always has a story and a warm meal.",
      "A cynical guard who has seen it all and expects the worst.",
      "A dedicated scholar who is oblivious to the world around them.",
      "A passionate artist who is completely absorbed in their work.",
      "A shrewd merchant who always gets the better end of a deal.",
      "A haunted veteran who is struggling to adjust to civilian life.",
      "A desperate criminal who is on the run from the law.",
      "A loyal friend who is always there when you need them.",
      "A conflicted hero who is struggling to do the right thing.",
      "A weary traveler who has seen too much of the world.",
      "A fiercely independent spirit who refuses to be tied down.",
      "A disgraced leader who is trying to regain their former glory.",
      "A master manipulator who is always pulling the strings from the shadows.",
      "A cynical observer who comments on the absurdities of life.",
      "A dedicated protector who will sacrifice themselves for others.",
      "A troubled soul who is searching for meaning in a chaotic world.",
      "A wise counselor who offers guidance to those in need.",
      "A charming scoundrel who always manages to talk their way out of trouble.",
      "A stern enforcer who ensures that the rules are followed.",
      "A mysterious figure who always seems to know more than they let on.",
      "A dedicated servant who is always anticipating their master's needs.",
      "A loyal companion who will never leave your side.",
      "A seemingly ordinary person who is hiding a dark secret.",
      "A bitter enemy who will stop at nothing to destroy you.",
      "A tragic victim who is caught in the crossfire of a larger conflict.",
      "A cheerful optimist who always sees the bright side of things.",
      "A cynical realist who expects the worst from everyone.",
      "A dedicated idealist who believes in making the world a better place.",
      "A passionate rebel who fights against injustice.",
      "A shrewd pragmatist who always does what is necessary.",
      "A haunted soul who is tormented by their past.",
      "A desperate survivor who will do anything to stay alive.",
      "A loyal soldier who follows orders without question.",
      "A conflicted leader who is struggling to make the right decisions.",
      "A weary warrior who is tired of fighting.",
      "A fiercely independent thinker who refuses to follow the crowd.",
      "A disgraced scholar who is trying to prove their theories.",
      "A master artisan who is dedicated to their craft.",
    ],
  },

};
