// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const plotTables: Record<string, InspireTable> = {
  introductions: {
    id: 'introductions',
    title: 'Adventure Introductions',
    attribution: 'Original',
    entries: [
      "The party falls into the adventure literally — a sinkhole, a teleport mishap, a portal pulling them through.",
      "The party stumbles onto a body, and the evidence on it draws them in.",
      "An attack on the road forces the party to take refuge somewhere significant.",
      "A map surfaces — sold, stolen, or inherited — that points somewhere the party hadn't planned to go.",
      "A familiar face — a child, a friend, a lover — arrives begging for help.",
      "A stranger in a public place chooses the party out of a room and explains why.",
      "A community petitions the party formally, with a town meeting or a deputation.",
      "Someone the party owes a debt to calls in that debt now.",
      "A dream visits every member of the party on the same night.",
      "A magical compulsion — a geas, a curse, a binding — leaves no choice.",
      "A reward poster names a price that solves a personal problem.",
      "A ghost or vision appears and refuses to leave until the party acts.",
      "A dying messenger collapses at the party's feet and presses a letter into their hands.",
      "The party is mistakenly arrested for the crime and offered freedom in exchange for solving it.",
      "A package addressed to the party arrives with no sender and contents that imply danger.",
      "A drinking companion from the night before is missing in the morning, and so is the party's coin.",
      "A child appears at the inn, asks for the party by name, and refuses to say who sent them.",
      "An old letter is found tucked behind a portrait — its instructions are still actionable.",
      "The party wins something at a game they shouldn't have entered, and now must claim the prize in person.",
      "A storm forces the party to shelter in a place that turns out to be exactly where they were needed.",
      "An auction the party attended idly closes with them holding a deed to somewhere they've never been.",
      "A stranger dies in the party's arms after speaking a single name they didn't know.",
      "The party answers a knock at the door and finds a stranger who claims to be one of them.",
      "A summons bearing an official seal demands the party appear before someone important.",
      "An old enemy of one party member sends a peace offering with strings attached.",
      "The party is hired to do something simple, and discovers within an hour it isn't.",
      "A caravan they were riding with is ambushed, and the survivors look to the party to lead.",
      "A child in a market hands the party a coin that turns out to be something else.",
      "A fortune-teller refuses payment after a reading and tells the party to leave town tonight.",
      "The party wakes to find a stranger sleeping at their fire who knows things they shouldn't.",
      "A note slipped under a door names a meeting place and a time only hours away.",
      "A traveling preacher denounces the party from a platform and names them by deed.",
      "A relative the party didn't know they had dies and leaves them an obligation.",
      "Town criers announce a problem that the party realizes only they can address.",
      "The party is offered a place at a noble's table and learns the price during dessert.",
      "A magical item the party owns begins behaving differently in a specific direction.",
      "A friend's funeral is interrupted by an accusation that demands investigation.",
      "An animal — a dog, a raven, a cat — leads the party somewhere and refuses to be deterred.",
      "A scholar tracks the party down with a question only they can answer.",
      "An inheritance arrives by courier with conditions that send the party traveling.",
      "The party is hired as bodyguards for what is clearly not really a bodyguard job.",
      "A face in a crowd matches a face the party last saw years and miles ago.",
      "The town's bells ring at the wrong hour, and the party is closest to the source.",
      "A merchant short on guards offers passage in exchange for protection.",
      "The party stumbles into a ritual already in progress and must decide whether to interrupt.",
      "A child's drawing depicts something the party has not yet seen but is about to.",
      "An old mentor sends a final letter asking for one specific favor.",
      "A regional official requisitions the party's services under threat of arrest.",
      "A wager made over drinks turns into a binding contract by morning.",
      "The party is invited to a wedding that becomes something else entirely.",
      "A package the party agreed to deliver turns out to contain something else.",
      "A neighbor knocks at first light with news that someone is missing.",
      "The party finds their wanted poster nailed up in a town they have never visited.",
      "A traveling show the party attended hides an urgent request among its acts.",
      "An apologetic priest arrives at the party's lodgings to ask forgiveness for an oracle's request.",
      "The party witnesses an attempted kidnapping and the would-be victim won't explain why.",
      "A fugitive begs sanctuary, and pursuit is already at the door.",
      "A guild master the party has never met requests a private interview.",
      "The party hears a name spoken in a tongue they shouldn't understand — and they do.",
      "A festival contest is rigged in the party's favor by an unknown benefactor.",
      "A childhood promise comes due in the form of a stranger at the door.",
      "A drunk in a tavern recognizes the party from a future they haven't lived yet.",
      "The party's last job was paid in something that turns out to be a key.",
      "A stranger pays the party's tavern tab and leaves an address.",
      "Footprints lead from the party's camp to somewhere none of them remember going.",
      "The party recovers from an illness to find the world has moved on without them.",
      "A merchant's apprentice approaches with an offer the merchant doesn't know they're making.",
      "An entire town denies that yesterday's events happened, and the party remembers.",
      "A passing minstrel sings a song about the party that contains specific predictions.",
      "The party is named in a will read aloud in a town where they have no relatives.",
      "A familiar arrives without its master and refuses to leave the party's side.",
      "A request for sanctuary turns out to come from someone the party once condemned.",
      "A traveling judge stops the party on the road and asks them to witness a trial.",
      "An anonymous gift of equipment arrives with a note specifying when it must be used.",
      "The party is approached during a holy festival by someone offering pilgrim work.",
      "A nightmare shared by the party turns out to belong to a stranger sleeping nearby.",
      "An old comrade's child appears, alone, with their parent's weapon and no parent.",
      "The party finds a journal in their belongings that none of them remembers acquiring.",
      "A stranger duels one of the party at sunrise and explains why between bouts.",
      "A burning building gives up a survivor who only the party hears speak.",
      "A scholar publishes a paper that names one of the party in a footnote.",
      "The party is hired by someone obviously lying, and the lies themselves point somewhere.",
      "A delivery arrives bearing the seal of someone the party believed dead.",
      "An inheritance left to someone else passes to the party when the heir dies en route.",
      "A song the party half-remembers turns out to be a set of instructions.",
      "A coin in the party's pocket they did not earn bears a sigil they recognize.",
      "The party's mounts will not enter a particular stable, and the stable hand knows why.",
      "A constable arrives to ask the party about events they were nowhere near.",
      "An hourglass arrives in the post, half-run, with no other note.",
      "A magical message-spell delivers a single sentence and leaves no sender to question.",
      "The party witnesses a duel of honor where both parties die — and a sealed letter remains.",
      "A herald announces a tournament whose qualifying entry happens to be the adventure itself.",
      "A widow approaches the party with her late husband's unfinished work.",
      "An apprentice arrives alone with their master's research and instructions to find help.",
      "A roadside shrine the party leaves an offering at lights up in answer.",
      "A door in the party's lodgings opens onto a place that wasn't there yesterday.",
      "A child the party once helped is now grown, and has come to repay the favor.",
      "A ship's captain refuses to sail without the party aboard, for reasons they won't share.",
      "A market fortune-cake breaks open with a written line meant for the party alone.",
      "A creature the party has never seen approaches at dusk and waits to be followed.",
      "A sudden eclipse plunges the town into darkness, and a strange figure appears in the town square.",
      "The party is hired to deliver a simple letter, but the recipient is found murdered.",
      "A renowned local hero goes missing, and the party is the only group available to search.",
      "A magical anomaly causes everyone in town to swap bodies for a day, revealing hidden secrets.",
      "The party stumbles upon a hidden underground fighting ring and is forced to participate.",
      "A mysterious fog rolls in, trapping the party in a small village with a dark secret.",
      "A seemingly ordinary object the party bought at a market turns out to be a powerful artifact.",
      "The party is invited to a grand feast, but the food is poisoned.",
      "A talking sword demands the party take it to its rightful owner.",
      "The party wakes up in a dungeon with no memory of how they got there.",
      "A local festival is interrupted by an attack from strange, unidentified creatures.",
      "The party is hired to escort a wealthy merchant, but the merchant is secretly a spy.",
      "A series of cryptic messages are left for the party, leading them on a scavenger hunt.",
      "The party is accused of a crime they didn't commit and must prove their innocence.",
      "A magical portal opens in the middle of town, spewing out dangerous beasts.",
      "The party is hired to find a lost heir, but the heir doesn't want to be found.",
      "A strange illness sweeps through the town, and the party must find the cure.",
      "The party is hired to protect a valuable artifact, but they are betrayed by their employer.",
      "A mysterious stranger offers the party a dangerous but lucrative job.",
      "The party discovers a hidden map leading to a forgotten treasure.",
      "A local cult begins kidnapping townspeople, and the party must stop them.",
      "The party is hired to investigate a haunted house, but the ghosts are real.",
      "A powerful mage asks the party for help, but their motives are unclear.",
      "The party is drawn into a conflict between two rival factions.",
      "A strange, glowing rock falls from the sky, and everyone wants it.",
      "The party is hired to retrieve a stolen item, but the thief is a sympathetic character.",
      "A local ruler is assassinated, and the party must find the killer.",
      "The party discovers a plot to overthrow the government.",
      "A powerful artifact is stolen from a museum, and the party must get it back.",
      "The party is hired to explore a dangerous ruin, but they are not the only ones looking for it.",
      "A strange creature begins attacking livestock, and the party must hunt it down.",
      "The party is hired to deliver a message to a distant town, but the journey is perilous.",
      "A local tavern is destroyed, and the party must find out who did it.",
      "The party is hired to protect a caravan, but the caravan is carrying contraband.",
      "A mysterious stranger arrives in town, and strange things start happening.",
      "The party discovers a hidden cult worshipping an ancient evil.",
      "A powerful demon is summoned, and the party must banish it.",
      "The party is hired to find a missing person, but the person was taken by a monster.",
      "A local festival is disrupted by a magical prank gone wrong.",
      "The party is hired to investigate a series of robberies, but the thief is a ghost.",
      "A strange, magical fog covers the town, and people start disappearing.",
      "The party discovers a hidden underground city.",
      "A powerful dragon demands tribute from a nearby town.",
      "The party is hired to retrieve a lost artifact from a dangerous swamp.",
      "A local lord begins acting strangely, and the party must find out why.",
      "The party discovers a plot to poison the town's water supply.",
      "A powerful mage is murdered, and the party must find the killer.",
      "The party is hired to escort a group of pilgrims to a holy site.",
      "A strange, magical creature begins granting wishes, but with terrible consequences.",
      "The party discovers a hidden vault filled with ancient weapons.",
      "A powerful elemental attacks a nearby town.",
      "The party is hired to investigate a series of strange disappearances in a nearby forest.",
      "A local tavern owner goes missing, and the party must find them.",
      "The party discovers a hidden cult that is planning to summon an ancient evil.",
      "A powerful demon offers the party a dangerous deal.",
      "The party is hired to retrieve a stolen spellbook from a dangerous mage.",
      "A local lord is overthrown, and the party must help restore order.",
      "The party discovers a plot to start a war between two rival nations.",
      "A powerful artifact is discovered, and everyone wants it.",
      "The party is hired to explore a dangerous new continent.",
      "A strange, magical creature begins attacking travelers on the road.",
      "The party discovers a hidden underground network of smugglers.",
      "A powerful dragon attacks a nearby city.",
      "The party is hired to retrieve a lost artifact from a dangerous mountain peak.",
      "A local lord is assassinated, and the party must find the killer.",
      "The party discovers a plot to destroy the town.",
      "A powerful mage begins acting strangely, and the party must find out why.",
      "The party is hired to escort a group of refugees to a safe haven.",
      "A strange, magical fog covers the land, and monsters start appearing.",
      "The party discovers a hidden city floating in the sky.",
      "A powerful elemental lord demands tribute from a nearby kingdom.",
      "The party is hired to investigate a series of strange occurrences in a nearby mine.",
      "A local tavern owner is murdered, and the party must find the killer.",
      "The party discovers a hidden cult that is planning to overthrow the government.",
      "A powerful demon Lord is summoned, and the party must banish it.",
      "The party is hired to retrieve a stolen artifact from a dangerous cult.",
      "A local lord is overthrown, and the party must help the new ruler establish order.",
      "The party discovers a plot to destroy the world.",
      "A powerful artifact is discovered, and it is driving everyone mad.",
      "The party is hired to explore a dangerous, ancient ruin.",
      "A strange, magical creature begins granting wishes, but the wishes always go wrong.",
      "The party discovers a hidden network of spies.",
      "A powerful dragon is awakened from its slumber, and it is very angry.",
      "The party is hired to retrieve a lost artifact from a dangerous, ancient temple.",
      "A local lord is assassinated, and the party must find the killer.",
      "The party discovers a plot to assassinate the king.",
      "A powerful mage begins to lose their mind, and their magic becomes dangerous.",
      "The party is hired to escort a group of diplomats to a peace conference.",
      "A strange, magical fog covers the land, and the dead begin to rise.",
      "The party discovers a hidden city deep underwater.",
      "A powerful elemental lord attacks a nearby kingdom.",
      "The party is hired to investigate a series of strange occurrences in a nearby castle.",
      "A local tavern owner is kidnapped, and the party must rescue them.",
      "The party discovers a hidden cult that is planning to summon an ancient evil.",
      "A powerful demon Lord is summoned, and the party must destroy it.",
      "The party is hired to retrieve a stolen artifact from a dangerous, ancient dragon.",
      "A local lord is overthrown, and the party must help a rebel group take control.",
      "The party discovers a plot to destroy the universe.",
    ],
  },

  climaxes: {
    id: 'climaxes',
    title: 'Adventure Climaxes',
    attribution: 'Original',
    entries: [
      "A direct confrontation with the main villain and their inner circle.",
      "A pursuit through hostile terrain that ends at the villain's last refuge.",
      "A cataclysm the villain triggered — the party must escape it or stop it.",
      "A race against time to reach the villain before they complete their goal.",
      "Multiple simultaneous rituals or events that must be disrupted at once.",
      "A betrayal by an ally just as the goal seems within reach.",
      "A portal opening to somewhere worse, requiring the party to close it under attack.",
      "Environmental hazards turning the climax site itself into the enemy.",
      "The villain's lair collapsing or transforming around the final fight.",
      "A greater power arriving to eliminate the villain and pose a new threat.",
      "A choice between defeating the villain and saving someone the party loves.",
      "A revelation that the villain cannot be defeated until a hidden weakness is found.",
      "A duel of single combat that the villain demands and the party cannot refuse.",
      "A trial held by the villain themselves, with the party's deeds as evidence against them.",
      "A siege the party must hold long enough for reinforcements to arrive.",
      "A siege the party must break by reaching the commander before the walls fall.",
      "A negotiation with the villain that goes wrong at the exact moment it seemed to work.",
      "A naval battle that ends with the two ships grappled and the decks running together.",
      "A chase across rooftops, bridges, or treetops to keep the villain from escaping.",
      "A final confrontation where the villain reveals they have always been someone the party knows.",
      "A magical contest of wills — not weapons — that decides who walks away.",
      "An ambush sprung against the villain at the moment of their triumph.",
      "An assault on a moving target — a war-train, a sky-ship, a fleeing carriage.",
      "A confrontation interrupted by a rival faction storming in with their own agenda.",
      "The villain attempts apotheosis and the party must reach the altar before the ritual completes.",
      "A coronation, wedding, or treaty-signing the party must disrupt while in disguise.",
      "A descent into a deathtrap the party must survive alongside a willing villain.",
      "A confrontation underwater, underground, or aloft where the location itself fights back.",
      "A confrontation in a place the villain has never lost in — and the party must change that.",
      "A confrontation where the villain has hostages and reveals them one by one.",
      "A confrontation that begins with the villain already wounded by someone else.",
      "A confrontation where the villain's minions surrender as soon as their master falls.",
      "A confrontation where the villain's minions become more dangerous when their master falls.",
      "A confrontation interrupted by the arrival of the villain's patron, who is worse.",
      "A confrontation where the party's earlier choices appear to fight on the villain's side.",
      "A confrontation where the villain reveals the party were unknowing servants all along.",
      "A confrontation where the villain offers each party member a personalized last temptation.",
      "A final spell, jutting toward completion, that the party must interrupt by any means.",
      "A confrontation atop a structure that begins to fall the moment combat begins.",
      "A confrontation across a chasm with combat happening on a narrow bridge.",
      "A confrontation in a cathedral, court, or arena packed with witnesses.",
      "A confrontation in total darkness where only the villain can see.",
      "A confrontation in deep snow, deep water, or deep ash where movement is the real enemy.",
      "A confrontation across multiple chambers as the villain retreats deeper inward.",
      "A confrontation in a place sacred to one side that magically punishes the other.",
      "A confrontation at the moment of a celestial event the villain has been timing toward.",
      "A confrontation interrupted by the villain's intended victim arriving to save them.",
      "A confrontation in which the villain dies easily and the real fight begins after.",
      "A confrontation that ends with the villain escaping, and the party choosing whether to pursue.",
      "A confrontation in which the party must defeat the villain without killing them.",
      "A confrontation in which the party must kill the villain in a very specific way.",
      "A confrontation in which the villain has prepared a corpse-trap for if they die.",
      "A confrontation in which a friend already turned to the villain's side bars the door.",
      "A confrontation on a battlefield where allied and enemy soldiers fight around them.",
      "A confrontation where the villain has split themselves into pieces that must each be destroyed.",
      "A confrontation in which the villain pleads for mercy and the party must judge sincerity.",
      "A confrontation in which the party must hold a single position while a ritual completes.",
      "A confrontation that begins with a parley and ends when an outside force breaks it.",
      "A confrontation interrupted by an earthquake, eruption, or storm timed to the violence.",
      "A confrontation in which destroying the villain releases what the villain was containing.",
      "A confrontation in which the villain's power feeds on harm done to them.",
      "A confrontation in which the villain switches bodies with someone the party trusts.",
      "A confrontation in which only one weapon present can actually hurt the villain.",
      "A confrontation in which the villain calls in a debt the party owes them.",
      "A confrontation in which the party is offered a chance to take the villain's place.",
      "A confrontation in which the villain reveals they are dying anyway and only want company.",
      "A confrontation in which the villain has the upper hand until a forgotten ally arrives.",
      "A confrontation in which one of the party must be the one to strike the killing blow.",
      "A confrontation in which a third party arrives demanding the villain be taken alive.",
      "A confrontation in which the villain begins by destroying something irreplaceable.",
      "A confrontation in which the villain is already gone and a final trap remains.",
      "A confrontation in which the villain begs to be killed before they finish what they started.",
      "A confrontation that ends with a chase into a portal the party must follow through.",
      "A confrontation in which the location is a labyrinth and the villain knows it.",
      "A confrontation in which the villain wears the face and voice of a beloved ally.",
      "A confrontation where the party must rescue captives before finishing the villain.",
      "A confrontation where the villain has rigged a deadman's switch tied to their heartbeat.",
      "A confrontation where the villain's death triggers their resurrection somewhere else.",
      "A confrontation that resolves through a riddle or rite, not violence.",
      "A confrontation where the villain summons their original wrong-doer for the party to judge.",
      "A confrontation where a sealed door must be held shut until dawn comes.",
      "A confrontation in which the floor is rising water and only one platform is safe.",
      "A confrontation in which the villain's followers must be persuaded to stand down.",
      "A confrontation interrupted by the timely arrival of the law, on the wrong side.",
      "A confrontation interrupted by the timely arrival of the law, on the right side.",
      "A confrontation in which the villain's defenses include the party's own captured allies.",
      "A confrontation that ends in mutual exhaustion and a final negotiated peace.",
      "A confrontation in which the villain's death must be public to mean anything.",
      "A confrontation in which the villain's death must be secret to mean anything.",
      "A confrontation in which the villain reveals an heir who must be considered as well.",
      "A confrontation that climbs upward — tower, mountain, cliff — toward an inevitable summit.",
      "A confrontation across a frozen lake where the ice itself is the second enemy.",
      "A confrontation in which the party must keep something alive while they fight.",
      "A confrontation in which the villain is bound, and the question is whether to free or end them.",
      "A confrontation where the party must defeat the villain's idea, not just their body.",
      "A confrontation in which silence is required and any sound brings something worse.",
      "A confrontation across a burning building with civilians still inside.",
      "A confrontation that ends only when the villain's true name is spoken aloud.",
      "A confrontation that ends with the villain stepping aside to reveal the real enemy.",
      "A confrontation where the party's victory condition is making the villain walk away.",
      "A confrontation that takes place inside the mind of a sleeping god.",
      "A confrontation where the villain is using the party's own fears against them.",
      "A confrontation that must be won without using any magic.",
      "A confrontation where the villain is protected by an impenetrable shield that must be disabled from the inside.",
      "A confrontation that takes place on a series of floating platforms over a bottomless pit.",
      "A confrontation where the villain is slowly turning the party into stone.",
      "A confrontation that takes place in a room where gravity is constantly shifting.",
      "A confrontation where the villain is drawing power from the life force of the party.",
      "A confrontation that must be won by solving a complex puzzle while under attack.",
      "A confrontation where the villain is using hostages as human shields.",
      "A confrontation that takes place in a room filled with deadly traps that are triggered by sound.",
      "A confrontation where the villain is constantly teleporting around the room.",
      "A confrontation that must be won by convincing the villain's allies to turn against them.",
      "A confrontation where the villain is using an illusion to make themselves look like a party member.",
      "A confrontation that takes place in a room where the walls are slowly closing in.",
      "A confrontation where the villain is using a powerful artifact that the party must destroy.",
      "A confrontation that must be won by outsmarting the villain, not outfighting them.",
      "A confrontation where the villain is using a mind-control device to turn the party against each other.",
      "A confrontation that takes place on the back of a massive, flying creature.",
      "A confrontation where the villain is slowly draining the party's memories.",
      "A confrontation that must be won by finding the villain's hidden weakness.",
      "A confrontation where the villain is using a powerful spell that will destroy the world if not stopped.",
      "A confrontation that takes place in a room where time is moving backwards.",
      "A confrontation where the villain is using a magical mirror to create duplicates of themselves.",
      "A confrontation that must be won by working together in perfect synchronization.",
      "A confrontation where the villain is using a powerful poison that the party must find the antidote for.",
      "A confrontation that takes place in a room where the temperature is rapidly dropping.",
      "A confrontation where the villain is using a powerful illusion to make the party doubt reality.",
      "A confrontation that must be won by sacrificing something important.",
      "A confrontation where the villain is using a powerful artifact that the party must steal.",
      "A confrontation that takes place in a room filled with deadly gas.",
      "A confrontation where the villain is using a powerful spell that will turn the party into monsters.",
      "A confrontation that must be won by forgiving the villain.",
      "A confrontation where the villain is using a powerful artifact that the party must activate.",
      "A confrontation that takes place in a room where the floor is covered in lava.",
      "A confrontation where the villain is using a powerful spell that will banish the party to another dimension.",
      "A confrontation that must be won by understanding the villain's motives.",
      "A confrontation where the villain is using a powerful artifact that the party must destroy.",
      "A confrontation that takes place in a room where the walls are covered in spikes.",
      "A confrontation where the villain is using a powerful spell that will erase the party from existence.",
      "A confrontation that must be won by finding a peaceful resolution.",
      "A confrontation where the villain is using a powerful artifact that the party must use against them.",
      "A confrontation that takes place in a room where the ceiling is slowly lowering.",
      "A confrontation where the villain is using a powerful spell that will turn the party to dust.",
      "A confrontation that must be won by proving the villain wrong.",
      "A confrontation where the villain is using a powerful artifact that the party must protect.",
      "A confrontation that takes place in a room where the air is slowly being sucked out.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their slaves.",
      "A confrontation that must be won by showing the villain compassion.",
      "A confrontation where the villain is using a powerful artifact that the party must hide.",
      "A confrontation that takes place in a room where the floor is covered in acid.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their worst nightmares.",
      "A confrontation that must be won by accepting the villain's flaws.",
      "A confrontation where the villain is using a powerful artifact that the party must return to its rightful owner.",
      "A confrontation that takes place in a room where the walls are covered in fire.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their greatest fears.",
      "A confrontation that must be won by embracing the villain's darkness.",
      "A confrontation where the villain is using a powerful artifact that the party must destroy, even if it means destroying themselves.",
      "A confrontation that takes place in a room where the floor is covered in ice.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their deepest regrets.",
      "A confrontation that must be won by acknowledging the villain's pain.",
      "A confrontation where the villain is using a powerful artifact that the party must use to heal the world.",
      "A confrontation that takes place in a room where the walls are covered in electricity.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their darkest desires.",
      "A confrontation that must be won by understanding the villain's anger.",
      "A confrontation where the villain is using a powerful artifact that the party must use to bring peace to the world.",
      "A confrontation that takes place in a room where the floor is covered in spikes.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their worst enemies.",
      "A confrontation that must be won by forgiving the villain's mistakes.",
      "A confrontation where the villain is using a powerful artifact that the party must use to restore balance to the world.",
      "A confrontation that takes place in a room where the walls are covered in poison.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their own worst enemies.",
      "A confrontation that must be won by finding common ground with the villain.",
      "A confrontation where the villain is using a powerful artifact that the party must use to create a new world.",
      "A confrontation that takes place in a room where the floor is covered in lava, and the walls are closing in.",
      "A confrontation where the villain is using a powerful spell that will turn the party into dust, and the wind is blowing away their remains.",
      "A confrontation that must be won by showing the villain that they are not alone.",
      "A confrontation where the villain is using a powerful artifact that the party must use to destroy the world, and they have to choose between their own lives and the fate of the universe.",
      "A confrontation that takes place in a room where the air is slowly being sucked out, and the only way out is through a tiny hole in the ceiling.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their slaves forever, and they have to fight to retain their free will.",
      "A confrontation that must be won by proving to the villain that love is stronger than hate.",
      "A confrontation where the villain is using a powerful artifact that the party must use to heal the world, but the process will kill them.",
      "A confrontation that takes place in a room where the floor is covered in acid, and the only way out is to swim through it.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their worst nightmares, and they have to face their deepest fears.",
      "A confrontation that must be won by accepting the villain's flaws and forgiving them for their mistakes.",
      "A confrontation where the villain is using a powerful artifact that the party must return to its rightful owner, but the owner is dead.",
      "A confrontation that takes place in a room where the walls are covered in fire, and the only way out is to walk through the flames.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their greatest fears, and they have to conquer them.",
      "A confrontation that must be won by embracing the villain's darkness and turning it into light.",
      "A confrontation where the villain is using a powerful artifact that the party must destroy, even if it means destroying themselves, and they have to make the ultimate sacrifice.",
      "A confrontation that takes place in a room where the floor is covered in ice, and the only way out is to slide across it.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their deepest regrets, and they have to learn to let go of the past.",
      "A confrontation that must be won by acknowledging the villain's pain and helping them heal.",
      "A confrontation where the villain is using a powerful artifact that the party must use to bring peace to the world, but it requires them to give up their own happiness.",
      "A confrontation that takes place in a room where the walls are covered in electricity, and the only way out is to run through it.",
      "A confrontation where the villain is using a powerful spell that will turn the party into their darkest desires, and they have to resist the temptation.",
      "A confrontation that must be won by understanding the villain's anger and helping them find peace.",
    ],
  },

  twists: {
    id: 'twists',
    title: 'Twists',
    attribution: 'Original',
    entries: [
      "Another party is pursuing the same goal — they're competition, not allies.",
      "The party becomes responsible for protecting a noncombatant who slows them down.",
      "The villain cannot be killed for reasons the party only learns mid-adventure.",
      "There is a hard time limit, and the party doesn't know how much remains.",
      "Some of the information the party started with is wrong or outdated.",
      "Completing the obvious goal fulfills a prophecy that the party didn't want fulfilled.",
      "The party has two goals and can only complete one — choosing is the adventure.",
      "Succeeding at the goal serves the villain's larger plan in a way the party doesn't see.",
      "The party must cooperate with a known enemy to achieve the goal.",
      "Magical compulsion is driving the party toward the goal — they would not choose this freely.",
      "The patron who hired the party has a private agenda incompatible with what they hired the party to do.",
      "The villain is someone the party has met and not yet suspected.",
      "The victim is not the victim — they arranged the entire situation themselves.",
      "The artifact the party is recovering is not what they were told it is.",
      "The party's mission was never the real mission — they were sent to be distractions.",
      "The villain is already dead, and someone else is finishing what they started.",
      "The villain is one of the party's family, mentors, or former allies.",
      "The villain and the patron are working together against the party.",
      "The party's success requires the destruction of something they came to protect.",
      "An apparent ally is reporting the party's every move to the villain.",
      "The location of the adventure is itself sentient and choosing sides.",
      "A previously dead character is alive — and on the wrong side.",
      "The artifact only works for someone willing to pay a price the party didn't know existed.",
      "The villain's victims are returning as something the party will have to fight.",
      "The party is being tested by a power that will judge them on their choices, not their success.",
      "The villain is fulfilling an oath the party's patron forced on them generations ago.",
      "Stopping the villain doesn't stop the harm — the harm has its own momentum now.",
      "The villain is the only person who can prevent something worse, and the party is killing them.",
      "What the party took from the villain's first crime scene mattered — and they didn't notice.",
      "The party's earlier mercy is the reason the current crisis is happening.",
      "The party's earlier cruelty is the reason the current crisis is happening.",
      "The party are not the first to attempt this — and the remains of the last attempt are nearby.",
      "The party is being followed by something that does not want the goal to succeed at all.",
      "The villain's plan, succeeded, would have prevented a different disaster the party will now face.",
      "One of the party is carrying something that will betray them at a critical moment.",
      "A creature the party left for dead has rejoined the fight on the villain's side.",
      "The reward the party was promised was paid before the adventure started, to someone else.",
      "A trusted spell, item, or technique is suppressed in the place the climax must happen.",
      "The villain has hostages the party hadn't known about until well into the chase.",
      "The villain has been hiding in the party's own ranks for longer than they realize.",
      "The patron's previous agents the party will meet are also their previous failures.",
      "The villain has been counting on a specific party member's specific flaw the whole time.",
      "An older, larger power is using the villain as cover for its own movements.",
      "The party will achieve the goal — that's already foretold — but at a cost not yet specified.",
      "A piece of information the party has been keeping secret has already been leaked.",
      "The geography of the area changes at night and the party didn't realize they were sleeping.",
      "The villain has been using illusions to make the party fight phantoms instead of allies.",
      "Two factions the party thought were opposed are actually a single faction.",
      "Two factions the party thought were a single force are actively at war with each other.",
      "The cure the party seeks is the disease the party brought with them.",
      "The villain's defeat releases something the villain was deliberately keeping bound.",
      "The party's quest is a recreation of a quest someone else completed badly long ago.",
      "Speaking the villain's name in the climax site is what summons them.",
      "Each step the party takes closer to the goal is one step the villain takes closer to theirs.",
      "Killing the villain transfers their burden to the killer.",
      "The party's chosen route is the route the villain prepared for them.",
      "A weapon the party trusts was forged for the villain originally.",
      "The villain's victims have organized themselves into a force the party did not expect.",
      "The villain is human, but what speaks through them is not.",
      "What the party assumed was a trap was an invitation, and they declined it.",
      "What the party assumed was an invitation was a trap, and they accepted it.",
      "The villain's followers are bound by an oath the party can unweave, but only at cost.",
      "An old, half-forgotten promise the party made now controls how this resolves.",
      "Someone the party rescued in act one is the reason they will fail in act three.",
      "The villain has been operating on instructions left by someone the party reveres.",
      "The location of the climax cannot be entered by anyone carrying a particular thing the party carries.",
      "Removing the villain leaves a vacancy that the party will be expected to fill.",
      "The villain offered terms the party rejected, and those terms get worse each time they're refused.",
      "The party have been speaking, throughout the adventure, with someone who isn't real.",
      "A piece of evidence at the climax shows the party did the crime they're investigating.",
      "The patron is dying, and what they wanted the party to do was their last act of spite.",
      "The villain's sole motivation is one the party would share if they were in the same situation.",
      "The villain has been watching the party more closely than the party has been watching them.",
      "An object the party has been carrying since the start is the villain's actual goal.",
      "A child the party has been protecting is the villain's chosen successor.",
      "Each party member has been receiving private offers from the villain none of them mentioned.",
      "Half the party is being used by one side and the other half by the other.",
      "The party were not chosen for their virtues — they were chosen for their weaknesses.",
      "The villain knows the party's true names and has been preparing accordingly.",
      "The villain has a child whose existence changes how the climax must end.",
      "The villain is bound to a place, and removing them from that place will free them entirely.",
      "The party's patron is the villain's victim in a way that recasts the whole conflict.",
      "What the party have been told is a curse is in fact a protection.",
      "What the party have been told is a protection is in fact a curse.",
      "A neutral party the party trusts has been quietly choosing the villain's side all along.",
      "The party's last great victory was the villain's first great defeat — and they remember.",
      "A wound one of the party took early in the adventure is the lever the villain will use.",
      "The villain has prepared a death-message that will turn the party against each other.",
      "There is a witness to everything the party has done — and they're about to testify.",
      "A god the party invoked early is now expecting the rest of the bargain.",
      "The villain's plan ends with the villain's own death — that is the plan.",
      "What the villain wants is the same as what the party wants, only the order differs.",
      "The patron and the villain swapped places at some point, and the party didn't notice.",
      "The land the party stands on is, itself, the villain's stolen body.",
      "The artifact the party is recovering is the villain in another form.",
      "Each victory the party wins makes the villain a little stronger.",
      "The villain's defeat condition was specified by a contract the party can amend before the climax.",
      "The voice of authority the party has been obeying is not the person they think it is.",
      "The party has been split, geographically, and one half is being lied to about the other.",
      "The villain is a future version of one of the party — and changing the present changes them.",
      "The entire adventure so far has been a shared dream or simulation, and the party is just waking up.",
      "The item the party was hired to protect is actually the item the villain needs to complete their plan.",
      "The 'villain' is actually trying to stop a much worse threat that the party is unknowingly helping.",
      "The party's patron has been dead the entire time, their orders issued by an imposter.",
      "The dungeon the party is exploring is not a ruin, but a massive, sleeping creature.",
      "The prophecy that guides the party was forged by their enemies.",
      "The party is not the first group to attempt this quest, and the others are now working for the villain.",
      "The magical artifact the party seeks is sentient and doesn't want to be found.",
      "The plague the party is trying to cure is actually a side effect of a spell keeping a greater evil sealed.",
      "The beloved ruler the party serves is actually a doppelganger who replaced the real ruler years ago.",
      "The rebellion the party is supporting is secretly funded by the oppressive empire to root out dissent.",
      "The 'monsters' attacking the village are actually cursed villagers trying to warn them.",
      "The legendary weapon the party needs requires the sacrifice of an innocent soul to wield.",
      "The party realizes they are the villains in someone else's story.",
      "The god the party worships is actually a powerful demon in disguise.",
      "The safe haven the party finally reaches is actually a trap set by the villain.",
      "The treasure the party found is cursed, and the curse slowly transfers to anyone who spends it.",
      "The party discovers that their memories have been altered, and they are actually agents of the villain.",
      "The world they are trying to save is already doomed, and their true quest is to find a new home.",
      "The villain's evil plan is actually the only way to save the universe from destruction.",
      "The party's trusted ally is a spy who has been feeding information to the villain.",
      "The magical barrier keeping the monsters out is also keeping the party trapped inside.",
      "The seemingly innocent child the party rescued is the reincarnated villain.",
      "The party discovers that the history they were taught is a lie, written by the victors.",
      "The powerful mage the party seeks for help is actually the villain's master.",
      "The artifact the party needs is broken into pieces, and one piece is held by a party member who doesn't know it.",
      "The party's actions have inadvertently awakened an ancient evil.",
      "The 'cure' the party found actually speeds up the disease.",
      "The mysterious stranger who has been helping the party is actually their future self.",
      "The party discovers that they are actually clones, and the originals are dead.",
      "The legendary hero the party seeks is actually a coward who took credit for someone else's deeds.",
      "The villain's fortress is an illusion, and the real threat is somewhere else entirely.",
      "The party realizes that the 'gods' they worship are actually highly advanced aliens.",
      "The magical item the party has been relying on is slowly draining their life force.",
      "The party's true enemy is not the villain, but the society that created them.",
      "The party discovers that they are trapped in a time loop, and they must find a way to break it.",
      "The 'monster' the party killed was the only thing holding back a massive invasion.",
      "The party's patron is actually the villain's parent.",
      "The party discovers that the villain is actually trying to save their own people, at the expense of others.",
      "The magical artifact the party needs is powered by human souls.",
      "The party's true quest is not to defeat the villain, but to redeem them.",
      "The party discovers that the 'demon' they summoned is actually a celestial being, and the 'celestials' are demons.",
      "The 'curse' the party is trying to break is actually a blessing in disguise.",
      "The party realizes that their entire journey has been a test, orchestrated by higher powers.",
      "The party discovers that the 'villain' is actually a manifestation of their own fears and desires.",
      "The magical barrier the party needs to cross can only be passed by someone who is pure of heart, and none of them are.",
      "The party's true enemy is not a person, but an abstract concept, like entropy or despair.",
      "The party discovers that they are actually characters in a story, and they must break the fourth wall to survive.",
      "The 'treasure' the party found is actually a map to an even greater treasure, but it's heavily guarded.",
      "The party realizes that the 'villain' is actually trying to protect them from a much worse fate.",
      "The magical artifact the party needs is actually a living creature, and using it will kill it.",
      "The party's true quest is not to save the world, but to save a single person.",
      "The party discovers that the 'prophecy' is actually a self-fulfilling loop, and they are the ones who started it.",
      "The party realizes that the 'villain' is actually a necessary evil, maintaining balance in the universe.",
      "The magical barrier the party needs to cross can only be passed by someone who is willing to sacrifice everything.",
      "The party's true enemy is not a monster, but the consequences of their own actions.",
      "The party discovers that they are actually the descendants of the villain.",
      "The 'treasure' the party found is actually a powerful weapon, and it's slowly driving them mad.",
      "The party realizes that the 'villain' is actually a tragic figure, driven to evil by circumstances beyond their control.",
      "The magical artifact the party needs is actually a key, and they must find the lock it opens.",
      "The party's true quest is not to defeat the villain, but to learn to live with them.",
      "The party discovers that the 'prophecy' is actually a warning, and they must try to prevent it from coming true.",
      "The party realizes that the 'villain' is actually a reflection of themselves, a dark mirror of what they could become.",
      "The magical barrier the party needs to cross can only be passed by someone who has truly let go of their past.",
      "The party's true enemy is not a physical threat, but a creeping sense of apathy and despair.",
      "The party discovers that they are actually the villains of their own story.",
      "The 'treasure' the party found is actually a burden, and they must carry it to the end of the world to destroy it.",
      "The party realizes that the 'villain' is actually a necessary part of the world's ecosystem, and destroying them would cause chaos.",
      "The magical artifact the party needs is actually a piece of a larger whole, and they must assemble all the pieces to unlock its true power.",
      "The party's true quest is not to save the world, but to learn to accept its flaws.",
      "The party discovers that the 'prophecy' is actually a joke, played by the gods on mortals.",
      "The party realizes that the 'villain' is actually a misunderstood hero, trying to do the right thing the wrong way.",
      "The magical barrier the party needs to cross can only be passed by someone who is truly free.",
      "The party's true enemy is not a tangible entity, but the idea of evil itself.",
      "The party discovers that they are actually immortal, and they must learn to live with the consequences of their actions forever.",
      "The 'treasure' the party found is actually a curse, and they must pass it on to someone else to be rid of it.",
      "The party realizes that the 'villain' is actually a necessary evil, a force of destruction that clears the way for new creation.",
      "The magical artifact the party needs is actually a prison, holding a being of unimaginable power.",
      "The party's true quest is not to defeat the villain, but to understand them.",
      "The party discovers that the 'prophecy' is actually a riddle, and they must solve it to unlock its true meaning.",
      "The party realizes that the 'villain' is actually a reflection of society's flaws, a manifestation of its deepest fears.",
      "The magical barrier the party needs to cross can only be passed by someone who is truly selfless.",
      "The party's true enemy is not a person, but the inexorable march of time.",
      "The party discovers that they are actually the gods of their own world.",
      "The 'treasure' the party found is actually a memory, a forgotten truth that changes everything.",
      "The party realizes that the 'villain' is actually a necessary part of the human experience, a reminder of our own capacity for darkness.",
      "The magical artifact the party needs is actually a mirror, revealing their true selves.",
      "The party's true quest is not to save the world, but to change it.",
      "The party discovers that the 'prophecy' is actually a choice, and they must decide their own fate.",
      "The party realizes that the 'villain' is actually a necessary evil, a force that pushes us to be better.",
      "The magical barrier the party needs to cross can only be passed by someone who is truly alive.",
      "The party's true enemy is not a force of nature, but the limitations of their own minds.",
      "The party discovers that they are actually the only real people in a world of illusions.",
      "The 'treasure' the party found is actually a feeling, a moment of pure joy that makes everything worth it.",
      "The party realizes that the 'villain' is actually a necessary part of the universe, a counterpart to the light.",
      "The magical artifact the party needs is actually a feeling, a deep connection to the world around them.",
      "The party's true quest is not to defeat the villain, but to find peace.",
    ],
  },

};
