// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const sensoryTables: Record<string, InspireTable> = {
  atmosphericSights: {
    id: 'atmosphericSights',
    title: 'Atmospheric Sights (Stalling)',
    attribution: 'Original',
    entries: [
      "A sudden, swirling gust of wind kicks up dust and leaves, obscuring vision for just a moment.",
      "The sunlight catches a pane of glass or a piece of metal, sending a blinding reflection across the area.",
      "A thick bank of fog rolls in unnaturally fast, softening the edges of the buildings.",
      "A flock of birds suddenly takes flight from a nearby roof, their wings beating loudly in the quiet.",
      "The shadows lengthen dramatically as the sun dips behind a large cloud.",
      "A lone, ragged banner snaps violently in the wind on a distant tower.",
      "A strange, iridescent oil slick catches the light in a nearby puddle.",
      "Dust motes dance lazily in a single, distinct shaft of sunlight.",
      "A piece of debris tumbles across the path, scraping loudly against the stone.",
      "The silhouettes of distant figures can be seen moving slowly along the horizon.",
      "A brief, intense shower of rain falls only on a small patch of ground nearby.",
      "A localized patch of frost clings to the stones, despite the temperature.",
      "A sudden swarm of gnats or midges forms a shifting cloud in the air.",
      "The ambient light shifts to a strange, bruised purple hue for a few seconds.",
      "A large, ominous bird circles lazily high above, casting a fleeting shadow.",
      "A distant flash of heat lightning illuminates the sky without a sound.",
      "The air shimmers with heat distortion, making the distance look wavy and unreal.",
      "A strange, glowing spore drifts down from the canopy above.",
      "The colors of the surrounding area seem to wash out, leaving everything muted and grey.",
      "A sudden flurry of snow falls from a cloudless sky, melting instantly.",
      "A double rainbow forms, even though it hasn't rained.",
      "The clouds overhead suddenly form the shape of a massive, menacing face.",
      "A strange, glowing aurora appears in the daytime sky.",
      "A localized eclipse darkens only a small area of the town.",
      "A flock of birds flies backward for a few seconds.",
      "A strange, green mist rolls down the street, clinging to the cobblestones.",
      "The stars become visible in the sky, even though it's the middle of the day.",
      "A sudden, inexplicable shadow falls over the party, though there is nothing to cast it.",
      "A strange, shimmering mirage appears, showing a city that isn't there.",
      "The moon appears unusually large and blood-red for a brief moment.",
      "A strange, glowing dust settles over the area, making everything sparkle.",
      "The sun seems to flicker, like a candle caught in a draft.",
      "A strange, localized fog banks only hides a single building.",
      "A sudden, intense beam of sunlight pierces through thick clouds, illuminating a specific spot.",
      "A strange, swirling vortex of leaves forms in the street, then collapses.",
      "The sky momentarily turns a deep, unnatural shade of green.",
      "A strange, glowing phenomenon appears in a nearby window, then vanishes.",
      "A sudden, inexplicable shower of small, harmless pebbles falls from the sky.",
      "The clouds overhead move unnaturally fast, as if driven by a magical wind.",
      "A strange, glowing mist rises from a nearby well.",
      "A sudden, inexplicable flash of lightning strikes a nearby tree without a sound.",
      "The shadows seem to detach from their objects for a split second.",
      "A strange, shimmering energy field briefly surrounds a nearby building.",
      "A sudden, localized downpour of brightly colored flower petals.",
      "The moon seems to multiply, creating several smaller moons in the sky.",
      "A strange, glowing aura surrounds a nearby statue.",
      "A sudden, inexplicable shift in the angle of the sun, changing the time of day for a moment.",
      "The sky momentarily turns perfectly black, like a starless night.",
      "A strange, swirling pattern appears in a nearby puddle.",
      "A sudden, inexplicable shower of silver coins falls from the sky.",
      "The clouds overhead form a perfect circle.",
      "A strange, glowing symbol appears in the sky, then fades away.",
      "A sudden, localized fog bank that smells strongly of ozone.",
      "The stars seem to rearrange themselves into a new constellation.",
      "A strange, shimmering mirage appears, showing a battle from the past.",
      "A sudden, inexplicable flash of blue light illuminates the area.",
      "The sun seems to change color, turning a pale, sickly yellow.",
      "A strange, glowing mist seeps from the cracks in the pavement.",
      "A sudden, inexplicable shower of tiny, harmless sparks falls from the sky.",
      "The sky momentarily turns a bright, unnatural shade of pink.",
      "A strange, glowing phenomenon appears on the surface of a nearby river.",
      "A sudden, localized downpour of glowing, blue rain.",
      "The moon seems to shatter into a million pieces, then re-form.",
      "A strange, glowing aura surrounds a nearby tree.",
      "A sudden, inexplicable shift in the wind, carrying the smell of the ocean.",
      "The shadows seem to dance and twist of their own accord.",
      "A strange, shimmering energy field briefly surrounds the party.",
      "A sudden, localized shower of perfectly formed snowflakes.",
      "The sky momentarily turns a deep, bloody red.",
      "A strange, swirling pattern appears in the dust on the road.",
      "A sudden, inexplicable shower of small, harmless insects falls from the sky.",
      "The clouds overhead form the shape of a massive dragon.",
      "A strange, glowing symbol appears on a nearby wall, then fades away.",
      "A sudden, localized fog bank that smells strongly of sulfur.",
      "The stars seem to fall from the sky, like a meteor shower.",
      "A strange, shimmering mirage appears, showing a lush oasis.",
      "A sudden, inexplicable flash of green light illuminates the area.",
      "The sun seems to grow larger, filling the sky with blinding light.",
      "A strange, glowing mist rises from a nearby graveyard.",
      "A sudden, inexplicable shower of tiny, harmless frogs falls from the sky.",
      "The sky momentarily turns a pale, ghostly white.",
      "A strange, glowing phenomenon appears in the branches of a nearby tree.",
      "A sudden, localized downpour of warm, red rain.",
      "The moon seems to grow closer, filling the sky.",
      "A strange, glowing aura surrounds a nearby fountain.",
      "A sudden, inexplicable shift in the wind, carrying the smell of burning wood.",
      "The shadows seem to stretch and lengthen, pointing toward a specific building.",
      "A strange, shimmering energy field briefly surrounds a nearby monument.",
      "A sudden, localized shower of perfectly formed ash.",
      "The sky momentarily turns a deep, oceanic blue.",
      "A strange, swirling pattern appears in the smoke from a nearby chimney.",
      "A sudden, inexplicable shower of small, harmless fish falls from the sky.",
      "The clouds overhead form a perfect square.",
      "A strange, glowing symbol appears on the ground, then fades away.",
      "A sudden, localized fog bank that smells strongly of perfume.",
      "The stars seem to spell out a word in a forgotten language.",
      "A strange, shimmering mirage appears, showing a frozen wasteland.",
      "A sudden, inexplicable flash of yellow light illuminates the area.",
      "The sun seems to disappear, replaced by a massive, glowing eye.",
    ],
  },

  ambientSounds: {
    id: 'ambientSounds',
    title: 'Ambient Sounds (Stalling)',
    attribution: 'Original',
    entries: [
      "A sudden, sharp crack echoes from somewhere out of sight, like a breaking branch or a falling rock.",
      "The distant, rhythmic sound of a hammer striking an anvil rings out in a steady cadence.",
      "A low, mournful howl drifts on the wind, too far away to identify the source.",
      "The sudden, loud clatter of something metal falling to the stone floor nearby.",
      "A strange, resonant humming sound seems to come from the very ground beneath your feet.",
      "The wind whistles sharply through a narrow gap, sounding almost like a voice.",
      "A sudden burst of raucous laughter erupts from a nearby building, then cuts off abruptly.",
      "The unmistakable sound of footsteps dragging slowly on gravel, just out of sight.",
      "A heavy door slams shut with a boom that shakes the dust from the ceiling.",
      "The sudden, frantic scrabbling of claws on stone as something small and fast scurries away.",
      "A low, rumbling groan sounds from the architecture, as if the building is settling.",
      "The distant, chaotic sounds of a bustling market, blending into an indistinct roar.",
      "A sudden, sharp whistle cuts through the air, followed by complete silence.",
      "The sound of water dripping rhythmically into a hollow pool.",
      "A strange, metallic screeching noise, like something heavy being dragged across metal.",
      "The sound of a bell tolling slowly, though there is no church or tower nearby.",
      "A sudden, loud splash from a nearby body of water, as if something large just jumped in.",
      "The sound of hurried, panicked breathing coming from a dark alleyway.",
      "A low, guttural growl that seems to echo from multiple directions at once.",
      "The sudden, loud shattering of glass from an upper window.",
      "A repetitive, rhythmic tapping sound, like a branch against a window, but there are no trees.",
      "The distinct sound of a sword being drawn from a scabbard, just around the corner.",
      "A chorus of crickets that suddenly stops in unison.",
      "The low, continuous buzz of a massive swarm of insects, moving slowly.",
      "A high-pitched, almost inaudible keening that sets your teeth on edge.",
      "The sound of a heavy coin purse hitting the ground.",
      "A rhythmic sloshing sound, like someone wading through deep water.",
      "The sharp, undeniable sound of a bone breaking.",
      "A child's voice whispering a secret, though no child is visible.",
      "The clatter of hooves on cobblestone, but the tempo is wrong for a horse.",
      "A deep, resonant gong sounding a single time.",
      "The sound of tearing fabric, slow and deliberate.",
      "A wet, squelching sound, like someone walking in mud.",
      "The unmistakable sound of a bowstring being drawn taut.",
      "A sudden, chaotic cacophony of birds taking flight.",
      "The sound of a large book slamming shut.",
      "A low, rhythmic chanting that seems to come from underground.",
      "The sharp hiss of something hot being quenched in water.",
      "A sudden, terrifyingly human-sounding scream from a feral animal.",
      "The sound of a lock clicking into place, loudly.",
      "A chaotic clanging of pots and pans, as if a kitchen is being destroyed.",
      "The gentle, melodic sound of wind chimes in a completely still air.",
      "A sudden, loud sneeze from someone hiding nearby.",
      "The sound of heavy, labored breathing right behind a party member.",
      "A rhythmic clicking sound, like a clock ticking, but much louder.",
      "The unmistakable sound of a match being struck.",
      "A sudden, chaotic sound of a large group of people arguing.",
      "The sound of a single, heavy drop of water hitting a metal surface repeatedly.",
      "A low, guttural chanting that seems to be in an unknown language.",
      "The sharp, rhythmic sound of a pickaxe hitting stone.",
      "A sudden, loud burst of static, as if from a magical communication device.",
      "The sound of a large creature moving through dense undergrowth.",
      "A rhythmic thumping sound, like a heartbeat, but coming from the walls.",
      "The unmistakable sound of someone weeping softly.",
      "A sudden, chaotic sound of a marketplace in full swing, despite the location.",
      "The sound of a single, mournful note played on a flute.",
      "A low, rumbling sound that shakes the ground, like an approaching stampede.",
      "The sharp, rhythmic sound of a blade being sharpened on a whetstone.",
      "A sudden, loud crack of thunder, despite the clear sky.",
      "The sound of a large pair of wings flapping heavily.",
      "A rhythmic swishing sound, like someone practicing with a sword.",
      "The unmistakable sound of a coin spinning on a hard surface.",
      "A sudden, chaotic sound of a tavern brawl.",
      "The sound of a single, heavy footstep, then silence.",
      "A low, guttural snoring sound.",
      "The sharp, rhythmic sound of a woodpecker, but much louder.",
      "A sudden, loud burst of magical energy, like a localized explosion.",
      "The sound of a large creature dragging something heavy.",
      "A rhythmic dripping sound, like a leaky faucet.",
      "The unmistakable sound of someone whispering your name.",
      "A sudden, chaotic sound of a flock of crows cawing.",
      "The sound of a single, beautiful note sung by a soprano.",
      "A low, rumbling sound that seems to come from the sky.",
      "The sharp, rhythmic sound of a hammer hitting a nail.",
      "A sudden, loud crash, like a building collapsing.",
      "The sound of a large creature eating something crunchy.",
      "A rhythmic ticking sound, like a time bomb.",
      "The unmistakable sound of someone laughing maniacally.",
      "A sudden, chaotic sound of a stampede of animals.",
      "The sound of a single, heavy breath.",
      "A low, guttural growling sound that slowly fades away.",
      "The sharp, rhythmic sound of a saw cutting through wood.",
      "A sudden, loud burst of flame, like a dragon's breath.",
      "The sound of a large creature digging.",
      "A rhythmic tapping sound, like a telegraph.",
      "The unmistakable sound of someone screaming for help.",
      "A sudden, chaotic sound of a large group of people cheering.",
      "The sound of a single, beautiful chord played on a lute.",
      "A low, rumbling sound that seems to come from the water.",
      "The sharp, rhythmic sound of a bell ringing.",
      "A sudden, loud crash of cymbals.",
      "The sound of a large creature swimming.",
      "A rhythmic thumping sound, like a drumbeat.",
      "The unmistakable sound of someone crying.",
      "A sudden, chaotic sound of a large group of people panicking.",
      "The sound of a single, heavy sigh.",
      "A low, guttural hissing sound.",
      "The sharp, rhythmic sound of a clock ticking.",
      "A sudden, loud burst of laughter.",
    ],
  },

  sensoryDetails: {
    id: 'sensoryDetails',
    title: 'Sensory Details (Stalling)',
    attribution: 'Original',
    entries: [
      "A sudden drop in temperature makes the air feel icy and raises goosebumps on your arms.",
      "The overwhelming smell of ozone and burnt copper fills the air, like the aftermath of a lightning strike.",
      "A strange, metallic taste settles on the back of your tongue.",
      "The air feels heavy and oppressive, making it difficult to draw a full breath.",
      "A sudden, cloying scent of sweet perfume masks an underlying smell of decay.",
      "The ground trembles slightly, a subtle vibration felt only through the soles of your boots.",
      "A sudden rush of warm, stale air blows past, carrying the smell of old paper and dust.",
      "The distinct smell of woodsmoke and roasting meat drifts from an unseen source.",
      "A strange, tingling sensation prickles across your skin, like static electricity.",
      "The air feels suddenly damp and clammy, leaving a sheen of moisture on everything.",
      "A sudden, sharp smell of vinegar and spoiled wine assaults your senses.",
      "The feeling of being watched intensely, causing the hairs on the back of your neck to stand up.",
      "A sudden, overpowering smell of blooming night-flowers fills the area.",
      "The air feels unusually still, as if the world is holding its breath.",
      "A sudden, cold draft chills you to the bone, despite the warmth of the day.",
      "The smell of wet earth and impending rain grows stronger.",
      "A strange, ringing pressure builds in your ears, as if descending rapidly.",
      "The distinct smell of hot iron and blood cuts through the ambient odors.",
      "A sudden, localized feeling of intense heat radiates from a nearby wall.",
      "The scent of ancient, stagnant water wafts up from the drains.",
      "A sudden, inexplicable smell of freshly baked bread in a barren place.",
      "The air suddenly feels incredibly dry, instantly chapping your lips.",
      "A sharp, stinging sensation in your eyes, as if chopping onions.",
      "The smell of rotting meat, faint but unmistakable.",
      "A sudden, inexplicable warmth spreads through your body.",
      "The air tastes like ash and soot.",
      "A sudden, sharp prickling sensation on the back of your neck.",
      "The smell of blooming roses, overpowering and sweet.",
      "A sudden, inexplicable coldness that seeps into your bones.",
      "The air feels thick and viscous, like moving through water.",
      "A sudden, sharp smell of pine needles and sap.",
      "The feeling of a cobweb brushing against your face, though there is none.",
      "A sudden, inexplicable smell of old books and parchment.",
      "The air suddenly feels electrically charged, making your hair stand on end.",
      "A sudden, sharp pain in your temples, like a fast-approaching headache.",
      "The smell of sea salt and brine, even far inland.",
      "A sudden, inexplicable feeling of extreme lethargy.",
      "The air tastes incredibly sweet, like honey.",
      "A sudden, sharp itch on the palm of your hand.",
      "The smell of burning hair, acrid and disturbing.",
      "A sudden, inexplicable feeling of extreme energy and restlessness.",
      "The air feels completely devoid of moisture, like a desert wind.",
      "A sudden, sharp smell of cinnamon and spices.",
      "The feeling of someone breathing gently on your neck.",
      "A sudden, inexplicable smell of fresh rain on dry earth.",
      "The air suddenly feels incredibly cold, freezing your breath.",
      "A sudden, sharp ringing in your ears that fades slowly.",
      "The smell of sour milk and decay.",
      "A sudden, inexplicable feeling of nausea.",
      "The air tastes like copper and blood.",
      "A sudden, sharp pain in your chest, like a muscle spasm.",
      "The smell of freshly cut grass, strong and vibrant.",
      "A sudden, inexplicable feeling of profound sadness.",
      "The air feels heavy and oppressive, like a physical weight.",
      "A sudden, sharp smell of ozone and electricity.",
      "The feeling of something small and furry brushing against your leg.",
      "A sudden, inexplicable smell of burning sulfur.",
      "The air suddenly feels incredibly warm and comforting.",
      "A sudden, sharp headache that vanishes instantly.",
      "The smell of damp earth and mold.",
      "A sudden, inexplicable feeling of extreme paranoia.",
      "The air tastes bitter and metallic.",
      "A sudden, sharp pain in your shoulder, like a phantom blow.",
      "The smell of blooming jasmine, sweet and intoxicating.",
      "A sudden, inexplicable feeling of joy and elation.",
      "The air feels incredibly thin, making it hard to catch your breath.",
      "A sudden, sharp smell of peppermint and camphor.",
      "The feeling of a cold hand grabbing your shoulder, but no one is there.",
      "A sudden, inexplicable smell of roasting nuts and caramel.",
      "The air suddenly feels electrically charged, making your skin tingle.",
      "A sudden, sharp pain in your knee, like a sudden twist.",
      "The smell of ancient dust and decay.",
      "A sudden, inexplicable feeling of extreme confidence.",
      "The air tastes incredibly sour, like lemon juice.",
      "A sudden, sharp itch on the bottom of your foot.",
      "The smell of burning rubber and pitch.",
      "A sudden, inexplicable feeling of extreme fear.",
      "The air feels completely devoid of heat, chilling you instantly.",
      "A sudden, sharp smell of lavender and herbs.",
      "The feeling of someone whispering in your ear.",
      "A sudden, inexplicable smell of fresh snow.",
      "The air suddenly feels incredibly dense, like walking through syrup.",
      "A sudden, sharp ringing in your ears that quickly becomes deafening.",
      "The smell of spoiled meat and offal.",
      "A sudden, inexplicable feeling of extreme hunger.",
      "The air tastes like chalk and dust.",
      "A sudden, sharp pain in your back, like a pulled muscle.",
      "The smell of freshly baked cookies, warm and inviting.",
      "A sudden, inexplicable feeling of profound peace.",
      "The air feels heavy and humid, like a jungle.",
      "A sudden, sharp smell of ammonia and cleaning supplies.",
      "The feeling of something wet and slimy touching your hand.",
      "A sudden, inexplicable smell of burning wood.",
      "The air suddenly feels incredibly dry and arid.",
      "A sudden, sharp headache that pulses rhythmically.",
      "The smell of damp stone and moss.",
      "A sudden, inexplicable feeling of extreme anger.",
      "The air tastes incredibly spicy, burning your throat.",
      "A sudden, sharp pain in your foot, like stepping on a nail.",
    ],
  },

  passerbyVignettes: {
    id: 'passerbyVignettes',
    title: 'Passerby Vignettes (Stalling)',
    attribution: 'Original',
    entries: [
      "A haggard-looking person drops a bundle of papers, frantically scrambling to collect them before the wind takes them.",
      "Two people are having a hushed, intense argument in a doorway, stopping to stare as you pass.",
      "A child runs past, laughing hysterically, chased by a frustrated-looking dog.",
      "An elderly person leans heavily on a cane, muttering a repetitive phrase under their breath.",
      "A merchant loudly berates an apprentice for a seemingly minor mistake.",
      "A person in an oversized cloak scurries past, keeping their face completely hidden.",
      "A street sweeper pauses their work to meticulously examine a shiny object they found in the dirt.",
      "A person stands frozen in the middle of the street, staring blankly at the sky.",
      "A pair of guards lean against a wall, sharing a joke and ignoring their surroundings.",
      "A person carrying a precarious stack of boxes stumbles, almost dropping everything.",
      "A well-dressed noble steps carefully through the mud, a look of extreme disgust on their face.",
      "A person sits on a stoop, carefully carving a small piece of wood with a knife.",
      "A group of children are playing a complicated game with chalk and pebbles, arguing over the rules.",
      "A person is frantically searching their pockets, looking increasingly panicked.",
      "A musician is tuning their instrument, repeatedly playing the same discordant note.",
      "A person is trying to coax a stubborn pack animal to move, offering it handfuls of hay.",
      "A beggar holding a sign that says something completely nonsensical.",
      "A person is carefully painting over a symbol on a wall.",
      "A group of people are huddled together, passing a small object back and forth.",
      "A person is leaning against a post, completely asleep while standing up.",
      "A street performer is mimicking the walk and mannerisms of one of the party members.",
      "A young couple is arguing over whether to buy a very ugly piece of jewelry.",
      "An older person is feeding stray animals from a large sack.",
      "A guard is trying to discreetly pick a wedgie while remaining at attention.",
      "A person is reading a map upside down and looking very confused.",
      "A child is trying to sell 'magic pebbles' that are clearly just rocks.",
      "A person is walking a very small, very angry-looking dog.",
      "A merchant is furiously trying to clean a stain off their finest silk shirt.",
      "A person is whispering intensely to a potted plant.",
      "A group of teens is practicing a complicated dance routine.",
      "A person is balancing an impossible number of hats on their head.",
      "A beggar is meticulously organizing their coins by size and shininess.",
      "A person is walking backwards, apparently to avoid stepping on cracks.",
      "A musician is playing a lute with broken strings, completely oblivious to the terrible sound.",
      "A person is trying to coax a stubborn cat out of a tree.",
      "A guard is falling asleep while standing, occasionally jerking awake.",
      "A person is arguing with their own reflection in a puddle.",
      "A child is dragging a massive, clearly too heavy wooden sword.",
      "A person is carefully inspecting every single piece of fruit at a stall.",
      "A merchant is singing a surprisingly beautiful aria while stocking shelves.",
      "A person is walking while entirely engrossed in a book, bumping into things.",
      "A group of people is clustered around a small, unremarkable rock, murmuring.",
      "A person is frantically searching the ground for a lost contact lens... or its fantasy equivalent.",
      "A beggar is handing out crude, hand-drawn maps to 'treasure'.",
      "A person is wearing a completely ridiculous outfit with absolute confidence.",
      "A guard is practicing their 'intimidating glare' in a shop window reflection.",
      "A person is trying to train a pigeon to perform tricks.",
      "A child is wearing a bucket as a helmet and a pot lid as a shield.",
      "A person is carrying a very large, very ugly painting.",
      "A merchant is enthusiastically haggling with a customer who doesn't speak their language.",
      "A person is trying to juggle three identical apples.",
      "A group of teens is trying to sneak past a guard by walking on tiptoe.",
      "A person is walking a very large, very lazy pig.",
      "A beggar is playing a beautiful melody on a crude, homemade instrument.",
      "A person is carefully writing something in a tiny notebook.",
      "A guard is eating a very messy meat pie and trying not to get it on their uniform.",
      "A person is arguing with a street vendor about the freshness of a fish.",
      "A child is crying because their ice cream (or local equivalent) fell on the ground.",
      "A person is trying to fix a broken umbrella.",
      "A merchant is furiously chasing a dog that stole a sausage.",
      "A person is walking while carrying a massive, towering stack of books.",
      "A group of people is watching a spider spin a web.",
      "A person is frantically trying to clean a spot off their glasses.",
      "A beggar is offering to tell fortunes for a copper piece.",
      "A person is wearing a hat that is entirely too small for their head.",
      "A guard is yawning widely, completely unaware they are being watched.",
      "A person is trying to teach a parrot to say a bad word.",
      "A child is trying to catch a butterfly.",
      "A person is carrying a very small, very fragile-looking box.",
      "A merchant is enthusiastically promoting a new, completely useless product.",
      "A person is trying to juggle four identical balls.",
      "A group of teens is trying to impress each other with terrible jokes.",
      "A person is walking a very small, very fast turtle.",
      "A beggar is drawing a beautiful picture on the ground with chalk.",
      "A person is carefully inspecting a very ordinary-looking stone.",
      "A guard is trying to discreetly scratch an itch in an awkward place.",
      "A person is arguing with a stranger about the best way to cook a potato.",
      "A child is playing with a very intricate, very loud toy.",
      "A person is trying to fix a broken shoe.",
      "A merchant is furiously counting their money.",
      "A person is walking while carrying a massive, towering stack of papers.",
      "A group of people is watching a cloud formation.",
      "A person is frantically trying to find their keys.",
      "A beggar is offering to tell a story for a copper piece.",
      "A person is wearing a shirt that is entirely too large for their body.",
      "A guard is staring blankly into space.",
      "A person is trying to teach a dog to fetch.",
      "A child is trying to build a sandcastle in the dirt.",
      "A person is carrying a very large, very heavy bag.",
      "A merchant is enthusiastically greeting everyone who walks by.",
      "A person is trying to juggle five identical rings.",
      "A group of teens is trying to start a band.",
      "A person is walking a very large, very friendly snake.",
      "A beggar is carving a beautiful wooden figure.",
      "A person is carefully inspecting a very ordinary-looking leaf.",
      "A guard is trying to discreetly adjust their armor.",
      "A person is arguing with a wall.",
      "A child is playing hide-and-seek by themselves.",
      "A person is trying to fix a broken wagon wheel.",
    ],
  },

};
