// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const travelTables: Record<string, InspireTable> = {
  travelDelays: {
    id: 'travelDelays',
    title: 'Travel Delays',
    attribution: 'Original',
    entries: [
      "A massive herd of sheep or cattle is being moved down the only road, moving at a crawl.",
      "A bridge is out, and the only ferry is currently on the other side with a sleeping ferryman.",
      "A sudden, localized downpour turns the dirt road into knee-deep mud for a mile.",
      "A merchant cart has broken an axle in a narrow pass, blocking all traffic.",
      "Local guards have set up a checkpoint and are inspecting all cargo very, very slowly.",
      "A thick, unseasonable fog rolls in, making it impossible to see more than ten feet ahead.",
      "A fallen tree blocks the path, too large to easily move without teamwork.",
      "A religious procession is walking barefoot down the road, and it is a crime to pass them.",
      "The party finds a lost, crying child who refuses to speak and points in the wrong direction.",
      "A swarm of non-hostile but very distracting insects descends on the party.",
      "A sinkhole has opened in the middle of the road, and local officials are debating whose jurisdiction it is.",
      "A toll booth has been newly erected by someone who may or may not actually have the authority to do so.",
      "A wandering peddler refuses to let the party pass without showing them their entire inventory.",
      "A minor landslide has covered the trail in loose shale, requiring slow and careful footing.",
      "A pair of rival bards are having a 'duel' in the middle of the crossroads, drawing a large crowd.",
      "A nobleman's carriage is stuck in a ditch, and they demand the party's help.",
      "A sudden hail storm forces everyone to seek shelter immediately.",
      "A local festival involves blocking the main road for a traditional dance.",
      "A strange, glowing fungus has overgrown the path, and stepping on it might be dangerous.",
      "A group of scholars is excavating a small ruin right in the middle of the road.",
      "A sudden sinkhole blocks the main path.",
      "A pack of wild dogs refuses to let anyone pass.",
      "A wandering prophet insists on reading the party's fortune before they can proceed.",
      "A local noble's entourage demands the right of way, moving agonizingly slow.",
      "A sudden, inexplicable drop in temperature freezes the mud on the road.",
      "A group of pilgrims is walking on their knees, blocking the path.",
      "A large, aggressive bird is nesting on the only bridge.",
      "A traveling merchant's cart has spilled a cargo of tiny, slippery beads.",
      "A sudden swarm of bees makes the area impassable.",
      "A local guard demands to see a permit the party has never heard of.",
      "A bridge is out, and the river is swollen.",
      "A massive fallen tree blocks the road, requiring teamwork to move.",
      "A sudden, blinding snowstorm forces the party to seek shelter.",
      "A group of heavily armed bandits demands a toll.",
      "A strange, glowing rock in the road is causing the horses to panic.",
      "A local festival involves blocking the road for a traditional dance.",
      "A sudden, localized earthquake cracks the road.",
      "A group of refugees is moving in the opposite direction, slowing travel.",
      "A traveling bard is performing a very long, very boring song.",
      "A sudden, inexplicable silence makes everyone uneasy.",
      "A group of lost children needs help finding their way home.",
      "A strange, glowing fungus is growing over the path.",
      "A local lord is holding a jousting tournament in the middle of the road.",
      "A sudden, intense heatwave makes travel unbearable.",
      "A group of heavily armed mercenaries is blocking the path.",
      "A massive, ancient statue has fallen across the road.",
      "A sudden, localized downpour turns the road to mud.",
      "A group of religious zealots is burning an effigy in the road.",
      "A strange, glowing portal has opened in the middle of the path.",
      "A local guard patrol is insisting on a full inspection of the party's gear.",
      "A sudden, incredibly strong wind makes it hard to stand.",
      "A group of traveling performers is blocking the path with their carts.",
      "A strange, glowing mist is rising from the ground.",
      "A local noble is throwing a tantrum and refuses to move.",
      "A sudden, terrifying roar echoes through the valley.",
      "A group of lost miners is wandering the road.",
      "A strange, glowing symbol is burned into the path.",
      "A local festival involves a race that uses the main road.",
      "A sudden, inexplicable change in gravity makes walking difficult.",
      "A group of heavily armed soldiers is marching down the road.",
      "A massive, ancient tree is blocking the path.",
      "A sudden, intense thunderstorm forces the party to take cover.",
      "A group of religious pilgrims is blocking the road.",
      "A strange, glowing flower is blooming in the middle of the path.",
      "A local guard is demanding a bribe to pass.",
      "A sudden, localized blizzard strikes without warning.",
      "A group of heavily armed bandits is blocking the path.",
      "A strange, glowing rock is floating in the middle of the road.",
      "A local noble is having a picnic in the middle of the path.",
      "A sudden, inexplicable feeling of dread washes over the party.",
      "A group of traveling merchants is arguing over prices.",
      "A strange, glowing fungus is spreading rapidly over the road.",
      "A local guard patrol is arresting someone on the path.",
      "A sudden, incredibly thick fog rolls in.",
      "A group of lost travelers is asking for directions.",
      "A strange, glowing mist is swirling around the party.",
      "A local festival involves a parade that blocks the road.",
      "A sudden, terrifying scream rings out.",
      "A group of heavily armed mercenaries is demanding a toll.",
      "A massive, ancient wall is blocking the path.",
      "A sudden, intense heatwave makes travel difficult.",
      "A group of religious zealots is preaching in the road.",
      "A strange, glowing portal is pulsing in the middle of the path.",
      "A local guard is inspecting everyone's paperwork.",
      "A sudden, incredibly strong gust of wind knocks everyone down.",
      "A group of traveling performers is putting on a show.",
      "A strange, glowing mist is seeping from the ground.",
      "A local noble is demanding the party's attention.",
      "A sudden, inexplicable change in the color of the sky.",
      "A group of heavily armed soldiers is blocking the road.",
      "A massive, ancient crater is blocking the path.",
      "A sudden, intense thunderstorm is raging overhead.",
      "A group of religious pilgrims is singing loudly.",
      "A strange, glowing flower is emitting a sweet scent.",
      "A local guard is refusing to let anyone pass.",
      "A sudden, localized snowstorm is freezing the road.",
      "A group of heavily armed bandits is demanding a ransom.",
      "A strange, glowing rock is humming loudly.",
      "A local noble is complaining about the quality of the road.",
      "A sudden, inexplicable feeling of euphoria washes over the party.",
    ],
  },

  urbanDistractions: {
    id: 'urbanDistractions',
    title: 'Urban Distractions',
    attribution: 'Original',
    entries: [
      "A street performer accidentally sets their own props on fire, causing a panic.",
      "A runaway draft horse is tearing through the market pulling a cart full of cabbages.",
      "Two rival guilds have decided to hold a loud, public argument in the town square.",
      "A 'prophet' is preaching the end of the world, blocking the alleyway the party needs.",
      "A sudden, heavy rainstorm causes everyone in the street to cram under the nearest awnings.",
      "A flock of escaped exotic birds is loose, and the owner is offering a reward to anyone who can catch them.",
      "A local noble is throwing coins from a balcony, causing a massive crush of people.",
      "A pickpocket bumps into a party member, but instead of taking something, they leave a strange object.",
      "A parade of loudly playing musicians marches down the street, making conversation impossible.",
      "A building under construction suddenly drops a load of bricks near the party.",
      "A famous actor is visiting, and the crowd of fans is impenetrable.",
      "A merchant accuses a party member of breaking a fragile item they didn't even touch.",
      "A local festival involves everyone throwing colored powder, blinding and distracting the party.",
      "A pair of street urchins challenge the party to a game of chance.",
      "A sudden, foul smell from the sewers forces everyone to clear the street.",
      "A guard patrol is randomly stopping people to check for 'contraband' without explaining what it is.",
      "A local tavern is giving away free drinks, causing a massive, unruly queue.",
      "A strange, magical illusion appears in the sky above the city, stopping traffic as everyone watches.",
      "A runaway carriage careens down the street, and the driver is missing.",
      "A group of protesters is blocking the entrance to the building the party needs to enter.",
      "A street vendor is aggressively trying to sell the party a \"magic\" rock.",
      "A pair of rival gangs are having a standoff in the street.",
      "A sudden, localized magical effect turns everyone's hair green.",
      "A group of heavily armed guards is escorting a prisoner.",
      "A runaway carriage is careening down the street.",
      "A local noble is throwing coins to the crowd, causing a riot.",
      "A strange, glowing portal has opened in an alleyway.",
      "A sudden, intense downpour floods the street.",
      "A group of religious zealots is preaching on a corner.",
      "A massive, ancient statue is being moved down the street.",
      "A sudden, inexplicable silence falls over the city.",
      "A group of lost children is wandering the streets.",
      "A strange, glowing mist is rising from the sewers.",
      "A local festival is in full swing, blocking all traffic.",
      "A sudden, terrifying roar echoes through the city.",
      "A group of heavily armed mercenaries is looking for work.",
      "A runaway horse is causing chaos in the market.",
      "A local noble's carriage is stuck in the mud.",
      "A sudden, intense heatwave is making everyone miserable.",
      "A group of religious pilgrims is singing loudly.",
      "A strange, glowing symbol is burned into a wall.",
      "A local guard patrol is demanding to see everyone's papers.",
      "A sudden, incredibly strong wind knocks over market stalls.",
      "A group of traveling performers is putting on a show.",
      "A strange, glowing fungus is growing on a building.",
      "A local noble is throwing a tantrum.",
      "A sudden, inexplicable change in gravity makes walking difficult.",
      "A group of heavily armed soldiers is marching down the street.",
      "A massive, ancient tree is growing in the middle of the road.",
      "A sudden, localized snowstorm strikes the city.",
      "A group of religious zealots is burning an effigy.",
      "A strange, glowing flower is blooming in a window box.",
      "A local guard is demanding a bribe.",
      "A sudden, intense thunderstorm forces everyone indoors.",
      "A group of heavily armed bandits is robbing a store.",
      "A strange, glowing rock is floating in the street.",
      "A local noble is having a picnic in a park.",
      "A sudden, inexplicable feeling of dread washes over the party.",
      "A group of traveling merchants is arguing over prices.",
      "A strange, glowing mist is swirling around a corner.",
      "A local guard patrol is arresting someone.",
      "A sudden, incredibly thick fog rolls in.",
      "A group of lost travelers is asking for directions.",
      "A strange, glowing puddle is blocking the street.",
      "A local festival involves a parade.",
      "A sudden, terrifying scream rings out.",
      "A group of heavily armed mercenaries is demanding a toll.",
      "A massive, ancient wall is blocking an alleyway.",
      "A sudden, intense heatwave is melting the cobblestones.",
      "A group of religious pilgrims is blocking the street.",
      "A strange, glowing portal is pulsing in a doorway.",
      "A local guard is inspecting everyone's belongings.",
      "A sudden, incredibly strong gust of wind blows away a stall.",
      "A group of traveling performers is blocking traffic.",
      "A strange, glowing mist is seeping from a grate.",
      "A local noble is demanding the party's attention.",
      "A sudden, inexplicable change in the color of the sky.",
      "A group of heavily armed soldiers is blocking the road.",
      "A massive, ancient crater is blocking the street.",
      "A sudden, intense thunderstorm is raging.",
      "A group of religious zealots is chanting loudly.",
      "A strange, glowing flower is emitting a sweet scent.",
      "A local guard is refusing to let anyone pass.",
      "A sudden, localized snowstorm is freezing the street.",
      "A group of heavily armed bandits is demanding a ransom.",
      "A strange, glowing rock is humming loudly.",
      "A local noble is complaining about the smell.",
      "A sudden, inexplicable feeling of euphoria washes over the party.",
      "A runaway carriage crashes into a fruit stand.",
      "A flock of pigeons suddenly takes flight, startling everyone.",
      "A street performer starts juggling flaming torches.",
      "A pair of dogs gets into a noisy fight.",
      "A merchant's cart loses a wheel.",
      "A group of children starts playing a loud game.",
      "A sudden gust of wind blows off someone's hat.",
      "A person drops a pile of papers, which scatter everywhere.",
      "A loud argument breaks out between two shopkeepers.",
      "A musician starts playing a discordant tune.",
      "A sudden, strong smell of baking bread wafts through the air.",
    ],
  },

  minorMysteries: {
    id: 'minorMysteries',
    title: 'Minor Mysteries',
    attribution: 'Original',
    entries: [
      "A locked wooden box that, when finally opened, contains only a single, perfectly preserved autumn leaf.",
      "A series of chalk marks on the city walls that seem to lead somewhere, but end abruptly at a blank wall.",
      "A coin that always lands on edge when flipped.",
      "A local well whose water tastes faintly of strawberries.",
      "A book in the library with all the vowels carefully cut out of the pages.",
      "A statue in the town square that seems to be pointing in a different direction every morning.",
      "A stray dog that follows the party, but only walks backward.",
      "A room in the inn that is perfectly clean, but smells strongly of ozone.",
      "A painting where the eyes of the subject seem to follow the viewer, but the subject is a bowl of fruit.",
      "A key found in the road that hums a low tune when held near a specific type of metal.",
      "A local merchant who sells incredibly mundane items (like spoons) at exorbitant prices, and has customers.",
      "A perfectly circular patch of dead grass in an otherwise lush field.",
      "A letter addressed to a party member, dated ten years in the future, containing only a recipe for soup.",
      "A clock in the town square that chimes 13 times at midnight.",
      "A small, glowing rock that casts a shadow pointing toward the nearest source of water.",
      "A local tavern where the ale tastes different to everyone who drinks it.",
      "A cat that seems to understand Common, but only responds to insults.",
      "A door in an alleyway that opens to a blank brick wall, but smells like a bakery.",
      "A pair of shoes found on the side of the road that are perfectly clean, but leave muddy footprints.",
      "A local beggar who predicts the weather with 100% accuracy, but only speaks in rhymes.",
      "A room in the tavern where any candle lit immediately burns with a green flame.",
      "A merchant whose wares include a single, perfectly ordinary-looking apple that costs 1,000 gold.",
      "A statue that appears to change poses when no one is looking.",
      "A local well that occasionally echoes back secrets whispered into it.",
      "A book that tells a different story depending on the time of day it is read.",
      "A stray dog that leads the party to a buried chest filled only with more stray dogs' collars.",
      "A painting of a landscape that changes seasons to match the actual weather.",
      "A key that opens any door, but only if the user knocks first.",
      "A local merchant who insists they are a polymorphed dragon, despite zero evidence.",
      "A perfectly circular patch of dead grass where no snow ever falls.",
      "A letter addressed to a party member, sealed with wax that bears the party's own sigil.",
      "A clock that chimes the exact number of lies told in the room that hour.",
      "A small, glowing rock that hums when near a specific, mundane object like a wooden spoon.",
      "A local tavern where the bartender knows everyone's favorite drink before they order.",
      "A cat that always seems to be sitting on the exact item the party needs to find.",
      "A door that opens to a different location every time the handle is turned.",
      "A pair of shoes that make no sound when walking on gravel.",
      "A local beggar who seems to know the party's deepest fears.",
      "A room where any spilled liquid forms perfect geometric shapes.",
      "A merchant who sells shadows.",
      "A statue that weeps actual tears.",
      "A local well that occasionally spits out silver coins.",
      "A book that reads itself aloud when opened.",
      "A stray dog that can seemingly teleport short distances.",
      "A painting of a face that blinks.",
      "A key that is warm to the touch.",
      "A local merchant who sells dreams.",
      "A perfectly circular patch of dead grass that is warm to the touch.",
      "A letter that writes itself as it is read.",
      "A clock that runs backwards.",
      "A small, glowing rock that floats.",
      "A local tavern where the fire never burns out.",
      "A cat that can walk through walls.",
      "A door that opens into a void.",
      "A pair of shoes that make the wearer walk faster.",
      "A local beggar who can see the future.",
      "A room where gravity is reversed.",
      "A merchant who sells memories.",
      "A statue that breathes.",
      "A local well that grants wishes.",
      "A book that contains all the answers.",
      "A stray dog that can talk.",
      "A painting of a door that can be opened.",
      "A key that is invisible.",
      "A local merchant who sells time.",
      "A perfectly circular patch of dead grass that glows in the dark.",
      "A letter that can only be read by the intended recipient.",
      "A clock that stops time.",
      "A small, glowing rock that cures any disease.",
      "A local tavern where the drinks are free.",
      "A cat that can grant wishes.",
      "A door that leads to anywhere.",
      "A pair of shoes that allow the wearer to fly.",
      "A local beggar who is actually a god.",
      "A room where time stands still.",
      "A merchant who sells luck.",
      "A statue that can talk.",
      "A local well that shows the future.",
      "A book that can change the past.",
      "A stray dog that is actually a prince.",
      "A painting of a person who is actually alive.",
      "A key that can open any lock.",
      "A local merchant who sells love.",
      "A perfectly circular patch of dead grass that is a portal.",
      "A letter that can travel through time.",
      "A clock that can control time.",
      "A small, glowing rock that is a piece of a star.",
      "A local tavern where the patrons are all ghosts.",
      "A cat that is actually a demon.",
      "A door that leads to the underworld.",
      "A pair of shoes that allow the wearer to walk on water.",
      "A local beggar who is actually a king.",
      "A room where reality is malleable.",
      "A merchant who sells souls.",
      "A statue that can move.",
      "A local well that can heal any wound.",
      "A book that can predict the future.",
      "A stray dog that is actually a dragon.",
      "A painting of a place that doesn't exist.",
      "A key that can unlock the secrets of the universe.",
    ],
  },

  bureaucraticHurdles: {
    id: 'bureaucraticHurdles',
    title: 'Bureaucratic Hurdles',
    attribution: 'Original',
    entries: [
      "The guards require a 'Blue Form' to enter the city, but the office that issues them only accepts 'Red Forms' as ID.",
      "A toll booth charges by the pound, and they insist on weighing every single item in the party's packs individually.",
      "The local magistrate is on a 'mandated rest period' and will not sign the necessary documents until tomorrow afternoon.",
      "The party must prove they are not affiliated with a specific, obscure cult before being allowed to buy weapons.",
      "A city inspector demands to check the party's weapons for 'magical safety compliance' and confiscates them for 'testing'.",
      "The only person who can approve the party's request is currently attending a multi-hour poetry recital.",
      "The party must fill out a lengthy questionnaire about their recent travels, and any spelling mistakes require starting over.",
      "A local law requires all adventurers to wear a brightly colored sash, which must be purchased from a specific, distant vendor.",
      "The guards refuse to let the party pass because their description matches a group of notorious pie thieves.",
      "The required permit is written in a dead language, and the party must find the only scholar in town who can translate it.",
      "A new tax on 'exotic pets' means the party must pay a hefty fee for any familiars or animal companions.",
      "The office that issues the necessary paperwork has moved, but the signs haven't been updated.",
      "The official in charge of approving the request is deeply superstitious and won't work on days that end in 'Y'.",
      "The party must provide character references from three local citizens who have known them for at least a week.",
      "A local ordinance prohibits carrying 'concealed magic,' requiring the party to loudly announce every spell they know.",
      "The guards demand an 'exit fee' from the previous town, which the party didn't pay because it doesn't exist.",
      "The necessary paperwork must be stamped with a specific seal, but the seal has been misplaced.",
      "The official in charge is easily distracted and keeps changing the subject to their collection of rare beetles.",
      "The party must navigate a complex maze of administrative offices, each one sending them to another.",
      "A local law requires all visitors to participate in a town-wide game of hide-and-seek before conducting business.",
      "The guards demand a 'weapon safety deposit,' which is just a fancy term for a bribe.",
      "The necessary form is out of print, and the party must convince a scribe to write a new one from memory.",
      "A local ordinance requires all magical items to be registered, but the registry office is hidden by magic.",
      "The official in charge is on strike, demanding better quality ink for their quills.",
      "The party must pass a surprisingly difficult test on local history before being allowed to enter the archives.",
      "A sudden 'audit' freezes all bureaucratic processes for the next three days.",
      "The guards refuse entry unless the party can provide a detailed itinerary of their visit, in triplicate.",
      "A local law requires all visitors to wear a specific type of hat, which is currently sold out everywhere.",
      "The official in charge is asleep, and it is a crime to wake them.",
      "The necessary paperwork must be signed by three different officials who are currently feuding and refuse to speak to each other.",
      "A local ordinance prohibits carrying 'excessive wealth,' requiring the party to donate a portion of their gold to a 'charity'.",
      "The guards demand a 'noise tax' for clanking armor.",
      "The official in charge is convinced the party are spies and demands a ridiculous task to prove their innocence.",
      "The necessary form must be filled out in a specific dialect of Common that no one in the party speaks.",
      "A local law requires all visitors to participate in a mandatory 'community service' hour.",
      "The guards refuse entry because the party's cart is deemed 'aesthetically displeasing'.",
      "The official in charge has misplaced their glasses and cannot read any documents.",
      "The necessary paperwork must be notarized by a specific cleric, who is currently on a spiritual retreat.",
      "A local ordinance prohibits the use of 'aggressive posture,' requiring the party to slouch while in the city.",
      "The guards demand a 'breath tax' for consuming the city's air.",
      "The official in charge is busy playing a very intense game of cards and refuses to be interrupted.",
      "The necessary form must be submitted on a specific color of paper, which is only sold by a rival faction.",
      "A local law requires all visitors to sing a song of praise to the mayor before entering.",
      "The guards refuse entry because the party's mounts are deemed 'too intimidating'.",
      "The official in charge is currently experiencing an existential crisis and is questioning the nature of paperwork.",
      "The necessary paperwork must be signed in the blood of a specific, rare insect.",
      "A local ordinance prohibits carrying more than three weapons per person.",
      "The guards demand a 'footwear inspection fee'.",
      "The official in charge is convinced the party are famous actors and demands an autograph before processing their request.",
      "The necessary form must be filled out using a quill made from a griffin's feather.",
      "A local law requires all visitors to participate in a mandatory 'poetry slam'.",
      "The guards refuse entry because the party's clothing is deemed 'out of season'.",
      "The official in charge is currently conducting a 'spiritual cleanse' of the office and cannot be disturbed.",
      "The necessary paperwork must be approved by the local merchants' guild, which meets only once a month.",
      "A local ordinance prohibits the use of 'foul language,' with a hefty fine for every swear word.",
      "The guards demand a 'suspicious activity' fee because the party looks 'too competent'.",
      "The official in charge is secretly a goblin in disguise, and the party must pretend not to notice.",
      "The necessary form must be submitted at exactly noon, not a minute before or after.",
      "A local law requires all visitors to wear a nametag at all times.",
      "The guards refuse entry because the party's wizard looks 'too shady'.",
      "The official in charge is currently trapped under a massive pile of unfiled documents.",
      "The necessary paperwork must be signed by a local noble, who demands a favor in return.",
      "A local ordinance prohibits the casting of any spells within city limits, even cantrips.",
      "The guards demand a 'traveler's tax' that increases based on how far the party has traveled.",
      "The official in charge is a ghost who only appears at midnight.",
      "The necessary form must be written in invisible ink, which the party must purchase from a shady vendor.",
      "A local law requires all visitors to participate in a mandatory 'dance off'.",
      "The guards refuse entry because the party's rogue looks 'too sneaky'.",
      "The official in charge is currently stuck in a meeting that has been going on for three days.",
      "The necessary paperwork must be approved by the local thieves' guild.",
      "A local ordinance prohibits the wearing of armor in public.",
      "The guards demand a 'beast tax' for any familiars or animal companions.",
      "The official in charge is currently suffering from magical amnesia and doesn't know how to do their job.",
      "The necessary form must be submitted in a specific, highly complex puzzle box.",
      "A local law requires all visitors to carry a specific, heavy stone at all times.",
      "The guards refuse entry because the party's cleric looks 'too preachy'.",
      "The official in charge is currently participating in a 'bureaucratic decathlon'.",
      "The necessary paperwork must be signed by the mayor, who is currently missing.",
      "A local ordinance prohibits the carrying of any potions that are not blue.",
      "The guards demand a 'smell tax' if the party hasn't bathed recently.",
      "The official in charge is currently reviewing the party's entire adventuring history for 'irregularities'.",
      "The necessary form must be written on a scroll that is exactly three feet long.",
      "A local law requires all visitors to participate in a mandatory 'compliment circle'.",
      "The guards refuse entry because the party's fighter looks 'too aggressive'.",
      "The official in charge is currently on a 'quest for the perfect quill'.",
      "The necessary paperwork must be approved by a panel of three judges, who must all agree.",
      "A local ordinance prohibits the carrying of any magical weapons.",
      "The guards demand a 'magic tax' for any spells the party knows.",
      "The official in charge is currently dealing with a localized magical anomaly in their office.",
      "The necessary form must be submitted by a carrier pigeon.",
      "A local law requires all visitors to walk backwards while on the main street.",
      "The guards refuse entry because the party's bard is 'too loud'.",
      "The official in charge is currently writing a novel and refuses to be interrupted.",
      "The necessary paperwork must be signed in the presence of a specific, rare animal.",
      "A local ordinance prohibits the carrying of any gold coins.",
      "The guards demand a 'suspicion tax' because the party looks 'too innocent'.",
      "The official in charge is currently trying to tame a wild beast in their office.",
      "The necessary form must be written in a specific, archaic font.",
      "A local law requires all visitors to wear a specific color on Tuesdays.",
    ],
  },

  minorInconveniences: {
    id: 'minorInconveniences',
    title: 'Minor Inconveniences (Stalling)',
    attribution: 'Original',
    entries: [
      "A sudden gust of wind blows a cloud of dust directly into the party's eyes.",
      "A strap on a backpack suddenly snaps, spilling a few non-fragile items.",
      "A perfectly timed wagon crosses the street, blocking the party's path for a solid minute.",
      "A swarm of overly friendly, very persistent gnats surrounds the group.",
      "One of the party members steps in a deep, surprisingly sticky puddle of mud.",
      "A sudden, brief downpour of rain occurs right over the party, stopping as soon as they are soaked.",
      "A map blows out of someone's hands and gets stuck in a tree branch just out of reach.",
      "A local street vendor persistently tries to sell the party an obviously fake 'magic' rock.",
      "A large flock of pigeons decides to land exactly where the party needs to walk.",
      "Someone's bootlace snaps and immediately gets tangled in a knot.",
      "A sudden, inexplicable smell of skunk (or local equivalent) forces the party to take a detour.",
      "A group of children mistake a party member for a famous bard and demand a song.",
      "A merchant's cart loses a wheel right in front of the party, spilling cabbages everywhere.",
      "A stray dog decides to adopt the party, constantly tripping them up.",
      "A sudden drop in temperature fogs up any glasses or smooth surfaces.",
      "A piece of lint gets stuck in someone's eye.",
      "A belt loop catches on a passing nail, tearing slightly and stalling momentum.",
      "A local guard stops the party to 'randomly inspect' their travel permits.",
      "A sudden, localized fog bank makes it impossible to see more than a few feet ahead.",
      "A coin pouch develops a small hole, dropping a single copper piece every few steps.",
      "A street performer starts a very long, very bad juggling routine right in the party's path.",
      "A sudden, inexplicable itch develops right in the middle of someone's back.",
      "A local beggar latches onto the party, telling a very long, meandering story.",
      "A flock of geese aggressively defends their territory, blocking a bridge.",
      "A sudden, sharp pebble gets stuck perfectly inside a party member's boot.",
      "A merchant insists on showing the party their entire collection of 'rare' spoons.",
      "A local ordinance requires the party to wait for a 'crossing guard' who is nowhere to be found.",
      "A sudden, inexplicable craving for a very specific, hard-to-find food distracts a party member.",
      "A street urchin challenges a party member to a staring contest.",
      "A sudden, loud noise startled a nearby horse, causing it to block the road.",
      "A local festival forces the party to navigate a massive, slow-moving parade.",
      "A sudden, inexplicable feeling of lethargy washes over the group.",
      "A merchant's sign falls off its hinges, narrowly missing the party but blocking the door.",
      "A local guard stops the party to ask for directions to a place they've never heard of.",
      "A sudden, localized shower of sticky sap falls from a nearby tree.",
      "A street vendor aggressively tries to give the party a 'free sample' of something unidentifiable.",
      "A sudden, inexplicable hiccup fit plagues a party member.",
      "A local beggar demands a toll for crossing a 'magic' line drawn in the dirt.",
      "A flock of seagulls aggressively tries to steal the party's rations.",
      "A sudden, sharp briar gets caught in a party member's clothing.",
      "A merchant insists on telling the party the life story of every item in their shop.",
      "A local ordinance requires the party to walk backwards down a specific street.",
      "A sudden, inexplicable feeling of intense thirst distracts a party member.",
      "A street urchin challenges a party member to a thumb wrestling match.",
      "A sudden, loud noise causes a nearby flock of sheep to scatter, blocking the path.",
      "A local festival forces the party to participate in a mandatory dance.",
      "A sudden, inexplicable feeling of intense cold washes over the group.",
      "A merchant's cart spills a large load of feathers, creating a massive mess.",
      "A local guard stops the party to admire their weapons and ask a million questions.",
      "A sudden, localized shower of harmless but annoying pollen falls from the sky.",
      "A street vendor aggressively tries to sell the party a 'lucky' rabbit's foot.",
      "A sudden, inexplicable sneeze fit plagues a party member.",
      "A local beggar demands a toll for 'protecting' the street from dragons.",
      "A flock of crows aggressively caws at the party, following them closely.",
      "A sudden, sharp thorn gets caught in a party member's boot.",
      "A merchant insists on showing the party their 'invisible' collection.",
      "A local ordinance requires the party to wear silly hats while in the town square.",
      "A sudden, inexplicable craving for a very specific, hard-to-find drink distracts a party member.",
      "A street urchin challenges a party member to a race.",
      "A sudden, loud noise startled a nearby cow, causing it to block the road.",
      "A local festival forces the party to listen to a very long, very bad speech.",
      "A sudden, inexplicable feeling of intense heat washes over the group.",
      "A merchant's cart spills a large load of marbles, creating a massive hazard.",
      "A local guard stops the party to ask for their autograph.",
      "A sudden, localized shower of harmless but annoying dust falls from the sky.",
      "A street vendor aggressively tries to sell the party a 'magic' potion that is clearly just water.",
      "A sudden, inexplicable cough fit plagues a party member.",
      "A local beggar demands a toll for 'keeping the ghosts away'.",
      "A flock of ducks aggressively demands bread from the party.",
      "A sudden, sharp rock gets caught in a party member's shoe.",
      "A merchant insists on showing the party their collection of 'antique' rocks.",
      "A local ordinance requires the party to skip instead of walk.",
      "A sudden, inexplicable feeling of intense hunger distracts a party member.",
      "A street urchin challenges a party member to a game of tag.",
      "A sudden, loud noise causes a nearby horse to rear, blocking the path.",
      "A local festival forces the party to participate in a mandatory pie-eating contest.",
      "A sudden, inexplicable feeling of intense fatigue washes over the group.",
      "A merchant's cart spills a large load of apples, creating a massive mess.",
      "A local guard stops the party to tell them a very long, very bad joke.",
      "A sudden, localized shower of harmless but annoying leaves falls from the sky.",
      "A street vendor aggressively tries to sell the party a 'magic' ring that is clearly just a piece of wire.",
      "A sudden, inexplicable yawn fit plagues a party member.",
      "A local beggar demands a toll for 'blessing' the street.",
      "A flock of chickens aggressively pecks at the party's boots.",
      "A sudden, sharp twig gets caught in a party member's hair.",
      "A merchant insists on showing the party their collection of 'rare' dirt.",
      "A local ordinance requires the party to hop on one foot.",
      "A sudden, inexplicable craving for a very specific, hard-to-find dessert distracts a party member.",
      "A street urchin challenges a party member to a arm wrestling match.",
      "A sudden, loud noise causes a nearby dog to bark uncontrollably, blocking the path.",
      "A local festival forces the party to participate in a mandatory potato sack race.",
      "A sudden, inexplicable feeling of intense boredom washes over the group.",
      "A merchant's cart spills a large load of flour, creating a massive cloud.",
      "A local guard stops the party to ask for advice on their love life.",
      "A sudden, localized shower of harmless but annoying flower petals falls from the sky.",
      "A street vendor aggressively tries to sell the party a 'magic' sword that is clearly just a stick.",
      "A sudden, inexplicable stretch fit plagues a party member.",
      "A local beggar demands a toll for 'guarding' the puddles.",
      "A flock of pigeons aggressively demands crumbs from the party.",
      "A sudden, sharp burr gets caught in a party member's cloak.",
    ],
  },
};
