// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const villainyTables: Record<string, InspireTable> = {
  villainSchemes: {
    id: 'villainSchemes',
    title: 'Villain Schemes',
    attribution: 'Original',
    entries: [
      "Immortality — Acquire a legendary artifact rumored to extend life indefinitely.",
      "Immortality — Attain godhood through ritual, deed, or absorption of divine power.",
      "Immortality — Transfer their consciousness into a younger or constructed body.",
      "Immortality — Bind their soul to a hidden vessel, making themselves undestroyable.",
      "Influence — Seize a specific position of power — throne, council seat, guild office.",
      "Influence — Win a high-stakes contest or public competition.",
      "Influence — Earn the favor of a more powerful figure who will then advance their cause.",
      "Influence — Place a controlled pawn into a position of authority.",
      "Magic — Obtain a specific ancient artifact whose power they intend to misuse.",
      "Magic — Build a magical or technological device for a destructive purpose.",
      "Magic — Fulfill a deity's specific desires in exchange for power.",
      "Magic — Make extensive sacrifices to feed a hungry power.",
      "Magic — Re-establish contact with a forgotten or imprisoned deity.",
      "Magic — Open a permanent passage to another world or plane.",
      "Mayhem — Fulfill an apocalyptic prophecy they believe themselves to be the herald of.",
      "Mayhem — Carry out the will of a god of destruction.",
      "Mayhem — Spread a disease, curse, or corruption across a region.",
      "Mayhem — Overthrow an existing government, regardless of what replaces it.",
      "Mayhem — Trigger a natural disaster at the right place and time.",
      "Mayhem — Annihilate a specific bloodline, clan, or lineage entirely.",
      "Passion — Prolong the life of a loved one whose natural time is ending.",
      "Passion — Prove themselves worthy of another person's affection.",
      "Passion — Raise or restore a specific dead person they will not let go.",
      "Passion — Eliminate everyone competing for the affection of someone they want.",
      "Power — Conquer a region militarily, openly or through proxies.",
      "Power — Take command of an existing army, fleet, or fighting order.",
      "Power — Become the unacknowledged power behind a visible ruler.",
      "Power — Gain the personal favor of an established sovereign.",
      "Revenge — Avenge a humiliation or insult, however long ago.",
      "Revenge — Avenge an imprisonment, torture, or maiming.",
      "Revenge — Avenge the death of a loved one against those responsible — or their descendants.",
      "Revenge — Recover stolen property and punish the thief proportionally.",
      "Wealth — Control natural resources, trade routes, or scarce goods.",
      "Wealth — Marry into a fortune and consolidate the new wealth quickly.",
      "Wealth — Plunder a specific cache, hoard, or treasury.",
      "Wealth — Acquire land, goods, or assets through bureaucratic manipulation.",
      "Immortality — Drain the youth from a steady supply of victims to keep aging at bay.",
      "Immortality — Become a lich through a rite that requires the death of someone they love.",
      "Immortality — Inhabit a series of host bodies, abandoning each as it wears out.",
      "Immortality — Strike a binding bargain with a fiend for centuries of guaranteed life.",
      "Immortality — Replace their failing organs with the harvested parts of the living.",
      "Immortality — Bathe in a hidden spring whose waters demand a specific tribute.",
      "Immortality — Become the inheritor of an existing immortal by murdering them in the prescribed way.",
      "Influence — Manufacture a crisis only they can be seen to resolve.",
      "Influence — Discredit every rival in a council until only they remain credible.",
      "Influence — Marry strategically into a house whose voice will then become theirs.",
      "Influence — Forge a string of endorsements from figures too proud to publicly disavow them.",
      "Influence — Acquire kompromat on every official who might oppose them.",
      "Influence — Cultivate a movement of true believers willing to act on cue.",
      "Influence — Become indispensable to a weak ruler through unsolicited favors and quiet debts.",
      "Magic — Decode a forbidden grimoire whose final pages have been scattered across the world.",
      "Magic — Bind an elemental, fiend, or celestial into permanent service.",
      "Magic — Reforge an artifact that was broken specifically because it was too dangerous to exist whole.",
      "Magic — Steal the spellbook of a more accomplished mage and silence them afterward.",
      "Magic — Cultivate a ley line nexus whose power will fuel a single working.",
      "Magic — Awaken a sleeping titan, dragon, or primordial sealed away by older heroes.",
      "Magic — Master a forbidden school of magic outlawed by every reasonable authority.",
      "Magic — Establish a tower at the precise place where reality is thinnest.",
      "Mayhem — Burn a great library and erase whatever truth it protected.",
      "Mayhem — Poison the water supply of a city under cover of plague.",
      "Mayhem — Provoke two nations into a war that benefits neither but suits them.",
      "Mayhem — Unleash a captive monster into a population center.",
      "Mayhem — Crack the wards holding back a sealed evil beneath an unsuspecting town.",
      "Mayhem — Sabotage the granaries before winter sets in.",
      "Mayhem — Collapse a critical bridge, pass, or harbor at the moment it is most needed.",
      "Mayhem — Burn the harvest in three valleys to force a region into dependence on them.",
      "Passion — Force an unwilling beloved to accept a betrothal by removing all alternatives.",
      "Passion — Reunite themselves with a soul currently incarnated as someone else.",
      "Passion — Punish the family that forbade a marriage a generation ago.",
      "Passion — Recreate a dead child through any means, however unwise.",
      "Passion — Reclaim a former lover who has built a new life and refuses to return.",
      "Passion — Preserve an aging beloved in a state outside of time, with or without consent.",
      "Passion — Avenge a single rejection across an entire bloodline.",
      "Passion — Build a monument so monstrous in its scale that the loved one cannot help but be moved.",
      "Power — Subvert a knightly order from within until it answers only to them.",
      "Power — Establish themselves as the indispensable broker between two warring factions.",
      "Power — Acquire the loyalty of a sleeping dragon and waken it on their schedule.",
      "Power — Build a private fortress in territory no kingdom can claim.",
      "Power — Have themselves declared the legitimate heir of a dynasty that ended without one.",
      "Power — Quietly arrange the deaths of every person standing between them and a title.",
      "Power — Win the allegiance of a mercenary captain whose forces decide the next war.",
      "Power — Buy out the debts of a duchy until the duchy is functionally theirs.",
      "Revenge — Destroy the institution that wronged them, brick by brick and member by member.",
      "Revenge — Ruin the reputation of an enemy thoroughly enough that even their grave is spat upon.",
      "Revenge — Force an enemy to watch everyone they love die first.",
      "Revenge — Repay a betrayal with one designed to mirror it in every humiliating detail.",
      "Revenge — Burn down the town that turned them out as a child.",
      "Revenge — Hunt a former teacher across continents to make them admit what they did.",
      "Revenge — Wage a quiet war against the descendants of judges who condemned an ancestor.",
      "Wealth — Corner the market on a commodity by destroying every alternative source.",
      "Wealth — Counterfeit a kingdom's coinage thoroughly enough to wreck its economy at a chosen moment.",
      "Wealth — Forge a will and inherit an estate that should never have been theirs.",
      "Wealth — Insure ships they intend to sink, then collect.",
      "Wealth — Discover and quietly mine a vein that lies under someone else's land.",
      "Wealth — Tax a road they do not own through the threat of bandits they secretly command.",
      "Knowledge — Compile a catalog of every living person's secret and use it as both shield and sword.",
      "Knowledge — Recover a memory taken from them long ago, even if its return drives them mad.",
      "Liberation — Free a sealed power they alone believe to be wrongly imprisoned.",
      "Liberation — Overturn a generations-old law by making its enforcement personally catastrophic.",
      "Knowledge — Steal a piece of arcane lore so dangerous that its previous custodians killed themselves to keep it hidden.",
      "Chaos — Dismantle the city's defenses purely to see how long the citizens survive.",
      "Chaos — Release all prisoners from the kingdom's highest-security magical prison.",
      "Control — Replace the memories of a key leader with fabricated ones.",
      "Control — Engineer a magical addiction in the populace that only they can cure.",
      "Control — Manipulate the weather to extort compliance from farming communities.",
      "Creation — Build a massive golem army using the souls of the fallen as power sources.",
      "Creation — Forge a new plane of existence by tearing pieces away from the material world.",
      "Creation — Engineer a new, perfectly obedient race to replace humanity.",
      "Destruction — Erase a specific color or emotion from the world using high magic.",
      "Destruction — Cause a dormant volcano to erupt beneath a major population center.",
      "Destruction — Silence the song of the world, plunging everything into eternal quiet.",
      "Divinity — Silence the prayers of an entire nation to starve their god.",
      "Divinity — Steal the portfolio of a minor deity of luck or chance.",
      "Divinity — Convince a cult to worship them to siphon divine energy.",
      "Dominion — Merge the material plane with a realm of shadows or fire.",
      "Dominion — Enslave an entire species using a mass mind-control artifact.",
      "Dominion — Claim the title of 'Emperor of the Oceans' by controlling all sea monsters.",
      "Enlightenment — Force the population to experience a traumatic vision of the future to 'wake them up'.",
      "Enlightenment — Destroy all magical knowledge to force reliance on technology, or vice versa.",
      "Enlightenment — Subject a city to a magical experiment to test the limits of mortal sanity.",
      "Escape — Break free from a cosmic prison by sacrificing a million souls.",
      "Escape — Transfer their cursed existence onto an innocent, unsuspecting hero.",
      "Escape — Unmake the universe because existence itself is too painful.",
      "Evolution — Expose a city to a mutating mutagen to force the next stage of humanoid development.",
      "Evolution — Cull the 'weak' from society through a series of deadly trials.",
      "Evolution — Merge flesh and machine/magic to create a flawless, emotionless society.",
      "Greed — Steal the moon, or at least the magical reflection of it.",
      "Greed — Hoard all the water in a desert region and sell it at extortionate rates.",
      "Greed — Turn a bustling metropolis into a massive, forced labor mine.",
      "Ideology — Impose absolute, unyielding order, punishing even the smallest infraction with death.",
      "Ideology — Eradicate all religion because it 'weakens the mind'.",
      "Ideology — Enforce mandatory 'equality' by magically dampening the skills of the talented.",
      "Immortality — Drain the life force of the land itself, turning forests into ash.",
      "Immortality — Trap the concept of Death in a cage, so nothing can ever die again.",
      "Immortality — Consume the hearts of a thousand heroes to gain their strength and lifespan.",
      "Influence — Blackmail the gods themselves by holding an artifact they desperately need.",
      "Influence — Rewrite the history books using magic so they are remembered as the original founder of the empire.",
      "Influence — Indoctrinate the youth through a network of seemingly benign orphanages.",
      "Justice — Punish a city for the crimes of its ancestors by slowly drowning it.",
      "Justice — Act as a vigilante who executes anyone deemed 'corrupt' without trial.",
      "Justice — Summon a celestial judge who will likely condemn the entire world.",
      "Knowledge — Dissect a living angel to understand the mechanics of grace.",
      "Knowledge — Open a portal to the Far Realm just to see what comes out.",
      "Knowledge — Extract the collective wisdom of the elderly, leaving them mindless husks.",
      "Legacy — Father a child with a specific, prophesied individual by any means necessary.",
      "Legacy — Ensure their name is spoken every day by making it a curse word through terrible deeds.",
      "Legacy — Carve their face into the moon using a massive magical laser.",
      "Love — Plunge the world into eternal winter because their lover preferred the cold.",
      "Love — Kidnap the finest artists in the world to create a perfect replica of their lost spouse.",
      "Love — Destroy a kingdom because its prince rejected their advances.",
      "Magic — Drain all the ambient magic in the world into a single, massive battery.",
      "Magic — Alter the fundamental laws of magic so only their specific bloodline can cast spells.",
      "Magic — Create a spell that can rewrite reality with a single word.",
      "Mayhem — Introduce a magical plague that makes people violently attack anyone who speaks.",
      "Mayhem — Switch the minds of every ruler with their lowest-ranking servant.",
      "Mayhem — Animate every corpse in the world simultaneously, just to see what happens.",
      "Obsession — Collect one of every magical creature in the world, regardless of the ecological impact.",
      "Obsession — Complete a masterpiece of art that requires the blood of a thousand innocents as paint.",
      "Obsession — Rebuild a ruined city exactly as it was, forcing captives to play the roles of the dead inhabitants.",
      "Order — Encapsulate a city in a stasis field so it will remain 'perfect' forever.",
      "Order — Magically remove the capacity for free will from the population.",
      "Order — Standardize the appearance and thoughts of every citizen through alchemical conditioning.",
      "Passion — Ignite a continent-spanning war just to feel the thrill of battle.",
      "Passion — Hunt the most dangerous beasts (and heroes) for sport.",
      "Passion — Perform a grand, tragic play where the deaths of the actors (and audience) are real.",
      "Power — Ascend to the throne by framing the current royal family for a demonic pact.",
      "Power — Control the dreams of the populace to subtly guide their waking actions.",
      "Power — Steal the shadows of the citizens, using them to create an untraceable spy network.",
      "Pride — Challenge a god to a duel, using the lives of mortals as collateral.",
      "Pride — Prove they are the greatest thief by stealing the concept of a specific day of the week.",
      "Pride — Demand that every statue in the world be recast in their image.",
      "Purity — Cleanse the world of all magic, seeing it as an unnatural blight.",
      "Purity — Eradicate a specific species or race they deem 'unclean'.",
      "Purity — Flood the world to wash away the 'sin' and start anew.",
      "Rebirth — Burn the world to ashes so a new, 'better' world can grow from it.",
      "Rebirth — Summon a cosmic entity to devour the planet and start the cycle over.",
      "Rebirth — Revert the world to a prehistoric state, wiping out all civilization.",
      "Revenge — Curse the bloodline of their enemy so their descendants always die on their 30th birthday.",
      "Revenge — Trap their enemy in a time loop of their worst memory.",
      "Revenge — Destroy the sun because it reminds them of the god who slighted them.",
      "Survival — Consume the souls of others to stave off a magical disease.",
      "Survival — Steal a fertile valley, displacing its inhabitants, because their own land is dying.",
      "Survival — Sacrifice a portion of the population to appease a cosmic threat and save the rest.",
      "Wealth — Turn a king's daughter into gold and hold her for ransom.",
      "Wealth — Establish a monopoly on the cure for a disease they secretly created.",
      "Wealth — Use a magical artifact to constantly duplicate their own gold, crashing the global economy.",
    ],
  },

  villainMethods: {
    id: 'villainMethods',
    title: 'Villain Methods',
    attribution: 'Original',
    entries: [
      "Agricultural sabotage — blights, poisonings, drought magic, livestock killings.",
      "Direct violence — beatings, assaults, ordered killings.",
      "Bounty hunting or contracted assassination.",
      "Coercion — bribery, blackmail, threats against loved ones, imprisonment.",
      "Confidence schemes — fraud, false contracts, fast-talking marks into ruin.",
      "Defamation — libel, gossip, planted evidence, public humiliation campaigns.",
      "Formal challenges and dueling under cover of honor.",
      "Public execution — by hanging, burning, beheading, sacrifice, display.",
      "Impersonation, disguise, or substitution of one person for another.",
      "Habitual lying, perjury under oath, and false testimony.",
      "Magical mayhem — hauntings, illusions, mind control, summoning, animation of the dead.",
      "Murder concealed as accident, illness, suicide, or vanishing.",
      "Neglect — withholding food, medicine, shelter from those depending on them.",
      "Political maneuvering — betrayal, conspiracy, espionage, oppression by law.",
      "Religious abuse — curses, desecrations, false prophecies, weaponized cults.",
      "Stalking — patient observation, escalating intrusion, ultimate confrontation.",
      "Theft and property crime — arson, blackmail, burglary, counterfeiting, smuggling.",
      "Torture — for confession, for vengeance, for entertainment.",
      "Vice — supplying addictions, ruining marriages, corrupting officials.",
      "Open warfare — ambushes, invasions, massacres, mercenary actions, terrorism.",
      "Hostage-taking — kidnapping the loved ones of those who must comply.",
      "Sieges — starving a place until it surrenders on whatever terms are offered.",
      "Press-ganging — abducting able-bodied workers into forced labor or service.",
      "Slave trading — buying, selling, and breaking human beings as commodities.",
      "Cattle rustling — picking herds clean over a season until the owners are ruined.",
      "Banditry — roadside ambushes calibrated to take everything without leaving witnesses.",
      "Piracy — boarding ships, ransoming crews, sinking what cannot be sold.",
      "Smuggling — moving contraband through the seams of every customs house.",
      "Counterfeiting — forging coin, seals, signatures, deeds, and bills of trade.",
      "Forgery of documents — wills, charters, pardons, marriage records.",
      "Embezzlement — quietly bleeding funds from any organization that trusts them.",
      "Usury — predatory lending designed to seize collateral, never to be repaid.",
      "Extortion rackets — protection schemes that exist by manufacturing the threats they protect against.",
      "Tax farming abuses — collecting in the king's name and keeping the surplus.",
      "Judicial corruption — verdicts purchased, juries packed, judges in pocket.",
      "Bribery — paying officials, witnesses, and clergy to look the other way.",
      "Frame-ups — planting evidence to convict an innocent and remove a rival.",
      "Hostile witnesses suborned — paying or threatening people into damaging testimony.",
      "Show trials — public proceedings whose verdicts were decided beforehand.",
      "Mob incitement — fanning rumor and grievance into riot at chosen times.",
      "Pogroms — orchestrating sectarian violence and standing back to profit.",
      "Witch-hunts — naming any opposition as heretics, demons, or worse.",
      "Heresy accusations — using religious courts to dispossess and execute.",
      "Excommunication and shunning — formal isolation of victims from their community.",
      "Cult conversion — recruiting the lonely and desperate into binding service.",
      "Indoctrination — slow shaping of children, soldiers, or apprentices into instruments.",
      "Brainwashing — sustained psychological breaking of captives until they cooperate.",
      "Honey traps — seduction used to acquire compromising information.",
      "Sextortion — leveraging illicit affairs into blackmail.",
      "Marriage of convenience — using bonds of family to control the bound party.",
      "Arranged disappearances — quiet abductions where bodies are never recovered.",
      "Whispering campaigns — anonymous letters and rumors planted in influential ears.",
      "Pamphleteering — printed slanders distributed faster than they can be refuted.",
      "Burning books — destroying the written record of anything inconvenient.",
      "Burning archives — incinerating evidence of titles, debts, crimes, and births.",
      "Poisoning — slow doses calibrated to imitate disease.",
      "Mass poisoning — wells, feasts, supply wagons hit at the worst possible moment.",
      "Plague-spreading — deliberate seeding of contagion in populations.",
      "Diseased gifts — blankets, food, livestock laced with infection.",
      "Cursed gifts — beautiful objects bearing concealed magical harm.",
      "Drugged hospitality — drinks doctored at feasts where the guest cannot refuse.",
      "Pit traps and snares — engineered hazards on paths the victim will take.",
      "Arson — fires set to destroy property, evidence, or specific people inside.",
      "Sabotage of structures — bridges, dams, mineshafts collapsed on schedule.",
      "Sabotage of equipment — tools, weapons, or ships made to fail at the critical moment.",
      "Riot-grade alchemy — explosives, incendiaries, smoke, paralytic clouds.",
      "Necromancy — raising the dead as labor, soldiery, or interrogators.",
      "Soul-binding — trapping the dying in objects, places, or servants.",
      "Possession by proxy — using lesser spirits to act through unwitting hosts.",
      "Dream invasion — visiting victims in sleep to terrify, mislead, or command.",
      "Memory theft — stripping witnesses of recollections they need to testify.",
      "Identity theft — assuming another's name, papers, and life over time.",
      "Doppelganger insertion — replacing a person with someone who answers to the villain.",
      "Long-game infiltration — placing children in service who will rise into useful positions.",
      "Patronage of artists — funding plays, songs, and paintings that subtly shape public opinion.",
      "Patronage of scholars — funding theories that legitimize whatever the villain is already doing.",
      "Religious patronage — endowing temples whose clergy then preach conveniently.",
      "Festivals and bread — buying the affection of a populace too tired to look closely.",
      "Charity as cover — public good works that mask private predation.",
      "Beasts deployed — hunting dogs, war-trained wolves, bound monsters set on enemies.",
      "Mercenary subcontracting — paying others to do anything that might be traced.",
      "Plausible deniability — every act passed through enough hands that none can be proved.",
      "Selective enforcement — using laws against rivals that are ignored for allies.",
      "Tariffs and tolls — choking competitors out of markets they need to survive.",
      "Sumptuary laws — banning the symbols by which a rival community recognizes itself.",
      "Hostile foreclosures — calling debts in unison to seize estates at a single stroke.",
      "Public denunciation — speeches in council, market, or pulpit that name and ruin.",
      "Anonymous denunciation — written accusations dropped in the right hands at the right time.",
      "Disinheritance — manipulating succession to cut off rivals before they inherit.",
      "Spying — networks of informers, postal interception, paid servants in every house.",
      "Counter-spying — feeding rivals false intelligence so they act on lies.",
      "Provocations — staging incidents that justify the response the villain wanted to make.",
      "Hostile architecture — building, walling, or rerouting to displace and immiserate.",
      "Quarantine abuse — using public health powers to seal in or seal out specific groups.",
      "Cult of personality — propaganda turning the villain into a figure no one dares oppose.",
      "Festive cruelty — public spectacles of harm dressed up as celebration.",
      "Patient absence — letting an enemy ruin themselves while doing nothing visible.",
      "Inheritance manipulation — adoptions, betrothals, and codicils that redirect fortunes.",
      "Lawfare — endless litigation designed to exhaust opponents into surrender.",
      "Bond-servitude — debt contracts engineered to escalate until the signer is owned in all but name.",
      "Assassination — removing key figures quietly before they become a real threat.",
      "Blackmail — forcing compliance by threatening to reveal ruinous secrets.",
      "Bribery — purchasing the loyalty or silence of guards, officials, and witnesses.",
      "Corruption — slowly eroding the morals of a community until they accept the villain's rule.",
      "Deception — spreading false rumors and forged documents to mislead enemies.",
      "Extortion — demanding payment for 'protection' against threats the villain created.",
      "Kidnapping — taking loved ones hostage to ensure cooperation.",
      "Manipulation — subtly guiding others to act against their own interests.",
      "Propaganda — controlling the flow of information to shape public opinion.",
      "Sabotage — secretly destroying resources or infrastructure to weaken rivals.",
      "Sedition — inciting rebellion or unrest in an enemy's territory.",
      "Terrorism — using random acts of violence to create fear and compliance.",
      "Torture — extracting information or forced confessions through physical or mental pain.",
      "Treachery — betraying allies the moment they are no longer useful.",
      "Usurpation — claiming a title or position through force or fraud.",
      "Vandalism — defacing symbols of authority or hope to demoralize the public.",
      "Brainwashing — magically or chemically altering minds to ensure absolute loyalty.",
      "Necromancy — raising the dead to serve as an untiring, unquestioning army.",
      "Demonology — bargaining with fiends for power, regardless of the cost to others.",
      "Biological Warfare — releasing plagues or curses that only the villain can cure.",
      "Economic Warfare — manipulating markets to bankrupt rivals and consolidate power.",
      "Psychological Warfare — driving enemies mad with illusions, phantoms, or gaslighting.",
      "Environmental Destruction — poisoning land or water to force populations to move or submit.",
      "Mind Control — dominating the wills of key individuals to act as sleeper agents.",
      "Mass Surveillance — using magic or mundane spies to monitor every whisper of dissent.",
      "Resource Hoarding — controlling the supply of food, water, or medicine to enforce obedience.",
      "Cultural Erasure — destroying art, history, and language to break a people's spirit.",
      "False Flag Operations — staging attacks and blaming them on enemies to justify war or repression.",
      "Indoctrination — raising children in isolated camps to be fanatical followers.",
      "Magical Addiction — creating a dependency on a substance or spell only the villain can provide.",
      "Sow Discord — turning allies against each other through whispers and planted evidence.",
      "Systematic Oppression — creating laws that legally disenfranchise specific groups.",
      "Weaponized Bureaucracy — burying opponents in endless, impossible paperwork and regulations.",
      "Ritual Sacrifice — using the lives of innocents to fuel dark magic or appease dark gods.",
    ],
  },

  villainWeaknesses: {
    id: 'villainWeaknesses',
    title: 'Villain Secret Weaknesses',
    attribution: 'Original',
    entries: [
      "A hidden object holds the villain's soul. Destroy it, end them.",
      "The villain's power breaks when the death of their true love is avenged.",
      "Weakened in the presence of a specific named artifact.",
      "A specific weapon — known but hard to acquire — deals catastrophic damage.",
      "Speaking the villain's true name aloud unravels them.",
      "An ancient prophecy or riddle holds the precise method of their defeat.",
      "Falls when an ancient enemy publicly forgives their original transgression.",
      "Loses all power if a long-ago mystic bargain is finally completed.",
      "Cannot harm those who have eaten salt at their table — and remembers it.",
      "Bound by an old oath they no longer remember making.",
      "Cannot cross running water once it has been blessed by a priest of any honest faith.",
      "Their reflection shows their true face, and seeing it forces them to flee any room with a mirror.",
      "A single living descendant of the family they wronged anchors their power; freeing that descendant ends it.",
      "Sunlight burns them not for their body but for their secret, and revealing it in sunlight finishes the work.",
      "They cannot enter a home without explicit invitation, and revoked invitations cast them out.",
      "A locket of hair from someone who loved them as a child renders them unable to lift a hand against the bearer.",
      "Their heart beats inside an animal that wanders the countryside; kill the animal and they fall.",
      "They must consume something specific each new moon, and denying them that thing weakens them with each cycle.",
      "The first oath they ever broke can be redeemed by anyone willing to keep it on their behalf.",
      "A song from their childhood, sung in their hearing, paralyzes them with grief.",
      "They cannot be killed by a man or a woman, by the old or the young — but a single category they overlooked can.",
      "Their power requires the consent, willing or unwilling, of a captive they have hidden away. Free the captive.",
      "A single tear shed for them by someone they harmed disarms their magic for a full day.",
      "They are sustained by the unburied bones of a long-ago betrayal; consecrate the grave, end the sustenance.",
      "Their shadow is a separate creature on a leash; cut the leash and the two cannot exist apart for long.",
      "An apology, spoken aloud and meant, to the person they wronged most strips them of their unnatural longevity.",
      "They cannot lie three times in a single day, and the third lie they attempt will be the one that destroys them.",
      "A binding scar on their body can be reopened by a blade forged from the iron of their first prison.",
      "They must reaffirm their pact at a specific shrine each year; defiling the shrine before the day breaks the pact.",
      "Sunset over the spot where they were born undoes whatever magic preserves them, if they can be brought to it.",
      "Their breath was taken in a bottle long ago; smash the bottle and the breath returns, killing them.",
      "A particular flower grown on the grave of their first victim is poison to them.",
      "They cannot enter the place where their childhood self was happiest without forfeiting their power inside it.",
      "A bell rung at the hour of their birth disorients them and reveals their true form.",
      "They die if they ever set foot on the soil of their homeland again.",
      "They die if they ever leave the soil of their homeland.",
      "They die the moment they finally admit, out loud and unprompted, what they have done.",
      "Their armor is held together by a single cursed pin; remove it and the rest cannot hold.",
      "They are bound to a contract that voids itself if the other signatory revokes consent in person.",
      "A child born under the comet that marked their rise is the only one whose touch they cannot endure.",
      "Their power weakens by a measurable fraction with each living witness to their first crime who refuses to be silenced.",
      "They must answer truthfully when asked a question they once asked their teacher; finding that question is the work.",
      "The bones of the person they cheated to gain their power, if returned to consecrated ground, sever the gain.",
      "They are vulnerable only during the few seconds when they laugh, and they have not been heard to laugh in decades.",
      "Drinking the water of a particular forgotten well unbinds them; the well's location is the puzzle.",
      "They cannot exist in the same room as a particular surviving rival; force the meeting and one will not leave.",
      "A page from their journal, read aloud in their presence, rebinds them to the man they were before their pact.",
      "They are anchored to this world by a single relationship; sever it gently or harshly and they drift away.",
      "Their luck transfers to anyone who eats from their plate; share a meal, share the protection it gives.",
      "Their power is fueled by an unspoken secret; speaking it publicly extinguishes the fuel.",
      "They have a counterpart somewhere in the world whose death is their death; finding the counterpart is the quest.",
      "An oath sworn on their behalf by a parent they never met still binds them; that parent's bones can break the oath.",
      "Their pact specifies they will fall when defeated by an unarmed opponent who has nothing to gain.",
      "A particular constellation, only visible from one mountain, dispels their illusions completely.",
      "Their magic is sustained by the breath of sleepers in a particular village; relocate the village and the spell fades.",
      "They die by drowning, and only by drowning, in water from a specific spring.",
      "An old wound never properly closed reopens whenever a particular old hymn is sung within their hearing.",
      "Iron forged by a smith they once spared deals true wounds where other iron only inconveniences.",
      "Their grip on this world loosens each time someone they wronged dies at peace.",
      "A particular phrase, spoken in the language they were tutored in as a child, freezes them for one full minute.",
      "The first person they ever loved is still alive somewhere, hidden; reuniting them strips their cruelty away.",
      "They cannot recover from any wound dealt by a weapon held by both their hands and the wielder's hands together.",
      "An object they buried in shame, if exhumed and shown to them, robs them of speech and spellcasting.",
      "Salt poured across their threshold prevents them entering or leaving without breaking their own oath.",
      "Their power is leased, not owned, and the lease comes due at a specific astronomical event.",
      "A coin minted in the year of their birth, pressed into their palm, dispels their disguise.",
      "Reading their full name from a particular cursed book burns out their magical reserves for a season.",
      "They lose all power inside the ruins of the house they were born in, no matter how rebuilt.",
      "An apology accepted by the spirit of their first murder grants any wielder of a specific blade a single killing strike against them.",
      "They cannot be wounded by metal, only by stone, bone, or wood — and only one specimen of each at the right time.",
      "Their familiar carries their pain; kill the familiar and the next blow lands where it would have landed long ago.",
      "A vow of celibacy or sobriety taken in their youth is still magically active; provoking them to break it ends their protection.",
      "They are vulnerable on the anniversary of their crime, and only then, and only at the exact hour of its commission.",
      "Their power is shared with three other villains across the realm; the deaths must be coordinated, or none stick.",
      "Their immortality is contingent on never speaking the name of a particular sibling; force them to say it.",
      "An object made by their own hand in childhood still recognizes them; pressing it to their skin reveals their lies.",
      "They cannot kill anyone who has saved their life, even if they have forgotten the rescue; find the rescuer.",
      "A particular tune played on a specific instrument disrupts their concentration enough to render them mortal.",
      "Their patron will withdraw protection if presented with proof that the villain broke the patron's first commandment.",
      "Their wards collapse if a specific kind of creature — bee, swan, fox — enters the building uninvited.",
      "Their power was bought with a child's tears, and any child weeping in their presence weakens them measurably.",
      "Their oath to a deceased monarch still binds them; producing a true heir of that line commands their obedience.",
      "They are bound to the land where they died once; carry them off it, and they begin to dissolve.",
      "A scrap of cloth from their burial shroud, if any survives, drains their strength on contact.",
      "Their true form is a small, harmless creature; force them to assume it and they cannot return for a time.",
      "They cannot harm anyone wearing a token bearing the symbol of the order they betrayed.",
      "A confession recorded in a particular book becomes binding if read aloud in a courtroom of their peers.",
      "They must obey any command given by the spirit of the teacher they killed; calling that spirit forth is the challenge.",
      "Their power lives in their hands; cutting them off — at any cost — ends the threat permanently.",
      "Their voice is the conduit of all their magic; rob them of speech and the magic stops.",
      "Their eyes carry the curse they impose on others; blind them and their gaze cannot work.",
      "The conditions of their immortality include a clause about hospitality that they have technically already violated.",
      "Three witnesses to their original crime must each forgive them in turn; only the third forgiveness ends them.",
      "Their power is rooted in a tree somewhere; the tree's location was hidden centuries ago and is the heart of the quest.",
      "They cannot strike a person who is unarmed and holding a particular flower native only to their birthplace.",
      "Their patron is a sleeping god; sing the waking-hymn at the proper hour and the patronage transfers away from them.",
      "A drop of their own blood, returned willingly to its source, severs their tie to the power that sustains them.",
      "They die instantly when they look upon their own portrait painted by a child who has never met them.",
      "Their immortality unwinds if they are made to weep — and they have not wept since the night they made the pact.",
      "A clock that has run continuously since the day they were born stands hidden in a manor cellar; stop it, and they stop too.",
      "They are allergic to a common, everyday herb, which causes them severe magical interference.",
      "Their power is tied to the phase of the moon, rendering them almost mortal during a new moon.",
      "They cannot bear the sound of a specific, very common animal's cry.",
      "A deep-seated arrogance leads them to constantly underestimate their opponents.",
      "They have an irrational fear of a specific color, refusing to wear it or allow it in their presence.",
      "Their magic falters if they are forced to break a specific, obscure rule of etiquette.",
      "They are deeply, secretly in love with one of the heroes, and will hesitate to harm them.",
      "A cursed wound from their past never fully healed and occasionally causes them paralyzing pain.",
      "They cannot tell a lie on a specific day of the week.",
      "Their strength diminishes dramatically if they are separated from a specific, seemingly mundane object.",
      "They are bound by a rigid code of honor that their enemies can exploit.",
      "A specific phobia (e.g., spiders, heights, confined spaces) can trigger a panic attack.",
      "They rely heavily on a specific lieutenant, and the loss of that person would send them into a spiral.",
      "Their grand plans always include a deliberate, theatrical flaw because they enjoy the 'game'.",
      "They are physically tethered to their lair; leaving it drains their vitality.",
      "A lingering guilt over their first evil act makes them hesitate when faced with a similar situation.",
      "They cannot resist a wager, even a foolish one, if properly challenged.",
      "Their magical power requires a complex, daily ritual; interrupting it leaves them vulnerable for 24 hours.",
      "They are blind in one eye, though they use magic to hide the fact.",
      "A specific childhood nickname, if used, sends them into a blind, reckless rage.",
      "They are compelled to count scattered objects, a compulsion that can be used to delay them.",
      "Their power stems from an ancient pact that they are constantly struggling to keep fulfilling.",
      "They cannot harm anyone who genuinely pities them.",
      "A secret addiction to a rare substance leaves them vulnerable to blackmail or withdrawal.",
      "They are terrified of the dark and must always have a light source nearby.",
      "Their physical form is unstable and requires constant magical concentration to maintain.",
      "They cannot abide the smell of a certain flower, which makes them physically ill.",
      "A specific piece of music puts them into a deep, unbreakable trance.",
      "They are fiercely protective of a seemingly insignificant pet or familiar.",
      "Their pride prevents them from ever retreating, even when tactical withdrawal is necessary.",
      "They cannot use their most powerful abilities without causing themselves significant harm.",
      "A piece of their soul is missing, leaving them devoid of a specific emotion (like fear or empathy), which makes them predictable.",
      "They are secretly a coward who hides behind illusions and minions, crumbling in direct combat.",
      "Their lair has a single, catastrophic structural flaw they have ignored due to cost or oversight.",
      "They must constantly consume magic items to sustain their own power, leaving a trail of drained artifacts.",
      "A long-forgotten curse makes them physically unable to speak the name of their greatest enemy.",
      "They are deeply superstitious and will abandon plans if they encounter a 'bad omen'.",
      "Their magic is incredibly powerful but highly unstable and prone to spectacular backfires.",
      "They cannot cross the threshold of a holy place, regardless of the deity.",
      "A specific combination of mundane elements (e.g., iron and salt) completely neutralizes their magic.",
      "They are slowly being consumed by the very dark power they wield, and their sanity is slipping.",
      "Their 'invulnerability' is an illusion; they actually redirect the damage to a hidden portrait or statue.",
      "They have a terrible, easily identifiable 'tell' when they are lying or preparing a powerful spell.",
    ],
  },

  raceCharacterNotes: {
    id: 'raceCharacterNotes',
    title: 'Race / Species Quick Notes',
    attribution: 'Original (system-agnostic)',
    entries: [
      "Aarakocra: bird-folk. Hollow-boned, owl-eyed, intensely territorial in flight.",
      "Bullywug: amphibious. Hop everywhere, smell of swamp, speak with frogs.",
      "Dragonborn: dragon-blooded. Breath weapon, scaled skin, lineage matters.",
      "Drow: deep-dwelling elf. Dark-vision, light-sensitive, kept apart by old shame.",
      "Dwarf: mountain or hill. Resistant to poison, suspicious of magic, longer-lived than humans.",
      "Elf: forest or city. Trances rather than sleeps, ages slowly, sees keenly in dim light.",
      "Gnoll: hyena-folk. Hunger-driven, pack-organized, low impulse control by nature.",
      "Gnome: small and clever. Fascinated by invention or by stone, depending on lineage.",
      "Goblin: small and adaptable. Nimble, social, often dismissed by larger creatures who shouldn't.",
      "Half-elf: between two worlds. Often passes in both, belongs fully to neither.",
      "Half-orc: between two worlds. Strong, enduring, often misjudged by those who haven't met one.",
      "Halfling: small and lucky. Brave under pressure, hard to startle, sees the everyday as miraculous.",
      "Hobgoblin: martial goblinoid. Disciplined, hierarchical, takes oaths seriously.",
      "Kenku: crow-folk. Cannot speak originally — only repeat what they've heard.",
      "Kobold: dragon-touched small folk. Pack-tactical, light-sensitive, ambitious beyond their size.",
      "Lizardfolk: reptilian. Practical to the point of seeming cold, unmoved by mammal sentimentality.",
      "Merfolk: ocean-dwelling. Amphibious, can't survive long out of water without preparation.",
      "Orc: war-bred. Quick to anger, quick to fight, quick to laugh in equal measure.",
      "Tiefling: fiend-touched. Distinct horns, tail, eyes — and a lifetime of being looked at sideways.",
      "Troglodyte: cave-dwelling reptilian. Stench is part of their natural defense — there's no polite version.",
      "Aasimar: celestial-touched. Faintly luminous, slow to anger, plagued by visions they cannot turn off.",
      "Genasi (Air): elemental-blooded. Pale-skinned with windswept hair, light on their feet, restless indoors.",
      "Genasi (Earth): elemental-blooded. Heavy-framed and stone-skinned, slow to speak, hard to move once settled.",
      "Genasi (Fire): elemental-blooded. Embers in the eyes, hot to the touch, tempers shorter than the fuse.",
      "Genasi (Water): elemental-blooded. Sea-colored skin, breathes either element, calm until they aren't.",
      "Tabaxi: cat-folk. Curious past sense, fast on their feet, never quite finished with a question.",
      "Tortle: turtle-folk. Live in their own armor, slow walkers and slower talkers, patient in everything.",
      "Triton: deep-sea folk. Aristocratic by temperament, distrust surface customs, see the sea as a country.",
      "Yuan-ti: serpent-blooded. Cold-eyed and cold-blooded, charming when they need to be, never warm.",
      "Centaur: half-horse. Gallop where others walk, sleep standing, judge strangers by their hands.",
      "Minotaur: bull-headed. Strong-necked, surefooted, never quite lost no matter how strange the path.",
      "Satyr: goat-legged. Music in the blood, mischief in the smile, drink anyone else under the table.",
      "Firbolg: forest giant. Gentle for their size, distrust crowds, speak to plants more readily than to people.",
      "Goliath: mountain-folk. Stone-grey skin, marked at birth, count their honor in deeds done in the open.",
      "Loxodon: elephant-folk. Long memory, longer patience, tusks they neither hide nor brandish.",
      "Owlin: owl-folk. Feathered and silent in flight, see in the dark, awkward at parties for the same reason.",
      "Harengon: rabbit-folk. Long-legged jumpers, ears always swiveling, harder to startle than they look.",
      "Changeling: shapeshifter. Wear other faces as easily as clothes, slow to trust anyone who knows the trick.",
      "Warforged: constructed. Built for a war they outlived, repair instead of heal, weigh a great deal.",
      "Shifter (Beasthide): lycan-blooded. Thick-skinned and slow to tire, shift to a sturdier shape under pressure.",
      "Shifter (Longtooth): lycan-blooded. Wolf-toothed when roused, family-loyal, hate being cornered.",
      "Shifter (Swiftstride): lycan-blooded. Lean and quick, run further than seems possible, restless in rooms.",
      "Shifter (Wildhunt): lycan-blooded. Keen-nosed, slow to forget a scent, uneasy in cities.",
      "Kalashtar: dream-touched. Two minds in one body, sleep lightly, speak with unsettling stillness.",
      "Plant-folk: vegetal lineage. Photosynthesize a little, smell of crushed leaves, slower in winter.",
      "Mushroom-folk: fungal lineage. Pale and damp-skinned, communicate in spore and gesture, distrust open sun.",
      "Insect-folk: chitin-skinned. Compound eyes, antennae twitch when listening, sleep in short stretches.",
      "Ooze-folk: gelatinous lineage. Hold a shape by effort of will, slip through gaps, leave a faint trail.",
      "Crystal-folk: mineral-born. Faceted skin, refract light when angry, slowly grow back what they lose.",
      "Shadow-touched: umbral lineage. Cast a thinner shadow than they should, prefer dusk, harder to see clearly.",
      "Star-touched: astral lineage. Faint constellations under the skin, sleep with eyes half-open, dream in pictures.",
      "Moon-touched: lunar lineage. Mood swings with the phases, silver-eyed, prefer night work for good reason.",
      "Sun-touched: solar lineage. Warm to the touch, tan readily, find cellars and tunnels genuinely unpleasant.",
      "Hag-born: cursed lineage. Inherited a small ugliness and a small gift, distrusted by anyone who knows the sign.",
      "Wereblood-touched: cursed lineage. Don't fully change, but the wrong moon brings sharper teeth and shorter tempers.",
      "Half-giant: titan-blooded. Stand a head above the room, eat twice as much, break furniture by accident.",
      "Half-dragon: scaled lineage. A patch of scales, a hint of breath, eyes that hold a candle far too long.",
      "Vampire-spawn unbroken: undead-touched. Pale, cold-handed, drink a little blood and pretend it is wine.",
      "Mummy-blood: desert-cursed. Wrappings under their clothes, do not bleed quite right, last a long time dry.",
      "Quasit-touched: minor fiend-blood. Small horns under the hair, mischievous to a fault, cannot resist a dare.",
      "Imp-pacted: pact-marked. A red sigil somewhere on the skin, a whisperer in their dreams, useful information that costs.",
      "Sahuagin: shark-folk. Webbed and fanged, smell blood through saltwater, count strength as the only argument.",
      "Sea-elf: ocean-elf. Gill-slits behind the ears, hair drifts strangely on land, count tides instead of weeks.",
      "Wood-elf: forest-elf. Bark-brown skin and leaf-green hair, move through undergrowth without sound, distrust pavement.",
      "High-elf: court-elf. Trained from childhood in arms and letters, conscious of bearing, see five generations forward.",
      "Sun-elf: golden lineage. Coppery skin, gold-flecked eyes, hold themselves a little apart even among kin.",
      "Moon-elf: silver lineage. Pale skin with a bluish cast, prefer twilight, speak more softly than the room requires.",
      "Hill Dwarf: lowland dwarf. Broader-shouldered, deeper-rooted in their valleys, brew the better beer by general agreement.",
      "Mountain Dwarf: highland dwarf. Stockier and stonier, raised to arms early, distrust anything that flies.",
      "Duergar: deep dwarf. Grey-skinned and grim-faced, can swell to a larger shape, slow to forgive an old wrong.",
      "Forest Gnome: woodland gnome. Small enough to vanish in the brush, speak with small animals, hide from large strangers.",
      "Rock Gnome: tinker gnome. Pockets full of half-finished devices, lecture given any opening, sleep in a workshop.",
      "Deep Gnome: svirfneblin. Stone-grey and quiet-footed, lived too long under stone to enjoy the open sky.",
      "Stout Halfling: hardy halfling. Mostly resistant to poison, eat anything once, last to leave a long meal.",
      "Lightfoot Halfling: nimble halfling. Hard to see if they don't want to be seen, naturally diplomatic, travelers by default.",
      "Ghostwise Halfling: telepathic halfling. Speak mind-to-mind at short range, reserved with outsiders, fierce among kin.",
      "Bear-folk: ursine lineage. Heavy, slow to rouse, terrifying once roused, sleep deeply in cold months.",
      "Wolf-folk: lupine lineage. Travel in family bands, sing in the night, defer to elders without resentment.",
      "Cat-folk: feline lineage. Land on their feet, sleep in patches of sun, ignore commands they find boring.",
      "Fox-folk: vulpine lineage. Sharp-faced and sharper-witted, never quite where you saw them last, lie cheerfully.",
      "Rat-folk: rodent lineage. Tunnel and scavenge, distrust open fields, look out for their own first and last.",
      "Boar-folk: porcine lineage. Tusked and short-tempered, root through ruins others have given up on, eat anything.",
      "Hare-folk: lagomorph lineage. Long-eared and fleet, freeze before they run, count their family by the dozen.",
      "Stag-folk: cervine lineage. Antlered in season, light-footed, observe more than they say.",
      "Hawk-folk: raptor lineage. Sharp-eyed at impossible distances, patient hunters, awkward at close quarters.",
      "Frog-folk: anuran lineage. Wide-mouthed and wet-skinned, leap further than they walk, swallow problems whole.",
      "Snake-folk: serpentine lineage. Smell with the tongue, prefer warm rooms, judge slowly and strike once.",
      "Spider-folk: arachnid lineage. Many-eyed and many-legged by descent, weave in private, distrusted on sight.",
      "Bee-folk: apian lineage. Striped and fuzzy, organized by hive, take honor and grudges equally seriously.",
      "Ant-folk: formic lineage. Small and sturdy, work in teams without being told, do not understand idleness.",
      "Crab-folk: crustacean lineage. Carry their own armor, sidle rather than walk, slow to drop a claim.",
      "Octopus-folk: cephalopod lineage. Many-armed and clever-fingered, change color with mood, prefer water.",
      "Clockwork: gear-built construct. Tick faintly when still, need winding, count the day in measured intervals.",
      "Golem-born: stone-built awakened. Heavy and patient, slow to learn but slower to forget, marked with their maker's sign.",
      "Awakened beast: spell-given mind. Body of a beast, mind newly its own, still learning what hands or words are for.",
      "Awakened plant: spell-given mind. Rooted by habit, walks at need, speaks slowly and only at length.",
      "Reborn: returned from death. Cold-skinned, sleep is optional, do not remember most of who they used to be.",
      "Hexblood: hag-cursed living. Marked with a small unnatural feature, hear whispers others don't, treated warily by hedge-witches.",
      "Dhampir: half-undead. Need blood occasionally, sunlight is uncomfortable but not deadly, age very slowly.",
      "Leonin: lion-folk. Maned and proud, count their honor in deeds witnessed, distrust soft hands.",
      "Centaur: half-horse, half-human. Restless travelers, view walls as prisons, incredibly fast on open ground.",
      "Minotaur: bull-headed folk. Culturally focused on maritime trade or deep labyrinths, prone to explosive rage but deeply loyal.",
      "Loxodon: elephant-folk. Slow to anger but unstoppable when provoked, value community and ancestral memory.",
      "Simic Hybrid: magically altered mutants. Constantly seeking 'perfection' through unnatural adaptations.",
      "Vedalken: blue-skinned scholars. Driven by logic and an endless pursuit of improvement, often emotionally distant.",
      "Shifter: part-lycanthrope. More feral than human, trust instinct over reason, fiercely territorial.",
      "Changeling: shapeshifters. Fluid identity, wear faces like clothes, often struggle with a true sense of self.",
      "Kalashtar: dream-touched. Bound to benign spirits, serene but fighting a hidden war in their minds.",
      "Warforged: sentient constructs. Built for war, struggling to find purpose in peace, physically tire less than others.",
      "Githyanki: astral raiders. Militaristic and cruel, revere their lich-queen, deeply hate mind flayers.",
      "Githzerai: ascetic monks. Value mental discipline above all, live in the chaotic limbo, deeply hate mind flayers.",
      "Yuan-ti Pureblood: snake-blooded infiltrators. Emotionless, calculating, believe they are the pinnacle of evolution.",
      "Triton: deep-sea guardians. Arrogant but noble, believe they are the sole protectors of the oceans.",
      "Tortle: turtle-folk. Nomadic and easygoing, carry their homes on their backs, fascinated by the wider world.",
      "Tabaxi: cat-folk. Driven by intense, fleeting curiosities, agile and unpredictable.",
      "Goliath: mountain giants. Competitive, believe in survival of the fittest, deeply respect physical strength.",
      "Genasi: elemental-blooded. Volatile temperaments reflecting their elemental heritage, often feel alienated from 'normal' societies.",
      "Aasimar: celestial-blooded. Bear a heavy burden of destiny, guided by angelic voices, struggle with the weight of expectations.",
      "Firbolg: fey-touched giants. Reclusive forest guardians, use magic to remain unseen, value harmony with nature.",
      "Kenku: raven-folk. Accurately mimic any sound but lack their own creative voice, often relegated to undercity work.",
      "Lizardfolk: reptilian survivors. Pragmatic to a fault, view the world purely in terms of predator and prey.",
      "Bugbear: oversized goblinoids. Lazy but surprisingly stealthy, strike from the shadows with brutal force.",
      "Hobgoblin: militaristic goblinoids. Highly disciplined, value honor and strategic superiority above all.",
      "Goblin: small, cunning survivors. Often oppressed, use numbers and traps to survive, surprisingly resourceful.",
      "Orc: fierce tribal warriors. Driven by the aggressive influence of their god, value strength and combat prowess.",
      "Kobold: draconic scavengers. Weak individually but deadly in groups, fiercely loyal to their tribe or a true dragon.",
      "Satyr: fey revelers. Hedonistic and chaotic, seek pleasure above all else, deeply resent rules and restrictions.",
      "Fairy: tiny fey creatures. Mischievous and unpredictable, view the mortal world as a source of amusement.",
      "Harengon: rabbit-folk. Energetic and lucky, prone to fleeing from danger but incredibly fast.",
      "Owlin: owl-folk. Silent fliers, often drawn to academic pursuits or the secrets of the night.",
    ],
  },

};
