// Inspiration tables for campaign prep — split by category.
// Original content authored for this project.
import type { InspireTable } from '../inspirationTables';

export const worldEventTables: Record<string, InspireTable> = {
  campaignEvents: {
    id: 'campaignEvents',
    title: 'Campaign-Level Events',
    attribution: 'Original',
    entries: [
      "A coronation, succession, or transfer of power changes who rules.",
      "An assassination removes a public figure from the board.",
      "A scandal breaks in the highest social circles and dominates conversation.",
      "A natural disaster — earthquake, plague, flood — strikes a community.",
      "A celestial event — eclipse, comet, planar conjunction — disturbs the populace.",
      "A long war ends, with whichever consequences the truce specifies.",
      "A long war begins, formally or by undeclared incursion.",
      "A treaty is signed between groups previously hostile.",
      "A treaty fractures, and both parties begin readying for conflict.",
      "A religious holiday or festival arrives, halting normal business.",
      "A trial of public interest reaches its verdict.",
      "A marriage, alliance, or formal joining of houses occurs.",
      "A famous figure dies of old age, illness, or accident.",
      "A new religion or sect rises to prominence.",
      "An old religion or sect is openly suppressed.",
      "A market crash, harvest failure, or trade disruption hits the economy.",
      "A trove of ancient lore is discovered and made publicly available.",
      "A new technology, spell, or technique becomes widely available.",
      "Refugees from a distant disaster begin arriving in significant numbers.",
      "A long-lost ship, expedition, or family returns from where they vanished.",
      "A border is redrawn by force, decree, or quiet purchase.",
      "A colony declares independence from the parent power that founded it.",
      "A succession war erupts between rival claimants to a vacant throne.",
      "A regent is named for an heir too young to rule, and immediately mistrusted.",
      "A general returns from the frontier with troops who haven't been paid.",
      "A mercenary company switches sides between two warring powers.",
      "A long-besieged city finally falls, and its sack runs through the chronicles for years.",
      "A peace conference is convened at neutral ground under fragile guarantees.",
      "A famous warship is lost at sea with all hands and no clear cause.",
      "A flagship is launched amid public ceremony and political signaling.",
      "A pirate fleet consolidates under a single warlord for the first time in memory.",
      "A trade monopoly is awarded — or revoked — by royal charter.",
      "Two great merchant houses go to court over a contract no one can untangle.",
      "A currency is debased, and prices begin to climb everywhere at once.",
      "A new mint opens, stamping coins under an unfamiliar device.",
      "A guild expels a master under accusations that don't quite add up.",
      "A craft guild declares a strike, freezing supply of a critical good.",
      "A bank fails, taking the deposits of several powerful families with it.",
      "A new tax is levied that falls hardest on a politically inconvenient group.",
      "A census is ordered, and people begin to disappear from its rolls.",
      "A famine creeps in slowly enough that no one notices until the markets thin.",
      "A plague burns through a quarter, then is contained — barely, and at cost.",
      "A new disease is named that no healer can yet treat reliably.",
      "A great fire takes a district, and rebuilding becomes its own political battle.",
      "A river changes course, ruining one town and enriching another overnight.",
      "A volcano wakes that had been considered safe in living memory.",
      "A long winter arrives early and refuses to end on time.",
      "A drought stretches into its second year, hardening every existing conflict.",
      "A migration of beasts from a wilder region pushes hard against settled lands.",
      "A monster long thought legendary is sighted by multiple credible witnesses.",
      "A dragon is reported to have taken a new lair within the realm's borders.",
      "Undead are walking in a province where they have not walked in generations.",
      "A demonic incursion is contained, but rumors persist that some got through.",
      "A planar rift opens briefly and closes — leaving things behind on both sides.",
      "A magical experiment goes wrong publicly, and witnesses cannot agree on what they saw.",
      "A magical school splits over a doctrinal dispute and its students choose sides.",
      "An archmage retires from public life, and their tower is sealed against visitors.",
      "An artifact long held by a temple is stolen, and the temple will not say which artifact.",
      "A holy relic is recovered from a battlefield and paraded through several capitals.",
      "A prophecy is uttered publicly by a figure too credible to ignore.",
      "An oracle's last words on her deathbed are recorded and begin to be passed around.",
      "A god ceases answering its clerics' prayers, quietly and without explanation.",
      "A god answers prayers in a different region than it ever had before.",
      "A new saint is canonized, and pilgrims begin redirecting toward their shrine.",
      "A heresy spreads from a backwater into the cities, picking up educated converts.",
      "A messianic figure begins drawing crowds with miracles witnesses dispute.",
      "A wizard publishes a treatise that overturns assumptions every apprentice was taught.",
      "A printing press, scriptorium boom, or pamphlet craze changes how news travels.",
      "A great library burns, and copies of what was lost become priceless overnight.",
      "A university charters a new faculty, and the old ones go to war over its budget.",
      "An exploratory expedition returns with maps of a place no one knew was there.",
      "Settlers begin pushing into a frontier that was previously considered too dangerous.",
      "A treaty with a nonhuman people is broken by one side, and no one will admit which.",
      "A nonhuman embassy is established openly in a human capital for the first time.",
      "A noble house ends in its last child, and its holdings are contested in writing.",
      "A noble house is exiled by decree, and its loyalists begin quietly leaving the realm.",
      "A peasant uprising is put down, but its slogans keep reappearing on walls.",
      "A reformer wins enough support that the establishment must answer them publicly.",
      "A demagogue's followers begin enforcing the demagogue's positions in the street.",
      "A secret order is exposed and dragged into a sunlight it had not prepared for.",
      "A cult performs a public miracle no one can convincingly debunk.",
      "A criminal syndicate goes to war with itself, and bodies surface in the canals.",
      "A famous duelist is killed by a nobody, and the implications ripple outward.",
      "A diplomatic incident at a banquet escalates faster than anyone wanted it to.",
      "A royal favorite is dismissed without warning, and factions reorganize overnight.",
      "A royal child is born with a feature, mark, or omen that will not be ignored.",
      "An heir is sent away to be fostered, raised, or hidden — and the why is whispered.",
      "A monarch's illness is officially denied while every court hedges its bets.",
      "Tax records vanish from a provincial seat, and no one is admitting to ordering it.",
      "A great clock, calendar, or astronomical instrument is built and made public.",
      "A magical means of communication — sending, scrying, signal — becomes affordable.",
      "An old road is reopened after generations of disuse, and traffic shifts onto it.",
      "A new road is cut through previously unworkable terrain by sheer engineering.",
      "A canal is finished, linking two rivers and rewriting regional trade.",
      "A wonder of construction — bridge, dome, statue — is completed and dedicated.",
      "An old hero's tomb is opened, officially or otherwise, and the grave is empty.",
      "A long-vanished noble line is revived through a credible distant claimant.",
      "A treaty with the dead, the fey, or another power is renegotiated in public ceremony.",
      "A war crime committed years ago is publicly admitted by one of those responsible.",
      "An amnesty is declared, and people thought dead begin showing themselves again.",
      "A sudden, inexplicable change in the weather patterns causes mass panic.",
      "A long-dormant volcano shows signs of erupting, threatening nearby cities.",
      "A strange, new constellation appears in the night sky, confounding astronomers.",
      "A massive influx of refugees from a previously unknown conflict arrives at the border.",
      "A prominent political figure is discovered to be a shapeshifter or spy.",
      "A highly contagious, magical disease begins spreading rapidly through the population.",
      "A powerful, ancient artifact is unearthed, sparking a violent scramble for control.",
      "A key trade route is permanently blocked by a strange, magical anomaly.",
      "A renowned academy of magic is destroyed in a spectacular, unexplained explosion.",
      "A charismatic new leader unites several disparate factions into a terrifying new force.",
      "A massive, ancient beast awakens from a centuries-long slumber.",
      "A sudden, complete eclipse of the sun lasts for several days.",
      "A previously thought extinct race makes contact with civilization.",
      "A major city mysteriously vanishes overnight, leaving behind only a smooth crater.",
      "A powerful magical ward that protected the region suddenly fails.",
      "A massive, glowing rift opens in the sky, raining strange debris onto the land.",
      "A popular uprising overthrows a long-standing monarchy.",
      "A crucial alliance between two major powers unexpectedly collapses.",
      "A terrifying new type of monster begins appearing in the wilderness.",
      "A famous, seemingly impregnable fortress is breached and conquered.",
      "A sudden, widespread famine causes widespread unrest and starvation.",
      "A powerful new magical substance is discovered, revolutionizing industry and warfare.",
      "A massive fleet of unknown origin appears off the coast.",
      "A series of devastating earthquakes wrack the region.",
      "A prominent religious leader receives a terrifying vision that changes their dogma.",
      "A long-lost heir to a powerful throne suddenly appears to claim their birthright.",
      "A massive, unexplainable magical silence falls over a major city.",
      "A sudden, widespread madness afflicts a specific demographic.",
      "A powerful, magical storm ravages the coast for weeks.",
      "A key resource suddenly becomes incredibly scarce, sparking wars.",
      "A massive, intricate labyrinth is discovered beneath a major city.",
      "A prominent figure is assassinated publicly, sparking a succession crisis.",
      "A new, highly addictive magical substance floods the streets.",
      "A massive, ancient tree that served as a religious center suddenly dies.",
      "A powerful new spell is invented that threatens the balance of power.",
      "A massive, unexplainable magical darkness covers the land.",
      "A sudden, widespread awakening of magical potential in ordinary citizens.",
      "A powerful, magical beast claims a major city as its new lair.",
      "A massive, unexplainable magical sleep falls over a major city.",
      "A sudden, widespread loss of magical potential in previously skilled casters.",
      "A powerful, ancient god is rumored to have been reborn.",
      "A massive, unexplainable magical portal opens in the center of a major city.",
      "A sudden, widespread infestation of dangerous, magical creatures.",
      "A powerful new weapon is developed that makes traditional fortifications obsolete.",
      "A massive, unexplainable magical mutation afflicts a specific region.",
      "A sudden, widespread rebellion of magical constructs or familiars.",
      "A powerful, ancient curse is unleashed upon the land.",
      "A massive, unexplainable magical silence falls over a major city.",
      "A sudden, widespread madness afflicts a specific demographic.",
      "A powerful, magical storm ravages the coast for weeks.",
      "A key resource suddenly becomes incredibly scarce, sparking wars.",
      "A massive, intricate labyrinth is discovered beneath a major city.",
      "A prominent figure is assassinated publicly, sparking a succession crisis.",
      "A new, highly addictive magical substance floods the streets.",
      "A massive, ancient tree that served as a religious center suddenly dies.",
      "A powerful new spell is invented that threatens the balance of power.",
      "A massive, unexplainable magical darkness covers the land.",
      "A sudden, widespread awakening of magical potential in ordinary citizens.",
      "A powerful, magical beast claims a major city as its new lair.",
      "A massive, unexplainable magical sleep falls over a major city.",
      "A sudden, widespread loss of magical potential in previously skilled casters.",
      "A powerful, ancient god is rumored to have been reborn.",
      "A massive, unexplainable magical portal opens in the center of a major city.",
      "A sudden, widespread infestation of dangerous, magical creatures.",
      "A powerful new weapon is developed that makes traditional fortifications obsolete.",
      "A massive, unexplainable magical mutation afflicts a specific region.",
      "A sudden, widespread rebellion of magical constructs or familiars.",
      "A powerful, ancient curse is unleashed upon the land.",
      "A massive, unexplainable magical silence falls over a major city.",
      "A sudden, widespread madness afflicts a specific demographic.",
      "A powerful, magical storm ravages the coast for weeks.",
      "A key resource suddenly becomes incredibly scarce, sparking wars.",
      "A massive, intricate labyrinth is discovered beneath a major city.",
      "A prominent figure is assassinated publicly, sparking a succession crisis.",
      "A new, highly addictive magical substance floods the streets.",
      "A massive, ancient tree that served as a religious center suddenly dies.",
      "A powerful new spell is invented that threatens the balance of power.",
      "A massive, unexplainable magical darkness covers the land.",
      "A sudden, widespread awakening of magical potential in ordinary citizens.",
      "A powerful, magical beast claims a major city as its new lair.",
      "A massive, unexplainable magical sleep falls over a major city.",
      "A sudden, widespread loss of magical potential in previously skilled casters.",
      "A powerful, ancient god is rumored to have been reborn.",
      "A massive, unexplainable magical portal opens in the center of a major city.",
      "A sudden, widespread infestation of dangerous, magical creatures.",
      "A powerful new weapon is developed that makes traditional fortifications obsolete.",
      "A massive, unexplainable magical mutation afflicts a specific region.",
      "A sudden, widespread rebellion of magical constructs or familiars.",
      "A powerful, ancient curse is unleashed upon the land.",
    ],
  },

  tavernEncounters: {
    id: 'tavernEncounters',
    title: 'Tavern Encounters',
    attribution: 'Original',
    entries: [
      "A patron accuses the bartender of watering the ale, drawing a blade.",
      "Two rival mercenary bands are engaged in a tense drinking contest.",
      "A cloaked figure slips a vial of something dark into another's drink.",
      "The hearth fire suddenly flares bright green and spits out ash.",
      "A local bard begins a song that insults a prominent noble in the room.",
      "A drunken wizard accidentally turns their stool into a sheep.",
      "Someone tries to sell the party a treasure map stained with fresh blood.",
      "A group of miners celebrates a strike, buying drinks for everyone.",
      "A pickpocket bumps into a party member and immediately apologizes profusely.",
      "The tavern door slams open, but no one is there.",
      "A mysterious stranger offers a high-stakes game of cards.",
      "A massive brawl breaks out over a spilled bowl of stew.",
      "The serving staff are all acting perfectly synchronized and glassy-eyed.",
      "A patron collapses, clutching their chest and pointing at the ceiling.",
      "A rat scurries across the bar carrying a gold ring in its mouth.",
      "A recruiter is loudly seeking volunteers for a doomed expedition.",
      "A weeping woman asks for help finding her missing husband.",
      "The ale suddenly tastes like seawater and kelp.",
      "A shadowy figure watches the party from the darkest corner.",
      "A wealthy merchant offers to buy the party's most valuable weapon.",
      "A group of cultists tries to recruit patrons over cheap wine.",
      "A magical duel erupts between two angry apprentices.",
      "The tavern keeper asks the party to deal with a 'problem' in the cellar.",
      "A beautiful stranger tries to seduce a party member to steal their coin purse.",
      "A massive, armored knight challenges anyone to an arm-wrestling match.",
      "A patron claims to have seen a dragon flying near the city walls.",
      "A thief tries to fence stolen goods right at the party's table.",
      "A sudden, inexplicable chill freezes the drinks in their mugs.",
      "A local constabulary raids the tavern searching for a fugitive.",
      "A mysterious patron pays for the party's drinks and leaves without a word.",
      "A goblin in disguise accidentally reveals themselves and panics.",
      "A fortune teller offers free readings that are unnervingly accurate.",
      "A group of rowdy sailors starts a sea shanty that summons a minor water elemental.",
      "A patron chokes on a silver coin hidden in their pie.",
      "A mysterious stranger slips a note into a party member's pocket.",
      "A drunken brawler mistakes a party member for an old rival.",
      "A patron offers a magical item in exchange for a simple favor.",
      "A group of thugs tries to extort protection money from the tavern keeper.",
      "A sudden blackout plunges the tavern into darkness for a full minute.",
      "A patron claims to be the rightful heir to the throne, and has proof.",
      "A mysterious stranger asks the party to hide a small, pulsing box.",
      "A drunken patron tries to ride the tavern's hunting hound.",
      "A local magistrate is caught accepting a bribe in a quiet booth.",
      "A patron claims they were just robbed by a ghost.",
      "A group of adventurers returns, battered and boasting of their kills.",
      "A mysterious patron leaves a trail of strange, glowing footprints.",
      "A sudden gust of wind blows open all the windows, scattering papers.",
      "A patron offers to sell a 'genuine' piece of a famous saint.",
      "A group of revelers tries to drag the party into a chaotic dance.",
      "A mysterious stranger asks for directions to a place that doesn't exist.",
      "A patron collapses in a fit of prophetic visions.",
      "A local gang corners a lone patron, demanding payment.",
      "A mysterious patron seems to know everyone's deepest secret.",
      "A drunken wizard challenges the party to a contest of illusions.",
      "A patron claims they found a portal to another world in the privy.",
      "A group of angry locals demands the tavern keeper stop serving outsiders.",
      "A mysterious stranger offers a vial of liquid that promises perfect memory.",
      "A patron tries to sell a talking parrot that knows too many secrets.",
      "A sudden, localized tremor shakes only the tavern.",
      "A patron claims they were cursed by a witch and begs for help.",
      "A local hero is holding court, recounting exaggerated tales.",
      "A mysterious patron leaves a hefty pouch of gold and vanishes.",
      "A drunken patron tries to start a revolution right there in the taproom.",
      "A patron claims they are being hunted by invisible assassins.",
      "A group of scholars debates a controversial theory until punches are thrown.",
      "A mysterious stranger offers a map to a hidden trove, for a steep price.",
      "A patron tries to sell a weapon that supposedly killed a king.",
      "A sudden, deafening silence falls over the entire tavern.",
      "A patron claims they have a cure for a plague that hasn't started yet.",
      "A local noble tries to recruit the party for a dangerous hunt.",
      "A mysterious patron is seen passing a coded message to the bartender.",
      "A drunken patron tries to cast a spell they clearly don't understand.",
      "A patron claims they have seen the end of the world.",
      "A group of mercenaries celebrates a successful assassination.",
      "A mysterious stranger offers a deal that sounds too good to be true.",
      "A patron tries to sell a 'dragon egg' that looks suspiciously like a painted rock.",
      "A sudden, foul odor permeates the tavern, driving patrons out.",
      "A patron claims they are the reincarnation of a legendary hero.",
      "A local gang tries to muscle in on the tavern's territory.",
      "A mysterious patron leaves a strange, glowing symbol on the table.",
      "A drunken patron challenges the party to a drinking contest with magical ale.",
      "A patron claims they have a map to the lost city of gold.",
      "A group of revelers accidentally sets fire to a tapestry.",
      "A mysterious stranger offers a potion that grants temporary invulnerability.",
      "A patron tries to sell a 'cursed' item that they claim brings good luck.",
      "A sudden, blinding flash of light temporarily blinds everyone.",
      "A patron claims they are being followed by a demon.",
      "A local noble demands that everyone bow to them.",
      "A mysterious patron leaves a trail of silver coins.",
      "A drunken patron tries to climb the rafters and gets stuck.",
      "A patron claims they have found the fountain of youth.",
      "A group of adventurers tries to recruit the party for a suicide mission.",
      "A mysterious stranger offers a weapon that supposedly never misses.",
      "A patron tries to sell a 'magic' bean.",
      "A sudden, deafening roar echoes from the cellar.",
      "A patron claims they are the rightful owner of the tavern.",
      "A local gang tries to extort the party.",
      "A mysterious patron leaves a strange, humming device on the table.",
      "A drunken patron challenges the party to a duel to the death.",
      "A patron claims they have a message from the gods.",
      "A patron challenges anyone to a game of knives.",
      "A halfling attempts to slip out without paying, causing a commotion.",
      "A masked figure sits silently, observing the room.",
      "A stray dog wanders in and sits expectantly by the fire.",
      "A sudden argument erupts over a spilled drink.",
      "A patron passes out, revealing a strange tattoo.",
      "A loud crash from the kitchen halts all conversation.",
      "A stranger offers to buy the house a round of drinks.",
      "A pair of lovers argues loudly in a corner.",
      "A patron tries to sell a 'genuine' magic ring.",
      "A drunken brawl spills out into the street.",
      "A mysterious figure leaves a sealed envelope on a table.",
      "A patron complains loudly about the quality of the food.",
      "A sudden hush falls as a notorious criminal enters.",
      "A patron attempts to charm the bartender for free drinks.",
      "A group of travelers shares rumors of a nearby monster.",
      "A patron offers a wager on a game of chance.",
      "A sudden cold draft blows through the tavern.",
      "A patron tries to recruit someone for a 'simple job'.",
      "A mysterious stranger asks probing questions about the party.",
      "A patron claims to have a map to hidden treasure.",
      "A sudden fight breaks out between two dogs.",
      "A patron tries to sell a strange, glowing rock.",
      "A mysterious figure leaves a small wooden box on the bar.",
      "A patron complains about a strange noise in the walls.",
      "A sudden burst of laughter erupts from a dark corner.",
      "A patron attempts to pickpocket a sleeping traveler.",
      "A mysterious stranger offers a cryptic warning.",
      "A patron claims to have seen a ghost in the cellar.",
      "A sudden smell of smoke causes panic.",
      "A patron tries to sell a 'cure-all' potion.",
      "A mysterious figure leaves a silver coin on a table.",
      "A patron complains about the smell of a fellow traveler.",
      "A sudden argument over a game of cards turns violent.",
      "A patron tries to sell a 'magic' sword.",
      "A mysterious stranger asks for help finding a lost item.",
      "A patron claims to have been robbed.",
      "A sudden flash of light blinds everyone momentarily.",
      "A patron attempts to sneak a weapon past the guards.",
      "A mysterious figure leaves a strange, glowing symbol on the wall.",
      "A patron complains about the quality of the ale.",
      "A sudden silence falls as the tavern keeper enters.",
      "A patron tries to sell a 'genuine' piece of a famous saint.",
      "A mysterious stranger offers a high-stakes wager.",
      "A patron claims to have seen a monster in the woods.",
      "A sudden argument over a woman turns violent.",
      "A patron tries to sell a 'magic' ring.",
      "A mysterious figure leaves a small, wooden box on a table.",
      "A patron complains about the noise level.",
      "A sudden burst of song erupts from a group of travelers.",
      "A patron attempts to charm a guard for information.",
      "A mysterious stranger asks for help with a 'small problem'.",
      "A patron claims to have found a hidden passage.",
      "A sudden smell of rotting meat fills the tavern.",
      "A patron tries to sell a 'cure-all' potion.",
      "A mysterious figure leaves a silver coin on the bar.",
      "A patron complains about the cold.",
      "A sudden argument over a game of dice turns violent.",
      "A patron tries to sell a 'magic' shield.",
      "A mysterious stranger offers a cryptic message.",
      "A patron claims to have been cursed.",
      "A sudden flash of light blinds everyone momentarily.",
      "A patron attempts to sneak a stolen item past the guards.",
      "A mysterious figure leaves a strange, glowing symbol on a table.",
      "A patron complains about the service.",
      "A sudden silence falls as a group of armed men enters.",
      "A patron tries to sell a 'genuine' piece of a famous monster.",
      "A mysterious stranger offers a high-stakes game of chance.",
      "A patron claims to have seen a ghost in the woods.",
      "A sudden argument over a spilled drink turns violent.",
      "A patron tries to sell a 'magic' amulet.",
      "A mysterious figure leaves a small, wooden box on the floor.",
      "A patron complains about the food.",
      "A sudden burst of laughter erupts from a group of guards.",
      "A patron attempts to charm a barmaid for information.",
      "A mysterious stranger asks for help with a 'delicate matter'.",
      "A patron claims to have found a hidden treasure.",
      "A sudden smell of sulfur fills the tavern.",
      "A patron tries to sell a 'cure-all' potion.",
      "A mysterious figure leaves a silver coin on the floor.",
      "A patron complains about the heat.",
      "A sudden argument over a game of cards turns violent.",
      "A patron tries to sell a 'magic' wand.",
      "A mysterious stranger offers a cryptic warning.",
      "A patron claims to have been poisoned.",
      "A sudden flash of light blinds everyone momentarily.",
      "A patron attempts to sneak a weapon past the bartender.",
      "A mysterious figure leaves a strange, glowing symbol on the ceiling.",
      "A patron complains about the ale.",
      "A sudden silence falls as a group of travelers enters.",
      "A patron tries to sell a 'genuine' piece of a famous hero.",
      "A mysterious stranger offers a high-stakes wager.",
      "A patron claims to have seen a monster in the cellar.",
      "A sudden argument over a woman turns violent.",
      "A patron tries to sell a 'magic' ring.",
      "A mysterious figure leaves a small, wooden box on the bar.",
      "A patron complains about the noise.",
      "A sudden burst of song erupts from a group of guards.",
      "A patron attempts to charm a traveler for information.",
      "A mysterious stranger asks for help with a 'dangerous task'.",
      "A patron claims to have found a hidden passage.",
      "A sudden smell of smoke fills the tavern.",
      "A patron tries to sell a 'cure-all' potion.",
      "A group of miners celebrates a major strike, buying drinks for everyone.",
      "A mysterious woman in mourning clothes sits silently in the corner, watching.",
      "A seemingly innocent game of darts escalates into a knife-throwing competition.",
      "A patron insists they've been poisoned and demands a healer immediately.",
      "A local official attempts to collect an impromptu 'tax' from the patrons.",
      "A heavily armored knight arrives, looking for a specific, seemingly harmless patron.",
      "A sudden, violent argument erupts over the correct rules of a card game.",
      "A young apprentice mage accidentally turns their drink into a small, angry elemental.",
      "A patron offers a significant sum to anyone who will arm wrestle them.",
      "A group of cloaked figures quietly leaves the tavern, one by one.",
      "A sudden draft blows out all the candles, plunging the room into darkness.",
      "A patron tries to sell an obviously fake map to a 'hidden treasure'.",
      "A local bard is booed off the stage, leading to a small riot.",
      "A patron suddenly collapses, foaming at the mouth.",
      "A mysterious figure offers to buy the party's most valuable item for a fraction of its worth.",
      "A group of thugs tries to intimidate the bartender into paying 'protection money'.",
      "A sudden, loud crash from the kitchen is followed by an angry shout.",
      "A patron tries to convince the party to invest in a ridiculous business venture.",
      "A local noble arrives incognito, but is immediately recognized by everyone.",
      "A sudden thunderstorm forces everyone inside, making the tavern uncomfortably crowded.",
      "A patron offers to tell fortunes for the price of a drink.",
      "A group of traveling performers puts on a spectacular, fire-breathing show.",
      "A mysterious figure leaves a coded message pinned to the notice board.",
      "A sudden argument between two wizards results in minor, colorful explosions.",
      "A patron tries to sell a 'talking' parrot that only squawks insults.",
      "A local guard commander arrives, looking for 'volunteers' for a dangerous mission.",
      "A sudden, heavy silence falls over the tavern as a notorious criminal enters.",
      "A patron tries to convince the party to help them break someone out of prison.",
      "A group of off-duty soldiers shares war stories, some of which seem highly exaggerated.",
      "A sudden, loud knocking at the tavern door is followed by a frantic plea for help.",
      "A patron tries to sell a 'magical' weapon that is clearly just rusty iron.",
      "A local merchant complains loudly about the increase in highway robbery.",
      "A sudden influx of strange, exotic animals from a traveling menagerie causes chaos.",
      "A patron tries to pick a fight with the biggest person in the room.",
      "A group of scholars argues loudly about the true meaning of an ancient prophecy.",
      "A sudden, blinding flash of light from outside illuminates the tavern.",
      "A patron tries to sell a 'love potion' that smells suspiciously of garlic.",
      "A local official is caught taking a bribe in plain sight.",
      "A sudden, loud scream from the cellar sends everyone running.",
      "A patron tries to convince the party to help them 'reclaim' their family estate.",
      "A group of weary travelers arrives, bringing news of a terrible disaster.",
      "A sudden, inexplicable change in the taste of the ale causes widespread complaints.",
      "A patron tries to sell a 'haunted' painting.",
      "A local hero is challenged to a duel by a young upstart.",
      "A sudden, loud crash of thunder shakes the entire building.",
      "A patron tries to convince the party to join a secret society.",
      "A group of nervous-looking cultists tries to blend in with the regular patrons.",
      "A sudden, widespread outbreak of uncontrollable laughter afflicts the tavern.",
      "A patron tries to sell a 'treasure map' that is clearly drawn on a napkin.",
      "A local magistrate is drunkenly arguing with a barmaid.",
      "A sudden, loud explosion from the street outside shatters the windows.",
      "A patron tries to convince the party to help them find a lost pet.",
      "A group of masked individuals sits silently, refusing to speak to anyone.",
      "A sudden, inexplicably cold breeze sweeps through the tavern.",
      "A patron tries to sell a 'lucky' coin that keeps landing on its edge.",
      "A local mob boss arrives, demanding 'respect' from the patrons.",
      "A sudden, loud argument between the cook and the bartender spills into the common room.",
      "A patron tries to convince the party to help them fake their own death.",
      "A group of exhausted adventurers collapses at a table, refusing to speak.",
      "A sudden, loud ringing of a bell signals the arrival of the town guard.",
      "A patron tries to sell a 'magical' flute that only plays one terrible note.",
      "A local gossip spreads a rumor that the tavern is built on an ancient graveyard.",
      "A sudden, unexplainable disappearance of all the silverware.",
      "A patron tries to convince the party to help them start a revolution.",
      "A group of mysterious foreigners asks for directions to an obscure location.",
      "A sudden, loud argument between two patrons over a perceived insult.",
      "A patron tries to sell a 'dragon egg' that is clearly just a large rock.",
      "A local thief is caught red-handed picking a pocket.",
      "A sudden, loud crash of breaking glass from an upstairs room.",
      "A patron tries to convince the party to help them win a bet.",
      "A group of rowdy sailors celebrates a successful voyage.",
      "A sudden, inexplicable smell of ozone fills the tavern.",
      "A patron tries to sell a 'magical' cloak that is visibly moth-eaten.",
    ],
  },

  wildernessEncounters: {
    id: 'wildernessEncounters',
    title: 'Wilderness Encounters',
    attribution: 'Original',
    entries: [
      "A massive set of footprints, still filling with water, crosses the path.",
      "A cluster of perfectly spherical boulders arranged in a triangle.",
      "A sudden, localized downpour that smells strongly of ozone.",
      "A merchant caravan stuck in mud, arguing about who pushed them in.",
      "A tree with bark that glows faintly under moonlight.",
      "A wounded griffin resting near a stream, watching warily.",
      "A circle of mushrooms that hums a low, resonant note.",
      "A lone child playing with a remarkably tame wolf.",
      "A group of bandits arguing over how to divide a meager haul.",
      "A sudden drop in temperature accompanied by a thick, clinging fog.",
      "A small shrine to an unknown god, freshly adorned with wildflowers.",
      "A stampede of deer fleeing something unseen in the woods.",
      "A ruined watchtower with a single, unbroken stained-glass window.",
      "A traveling bard singing a song about a legendary beast nearby.",
      "A pool of water that perfectly reflects the stars, even at midday.",
      "A massive, ancient sword stuck deep into a stone outcropping.",
      "A sudden swarm of brilliantly colored butterflies.",
      "A group of pilgrims lost and seeking directions to a holy site.",
      "A strange, glowing rock that is warm to the touch.",
      "A sudden, unnatural silence falls over the forest.",
      "A lone hermit offering cryptic advice for a small donation.",
      "A pack of wolves that seem to be following the party at a distance.",
      "A sudden burst of colorful, harmless magical sparks in the air.",
      "A traveling merchant selling 'genuine' dragon scales.",
      "A ruined campsite with signs of a struggle but no bodies.",
      "A massive, ancient tree with a door carved into its trunk.",
      "A sudden, powerful gust of wind that knocks everyone off balance.",
      "A group of hunters arguing over who shot the prized stag.",
      "A strange, glowing plant that seems to pulse with a heartbeat.",
      "A sudden, heavy rain of small, smooth pebbles.",
      "A lone knight challenging anyone who passes to a joust.",
      "A pack of wild dogs scavenging a recent kill.",
      "A sudden, deafening roar from a nearby cave.",
      "A traveling apothecary offering strange and potent potions.",
      "A ruined village with no sign of what destroyed it.",
      "A massive, ancient bridge spanning a seemingly bottomless chasm.",
      "A sudden, thick swarm of biting insects.",
      "A group of refugees fleeing a war-torn region.",
      "A strange, glowing mushroom that smells like rotting meat.",
      "A sudden, powerful earthquake that shakes the ground violently.",
      "A lone wanderer offering to trade a valuable secret for a hot meal.",
      "A pack of coyotes howling in an unnerving, synchronized chorus.",
      "A sudden, blinding flash of lightning from a clear sky.",
      "A traveling tinker offering to repair armor for a steep price.",
      "A ruined temple with a perfectly intact altar.",
      "A massive, ancient standing stone covered in incomprehensible runes.",
      "A sudden, thick fog that obscures vision beyond a few feet.",
      "A group of mercenaries looking for work or trouble.",
      "A strange, glowing insect that seems to guide the party.",
      "A sudden, torrential downpour that quickly causes flash flooding.",
      "A lone prospector claiming to have found a massive vein of gold.",
      "A pack of wild boars rooting around in the underbrush.",
      "A sudden, strange odor of sulfur and burning hair.",
      "A traveling showman with a wagon full of 'exotic' creatures.",
      "A ruined fortress with a single, perfectly preserved room.",
      "A massive, ancient tree with branches that seem to reach out.",
      "A sudden, powerful gust of wind that carries a strange, haunting melody.",
      "A group of scholars studying a strange geological formation.",
      "A strange, glowing flower that blooms only at night.",
      "A sudden, heavy snowfall in the middle of summer.",
      "A lone druid tending to a wounded animal.",
      "A pack of wolves that seem to be communicating with each other.",
      "A sudden, blinding flash of light from a nearby hilltop.",
      "A traveling merchant selling rare and exotic spices.",
      "A ruined bridge with a sign warning of a troll.",
      "A massive, ancient statue of a forgotten king.",
      "A sudden, thick swarm of locusts.",
      "A group of adventurers resting after a tough battle.",
      "A strange, glowing rock that floats a few inches off the ground.",
      "A sudden, powerful thunderstorm that forces the party to seek shelter.",
      "A lone hunter tracking a dangerous beast.",
      "A pack of wild dogs chasing a deer.",
      "A sudden, deafening roar from the sky.",
      "A traveling apothecary selling 'miracle' cures.",
      "A ruined village with signs of a recent battle.",
      "A massive, ancient standing stone that hums with energy.",
      "A sudden, thick fog that smells like the sea.",
      "A group of pilgrims on a journey to a holy site.",
      "A strange, glowing insect that seems to be watching the party.",
      "A sudden, torrential downpour of blood-red rain.",
      "A lone wanderer offering to guide the party for a price.",
      "A pack of coyotes fighting over a scrap of meat.",
      "A sudden, blinding flash of lightning that strikes a nearby tree.",
      "A traveling tinker offering to repair weapons for a steep price.",
      "A ruined temple with a sign warning of a curse.",
      "A massive, ancient tree with a face carved into its trunk.",
      "A sudden, powerful gust of wind that knocks down trees.",
      "A group of mercenaries guarding a valuable caravan.",
      "A strange, glowing mushroom that smells like sweet perfume.",
      "A sudden, powerful earthquake that opens a massive fissure.",
      "A lone prospector looking for a lost mine.",
      "A pack of wild boars aggressive towards the party.",
      "A sudden, strange odor of ozone and burnt sugar.",
      "A traveling showman with a wagon full of 'magical' artifacts.",
      "A ruined fortress with a sign warning of ghosts.",
      "A massive, ancient bridge spanning a raging river.",
      "A sudden, thick swarm of bats.",
      "A group of scholars searching for a lost library.",
      "A strange, glowing flower that seems to sing.",
      "A sudden, heavy snowfall that quickly covers the ground.",
      "A lone druid performing a strange ritual.",
      "A pack of wolves that seem to be hunting the party.",
      "A sudden, blinding flash of light from a nearby cave.",
      "A traveling merchant selling rare and exotic weapons.",
      "A ruined bridge with a troll demanding a toll.",
      "A massive, ancient statue of a forgotten god.",
      "A sudden, thick swarm of bees.",
      "A group of adventurers preparing for a tough battle.",
      "A strange, glowing rock that seems to pulse with power.",
      "A sudden, powerful thunderstorm that causes flash flooding.",
      "A lone hunter offering to share their kill.",
      "A pack of wild dogs scavenging a recent kill.",
      "A sudden, deafening roar from the woods.",
      "A traveling apothecary selling 'miracle' cures.",
      "A ruined village with signs of a recent battle.",
      "A massive, ancient standing stone that hums with energy.",
      "A sudden, thick fog that smells like the sea.",
      "A group of pilgrims on a journey to a holy site.",
      "A strange, glowing insect that seems to be watching the party.",
      "A sudden, torrential downpour of blood-red rain.",
      "A lone wanderer offering to guide the party for a price.",
      "A pack of coyotes fighting over a scrap of meat.",
      "A sudden, inexplicable silence that blankets the entire forest.",
      "A massive, ancient tree that has been struck by lightning, still smoldering.",
      "A group of heavily armed merchants arguing about which path to take.",
      "A ruined watchtower, its stones covered in strange, glowing runes.",
      "A sudden drop in temperature, accompanied by a thick, freezing fog.",
      "A pack of wolves that seem to be watching the party intelligently, not attacking.",
      "A lone, incredibly old tortoise walking slowly across the path.",
      "A sudden, powerful earthquake that leaves a deep fissure in the ground.",
      "A group of pilgrims who have lost their way and are desperately thirsty.",
      "A strange, glowing plant that seems to pulse in time with a heartbeat.",
      "A sudden swarm of brightly colored, harmless insects.",
      "A ruined shrine to a forgotten deity, covered in fresh, bloodless offerings.",
      "A massive, incredibly deep footprint left in the mud.",
      "A group of bards traveling between towns, eager to share news and songs.",
      "A sudden, intense heatwave that makes travel nearly impossible.",
      "A lone, wild horse that seems to want the party to follow it.",
      "A ruined bridge over a raging river, forcing a dangerous crossing.",
      "A sudden, heavy rainstorm that washes away all tracks.",
      "A group of refugees fleeing from an unseen danger.",
      "A strange, glowing rock that is warm to the touch.",
      "A sudden, inexplicably sweet smell that fills the air.",
      "A ruined campsite, abandoned in a hurry with supplies left behind.",
      "A massive, ancient statue that seems to be watching the party.",
      "A group of hunters tracking a dangerous, mythical beast.",
      "A sudden, localized snowstorm in the middle of summer.",
      "A lone, strange-looking bird that follows the party for days.",
      "A ruined village, reclaimed by nature, with no signs of its former inhabitants.",
      "A sudden, terrifying roar from a creature that sounds incredibly large.",
      "A group of nomadic herders moving their flock to new pastures.",
      "A strange, glowing pool of water that reflects the stars even during the day.",
      "A sudden, incredibly strong gust of wind that knocks everyone off their feet.",
      "A ruined temple, its entrance blocked by a massive stone door.",
      "A massive, ancient bone structure sticking out of the ground.",
      "A group of bandits ambushing a wealthy merchant caravan.",
      "A sudden, inexplicable feeling of being watched by many eyes.",
      "A lone, ancient tree that is the only source of shade in a vast desert.",
      "A ruined castle, seemingly floating in the air above a deep chasm.",
      "A sudden, intense thunderstorm with lightning striking all around.",
      "A group of lost children who claim they were taken by 'the fairy folk'.",
      "A strange, glowing fungus that covers the entire forest floor.",
      "A sudden, inexplicable change in the color of the sky.",
      "A ruined lighthouse on a rocky coast, its light still miraculously shining.",
      "A massive, ancient crater filled with strange, glowing crystals.",
      "A group of heavily armed soldiers patrolling the border.",
      "A sudden, incredibly thick fog that reduces visibility to zero.",
      "A lone, mysterious figure who refuses to speak but points the way.",
      "A ruined aqueduct, its water long dried up.",
      "A sudden, terrifying scream from a humanoid creature.",
      "A group of traveling merchants selling strange, exotic goods.",
      "A strange, glowing moss that seems to point in a specific direction.",
      "A sudden, inexplicably cold breeze that chills to the bone.",
      "A ruined graveyard, its tombstones overturned and graves empty.",
      "A massive, ancient wall that stretches as far as the eye can see.",
      "A group of eager young adventurers setting out on their first quest.",
      "A sudden, terrifying silence broken only by the sound of heavy breathing.",
      "A lone, strange-looking animal that seems to be trying to communicate.",
      "A ruined monastery, its monks long dead but their spirits still present.",
      "A sudden, incredibly bright flash of light that temporarily blinds everyone.",
      "A group of traveling performers putting on a show for nobody in particular.",
      "A strange, glowing flower that blooms only at midnight.",
      "A sudden, inexplicable feeling of profound sadness.",
      "A ruined mansion, its former glory still visible despite the decay.",
      "A massive, ancient tree that is said to grant wishes.",
      "A group of heavily armed mercenaries looking for work.",
      "A sudden, incredibly strong smell of sulfur and brimstone.",
      "A lone, mysterious figure who offers the party a 'bargain'.",
      "A ruined fort, its walls covered in strange, ominous graffiti.",
      "A sudden, terrifying roar from a creature that sounds incredibly angry.",
    ],
  },

};
