// Inspiration tables for campaign prep
// Original content authored for this project.
// Categories are inspired by GM-craft conventions found across tabletop sources,
// but all entries are original work.

export type InspireTable = {
  id: string;
  title: string;
  attribution: string;
  entries: string[];
};

export const TABLES: Record<string, InspireTable> = {

  dungeonGoals: {
    id: 'dungeonGoals',
    title: 'Dungeon Goals',
    attribution: 'Original',
    entries: [
      "Stop the inhabitants from raiding nearby settlements.",
      "Foil a specific scheme being orchestrated from within.",
      "Destroy a magical wellspring corrupting the surrounding area.",
      "Acquire a hoard of treasure rumored to lie deep within.",
      "Find a single specific item needed to complete a ritual.",
      "Retrieve property stolen from a patron or community.",
      "Discover information needed to solve a mystery aboveground.",
      "Rescue a prisoner held by the dungeon's master.",
      "Discover the fate of a previous expedition that never returned.",
      "Find an NPC who was last seen entering the area.",
      "Slay a legendary creature making its lair here.",
      "Investigate strange phenomena originating from this place.",
      "Pursue enemies who fled into the dungeon for refuge.",
      "Escape from the dungeon after being imprisoned within it.",
      "Clear the ruin so it can be claimed and rebuilt.",
      "Discover why a third party is also exploring this dungeon.",
      "Survive a set period within the dungeon as a test or wager.",
      "Negotiate with the dungeon's master rather than kill them.",
      "Hide in the dungeon from a threat outside.",
      "Seal the dungeon permanently so nothing else escapes.",
    ],
  },

  wildernessGoals: {
    id: 'wildernessGoals',
    title: 'Wilderness Goals',
    attribution: 'Original',
    entries: [
      "Locate a hidden site whose entrance is concealed in the wilds.",
      "Assess the scope of a natural or magical disaster.",
      "Escort an NPC safely to a remote destination.",
      "Reach a destination without being detected by hostile forces.",
      "Stop monsters from raiding caravans, roads, or settlements.",
      "Establish a trade route between two distant communities.",
      "Protect a caravan against the wilderness's many dangers.",
      "Map an uncharted region for a patron or expedition.",
      "Identify a location suitable for founding a settlement.",
      "Locate a specific natural resource — a vein, grove, or spring.",
      "Hunt a named beast plaguing a region.",
      "Travel home from a place where the party is stranded.",
      "Obtain information from a reclusive hermit or oracle.",
      "Recover an object lost or hidden somewhere in the wilds.",
      "Determine what happened to a missing group of travelers.",
      "Pursue and capture fugitives fleeing through the wilderness.",
      "Reconnoiter an approaching army or invasion force.",
      "Escape across a wilderness from a regime that hunts the party.",
      "Defend a wilderness location from approaching attackers.",
      "Cleanse a place of corruption tied to the land itself.",
    ],
  },

  urbanGoals: {
    id: 'urbanGoals',
    title: 'Urban & Other Goals',
    attribution: 'Original',
    entries: [
      "Seize control of a fortified place — a tower, ship, or compound.",
      "Defend a place against attackers who will arrive soon.",
      "Steal a specific object from inside a guarded building.",
      "Steal a specific object from a moving caravan or convoy.",
      "Recover salvage from a wrecked vessel or destroyed caravan.",
      "Break a specific prisoner out of confinement.",
      "Escape captivity after being imprisoned.",
      "Win standing or recognition by completing a public trial.",
      "Infiltrate a closed organization or stronghold.",
      "Investigate strange happenings in a single haunted location.",
      "Disrupt the operations of a specific business or guild.",
      "Rescue someone from an unfolding disaster as it happens.",
      "Win a contest, tournament, or duel against named rivals.",
      "Expose a corrupt official by gathering admissible evidence.",
      "Smuggle a person or object past a watchful authority.",
      "Mediate a dispute that threatens to erupt into violence.",
      "Solve a murder before the wrong person is condemned.",
      "Discredit a public figure who deserves to fall.",
      "Survive a single night under conditions designed to kill you.",
      "Recover stolen identity, status, or rightful position.",
    ],
  },

  villainArchetypes: {
    id: 'villainArchetypes',
    title: 'Villain Archetypes',
    attribution: 'Original',
    entries: [
      "A beast or monstrosity hunting through instinct, not malice.",
      "An aberration whose presence warps the minds of those nearby.",
      "A fiend pursuing the slow corruption of a region or people.",
      "A dragon claiming territory and demanding tribute.",
      "A giant raiding for plunder and old grievances.",
      "An undead lord seeking to extend its dominion.",
      "A fey power whose goals follow rules no mortal understands.",
      "A cultist working to summon something that should not return.",
      "A conqueror building an army to take what they want.",
      "A wronged person seeking revenge against the right targets.",
      "A wronged person seeking revenge against the wrong targets.",
      "A schemer maneuvering to seize a position of authority.",
      "A criminal mastermind running an empire from the shadows.",
      "A raider profiting from a region's instability.",
      "A cursed individual whose harm is largely involuntary.",
      "A zealot certain that terrible means justify their righteous end.",
      "A jealous lover whose grief has curdled into harm.",
      "A scholar pursuing forbidden knowledge regardless of cost.",
      "An aristocrat insulated from consequence by station and wealth.",
      "A former hero whose victory turned them into what they fought.",
    ],
  },

  allyTypes: {
    id: 'allyTypes',
    title: 'Ally Types',
    attribution: 'Original',
    entries: [
      "A skilled adventurer of comparable level to the party.",
      "An inexperienced adventurer eager but unproven.",
      "A commoner whose enthusiasm exceeds their competence.",
      "A soldier or guard formally assigned to the party.",
      "A priest offering blessings, healing, and counsel.",
      "A sage with access to lore the party cannot find elsewhere.",
      "Someone with their own vendetta that aligns with the party's mission.",
      "A wandering eccentric whose unpredictability sometimes saves the day.",
      "A celestial agent on a sanctioned mission.",
      "A fey companion bound by an oath to assist.",
      "A creature in disguise as an ally — a polymorphed dragon, a doppelganger, a benevolent spirit.",
      "An apparent ally who is secretly working for the villain.",
    ],
  },

  patronTypes: {
    id: 'patronTypes',
    title: 'Patron Types',
    attribution: 'Original',
    entries: [
      "A retired adventurer recruiting heirs to their old struggles.",
      "A local ruler — mayor, baron, governor — with a specific problem.",
      "A military officer with a mission their own forces cannot handle.",
      "A temple official acting on behalf of their faith.",
      "A sage who needs field agents to verify their theories.",
      "An elder of a community speaking on its collective behalf.",
      "A deity or celestial communicating through visions or signs.",
      "A fey lord whose offers always carry hidden costs.",
      "An old friend of the party calling in a favor.",
      "A former teacher who shaped one of the party members.",
      "A parent or family member of one of the characters.",
      "A desperate commoner with no one else to turn to.",
      "A struggling merchant whose livelihood depends on resolving this.",
      "An academic institution funding the expedition.",
      "A criminal organization offering legitimate work for once.",
      "A rival of the villain whose enemy-of-my-enemy logic applies.",
      "A guild whose interests are threatened by the situation.",
      "A spirit or ghost unable to act directly but able to direct the living.",
      "A construct or artifact with its own agenda and resources.",
      "Someone posing as a patron who will betray the party.",
    ],
  },

  introductions: {
    id: 'introductions',
    title: 'Adventure Introductions',
    attribution: 'Original',
    entries: [
      "The party falls into the adventure literally — a sinkhole, a teleport mishap, a portal pulling them through.",
      "The party stumbles onto a body, and the evidence on it draws them in.",
      "An attack on the road forces the party to take refuge somewhere significant.",
      "A map surfaces — sold, stolen, or inherited — that points somewhere the party hadn't planned to go.",
      "A familiar face — a child, a friend, a lover — arrives begging for help.",
      "A stranger in a public place chooses the party out of a room and explains why.",
      "A community petitions the party formally, with a town meeting or a deputation.",
      "Someone the party owes a debt to calls in that debt now.",
      "A dream visits every member of the party on the same night.",
      "A magical compulsion — a geas, a curse, a binding — leaves no choice.",
      "A reward poster names a price that solves a personal problem.",
      "A ghost or vision appears and refuses to leave until the party acts.",
    ],
  },

  climaxes: {
    id: 'climaxes',
    title: 'Adventure Climaxes',
    attribution: 'Original',
    entries: [
      "A direct confrontation with the main villain and their inner circle.",
      "A pursuit through hostile terrain that ends at the villain's last refuge.",
      "A cataclysm the villain triggered — the party must escape it or stop it.",
      "A race against time to reach the villain before they complete their goal.",
      "Multiple simultaneous rituals or events that must be disrupted at once.",
      "A betrayal by an ally just as the goal seems within reach.",
      "A portal opening to somewhere worse, requiring the party to close it under attack.",
      "Environmental hazards turning the climax site itself into the enemy.",
      "The villain's lair collapsing or transforming around the final fight.",
      "A greater power arriving to eliminate the villain and pose a new threat.",
      "A choice between defeating the villain and saving someone the party loves.",
      "A revelation that the villain cannot be defeated until a hidden weakness is found.",
    ],
  },

  twists: {
    id: 'twists',
    title: 'Twists',
    attribution: 'Original',
    entries: [
      "Another party is pursuing the same goal — they're competition, not allies.",
      "The party becomes responsible for protecting a noncombatant who slows them down.",
      "The villain cannot be killed for reasons the party only learns mid-adventure.",
      "There is a hard time limit, and the party doesn't know how much remains.",
      "Some of the information the party started with is wrong or outdated.",
      "Completing the obvious goal fulfills a prophecy that the party didn't want fulfilled.",
      "The party has two goals and can only complete one — choosing is the adventure.",
      "Succeeding at the goal serves the villain's larger plan in a way the party doesn't see.",
      "The party must cooperate with a known enemy to achieve the goal.",
      "Magical compulsion is driving the party toward the goal — they would not choose this freely.",
    ],
  },

  moralQuandaries: {
    id: 'moralQuandaries',
    title: 'Moral Quandaries',
    attribution: 'Original',
    entries: [
      "Two allies the party desperately needs hate each other and refuse to work together.",
      "Someone the party loves demands they abandon a quest that affects many lives.",
      "A close friend pleads with the party to spare the villain to prove their own better nature.",
      "An NPC the party trusts asks for a chance to redeem themselves through a dangerous mission.",
      "A character's oath or code is incompatible with the most effective path forward.",
      "A loyal companion's faith demands an action the rest of the party finds repugnant.",
      "The party must choose between catching the villain and saving innocents the villain is harming.",
      "Two important advisors give directly opposing strategic advice — choosing one loses the other.",
      "A prisoner who deserves death has information the party cannot get any other way.",
      "An innocent will be punished for a crime the party committed.",
      "A child idolizes someone who genuinely doesn't deserve it — speaking up would shatter them.",
      "The party must decide whether to violate a sacred place to save lives.",
      "A villain offers to surrender peacefully if the party will simply let them keep what they took.",
      "Someone the party freed in an earlier adventure has gone on to commit terrible acts.",
      "The cure for one disaster requires materials taken from the victims of another.",
      "A young person begs to join the adventure that will likely kill them.",
      "The party can save a dying friend by accepting a deal that will haunt them.",
      "Two communities depend on a single scarce resource the party controls access to.",
      "A truth the party uncovered will destroy a peace that everyone is currently grateful for.",
      "Someone the party promised to protect asks them to break that promise to do what is right.",
    ],
  },

  sideQuests: {
    id: 'sideQuests',
    title: 'Side Quests',
    attribution: 'Original',
    entries: [
      "Recover a specific item rumored to be somewhere in this area.",
      "Take from the villain something the villain doesn't yet know is missing.",
      "Locate and persuade a single NPC who has information no one else does.",
      "Free a captive held somewhere along the path the party is already taking.",
      "Find what happened to an NPC who went this way and never came back.",
      "Slay a specific creature whose death would simplify the main quest.",
      "Learn the truth of a strange phenomenon affecting the area.",
      "Recruit someone whose specific skill the party will need later.",
    ],
  },

  npcMannerisms: {
    id: 'npcMannerisms',
    title: 'NPC Mannerisms',
    attribution: 'Original',
    entries: [
      "Hums quietly during silences in conversation.",
      "Speaks in short, complete sentences with no filler.",
      "Has a notably high, low, or rasping voice.",
      "Lisps, slurs, or stutters on specific sounds.",
      "Enunciates each word as if for a slow listener.",
      "Speaks louder than necessary in indoor settings.",
      "Whispers regardless of how private the setting actually is.",
      "Uses long words where short ones would do.",
      "Frequently misuses words but never accepts correction.",
      "Has a personal oath they swear instead of common ones.",
      "Makes jokes — usually bad — at inopportune moments.",
      "Predicts disaster regardless of evidence.",
      "Cannot sit still — taps, fidgets, paces.",
      "Squints at everything, near and far.",
      "Stares slightly past the person they're addressing.",
      "Always seems to be chewing on something — a toothpick, a stem, nothing.",
      "Drums fingers on any nearby surface.",
      "Bites their fingernails when thinking.",
      "Twirls hair, beard, or jewelry while speaking.",
      "Laughs at things that aren't funny, never at things that are.",
    ],
  },

  npcTalents: {
    id: 'npcTalents',
    title: 'NPC Talents',
    attribution: 'Original',
    entries: [
      "Plays a musical instrument well.",
      "Speaks several languages, including unusual ones.",
      "Has improbable luck — coins land their way, dice favor them.",
      "Has a flawless memory for faces or for words spoken aloud.",
      "Calms agitated animals without trying.",
      "Charms children without effort or condescension.",
      "Solves puzzles, riddles, and lateral problems quickly.",
      "Is unbeatable at one specific game — chess, cards, dice.",
      "Mimics voices and accents convincingly.",
      "Draws or sketches well from memory.",
      "Paints — formally or in charcoal — with real skill.",
      "Sings beautifully but rarely does so without prompting.",
      "Has impossibly high alcohol tolerance.",
      "Carpenters or builds skillfully as a hobby.",
      "Cooks well enough that others go out of their way to be fed.",
      "Throws, juggles, or skips objects with uncanny accuracy.",
      "Performs sleight of hand as casual entertainment.",
      "Acts well enough to disguise themselves convincingly.",
      "Dances better than their station would suggest.",
      "Knows a secret language — thieves' cant, druidic gesture, military signs.",
    ],
  },

  npcInteractionTraits: {
    id: 'npcInteractionTraits',
    title: 'NPC Interaction Traits',
    attribution: 'Original',
    entries: [
      "Argumentative — disagrees first, considers later.",
      "Arrogant — assumes their own superiority.",
      "Blustering — talks loudly to project confidence they don't have.",
      "Rude — abrupt, dismissive, easily annoyed.",
      "Curious — asks more questions than they answer.",
      "Friendly — open, warm, easily trusting.",
      "Honest — gives true answers even when it costs them.",
      "Hot-tempered — escalates quickly under pressure.",
      "Irritable — patience is a finite resource that's already low.",
      "Ponderous — slow to speak, slower to commit.",
      "Quiet — speaks only when they have something specific to say.",
      "Suspicious — assumes ulterior motives until proven otherwise.",
    ],
  },

  npcIdeals: {
    id: 'npcIdeals',
    title: 'NPC Ideals',
    attribution: 'Original',
    entries: [
      "Beauty — there should be more of it in the world. (Good)",
      "Charity — those with more should give to those with less. (Good)",
      "Greater good — individuals must sometimes sacrifice for the many. (Good)",
      "Life — every living being deserves their full span of years. (Good)",
      "Respect — every person deserves their dignity acknowledged. (Good)",
      "Self-sacrifice — to give is more important than to take. (Good)",
      "Domination — strength gives the right to rule weakness. (Evil)",
      "Greed — wealth and possessions measure a life's worth. (Evil)",
      "Might — only force matters in the end. (Evil)",
      "Cruelty — the suffering of others is its own justification. (Evil)",
      "Vengeance — wrongs must be repaid, never forgiven. (Evil)",
      "Slaughter — destruction is the purest form of action. (Evil)",
      "Community — bonds between people are sacred. (Lawful)",
      "Fairness — rules apply equally to everyone. (Lawful)",
      "Honor — promises and oaths must be kept. (Lawful)",
      "Logic — reason guides every decision worth making. (Lawful)",
      "Responsibility — duties to others come before personal want. (Lawful)",
      "Tradition — the wisdom of those before us deserves respect. (Lawful)",
      "Change — what stops growing dies. (Chaotic)",
      "Creativity — the new is always worth the risk of the unknown. (Chaotic)",
      "Freedom — no one should bind another's will. (Chaotic)",
      "Independence — each person decides for themselves. (Chaotic)",
      "No limits — rules exist to be tested and broken. (Chaotic)",
      "Whimsy — the moment matters more than the long arc. (Chaotic)",
      "Balance — extremes of any kind invite disaster. (Neutral)",
      "Knowledge — understanding is its own reward. (Neutral)",
      "Live and let live — others' choices are not your business. (Neutral)",
      "Moderation — too much of anything spoils it. (Neutral)",
      "Aspiration — to become more than you currently are. (Other)",
      "Discovery — what's around the next bend is the only thing that matters. (Other)",
      "Glory — to be remembered is to live forever. (Other)",
      "Nation — loyalty to a people or a place above all else. (Other)",
      "Redemption — past wrongs can and must be made right. (Other)",
      "Self-knowledge — the only real journey is inward. (Other)",
    ],
  },

  npcBonds: {
    id: 'npcBonds',
    title: 'NPC Bonds',
    attribution: 'Original',
    entries: [
      "Devoted to a personal goal they have not yet achieved.",
      "Fiercely protective of close family members.",
      "Loyal to colleagues, comrades, or guild-fellows.",
      "Owes a deep debt to a benefactor, patron, or employer.",
      "Carries an unfulfilled love or romantic obligation.",
      "Drawn to a specific place that has special meaning.",
      "Treasures a small keepsake of immense personal value.",
      "Tied to a valuable object — heirloom, prize, or instrument.",
      "Driven by a need for revenge against a specific party.",
      "Holds an oath to a deceased person they still consider binding.",
    ],
  },

  npcFlawsSecrets: {
    id: 'npcFlawsSecrets',
    title: 'NPC Flaws & Secrets',
    attribution: 'Original',
    entries: [
      "Carries a forbidden or socially unacceptable love.",
      "Indulges secret habits incompatible with their public role.",
      "Profound arrogance disguised as competence.",
      "Envies another person's life and would take it if they could.",
      "Greed deep enough to compromise their other values.",
      "Loses self-control under stress, sometimes destructively.",
      "Has a powerful enemy who doesn't know where they are yet.",
      "Carries a specific phobia they have arranged their life to avoid.",
      "Has a shameful incident in their past nobody else knows about.",
      "Committed a serious crime that remains unprosecuted.",
      "Possesses forbidden knowledge they would lose much by revealing.",
      "Is reckless to a degree that endangers their companions.",
    ],
  },

  villainSchemes: {
    id: 'villainSchemes',
    title: 'Villain Schemes',
    attribution: 'Original',
    entries: [
      "Immortality — Acquire a legendary artifact rumored to extend life indefinitely.",
      "Immortality — Attain godhood through ritual, deed, or absorption of divine power.",
      "Immortality — Transfer their consciousness into a younger or constructed body.",
      "Immortality — Bind their soul to a hidden vessel, making themselves undestroyable.",
      "Influence — Seize a specific position of power — throne, council seat, guild office.",
      "Influence — Win a high-stakes contest or public competition.",
      "Influence — Earn the favor of a more powerful figure who will then advance their cause.",
      "Influence — Place a controlled pawn into a position of authority.",
      "Magic — Obtain a specific ancient artifact whose power they intend to misuse.",
      "Magic — Build a magical or technological device for a destructive purpose.",
      "Magic — Fulfill a deity's specific desires in exchange for power.",
      "Magic — Make extensive sacrifices to feed a hungry power.",
      "Magic — Re-establish contact with a forgotten or imprisoned deity.",
      "Magic — Open a permanent passage to another world or plane.",
      "Mayhem — Fulfill an apocalyptic prophecy they believe themselves to be the herald of.",
      "Mayhem — Carry out the will of a god of destruction.",
      "Mayhem — Spread a disease, curse, or corruption across a region.",
      "Mayhem — Overthrow an existing government, regardless of what replaces it.",
      "Mayhem — Trigger a natural disaster at the right place and time.",
      "Mayhem — Annihilate a specific bloodline, clan, or lineage entirely.",
      "Passion — Prolong the life of a loved one whose natural time is ending.",
      "Passion — Prove themselves worthy of another person's affection.",
      "Passion — Raise or restore a specific dead person they will not let go.",
      "Passion — Eliminate everyone competing for the affection of someone they want.",
      "Power — Conquer a region militarily, openly or through proxies.",
      "Power — Take command of an existing army, fleet, or fighting order.",
      "Power — Become the unacknowledged power behind a visible ruler.",
      "Power — Gain the personal favor of an established sovereign.",
      "Revenge — Avenge a humiliation or insult, however long ago.",
      "Revenge — Avenge an imprisonment, torture, or maiming.",
      "Revenge — Avenge the death of a loved one against those responsible — or their descendants.",
      "Revenge — Recover stolen property and punish the thief proportionally.",
      "Wealth — Control natural resources, trade routes, or scarce goods.",
      "Wealth — Marry into a fortune and consolidate the new wealth quickly.",
      "Wealth — Plunder a specific cache, hoard, or treasury.",
      "Wealth — Acquire land, goods, or assets through bureaucratic manipulation.",
    ],
  },

  villainMethods: {
    id: 'villainMethods',
    title: 'Villain Methods',
    attribution: 'Original',
    entries: [
      "Agricultural sabotage — blights, poisonings, drought magic, livestock killings.",
      "Direct violence — beatings, assaults, ordered killings.",
      "Bounty hunting or contracted assassination.",
      "Coercion — bribery, blackmail, threats against loved ones, imprisonment.",
      "Confidence schemes — fraud, false contracts, fast-talking marks into ruin.",
      "Defamation — libel, gossip, planted evidence, public humiliation campaigns.",
      "Formal challenges and dueling under cover of honor.",
      "Public execution — by hanging, burning, beheading, sacrifice, display.",
      "Impersonation, disguise, or substitution of one person for another.",
      "Habitual lying, perjury under oath, and false testimony.",
      "Magical mayhem — hauntings, illusions, mind control, summoning, animation of the dead.",
      "Murder concealed as accident, illness, suicide, or vanishing.",
      "Neglect — withholding food, medicine, shelter from those depending on them.",
      "Political maneuvering — betrayal, conspiracy, espionage, oppression by law.",
      "Religious abuse — curses, desecrations, false prophecies, weaponized cults.",
      "Stalking — patient observation, escalating intrusion, ultimate confrontation.",
      "Theft and property crime — arson, blackmail, burglary, counterfeiting, smuggling.",
      "Torture — for confession, for vengeance, for entertainment.",
      "Vice — supplying addictions, ruining marriages, corrupting officials.",
      "Open warfare — ambushes, invasions, massacres, mercenary actions, terrorism.",
    ],
  },

  villainWeaknesses: {
    id: 'villainWeaknesses',
    title: 'Villain Secret Weaknesses',
    attribution: 'Original',
    entries: [
      "A hidden object holds the villain's soul. Destroy it, end them.",
      "The villain's power breaks when the death of their true love is avenged.",
      "Weakened in the presence of a specific named artifact.",
      "A specific weapon — known but hard to acquire — deals catastrophic damage.",
      "Speaking the villain's true name aloud unravels them.",
      "An ancient prophecy or riddle holds the precise method of their defeat.",
      "Falls when an ancient enemy publicly forgives their original transgression.",
      "Loses all power if a long-ago mystic bargain is finally completed.",
      "Cannot harm those who have eaten salt at their table — and remembers it.",
      "Bound by an old oath they no longer remember making.",
    ],
  },

  sideComplications: {
    id: 'sideComplications',
    title: 'Side Complications',
    attribution: 'Original',
    entries: [
      "A piece of equipment crucial to the next stage breaks at the worst time.",
      "The party's funds are stolen, frozen, or denied to them.",
      "A misunderstanding makes the party temporary targets of local law.",
      "Weather, terrain, or season makes the obvious route impossible.",
      "An NPC the party trusted has been replaced — recently and convincingly.",
      "A messenger arrives with urgent news that complicates current plans.",
      "Someone the party harmed earlier returns and remembers everything.",
      "A creature has been following the party for some time, and now reveals itself.",
      "The party arrives at a location to find others have been there first.",
      "A magical effect — wild magic, divine sign, planar bleed — alters the situation.",
    ],
  },

  campaignEvents: {
    id: 'campaignEvents',
    title: 'Campaign-Level Events',
    attribution: 'Original',
    entries: [
      "A coronation, succession, or transfer of power changes who rules.",
      "An assassination removes a public figure from the board.",
      "A scandal breaks in the highest social circles and dominates conversation.",
      "A natural disaster — earthquake, plague, flood — strikes a community.",
      "A celestial event — eclipse, comet, planar conjunction — disturbs the populace.",
      "A long war ends, with whichever consequences the truce specifies.",
      "A long war begins, formally or by undeclared incursion.",
      "A treaty is signed between groups previously hostile.",
      "A treaty fractures, and both parties begin readying for conflict.",
      "A religious holiday or festival arrives, halting normal business.",
      "A trial of public interest reaches its verdict.",
      "A marriage, alliance, or formal joining of houses occurs.",
      "A famous figure dies of old age, illness, or accident.",
      "A new religion or sect rises to prominence.",
      "An old religion or sect is openly suppressed.",
      "A market crash, harvest failure, or trade disruption hits the economy.",
      "A trove of ancient lore is discovered and made publicly available.",
      "A new technology, spell, or technique becomes widely available.",
      "Refugees from a distant disaster begin arriving in significant numbers.",
      "A long-lost ship, expedition, or family returns from where they vanished.",
    ],
  },

  npcBackgroundConcepts: {
    id: 'npcBackgroundConcepts',
    title: 'NPC Background Concepts',
    attribution: 'Original',
    entries: [
      "An acolyte who serves their temple loyally but doubts privately.",
      "A charlatan whose latest scheme has caught up with them in this town.",
      "A criminal trying to leave the life but unable to refuse one last job.",
      "An entertainer who performs in public to gather information for someone.",
      "A folk hero unable to live up to the story local people tell about them.",
      "A guild artisan whose mastery is recognized, whose loyalty is not.",
      "A hermit who knew something important and has come down from the hills to share it.",
      "A noble whose title is intact and whose fortune is not.",
      "An outlander whose people are no longer where they used to be.",
      "A sage whose theories are correct but professionally dismissed.",
      "A sailor whose ship will not have them back.",
      "A soldier whose war ended but whose habits did not.",
      "An urchin who knows the underside of the city better than anyone living.",
    ],
  },

  raceCharacterNotes: {
    id: 'raceCharacterNotes',
    title: 'Race / Species Quick Notes',
    attribution: 'Original (system-agnostic)',
    entries: [
      "Aarakocra: bird-folk. Hollow-boned, owl-eyed, intensely territorial in flight.",
      "Bullywug: amphibious. Hop everywhere, smell of swamp, speak with frogs.",
      "Dragonborn: dragon-blooded. Breath weapon, scaled skin, lineage matters.",
      "Drow: deep-dwelling elf. Dark-vision, light-sensitive, kept apart by old shame.",
      "Dwarf: mountain or hill. Resistant to poison, suspicious of magic, longer-lived than humans.",
      "Elf: forest or city. Trances rather than sleeps, ages slowly, sees keenly in dim light.",
      "Gnoll: hyena-folk. Hunger-driven, pack-organized, low impulse control by nature.",
      "Gnome: small and clever. Fascinated by invention or by stone, depending on lineage.",
      "Goblin: small and adaptable. Nimble, social, often dismissed by larger creatures who shouldn't.",
      "Half-elf: between two worlds. Often passes in both, belongs fully to neither.",
      "Half-orc: between two worlds. Strong, enduring, often misjudged by those who haven't met one.",
      "Halfling: small and lucky. Brave under pressure, hard to startle, sees the everyday as miraculous.",
      "Hobgoblin: martial goblinoid. Disciplined, hierarchical, takes oaths seriously.",
      "Kenku: crow-folk. Cannot speak originally — only repeat what they've heard.",
      "Kobold: dragon-touched small folk. Pack-tactical, light-sensitive, ambitious beyond their size.",
      "Lizardfolk: reptilian. Practical to the point of seeming cold, unmoved by mammal sentimentality.",
      "Merfolk: ocean-dwelling. Amphibious, can't survive long out of water without preparation.",
      "Orc: war-bred. Quick to anger, quick to fight, quick to laugh in equal measure.",
      "Tiefling: fiend-touched. Distinct horns, tail, eyes — and a lifetime of being looked at sideways.",
      "Troglodyte: cave-dwelling reptilian. Stench is part of their natural defense — there's no polite version.",
    ],
  },
};

// Pick one random entry from a table id
export function rollTable(tableId: string): string | null {
  const t = TABLES[tableId];
  if (!t || t.entries.length === 0) return null;
  return t.entries[Math.floor(Math.random() * t.entries.length)];
}

// Pick N distinct random entries from a table id
export function sampleTable(tableId: string, count: number): string[] {
  const t = TABLES[tableId];
  if (!t) return [];
  const shuffled = [...t.entries].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
