// Tavern names — ORIGINAL CONTENT (part 2 of 2).
// See tavern-name-tables.ts for the combined export and rationale.

export const TAVERN_NAMES_PART_2: readonly string[] = [
  // ── Long, scenic, or distinctive descriptive names ──────────────────────
  'Aubrey\'s Lantern at the Bend',
  'Caoimhe\'s Far-North House',
  'Carter\'s Last Mile',
  'Far Corner of Faith',
  'Fenward & Pell',
  'Highmoor & Hare',
  'House by the Slow Bridge',
  'Inn at the Crook of the River',
  'Inn at the Edge of Hearing',
  'Inn at the Mended Ford',
  'Inn at the Sixth Milestone',
  'Inn of the Glad Departure',
  'Inn of the Inkstained Hand',
  'Inn of the Latecomer',
  'Inn of the Listening Stones',
  'Inn of the Long Welcome',
  'Inn of the Onyx Door',
  'Inn of the Patient Door',
  'Inn of the Pewter Spoon',
  'Inn of the Reluctant Pilgrim',
  'Inn of the Slow Goodbye',
  'Inn of the Soft Argument',
  'Inn of the Untrue North',
  'Last Light at Marrowfen',
  'Light at the End of Ulwen Road',
  'No Bad News',
  'The Always-Open Door',
  'The Burnt-Out Beacon',
  'The First Inn Past the Wall',
  'The House of Better Reasons',
  'The House of Half-Said Things',
  'The House of Quiet Coin',
  'The House of Two Endings',
  'The Lantern That Never Went Out',
  'The Last House Before the Hills',
  'The Long Goodbye',
  'The Long Way Round',
  'The Place Where the Road Forgets',
  'The Place with Three Hearths',
  'The Quiet on the Hill',
  'The Sign Nobody Painted',
  'The Amber Swan',
  'The Ashen Crown',
  'The Autumn Leaf',
  'The Azure Dragon',
  'The Battered Shield',
  'The Beast & Barrel',
  'The Beggar\'s Banquet',
  'The Bitter End',
  'The Black Boar',
  'The Black Rose',
  'The Blind Seer',
  'The Bloodied Blade',
  'The Blue Mermaid',
  'The Boar & Bear',
  'The Bone & Cleaver',
  'The Brazen Head',
  'The Broken Anvil',
  'The Broken Drum',
  'The Broken Lute',
  'The Bronze Griffon',
  'The Burnt Offering',
  'The Cask & Cleaver',
  'The Cask & Crown',
  'The Cat & Fiddle',
  'The Celestial Steed',
  'The Chipped Cup',
  'The Cloaked Figure',
  'The Cloven Hoof',
  'The Cock & Bull',
  'The Coin & Purse',
  'The Cold Hearth',
  'The Copper Kettle',
  'The Cracked Bell',
  'The Crimson Blade',
  'The Crimson Cloak',
  'The Crooked House',
  'The Crossed Swords',
  'The Crown & Anchor',
  'The Crowned Eagle',
  'The Crying Child',
  'The Cursed Coin',
  'The Dancing Bear',
  'The Dancing Maiden',
  'The Dark Horse',
  'The Dead Man\'s Chest',
  'The Dead Man\'s Hand',
  'The Deep Well',
  'The Desert Sun',
  'The Devil\'s Due',
  'The Dog & Duck',
  'The Dog & Partridge',
  'The Dragon\'s Breath',
  'The Dragon\'s Hoard',
  'The Dripping Dagger',
  'The Drowned Sailor',
  'The Drunken Dwarf',
  'The Drunken Sailor',
  'The Dusty Tome',
  'The Eagle\'s Nest',
  'The Ebon Falcon',
  'The Eight Bells',
  'The Empty Glass',
  'The Empty Plate',
  'The Enchanted Apple',
  'The Fading Light',
  'The Fallen Angel',
  'The Fallen Star',
  'The Fat Boar',
  'The Fat Friar',
  'The Fateful Coin',
  'The Feathered Hat',
  'The Fiery Steed',
  'The First Step',
  'The Five Rings',
  'The Flaming Sword',
  'The Flying Horse',
  'The Flying Pig',
  'The Fool\'s Errand',
  'The Fool\'s Gold',
  'The Forge & Hammer',
  'The Forgotten King',
  'The Four Winds',
  'The Fox & Hound',
  'The Free Man',
  'The Friendly Ghost',
  'The Frosty Mug',
  'The Frozen North',
  'The Ghostly Galleon',
  'The Giant\'s Boot',
  'The Gilded Lily',
  'The Gilded Rose',
  'The Glass Slipper',
  'The Gleaming Shield',
  'The Gloomy Cave',
  'The Glowing Ember',
  'The Goat & Compass',
  'The Goblin\'s Cave',
  'The Gold Coin',
  'The Golden Apple',
  'The Golden Fleece',
  'The Golden Hind',
  'The Golden Lion',
  'The Golden Rule',
  'The Good Knight',
  'The Grand Duke',
  'The Great Bear',
  'The Green Dragon',
  'The Green Man',
  'The Grey Ghost',
  'The Grey Wolf',
  'The Griffon\'s Egg',
  'The Grinning Goblin',
  'The Half-Moon',
  'The Half-Orc\'s Head',
  'The Hanged Man',
  'The Hanging Tree',
  'The Happy Wanderer',
  'The Hare & Hounds',
  'The Harpy\'s Song',
  'The Harvest Moon',
  'The Haunted House',
  'The Healing Hand',
  'The Heavy Burden',
  'The Hero\'s Welcome',
  'The Hidden Path',
  'The High Tower',
  'The Hog & Heifer',
  'The Hole in the Wall',
  'The Hollow Tree',
  'The Holy Grail',
  'The Honest Merchant',
  'The Horned God',
  'The House of Cards',
  'The House of Mirrors',
  'The House of the Rising Sun',
  'The Howling Wolf',
  'The Hungry Bear',
  'The Hungry Dragon',
  'The Hunter\'s Moon',
  'The Ice Queen',
  'The Idle Hour',
  'The Ironclad',
  'The Iron Horse',
  'The Iron Mask',
  'The Ivory Tower',
  'The Jade Dragon',
  'The Jolly Roger',
  'The Jolly Tar',
  'The King\'s Arms',
  'The King\'s Head',
  'The King\'s Ransom',
  'The Knight\'s Rest',
  'The Last Cast',
  'The Last Chance',
  'The Last Drop',
  'The Last Resort',
  'The Laughing Dog',
  'The Laughing Gull',
  'The Leaky Cauldron',
  'The Leaping Salmon',
  'The Lightning Strike',
  'The Lion & Unicorn',
  'The Lion\'s Share',
  'The Little Mermaid',
  'The Lone Ranger',
  'The Lone Star',
  'The Lone Wolf',
  'The Long Bow',
  'The Long Journey',
  'The Lord\'s Prayer',
  'The Lost Cause',
  'The Lost City',
  'The Lost Sheep',
  'The Lost Soul',
  'The Loyal Hound',
  'The Lucky Coin',
  'The Lucky Strike',
  'The Mad Hatter',
  'The Magic Flute',
  'The Magic Wand',
  'The Maiden\'s Prayer',
  'The Many Hands',
  'The Mariner\'s Compass',
  'The Masked Ball',
  'The Merchant of Venice',
  'The Mermaid\'s Tail',
  'The Merry Men',
  'The Midnight Express',
  'The Midnight Sun',
  'The Mighty Oak',
  'The Million Dollar Bill',
  'The Missing Link',
  'The Misty Mountain',
  'The Moon & Sixpence',
  'The Moon in the Water',
  'The Moonlit Night',
  'The Morning Star',
  'The Muffled Drum',
  'The Musical Box',
  'The Mystic River',
  'The Naked Truth',
  'The Name of the Rose',
  'The Narrow Escape',
  'The Nervous Breakdown',
  'The New World',
  'The Night Owl',
  'The Night Watch',
  'The Nine Lives',
  'The No Man\'s Land',
  'The Noble Steed',
  'The North Star',
  'The Nutcracker',
  'The Oak & Ash',
  'The Ocean Wave',
  'The Old Curiosity Shop',
  'The Old Mill',
  'The Old Oak Tree',
  'The Old World',
  'The One & Only',
  'The One Ring',
  'The Open Door',
  'The Open Road',
  'The Other Side',
  'The Out of bounds',
  'The Painted Lady',
  'The Paper Moon',
  'The Pass of Arms',
  'The Passed Pawn',
  'The Peace Pipe',
  'The Pearl of Great Price',
  'The Pedlar\'s Pack',
  'The Penny Farthing',
  'The Penny Black',
  'The Phantom Coach',
  'The Phoenix from the Ashes',
  'The Piece of Eight',
  'The Pied Piper',
  'The Pig & Whistle',
  'The Pilgrim\'s Progress',
  'The Pillar of Fire',
  'The Pinch of Salt',
  'The Pipe of Peace',
  'The Pit & the Pendulum',
  'The Plate of Brass',
  'The Point of No Return',
  'The Polar Star',
  'The Poor Man\'s Friend',
  'The Port of Call',
  'The Pot of Gold',
  'The Pound of Flesh',
  'The Prince of Wales',
  'The Princess & the Pea',
  'The Prodigal Son',
  'The Promised Land',
  'The Purple Heart',
  'The Queen of Hearts',
  'The Queen\'s Head',
  'The Quick & the Dead',
  'The Quiet Man',
  'The Rabbit Hole',
  'The Race for the South Pole',
  'The Raging Bull',
  'The Rain Maker',
  'The Red Banner',
  'The Red Cross',
  'The Red Dragon',
  'The Red Herring',
  'The Red Lion',
  'The Red Planet',
  'The Red Ribbon',
  'The Red Rose',
  'The Red Shoes',
  'The Right of Way',
  'The Rising Sun',
  'The Roaring Forties',
  'The Rock of Ages',
  'The Rolling Stone',
  'The Rose & Crown',
  'The Rough Diamond',
  'The Round Table',
  'The Royal Flush',
  'The Royal Oak',
  'The Ruby Ring',
  'The Running Dog',
  'The Sacred Heart',
  'The Safe Haven',
  'The Salt of the Earth',
  'The Scarlet Letter',
  'The Scarlet Pimpernel',
  'The Sea Dog',
  'The Sea Serpent',
  'The Sea Wolf',
  'The Sealed Knot',
  'The Secret Garden',
  'The Secret Service',
  'The Setting Sun',
  'The Seven Deadly Sins',
  'The Seven Seas',
  'The Seven Sisters',
  'The Seven Wonders',
  'The Seventh Heaven',
  'The Shadow of a Doubt',
  'The Ship of the Desert',
  'The Shock of the New',
  'The Shooting Star',
  'The Short Straw',
  'The Silver Bullet',
  'The Silver Chalice',
  'The Silver Lining',
  'The Silver Screen',
  'The Silver Spoon',
  'The Simple Life',
  'The Sixth Sense',
  'The Sleeping Beauty',
  'The Sleeping Dog',
  'The Slippery Slope',
  'The Slow Boat',
  'The Small Hours',
  'The Smiling Assassin',
  'The Snow Queen',
  'The Solid Gold',
  'The Song of the Earth',
  'The Sound of Silence',
  'The South Sea Bubble',
  'The Sown Seed',
  'The Spanish Main',
  'The Spark of Life',
  'The Speaking Clock',
  'The Spirit of the Age',
  'The Splendid Isolation',
  'The Split Second',
  'The Spotted Dog',
  'The Spring Chicken',
  'The Square Peg',
  'The Square Route',
  'The Staff of Life',
  'The Star & Garter',
  'The Star of David',
  'The Star of India',
  'The State of the Art',
  'The Status Quo',
  'The Step in the Dark',
  'The Still Small Voice',
  'The Sting in the Tail',
  'The Stone\'s Throw',
  'The Storm in a Teacup',
  'The Straight & Narrow',
  'The Straw in the Wind',
  'The Stroke of Luck',
  'The Stumbling Block',
  'The Sudden Death',
  'The Sugar Plum',
  'The Sun in Splendour',
  'The Sunday Best',
  'The Swansong',
  'The Sweet Tooth',
  'The Sword of Damocles',
  'The Tame Shrew',
  'The Tangled Web',
  'The Tartan Ribbon',
  'The Teardrop',
  'The Tender Trap',
  'The Tenth Muse',
  'The Test of Time',
  'The Thin End of the Wedge',
  'The Thin Red Line',
  'The Third Degree',
  'The Third Man',
  'The Third World',
  'The Thirteenth Guest',
  'The Thirty-nine Steps',
  'The Thorn in the Flesh',
  'The Thought Police',
  'The Thousand and One Nights',
  'The Thread of Life',
  'The Three Bells',
  'The Three Bears',
  'The Three Blind Mice',
  'The Three Graces',
  'The Three Kings',
  'The Three Little Pigs',
  'The Three Musketeers',
  'The Three Sisters',
  'The Three Wishes',
  'The Tightrope Walker',
  'The Time of Your Life',
  'The Time Machine',
  'The Tip of the Iceberg',
  'The Toll of the Bell',
  'The Tomb of the Unknown Warrior',
  'The Topping Out',
  'The Torch Bearer',
  'The Touch of Frost',
  'The Touchstone',
  'The Tower of Babel',
  'The Town Mouse and the Country Mouse',
  'The Track Record',
  'The Trail of Tears',
  'The Treble Chance',
  'The Tree of Knowledge',
  'The Tree of Life',
  'The Trial of Strength',
  'The Trojan Horse',
  'The True Blue',
  'The True Colours',
  'The Trump Card',
  'The Truth of the Matter',
  'The Truth Will Out',
  'The Tune of the Pied Piper',
  'The Turn of the Screw',
  'The Turn of the Tide',
  'The Turning Point',
  'The Twelve Days of Christmas',
  'The Twentieth Century',
  'The Twenty-first Century',
  'The Twilight Zone',
  'The Two Edged Sword',
  'The Two Mules',
  'The Two of a Kind',
  'The Ugly Duckling',
  'The Uncharted Territory',
  'The Under Dog',
  'The Unfinished Symphony',
  'The Unknown Quantity',
  'The Unsung Hero',
  'The Untouchable',
  'The Upper Hand',
  'The Upper House',
  'The Vale of Tears',
  'The Valley of the Kings',
  'The Valley of the Shadow of Death',
  'The Vicious Circle',
  'The Victoria Cross',
  'The Vinegar Stroke',
  'The Virgin Queen',
  'The Virtuous Circle',
  'The Wailing Wall',
  'The Walk of Life',
  'The Wandering Jew',
  'The War of the Worlds',
  'The War to End All Wars',
  'The Warlord',
  'The Warm Welcome',
  'The Warning Shot',
  'The Wasp\'s Nest',
  'The Waste Land',
  'The Water Babies',
  'The Water of Life',
  'The Watering Hole',
  'The Way of the World',
  'The Way Out',
  'The Way we Live Now',
  'The Weakest Link',
  'The Wealth of Nations',
  'The Weather Eye',
  'The Wedding Guest',
  'The Weeping Willow',
  'The Well of Loneliness',
  'The White Elephant',
  'The White Feather',
  'The White Heat',
  'The White Hope',
  'The White Horse',
  'The White House',
  'The White Knight',
  'The White Magic',
  'The White Rabbit',
  'The White Ribbon',
  'The White Rose',
  'The White Swan',
  'The White Witch',
  'The Whole Truth',
  'The Wild Goose Chase',
  'The Wild West',
  'The Wind in the Willows',
  'The Wind of Change',
  'The Window of Opportunity',
  'The Winds of War',
  'The Winter\'s Tale',
  'The Wise Men',
  'The Witch\'s Brew',
  'The Wizard of Oz',
  'The Wolf in Sheep\'s Clothing',
  'The Word of God',
  'The Words of Wisdom',
  'The Work of Art',
  'The World\'s End',
  'The Worm Will Turn',
  'The Yellow Brick Road',
  'The Yellow Ribbon',
  'The Yellow River',
  'The Yellow Sea',
  'The Yorkshire Ripper',
  'The Young Pretender',
  'The Zero Hour',
];
