// Tavern names — ORIGINAL CONTENT (part 1 of 2).
// See tavern-name-tables.ts for the combined export and rationale.

export const TAVERN_NAMES_PART_1: readonly string[] = [
  // ── "The [Adjective] [Noun]" classics ───────────────────────────────────
  'The Brazen Hart',
  'The Bent Quill',
  'The Bloody Tankard',
  'The Bridled Sow',
  'The Broken Compass',
  'The Burnished Spoon',
  'The Charcoal Cat',
  'The Cinder Wren',
  'The Clattering Bell',
  'The Cloven Anvil',
  'The Crooked Lantern',
  'The Crimson Stag',
  'The Crowing Rooster',
  'The Dappled Mare',
  'The Doubting Friar',
  'The Drowsy Cooper',
  'The Drumming Hare',
  'The Dwindling Candle',
  'The Eager Sparrow',
  'The Empty Saddle',
  'The Fairspoken Stranger',
  'The Faithless Coin',
  'The Foundered Goat',
  'The Fox & Foxglove',
  'The Frosted Apple',
  'The Furred Pilgrim',
  'The Gilded Goose',
  'The Gilded Newt',
  'The Gilded Plover',
  'The Glassblower\'s Rest',
  'The Gleaming Wedge',
  'The Greatcoat & Glove',
  'The Greenest Reed',
  'The Grey Pilgrim',
  'The Half-Penny Drum',
  'The Half-Shod Mule',
  'The Hammered Bell',
  'The Harrow & Spade',
  'The Hempen Cord',
  'The Hindmost Hare',
  'The Hollow Bell',
  'The Honest Lie',
  'The Honeyed Tongue',
  'The Humble Apron',
  'The Hungry Tinker',
  'The Idle Anvil',
  'The Idle Hound',
  'The Ill-Tempered Crow',
  'The Iron Hen',
  'The Iron Maiden\'s Rest',
  'The Iron Quill',
  'The Iron Thimble',
  'The Jaundiced Eye',
  'The Jolly Drover',
  'The Jolly Friar',
  'The Kindly Reaver',
  'The Knotted Bough',
  'The Lacquered Crab',
  'The Lame Cobbler',
  'The Lampblack Owl',
  'The Last Bell',
  'The Last Furrow',
  'The Last Honest Inn',
  'The Last Lantern',
  'The Leaden Coin',
  'The Leaping Cat',
  'The Limping Pilgrim',
  'The Lonesome Ferry',
  'The Long Bone',
  'The Lopsided Crown',
  'The Lost Brigantine',
  'The Mended Wheel',
  'The Mended Cloak',
  'The Merry Widow',
  'The Middling Magpie',
  'The Midnight Plough',
  'The Mire & Mistletoe',
  'The Moaning Lamprey',
  'The Mournful Piper',
  'The Mousetrap',
  'The Muddled Wizard',
  'The Murmuring Spring',
  'The Mute Crier',
  'The Naked Friar',
  'The Nimble Hound',
  'The Nine Crowns',
  'The Old Argument',
  'The Old Bandage',
  'The Old Brass Latch',
  'The Old Sailmaker',
  'The Painted Owl',
  'The Pale Heron',
  'The Patient Spider',
  'The Pewter Mug',
  'The Pickled Crow',
  'The Piebald Pony',
  'The Pilgrim & Pelican',
  'The Plain Sergeant',
  'The Pleasant Toad',
  'The Plover\'s Foot',
  'The Plump Currant',
  'The Plundered Vine',
  'The Pock-Faced Moon',
  'The Porkpie Hat',
  'The Powdered Wig',
  'The Prudent Mariner',
  'The Quartered Apple',
  'The Quiet Pony',
  'The Rambling Vine',
  'The Rattle & Hum',
  'The Ravening Vole',
  'The Rest at Three Pines',
  'The Restless Mare',
  'The Ringing Bell',
  'The Rusty Cuirass',
  'The Saintly Sinner',
  'The Salt & Sextant',
  'The Salt Skipper',
  'The Scarlet Quill',
  'The Scholar\'s Repose',
  'The Sea-Worn Boot',
  'The Seven Stars',
  'The Shattered Goblet',
  'The Shilling & Stoat',
  'The Shrouded Lantern',
  'The Sidelong Glance',
  'The Silent Bellringer',
  'The Silver Otter',
  'The Silver Spigot',
  'The Singed Eyebrow',
  'The Singing Kettle',
  'The Six Sparrows',
  'The Skinflint Smile',
  'The Slack-Jawed Lamprey',
  'The Slanting Door',
  'The Sleepless Watchman',
  'The Smiling Cutpurse',
  'The Smoke & Sage',
  'The Smoke & Saltcod',
  'The Sober Wolf',
  'The Soldier\'s Sigh',
  'The Sooty Lark',
  'The Spent Quiver',
  'The Spiced Boar',
  'The Spiteful Magpie',
  'The Sprig & Sprocket',
  'The Squinting Saint',
  'The Stitched Boot',
  'The Stooped Pilgrim',
  'The Stubbed Toe',
  'The Sunken Anchor',
  'The Sussex Wheelhouse',
  'The Sweating Saint',
  'The Talking Cat',
  'The Tarred Rope',
  'The Tattered Banner',
  'The Tenpenny Loaf',
  'The Thirsty Friar',
  'The Thirsty Vicar',
  'The Three Black Hounds',
  'The Three Crowns',
  'The Three Cup Knot',
  'The Threadbare Cloak',
  'The Throat-Cleared Bard',
  'The Tilted Inkwell',
  'The Tilting Yardarm',
  'The Tipsy Cartographer',
  'The Toothless Lion',
  'The Topheavy Coach',
  'The Tossed Coin',
  'The Travelling Press',
  'The Trembling Mast',
  'The Trotting Mare',
  'The Truant Apprentice',
  'The Truthful Liar',
  'The Twin Compasses',
  'The Twisted Halberd',
  'The Two-Hearted Sparrow',
  'The Unbridled Goose',
  'The Uneven Stair',
  'The Unfinished Bridge',
  'The Unsteady Quill',
  'The Upturned Boot',
  'The Vagrant Star',
  'The Velvet Stoat',
  'The Verminous Earl',
  'The Vicar\'s Crook',
  'The Wandering Whetstone',
  'The Wandering Wineskin',
  'The Watchful Apricot',
  'The Wayfarer\'s Last',
  'The Weeping Stoat',
  'The Whetted Edge',
  'The Whistling Crow',
  'The White Roe',
  'The Widow\'s Walk',
  'The Wild Apple',
  'The Winking Crone',
  'The Wintering Rook',
  'The Wishing Tooth',
  'The Wormwood & Wattle',
  'The Worthy Plough',
  'The Yawning Tortoise',
  'The Yellow Glove',
  'The Yew & Yarrow',
  'The Yoked Ox',

  // ── Possessive / proprietor-named houses ────────────────────────────────
  'Aelinor\'s Rest',
  'Agnes & Sons',
  'Anvil-Wife\'s',
  'Barda\'s Larder',
  'Bayeux\'s Long Table',
  'Belyn\'s Burrow',
  'Brigid\'s Quiet House',
  'Cassel\'s Down-Stairs',
  'Cerys\'s Counting Room',
  'Coppershank\'s',
  'Daffyd\'s Three Doors',
  'Doryn\'s Half-Inn',
  'Eilfrid\'s Last Light',
  'Elder Marn\'s',
  'Ferra\'s Bakehouse-and-Bar',
  'Goodman Pell\'s',
  'Granny Hilde\'s Side Door',
  'Halver\'s Long Bench',
  'Holdar\'s Mead Hall',
  'Imel\'s Snug',
  'Jansek\'s Half-Penny',
  'Kerwin\'s Corner',
  'Larcen\'s',
  'Maggie\'s by the Well',
  'Marred Tom\'s',
  'Mauve & Brother\'s',
  'Old Bregor\'s',
  'Old Hosk\'s Riverside',
  'Old Mother Skeerl\'s',
  'Old Pell\'s',
  'Quintus\'s Slow Room',
  'Rachet & Daughter',
  'Roderyk\'s Riverhouse',
  'Salome\'s Quiet Corner',
  'Sergyn the Quieter\'s',
  'Sweep & Father\'s',
  'Tafta\'s Two-Stove',
  'Talbern\'s Late Light',
  'Tessa\'s Best Window',
  'Tovin Half-Foot\'s',
  'Uncle Whern\'s',
  'Vellis & Sons',
  'Walda\'s Far Bench',
  'Widow Cren\'s',
  'Wynne\'s Reed-House',
  'Ynys Ystrad\'s',

  // ── Sign of the … (signpost names; common in low-literacy regions) ──────
  'Sign of the Black Goat',
  'Sign of the Broken Wheel',
  'Sign of the Closed Door',
  'Sign of the Copper Kettle',
  'Sign of the Cracked Cup',
  'Sign of the Empty Saddle',
  'Sign of the Fallen Spear',
  'Sign of the Five Fingers',
  'Sign of the Folded Hand',
  'Sign of the Gold Tooth',
  'Sign of the Green Door',
  'Sign of the Half-Drawn Bow',
  'Sign of the Hooded Crow',
  'Sign of the Last Coin',
  'Sign of the Left Boot',
  'Sign of the Long Knife',
  'Sign of the Quiet Bell',
  'Sign of the Red Hand',
  'Sign of the Salt Lamb',
  'Sign of the Sealed Letter',
  'Sign of the Sleeping Bull',
  'Sign of the Three Crows',
  'Sign of the Three Hares',
  'Sign of the Three Owls',
  'Sign of the Turning Key',
  'Sign of the White Glove',

  // ── Single-word or place-name houses (often regional inns) ──────────────
  'Antlerlodge',
  'Ashfen',
  'Beggarsclose',
  'Brackenrest',
  'Catspaw House',
  'Cinderhearth',
  'Crowfoot Inn',
  'Driftgate',
  'Drystone Lodge',
  'Eldermarsh',
  'Fernwell',
  'Foxgully',
  'Gravelroost',
  'Hartholm',
  'Heatherbarrow',
  'Holmgate',
  'Larkholm',
  'Longshadow',
  'Lowfern',
  'Marshfen',
  'Mirefall',
  'Nettlebrook',
  'Pondsmere',
  'Ravenmote',
  'Reedsedge',
  'Rookhaven',
  'Saltwheel',
  'Sedgecliffe',
  'Sevenwicks',
  'Shorelock',
  'Sloeford',
  'Stillpool',
  'Stonefoot Inn',
  'Tannerwick',
  'Three Pines',
  'Thrushgate',
  'Tomb-Of-Bees',
  'Wickwood Lodge',
  'Willowmote',
  'Wormwood Hall',

  // ── Plural & numeric (counts, runs, sets) ───────────────────────────────
  'Eight Bells',
  'Five Brothers',
  'Four & Twenty',
  'Four Locks',
  'Nineteen Steps',
  'Seven Bells',
  'Six Doors',
  'Ten Bells',
  'The Eleventh Hour',
  'The Fifth Friar',
  'The Forty Steps',
  'The Half-Past Hour',
  'The Sixth Cup',
  'The Tenth Lamp',
  'The Third Door',
  'The Twelve Knots',
  'The Two Tankards',
  'Three Sails',
  'Twelve Hooks',
  'Two Crowns',

];
